const AUD_1={
"cadad692":{name:"HC1 Introduction (8 Sept)",slides:[
 {n:1,title:"Introduction - Beyond planning theory",kind:"title"},
 {n:2,title:"Today we will cover",kind:"title"},
 {n:3,title:"1. Introductions",kind:"title"},
 {n:4,title:"Lecturer: Daan Bossuyt",kind:"title"},
 {n:5,title:"Lecturer: Josje Bouwmeester",kind:"title"},
 {n:6,title:"Find someone who... (icebreaker)",kind:"title"},
 {n:7,title:"2. Course logistics",kind:"title"},
 {n:8,title:"Important information (Brightspace)",kind:"content",page:"fw",status:"covered",where:"lecture points 'The course in one idea: Escher's Relativity' and 'Course learning goal (Brightspace)'"},
 {n:9,title:"Assessment",kind:"content",page:"fw",status:"covered",where:"lecture table 'Assessment'"},
 {n:10,title:"Commentary",kind:"content",page:"fw",status:"covered",where:"lecture point 'Final exam: the commentary'"},
 {n:11,title:"Tutorials and student-led seminars",kind:"content",page:"fw",status:"covered",where:"lecture point 'Tutorials and student-led seminars'"},
 {n:12,title:"Why student-led seminars?",kind:"content",page:"fw",status:"covered",where:"lecture point 'Why student-led seminars'"},
 {n:13,title:"Electronic devices in the classroom",kind:"content",page:"fw",status:"covered",where:"lecture point 'Exam tip: take handwritten notes'"},
 {n:14,title:"A note on GenAI",kind:"content",page:"fw",status:"covered",where:"lecture point 'GenAI and the excursion'"},
 {n:15,title:"Questions? Comments?",kind:"title"},
 {n:16,title:"3. Why planning theory?",kind:"title"},
 {n:17,title:"What is planning theory?",kind:"content",page:"fw",status:"covered",where:"extended summary 'What the first lecture adds' (Føllesdal + Rydin quotes); quotes"},
 {n:18,title:"Planning theory: our focus",kind:"content",page:"fw",status:"covered",where:"lecture point 'Why planning theory matters to you'"},
 {n:19,title:"Theory A: ontology + epistemology + values",kind:"content",page:"fw",status:"covered",where:"lecture figure 'Theory as a lens between assumptions and research'"},
 {n:20,title:"Four dimensions table",kind:"content",page:"fw",status:"covered",where:"lecture table 'The four dimensions with the lecture's guiding questions'; main figure"},
 {n:21,title:"Four dimensions table (normative highlighted)",kind:"content",page:"fw",status:"covered",where:"lecture table 'The four dimensions...' (row 4)"},
 {n:22,title:"4. Normative commitments in planning theory",kind:"title"},
 {n:23,title:"Theories make different kinds of claims",kind:"content",page:"fw",status:"covered",where:"lecture table 'Theories make three kinds of claims'"},
 {n:24,title:"Kinds of claims (normative words highlighted)",kind:"content",page:"fw",status:"covered",where:"lecture table 'Theories make three kinds of claims' + point 'Evaluative and prescriptive claims carry the values'"},
 {n:25,title:"Normative commitments: definition",kind:"content",page:"fw",status:"covered",where:"concept 'Normative commitment'; point 'Evaluative and prescriptive claims carry the values'"},
 {n:26,title:"Examples of normative commitments?",kind:"content",page:"fw",status:"covered",where:"lecture point 'Evaluative and prescriptive claims carry the values' (question)"},
 {n:27,title:"Justice (Buitelaar; Fainstein)",kind:"content",page:"buit",status:"covered",where:"lecture point 'Citation year on the slides'"},
 {n:28,title:"Four conceptions of the Just City",kind:"content",page:"buit",status:"covered",where:"table of the four cities (philosophy row)"},
 {n:29,title:"In pairs: 'A city is just when...'",kind:"content",page:"buit",status:"covered",where:"added: point 'In pairs: a city is just when...'"},
 {n:30,title:"Case: a just housing plan (Metropolis)",kind:"content",page:"buit",status:"covered",where:"added: table 'Metropolis case: the two plans' + point 'Metropolis case: advise the municipality'"},
 {n:31,title:"The supportive city",kind:"title"},
 {n:32,title:"Example 1: Adequacy - room stress factor",kind:"content",page:"buit",status:"covered",where:"lecture figure 'Supportive City threshold: the room stress factor' + point 'Room stress: the slide's definition'"},
 {n:33,title:"Example 2: Vienna and social housing",kind:"content",page:"buit",status:"covered",where:"lecture point 'Supportive City example 2: Vienna and social housing'"},
 {n:34,title:"3-30-300 rule",kind:"content",page:"buit",status:"covered",where:"lecture figure 'Supportive City threshold for green: the 3–30–300 rule'"},
 {n:35,title:"The free city",kind:"title"},
 {n:36,title:"Example 1: Houston",kind:"content",page:"buit",status:"covered",where:"lecture point 'Free City example 1: Houston'"},
 {n:37,title:"Example 2: Almere Oosterwold",kind:"content",page:"buit",status:"covered",where:"lecture point 'Free City example 2: Almere Oosterwold (source)'"},
 {n:38,title:"Policy examples: framework rules",kind:"content",page:"buit",status:"covered",where:"lecture figure 'Free City policy: framework rules and step-by-step growth'"},
 {n:39,title:"Conclusion: why normative commitments?",kind:"content",page:"fw",status:"covered",where:"extended summary 'What the first lecture adds' (second paragraph)"},
 {n:40,title:"Questions? Comments?",kind:"title"},
 {n:41,title:"Thursday: excursion through Utrecht",kind:"content",page:"fw",status:"covered",where:"lecture point 'GenAI and the excursion'"},
 {n:42,title:"Coffee break",kind:"title"},
 {n:43,title:"End slide (UU logo)",kind:"title"}]},
"9ee0a69c":{name:"Tutorial 1 Anti-adaptive neighbourhoods (Cozzolino)",slides:[
 {n:1,title:"Tutorial 1",kind:"title"},
 {n:2,title:"Today",kind:"title"},
 {n:3,title:"How to prepare a seminar",kind:"title"},
 {n:4,title:"By the end of the first 45 minutes...",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Why objectives come first'"},
 {n:5,title:"Logistics: tables in 'islands'",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Steps 3–4: activity and wrap-up'"},
 {n:6,title:"Think of a seminar that worked really well",kind:"content",page:"cozz",status:"covered",where:"added: point 'Tutorial warm-up questions'"},
 {n:7,title:"How do we design an engaging seminar?",kind:"title"},
 {n:8,title:"Constructive alignment",kind:"content",page:"cozz",status:"covered",where:"lecture figure 'Constructive alignment'"},
 {n:9,title:"Objectives should match methods and assessment",kind:"content",page:"cozz",status:"covered",where:"lecture figure 'Constructive alignment'"},
 {n:10,title:"Misaligned vs aligned example",kind:"content",page:"cozz",status:"covered",where:"lecture table 'Misaligned vs aligned example'"},
 {n:11,title:"Step 1: defining learning goals",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Step 1: learning goals'"},
 {n:12,title:"Step 2: how do we check learning?",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Step 2: checking learning'"},
 {n:13,title:"Step 3: learning activity",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Steps 3–4: activity and wrap-up'"},
 {n:14,title:"Step 4: finishing your learning activity",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Steps 3–4: activity and wrap-up'"},
 {n:15,title:"Exercise: writing up seminar goals",kind:"content",page:"cozz",status:"covered",where:"added: point 'Exercise: writing up seminar goals'"},
 {n:16,title:"A heuristic skeleton for preparing a seminar",kind:"content",page:"cozz",status:"covered",where:"lecture figure 'Heuristic skeleton for preparing a seminar (and a commentary)'"},
 {n:17,title:"What could go wrong with the seminar?",kind:"content",page:"cozz",status:"covered",where:"added: point 'Tutorial warm-up questions'"},
 {n:18,title:"What can everyone do to make it a success?",kind:"content",page:"cozz",status:"covered",where:"lecture point 'What makes a seminar succeed'"},
 {n:19,title:"Inspiration for teaching activities",kind:"content",page:"cozz",status:"covered",where:"lecture table 'Teaching activities (UU Teaching and Learning Collection)'"},
 {n:20,title:"A successful seminar",kind:"content",page:"cozz",status:"covered",where:"lecture point 'What makes a seminar succeed'"},
 {n:21,title:"Discussing this week's article",kind:"title"},
 {n:22,title:"Seminar plan",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Seminar learning objectives (model)'"},
 {n:23,title:"Learning objectives",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Seminar learning objectives (model)'"},
 {n:24,title:"Anything you recognize, links you can make?",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Cozzolino and Hayek'"},
 {n:25,title:"Cozzolino title page with Hayek portrait",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Cozzolino and Hayek'"},
 {n:26,title:"What kind of article is this?",kind:"content",page:"cozz",status:"covered",where:"lecture point 'What kind of article is this?'"},
 {n:27,title:"Adaptive vs anti-adaptive (photos)",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Cozzolino and Hayek' (photo contrast)"},
 {n:28,title:"Exercise: reconstructing Cozzolino's argument",kind:"content",page:"cozz",status:"covered",where:"lecture table 'Reconstructing Cozzolino's argument in five steps'"},
 {n:29,title:"Assumptions",kind:"content",page:"cozz",status:"covered",where:"added: point 'Assumptions exercise: structure and agency'"},
 {n:30,title:"Assumptions: normative commitments",kind:"content",page:"cozz",status:"covered",where:"added: point 'Assumptions: Cozzolino's normative commitments (tutorial)'"},
 {n:31,title:"Assumptions: structure and agency",kind:"content",page:"cozz",status:"covered",where:"added: point 'Assumptions exercise: structure and agency'"},
 {n:32,title:"Structure and agency (position)",kind:"content",page:"cozz",status:"covered",where:"extended summary (agency-leaning, institutions enable/constrain) + added point 'Assumptions exercise: structure and agency'"},
 {n:33,title:"How could you criticize Cozzolino? (hint: Marx)",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Critique of the agency assumption (verbatim)'"},
 {n:34,title:"How could you criticize Cozzolino? (answers)",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Critique of the agency assumption (verbatim)'"},
 {n:35,title:"Concluding",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Concluding questions'"},
 {n:36,title:"Closing: how was this seminar built up?",kind:"content",page:"cozz",status:"covered",where:"lecture point 'Closing reflection'"}]}
};
const SLX_1={
 buit:{figs:[],
  tables:[{title:"Metropolis case: the two plans",head:["","Landowner's plan","Mixed-income plan (municipality)"],
   rows:[["Homes","2,000 market-rate homes","1,600 homes"],
         ["Affordable share","Unaffordable to most low-income households","40% affordable"],
         ["Allocation","Market","Priority for low-income households"],
         ["Public money","No public subsidy","€50 million municipal contribution"],
         ["Rules","Complies with the existing planning rules","Municipality would have to require it"]],
   slide:"HC1 slide 30"}],
  points:[
   {t:"In pairs: a city is just when...",d:"Lecture exercise: 1. Select one of the four conceptions (Happy, Equal, Supportive, Free City). 2. Use the article to complete the sentence: “A city is just when…”",slide:"HC1 slide 29"},
   {t:"Metropolis case: advise the municipality",d:"Context: Metropolis has a severe housing shortage; around 2,000 low-income households live in housing the municipality considers unaffordable or inadequate. The site is a former industrial site next to a railway station. “Advise the municipality from your perspective”: 1. What should the municipality consider most important when comparing the two plans? 2. How does each plan perform according to this consideration? 3. Which plan should the municipality choose and why?",slide:"HC1 slide 30"}]},
 cozz:{figs:[],tables:[],
  points:[
   {t:"Tutorial warm-up questions",d:"“Think of a seminar that worked really well - why did it work well? Write down 3 things.” Later: “What could go wrong with the seminar?” (discuss in pairs for 60 seconds).",slide:"Tutorial 1 slides 6, 17"},
   {t:"Exercise: writing up seminar goals",d:"In duos, on a whiteboard, with markers: write up one objective for a seminar covering today's reading (Cozzolino) and one way you would propose checking this goal; 5 minutes, then discuss with your neighbour.",slide:"Tutorial 1 slide 15"},
   {t:"Assumptions: Cozzolino's normative commitments (tutorial)",d:"“It assumes that adaptable neighborhoods are preferable. This produces a clear normative preference for: individual autonomy and freedom to modify property; distributed rather than centralized control; diversity and innovation; anti-paternalism.” Best fitting the conception of justice of the Free City.",slide:"Tutorial 1 slide 30"},
   {t:"Assumptions exercise: structure and agency",d:"“We have reconstructed Cozzolino’s argument. Now look beneath the argument: which assumptions does he rely on?” Focusing on structure and agency: which is given more explanatory weight, and which quotes support this? Answer: he explicitly describes “action (as the main source of urban change)” (p. 206), but also the “institutional framework that shaped [the city’s] evolutionary process” (p. 206). Position: towards agency, while recognizing that institutions enable or constrain agency.",slide:"Tutorial 1 slides 29, 31–32"}]}
};
