const AUD_2={"4338dfe7":{name:"Knowledge in planning theory (15 Sept)",slides:[
 {n:1,title:"Knowledge in planning theory",kind:"title"},
 {n:2,title:"Who are you?",kind:"title"},
 {n:3,title:"Antwerp skyline photo",kind:"photo"},
 {n:4,title:"Where this session sits",kind:"content",page:"fw",status:"covered",where:"table 'Where the first sessions sit'"},
 {n:5,title:"Where this session sits (2): blocks",kind:"content",page:"fw",status:"covered",where:"table 'Where the first sessions sit' (Block column)"},
 {n:6,title:"Recap: what is theory?",kind:"content",page:"fw",status:"covered",where:"quotes + extended summary (Føllesdal et al. and Rydin 2021 definitions)"},
 {n:7,title:"Theory as glasses (ontology + epistemology + values)",kind:"content",page:"fw",status:"covered",where:"figure 'theory as a lens' (Ontology + epistemology + values → Theory A → research design)"},
 {n:8,title:"Escher, Relativity",kind:"content",page:"fw",status:"covered",where:"point 'The course in one idea: Escher's Relativity'"},
 {n:9,title:"The four dimensions table",kind:"content",page:"fw",status:"covered",where:"table 'The four dimensions with the lecture's guiding questions'"},
 {n:10,title:"By the end of this session you can",kind:"content",page:"know",status:"covered",where:"point 'Learning goals of the knowledge lecture'"},
 {n:11,title:"A definition of planning (Friedmann)",kind:"content",page:"know",status:"covered",where:"point 'A definition of planning (Friedmann)'"},
 {n:12,title:"Planning's authority rests on knowledge",kind:"content",page:"know",status:"covered",where:"point 'Planning's authority rests on knowledge'"},
 {n:13,title:"The planning graduate (Hall 2014)",kind:"content",page:"hall",status:"covered",where:"concept 'Planning graduate 1955/1965/1975' + example 'The graduate planner 1955-1975'"},
 {n:14,title:"Think-pair-share: which knowledge, which expert?",kind:"content",page:"hall",status:"covered",where:"point 'Think-pair-share on Hall's three graduates'"},
 {n:15,title:"You have just asked two questions",kind:"content",page:"know",status:"covered",where:"point 'Epistemology'"},
 {n:16,title:"Two axes",kind:"content",page:"know",status:"covered",where:"figure 'Three epistemological questions and the two paradigms'"},
 {n:17,title:"Paradigms",kind:"content",page:"know",status:"covered",where:"point 'Paradigms: positivism and post-positivism'"},
 {n:18,title:"A brief history of planning and theory",kind:"title"},
 {n:19,title:"craft › positivism › fragmentation › consensus: craft",kind:"content",page:"hall",status:"covered",where:"main figure (craft › positivism › fragmentation › consensus) + table row 'Before 1955'"},
 {n:20,title:"Planning as a craft",kind:"content",page:"hall",status:"covered",where:"summary + concepts 'Planning as craft', 'Theory in vs theory of planning'"},
 {n:21,title:"Berlage, Plan Zuid",kind:"content",page:"hall",status:"covered",where:"example 'Berlage's Plan Zuid'"},
 {n:22,title:"Plan of Chicago (image, no caption)",kind:"content",page:"hall",status:"covered",where:"added: point 'A second craft-era blueprint image'"},
 {n:23,title:"Planning as craft: atheoretical?",kind:"content",page:"hall",status:"covered",where:"point 'Was craft planning atheoretical? Keeble (1952)'"},
 {n:24,title:"craft › positivism: the 1960s",kind:"content",page:"hall",status:"covered",where:"main figure + summary (systems revolution)"},
 {n:25,title:"Systems and rational planning",kind:"content",page:"hall",status:"covered",where:"concepts 'Systems planning', 'Rational (process) planning'"},
 {n:26,title:"The rational planner (photo)",kind:"content",page:"hall",status:"covered",where:"point 'Images of the systems planner'"},
 {n:27,title:"Rational planning",kind:"content",page:"hall",status:"covered",where:"figure 'Planning as a process of rational action' + point 'Rational planning on the slide'"},
 {n:28,title:"Systems planning",kind:"content",page:"hall",status:"covered",where:"point 'Systems planning on the slide'"},
 {n:29,title:"The systems planner (Cybersyn)",kind:"content",page:"hall",status:"covered",where:"point 'Images of the systems planner'"},
 {n:30,title:"SimCity screenshot",kind:"content",page:"hall",status:"covered",where:"point 'Images of the systems planner'"},
 {n:31,title:"Checking assessment through hands",kind:"content",page:"hall",status:"covered",where:"point 'Hands-up check: rational and systems planning'"},
 {n:32,title:"Rational and systems planning could not deliver",kind:"content",page:"hall",status:"covered",where:"point ''Can knowledge be value-free?''"},
 {n:33,title:"fragmentation: 1970s and 1980s",kind:"content",page:"hall",status:"covered",where:"main figure + table row 'Critiques 1965–75'"},
 {n:34,title:"Attacked from both sides",kind:"content",page:"hall",status:"covered",where:"point 'The attacks read as knowledge critiques'"},
 {n:35,title:"Planners lost their 'priestly clothing'",kind:"content",page:"hall",status:"covered",where:"concept 'Priestly clothing' + quote"},
 {n:36,title:"Discuss in pairs: skills, periods, knowledge",kind:"content",page:"hall",status:"covered",where:"point 'Pair discussion: which skill, which period, which knowledge?'"},
 {n:37,title:"consensus(?) since the 1990s",kind:"content",page:"hall",status:"covered",where:"point 'Consensus(?) since the 1990s'"},
 {n:38,title:"The communicative turn (book covers)",kind:"content",page:"know",status:"covered",where:"point 'Key communicative texts shown'"},
 {n:39,title:"The communicative turn as 'new orthodoxy'",kind:"content",page:"know",status:"covered",where:"point 'Hands up: where does the communicative turn sit?' + concept 'New orthodoxy'"},
 {n:40,title:"Examples of communicative theorists",kind:"content",page:"know",status:"covered",where:"point 'Exam tip: bachelor-level theory is assumed' + summary (Innes, Healey, Sandercock)"},
 {n:41,title:"Rydin (2007) article title page",kind:"title"},
 {n:42,title:"The limits to deliberation and collaboration",kind:"content",page:"know",status:"covered",where:"summary + point 'Consensus vs wicked problems'"},
 {n:43,title:"Grenfell Action Group and the Grenfell Tower fire",kind:"content",page:"know",status:"covered",where:"example (Grenfell Tower) + point 'Grenfell and the farmers' protest'"},
 {n:44,title:"Farmers' tractor protest, Brussels",kind:"content",page:"know",status:"covered",where:"point 'Grenfell and the farmers' protest'"},
 {n:45,title:"Are all knowledge claims equally valid?",kind:"content",page:"know",status:"covered",where:"point 'The lecture's guiding questions'"},
 {n:46,title:"Epistemological realism vs relativism",kind:"content",page:"know",status:"covered",where:"point 'Realism vs relativism: the slide's definitions'"},
 {n:47,title:"A question of epistemology (three axes)",kind:"content",page:"know",status:"covered",where:"figure 'Three epistemological questions and the two paradigms'"},
 {n:48,title:"The elephant parable",kind:"content",page:"know",status:"covered",where:"figure 'The elephant parable: realist vs relativist'"},
 {n:49,title:"How do we deal with multiple knowledges in practice?",kind:"content",page:"know",status:"covered",where:"point 'The lecture's guiding questions'"},
 {n:50,title:"Opening up & closing down (Rydin 2007)",kind:"content",page:"know",status:"covered",where:"concept 'Opening up & closing down' + ext 'Planners as co-producers'"},
 {n:51,title:"Experience is not of itself knowledge (quote)",kind:"content",page:"know",status:"covered",where:"quotes (second quote)"},
 {n:52,title:"Where knowledge claims sit (A, B, B1, B2)",kind:"content",page:"know",status:"covered",where:"main figure (Rydin Figure 1 as redrawn in the lecture)"},
 {n:53,title:"Which kind of claim + how would you test it?",kind:"content",page:"know",status:"covered",where:"example 'Utrecht and Rijnenburg claims' + figure caption + table (Table 2)"},
 {n:54,title:"Escher, Relativity (again)",kind:"content",page:"hall",status:"covered",where:"point 'Back to the staircases'"},
 {n:55,title:"Back to the staircases",kind:"content",page:"hall",status:"covered",where:"point 'Back to the staircases'"},
 {n:56,title:"Book tip: Encounters in Planning Thought",kind:"content",page:"hall",status:"covered",where:"point 'Book tip: Encounters in Planning Thought'"},
 {n:57,title:"On Thursday",kind:"content",page:"fw",status:"covered",where:"added: point 'Thursday 17 Sept: readings and Tutorial 1'"},
 {n:58,title:"Exit ticket",kind:"content",page:"know",status:"covered",where:"point 'Exit ticket'"},
 {n:59,title:"UU closing slide",kind:"title"}]},
"f68a0c76":{name:"HC4 Explaining social and spatial order: structure and agency (17 Sept)",slides:[
 {n:1,title:"Explaining social and spatial order: structure, agency and change",kind:"title"},
 {n:2,title:"Welcome!",kind:"title"},
 {n:3,title:"Today",kind:"title"},
 {n:4,title:"At 15:15 (tutorial rooms)",kind:"title"},
 {n:5,title:"Excursion",kind:"title"},
 {n:6,title:"Excursion reflection questions",kind:"content",page:"fw",status:"covered",where:"point 'Excursion reflection questions' + table 'Excursion quiz'"},
 {n:7,title:"Course framework: Marx and Hayek",kind:"title"},
 {n:8,title:"Four dimensions table (knowledge + normative highlighted)",kind:"content",page:"fw",status:"covered",where:"table 'The four dimensions…' + added: point 'Which dimensions HC4 adds'"},
 {n:9,title:"Four dimensions table: 'Discussed today!'",kind:"content",page:"fw",status:"covered",where:"added: point 'Which dimensions HC4 adds'"},
 {n:10,title:"Recap: Ontology. Say what now?",kind:"content",page:"fw",status:"covered",where:"lecture point on the ontology recap (HC4 slide 10)"},
 {n:11,title:"Marx vs Hayek book cover",kind:"photo"},
 {n:12,title:"Learning objectives",kind:"content",page:"fw",status:"covered",where:"lecture point with the HC4 learning objectives"},
 {n:13,title:"Marxism and its impact on social theory",kind:"content",page:"marx",status:"covered",where:"point 'Why Marx matters for social theory'"},
 {n:14,title:"Marx and Hegelianism",kind:"content",page:"marx",status:"covered",where:"figure 'From Hegel's idealism to Marx's materialism' + point 'Hegel's dialectic, Marx's question'"},
 {n:15,title:"Dialectic history: owners vs disowned",kind:"content",page:"marx",status:"covered",where:"figure 'From Hegel's idealism to Marx's materialism'"},
 {n:16,title:"Means of production / property rights",kind:"content",page:"marx",status:"covered",where:"point 'Full Marx quote on the slide' + example ''Better pay for slaves''"},
 {n:17,title:"Industrial revolution",kind:"content",page:"marx",status:"covered",where:"example 'Workers in the industrial revolution'"},
 {n:18,title:"Materialism: base and superstructure",kind:"content",page:"marx",status:"covered",where:"figure 'Base and superstructure maintain and shape each other'"},
 {n:19,title:"From Marx's history to his political ideology",kind:"content",page:"marx",status:"covered",where:"figure 'From Marx's history to his political ideology'"},
 {n:20,title:"Abolition of private property",kind:"content",page:"marx",status:"covered",where:"example 'Lenin on the transitional state' + figure caption"},
 {n:21,title:"Check-in questions (Marx)",kind:"content",page:"marx",status:"covered",where:"extended summary (lecture section: check-in questions)"},
 {n:22,title:"Liberalism enters the chat",kind:"content",page:"hayek",status:"covered",where:"point ''Liberalism enters the chat''"},
 {n:23,title:"Setting the stage",kind:"content",page:"hayek",status:"covered",where:"point 'Setting the stage'"},
 {n:24,title:"Friedrich Hayek",kind:"content",page:"hayek",status:"covered",where:"point 'Hayek and The Road to Serfdom'"},
 {n:25,title:"Determinism vs indeterminism",kind:"content",page:"hayek",status:"covered",where:"point 'Determinism vs indeterminism'"},
 {n:26,title:"Hayek (1989) The theory of complex phenomena",kind:"content",page:"hayek",status:"covered",where:"point 'Hayek (1989) The theory of complex phenomena'"},
 {n:27,title:"Spontaneous order",kind:"content",page:"hayek",status:"covered",where:"point 'Spontaneous order'"},
 {n:28,title:"Agreement only on the mechanism (quote)",kind:"content",page:"hayek",status:"covered",where:"point 'Quote: agreement only on the mechanism'"},
 {n:29,title:"The philosophy of individualism (quote)",kind:"content",page:"hayek",status:"covered",where:"ext section 'The philosophy of individualism'"},
 {n:30,title:"Planning in democracy (quote)",kind:"content",page:"hayek",status:"covered",where:"ext section 'The limits of the state's sphere'"},
 {n:31,title:"Back to our framework again (Hayek)",kind:"content",page:"hayek",status:"covered",where:"point 'Check-in questions on Hayek'"},
 {n:32,title:"Structure, agency and choices diagram",kind:"content",page:"fw",status:"covered",where:"figure 'Structure and agency meet in choices'"},
 {n:33,title:"Questions?",kind:"title"},
 {n:34,title:"What kind of State, then?",kind:"content",page:"hayek",status:"covered",where:"point 'What kind of state, then?'"},
 {n:35,title:"Different theories of the State and implicit values",kind:"content",page:"hayek",status:"covered",where:"figure 'Two theories of the state, two implicit values'"},
 {n:36,title:"The progressive planner (Madden & Marcuse)",kind:"content",page:"marx",status:"covered",where:"table 'The progressive (Marxist) planner vs the liberal planner' + added: point 'Madden & Marcuse: sheds and closets'"},
 {n:37,title:"… and the liberal one (Glaeser & Gyourko)",kind:"content",page:"hayek",status:"covered",where:"example 'Zoning as a tax' + added: point 'Glaeser & Gyourko: the slide's quotes'"},
 {n:38,title:"Key take-home messages",kind:"content",page:"marx",status:"covered",where:"points 'Take-home: …' on marx, hayek and fw"},
 {n:39,title:"Tutorials",kind:"title"},
 {n:40,title:"Short break",kind:"title"}]}};
const SLX_2={
 hall:{figs:[],tables:[],points:[
  {t:"A second craft-era blueprint image",d:"Next to Berlage's Plan Zuid, the craft section shows (without caption) a large city plan with radial avenues, a semicircle of boulevards and a lakefront: by its look Burnham and Bennett's 1909 Plan of Chicago (our identification). Like Plan Zuid it illustrates the pre-1955 craft: a detailed, aesthetic 'blueprint' end-state plan.",slide:"Knowledge lecture slide 22"}]},
 fw:{figs:[],tables:[],points:[
  {t:"Thursday 17 Sept: readings and Tutorial 1",d:"Lecture 13:15–15:00 'Explaining social and spatial order: structure, agency and change' (Josje Bouwmeester), readings: Hayek (1944) Planning and democracy; Marx (1844) Estranged Labor; Cozzolino (2020) The (anti) adaptive neighbourhoods. Tutorial 1 (15:15–17:00): “The instructors demonstrate how to deconstruct an academic article and facilitate discussion.” Bring Cozzolino (2020) on paper and your notes on the article.",slide:"Knowledge lecture slide 57"},
  {t:"Which dimensions HC4 adds",d:"HC4 shows the four-dimension table twice: first with dimensions 3 (knowledge and expertise) and 4 (normative commitments) framed, already treated in the first two lectures; then with dimensions 1 (sources of planning outcomes: structure ↔ agency) and 2 (reproduction and change: reproduction ↔ transformation, deliberate ↔ emergent) framed and marked “Discussed today!”, explained through Marx and Hayek.",slide:"HC4 slides 8–9"}]},
 marx:{figs:[],tables:[],points:[
  {t:"Madden & Marcuse: sheds and closets",d:"First quote on the progressive-planner slide: “In unequal contexts where the logic of commodification rules, some people will always be forced into uninhabitable dwelling spaces. Some will live in sheds, some in closets. Some will live amid toxic pollution. Some will be packed with twenty-five other people, including children, into a single home. These are not market failures—they are how the market works.” Lecturer's gloss: markets do not deliver what they promise, in fact they lead to (material) inequalities.",slide:"HC4 slide 36"}]},
 hayek:{figs:[],tables:[],points:[
  {t:"Glaeser & Gyourko: the slide's quotes",d:"“Measures of zoning strictness are highly correlated with high prices[…] it seems to suggest that this form of government regulation is responsible for high housing costs where they exist.” “[I]f policy advocates are interested in reducing housing costs, they would do well to start with zoning reform. Building small numbers of subsidized housing units is likely to have a trivial impact on average housing prices (given any reasonable demand elasticity), even if well targeted toward deserving poor households. However, reducing the implied zoning tax on new construction could well have a massive impact on housing prices.” (Glaeser & Gyourko 2003)",slide:"HC4 slide 37"}]}
};
