const AUD_3={
"e636c76c":{name:"HC5 Rational planning (22 Sept)",slides:[
 {n:1,title:"High modernism and the debate on rational-comprehensive planning",kind:"title"},
 {n:2,title:"By the end of this session you can",kind:"title"},
 {n:3,title:"Theory as a pair of glasses",kind:"content",page:"gov",status:"covered",where:"lecture figure 'Theory as a pair of glasses'"},
 {n:4,title:"Exit ticket (icon)",kind:"photo"},
 {n:5,title:"HC3 exit ticket responses (Brightspace)",kind:"content",page:"know",status:"covered",where:"added: point 'Exit ticket responses posted'"},
 {n:6,title:"TRUE / FALSE quiz",kind:"content",page:"know",status:"covered",where:"added: point 'Three true/false statements and corrections'"},
 {n:7,title:"Three corrections",kind:"content",page:"know",status:"covered",where:"added: point 'Three true/false statements and corrections' (also exam traps)"},
 {n:8,title:"Brooks: rationality is dead but keeps showing up",kind:"content",page:"gov",status:"covered",where:"summary paragraph 3 (Brooks 2002)"},
 {n:9,title:"Questions for today",kind:"content",page:"gov",status:"covered",where:"lecture point 'Three questions for the lecture'"},
 {n:10,title:"A definition: Rationality (Alexander 2000)",kind:"content",page:"alex",status:"covered",where:"lecture figure 'Rationality' (having/giving reasons, instrumental rationality)"},
 {n:11,title:"Context: High Modernism (Scott)",kind:"content",page:"scott",status:"covered",where:"concept 'high modernism' + lecture point on the three features"},
 {n:12,title:"Example: Brasília",kind:"content",page:"scott",status:"covered",where:"lecture point on the Brasília aerial photo"},
 {n:13,title:"Rational planning (I): planning = optimization",kind:"content",page:"gov",status:"covered",where:"lecture point 'Planning = optimisation (Friedmann 1987)'"},
 {n:14,title:"The rational planning process (Black; Lichfield)",kind:"content",page:"gov",status:"covered",where:"lecture figure 'Planning as a process of rational action' + concept 'Lichfield's 11 steps'"},
 {n:15,title:"Post-war social housing (1945–1965)",kind:"content",page:"gov",status:"covered",where:"example 'Post-war housing norms' + lecture point 'Post-war housing: standard floor plans'"},
 {n:16,title:"Rational planning (II): ideal-typical assumptions",kind:"content",page:"gov",status:"covered",where:"summary paragraph 3 + table 'Assumption / Challenged by'"},
 {n:17,title:"Rydin (2021): the hope of rational public administration",kind:"title"},
 {n:18,title:"The public interest (Weber)",kind:"content",page:"gov",status:"covered",where:"concept 'Weberian separation' + ext 'The Weberian division'"},
 {n:19,title:"Why plan at all? Welfare economics",kind:"content",page:"gov",status:"covered",where:"lecture figure 'Why plan at all? The welfare-economics chain'"},
 {n:20,title:"Institutionalisation in NL: PBL and CPB",kind:"content",page:"gov",status:"covered",where:"lecture point 'Institutionalised in the Netherlands: PBL and CPB'"},
 {n:21,title:"Example: the Westerscheldetunnel",kind:"content",page:"gov",status:"covered",where:"lecture point 'Westerscheldetunnel: the policy question'"},
 {n:22,title:"Example: social cost-benefit analysis (MKBA)",kind:"content",page:"gov",status:"covered",where:"lecture point 'What an MKBA does' + concept 'MKBA'"},
 {n:23,title:"What did the MKBA say about the tunnel?",kind:"content",page:"gov",status:"covered",where:"example (Westerscheldetunnel toll) + summary paragraph 3"},
 {n:24,title:"Critiques on the rational model",kind:"content",page:"gov",status:"covered",where:"lecture point 'Many more critiques' + table 'Assumption / Challenged by'"},
 {n:25,title:"Rittel & Webber (1973) wicked problems",kind:"content",page:"gov",status:"covered",where:"lecture point 'Wicked problems: the epistemological side'"},
 {n:26,title:"Wicked problems: implications (II)",kind:"content",page:"gov",status:"covered",where:"lecture point 'Wicked problems: implications'"},
 {n:27,title:"Incrementalism: The Science of Muddling Through",kind:"content",page:"gov",status:"covered",where:"lecture figure 'Rational-comprehensive versus muddling through' + point 'Lindblom (1959)'"},
 {n:28,title:"Summarizing challenges to rational-comprehensive planning",kind:"content",page:"gov",status:"covered",where:"lecture point 'Three challenges summarised'"},
 {n:29,title:"Planners still cling on to the rational model (quote)",kind:"content",page:"gov",status:"covered",where:"lecture point 'Why do planners cling to it?'"},
 {n:30,title:"Discuss: why do planners hang on to it?",kind:"content",page:"gov",status:"covered",where:"lecture point 'Why do planners cling to it?'"},
 {n:31,title:"What does the rational model assume about knowledge?",kind:"content",page:"gov",status:"covered",where:"quotes (p. 22 and p. 24)"},
 {n:32,title:"Where the rational model sits in the course framework",kind:"content",page:"gov",status:"covered",where:"lecture figure 'Where the rational model sits in the course framework'"},
 {n:33,title:"Core elements of the governmental model in research",kind:"content",page:"gov",status:"covered",where:"lecture table 'Core elements of the governmental model in research'"},
 {n:34,title:"In pairs: recognise the governmental approach",kind:"content",page:"gov",status:"covered",where:"lecture point 'Spotting the governmental approach: three signals'"},
 {n:35,title:"Questions within the rational public administration framework",kind:"content",page:"gov",status:"covered",where:"lecture point 'Typical research questions in this frame'"},
 {n:36,title:"Recognising the governmental approach in research",kind:"content",page:"gov",status:"covered",where:"exam tip + quote 'critical friend shadowing the steps' (p. 38)"},
 {n:37,title:"Exit ticket",kind:"content",page:"gov",status:"covered",where:"lecture point 'Exit ticket'"}
]},
"fd4cf759":{name:"HC6 Rational choice and self-interest (24 Sept)",slides:[
 {n:1,title:"Rational choice and self-interest",kind:"title"},
 {n:2,title:"Last week(s) we discussed",kind:"content",page:"rc",status:"covered",where:"lecture point 'Where HC6 sits in the course'"},
 {n:3,title:"Today's schedule",kind:"title"},
 {n:4,title:"Learning objectives",kind:"title"},
 {n:5,title:"Rational-comprehensive planning vs rational-choice theory (build)",kind:"content",page:"rc",status:"covered",where:"table 'Rational-comprehensive planning / Rational choice theory'"},
 {n:6,title:"Rational-comprehensive planning vs rational-choice theory",kind:"content",page:"rc",status:"covered",where:"table + ext 'Rational-comprehensive planning is not rational choice theory'"},
 {n:7,title:"What is rationality in rational choice theory?",kind:"content",page:"rc",status:"covered",where:"ext 'Rational-comprehensive planning is not rational choice theory' (para 2)"},
 {n:8,title:"What is rationality? (Rydin 2020)",kind:"content",page:"rc",status:"covered",where:"ext 'Rational-comprehensive planning is not rational choice theory' (para 2)"},
 {n:9,title:"Planning and property rights",kind:"title"},
 {n:10,title:"Different interests in land",kind:"photo"},
 {n:11,title:"Public interest according to rational choice",kind:"content",page:"rc",status:"covered",where:"summary para 2 + table row 'Public interest'"},
 {n:12,title:"The dual role of the State in planning",kind:"content",page:"needham",status:"covered",where:"lecture figure 'The dual role of the state in planning'"},
 {n:13,title:"Limited power of land use planning",kind:"content",page:"rc",status:"covered",where:"ext 'Planning and property rights: the dual role of the state' (veto right, Needham p. 24)"},
 {n:14,title:"Different interests in land: two situations",kind:"content",page:"rc",status:"covered",where:"ext 'Planning and property rights' (densification vs expansion; Airbnb)"},
 {n:15,title:"Densification or urban expansion?",kind:"title"},
 {n:16,title:"Model of planning phases (Bonczek & Halstenberg)",kind:"content",page:"rc",status:"covered",where:"lecture figure 'Land value rises with each planning phase'"},
 {n:17,title:"But also... regulatory takings",kind:"content",page:"rc",status:"covered",where:"ext 'Planning and property rights' (para 2) + concept 'Regulatory taking'"},
 {n:18,title:"Rent and landowner strategies",kind:"content",page:"rc",status:"covered",where:"concept 'Rent / rent-seeking' + ext 'Rent-seeking and landowner strategies'"},
 {n:19,title:"A big asymmetry",kind:"content",page:"rc",status:"covered",where:"concept 'Betterment / compensation asymmetry' + ext (value capture)"},
 {n:20,title:"Taylor (2016)",kind:"content",page:"taylor",status:"covered",where:"lecture figure 'Two rational strategies of existing owners'"},
 {n:21,title:"The case of Rijnenburg",kind:"content",page:"rc",status:"covered",where:"lecture point 'Who owns Rijnenburg' + ext 'Rent-seeking and landowner strategies'"},
 {n:22,title:"House price development (NL)",kind:"content",page:"rc",status:"covered",where:"lecture figure 'House price development in the Netherlands'"},
 {n:23,title:"Landowner strategies (Buitelaar et al. 2025)",kind:"content",page:"rc",status:"covered",where:"summary para 2 + ext 'Rent-seeking and landowner strategies'"},
 {n:24,title:"Based on my own research: Swiss densification",kind:"content",page:"rc",status:"covered",where:"ext 'A rational choice hypothesis: Swiss densification'"},
 {n:25,title:"Swiss property law (BGBB)",kind:"content",page:"rc",status:"covered",where:"example 'Swiss farmland law and densification'"},
 {n:26,title:"Planning phases adapted to Switzerland",kind:"content",page:"rc",status:"covered",where:"lecture figure 'Swiss version: no speculative value before zoning'"},
 {n:27,title:"Hypothesized effect + thesis tip",kind:"content",page:"rc",status:"covered",where:"ext 'A rational choice hypothesis: Swiss densification' (incl. thesis tip)"},
 {n:28,title:"Mid-term exam",kind:"title"},
 {n:29,title:"Mid-term exam format",kind:"content",page:"rc",status:"covered",where:"lecture point 'Midterm format'"},
 {n:30,title:"Mid-term exam content (learning goals)",kind:"content",page:"rc",status:"covered",where:"lecture point 'Midterm content and focus'"},
 {n:31,title:"Mid-term exam content (material)",kind:"content",page:"rc",status:"covered",where:"lecture point 'Midterm content and focus'"},
 {n:32,title:"Airbnb as a case study",kind:"title"},
 {n:33,title:"Potential theoretical lenses",kind:"content",page:"rc",status:"covered",where:"lecture point 'Other lenses on Airbnb'"},
 {n:34,title:"Gurran et al. (2018) title page",kind:"content",page:"rc",status:"covered",where:"lecture point 'Other lenses on Airbnb'"},
 {n:35,title:"Gurran et al. (2018) quote",kind:"content",page:"rc",status:"covered",where:"ext 'Airbnb: incentives, externalities and collective action'"},
 {n:36,title:"Incentives and rational choice",kind:"content",page:"rc",status:"covered",where:"lecture table 'Airbnb: incentives per actor'"},
 {n:37,title:"Incentives: neighbours highlighted",kind:"content",page:"rc",status:"covered",where:"lecture table 'Airbnb: incentives per actor' (externalities)"},
 {n:38,title:"Protests: New York, Barcelona, Amsterdam, Athens",kind:"content",page:"rc",status:"covered",where:"ext 'Airbnb: incentives, externalities and collective action' (para 2)"},
 {n:39,title:"Lack of Airbnb regulation: collective action problem",kind:"content",page:"olson",status:"covered",where:"lecture figure 'Airbnb: why regulation lags'"},
 {n:40,title:"Planner's toolbox (discussion)",kind:"content",page:"rc",status:"covered",where:"added: point 'Planner's toolbox: two discussion questions'"},
 {n:41,title:"Some potential solutions",kind:"content",page:"rc",status:"covered",where:"lecture table 'Restricting versus Coasean-inspired tools'"},
 {n:42,title:"Policy in Utrecht (2018)",kind:"content",page:"rc",status:"covered",where:"example 'Utrecht's short-stay rules (2018)'"},
 {n:43,title:"Problems with one-size-fits-all regulations",kind:"content",page:"rc",status:"covered",where:"lecture table 'Restricting versus Coasean-inspired tools' (middle column)"},
 {n:44,title:"From Airbnb Newsroom (2023)",kind:"content",page:"rc",status:"covered",where:"lecture point 'Airbnb's counter-message'"},
 {n:45,title:"What solution would a rational-choice scholar propose?",kind:"content",page:"rc",status:"covered",where:"ext 'Regulation and its problems' (last sentence)"},
 {n:46,title:"Coase's theorem (+ graph)",kind:"content",page:"rc",status:"covered",where:"concept 'Coase theorem' + lecture figure 'Coase theorem graph'"},
 {n:47,title:"Example of a noisy factory",kind:"content",page:"rc",status:"covered",where:"figure 'Coase: the noisy factory' + example"},
 {n:48,title:"But only if TC = 0",kind:"content",page:"rc",status:"covered",where:"concept 'Transaction costs' + ext 'Coase's theorem and Coasean solutions'"},
 {n:49,title:"Back to Airbnb: which rights?",kind:"content",page:"rc",status:"covered",where:"lecture point 'Question: which rights must be defined?'"},
 {n:50,title:"Coasean-inspired approaches",kind:"content",page:"rc",status:"covered",where:"lecture point 'Question: which rights must be defined?'"},
 {n:51,title:"Some examples (Coasean tools)",kind:"content",page:"rc",status:"covered",where:"lecture table 'Restricting versus Coasean-inspired tools' (right column)"},
 {n:52,title:"Wrapping up: core assumptions in RC theory",kind:"title"},
 {n:53,title:"Core assumptions",kind:"content",page:"rc",status:"covered",where:"ext 'Core assumptions and critiques' + summary para 4"},
 {n:54,title:"Core assumptions: differ per author",kind:"content",page:"rc",status:"covered",where:"ext 'Core assumptions and critiques' (warning: read each paper critically)"},
 {n:55,title:"Example: Needham and Taylor",kind:"content",page:"rc",status:"covered",where:"quotes + ext 'Core assumptions and critiques' (para 2)"},
 {n:56,title:"Critiques of rational choice theories",kind:"content",page:"rc",status:"covered",where:"summary para 4 + ext 'Core assumptions and critiques'"},
 {n:57,title:"What's next?",kind:"title"}
]}
};
const SLX_3={
 know:{figs:[],tables:[],points:[
  {t:"Three true/false statements and corrections",d:"Quiz at the start of HC5: (1) 'A survey of a thousand residents makes knowledge pluralist': false, pluralism concerns who can be 'authorized to produce valid knowledge', not how many people you ask. (2) 'Positivists ignore that research is done by different people and what that does to the quality of research': false, a positivist may still recognise that different people have bias, but treats position as error to be removed by better methods. (3) 'Situated knowledge means no claim is better than another': false, situated does not mean anything goes; position shapes what is seen, but claims can still be judged vis-à-vis each other (a question of epistemological realism/relativism).",slide:"Rational planning slides 6–7"},
  {t:"Exit ticket responses posted",d:"The lecturer posted a written response to the HC3 exit tickets on Brightspace ('Exit ticket and responses', 16-09-2026). Its starting point: following Rydin, knowledge means knowledge claims about causal relations ('if we do X, then Y will follow'), which matters for planners because they link knowledge to action; a theory is a coherent set of such claims, and asking who can produce knowledge means asking who can make defensible causal claims.",slide:"Rational planning slide 5"}
 ]},
 rc:{figs:[],tables:[],points:[
  {t:"Planner's toolbox: two discussion questions",d:"Pair discussion, then plenary: 'As a planner... What instrument would you use to limit externalities? What may be potential difficulties in implementation?' The next slides answer it: standard solutions (land-use controls, taxes and fees, time limits, complaints systems) and the problems rational choice theorists see in them.",slide:"HC6 slide 40"}
 ]}
};
