const AUD_4={"0e1809a1":{name:"HC7 Neo-institutionalism & planning (Bouwmeester, 29 Sept)",slides:[
{n:1,title:"Neo-institutionalism & planning",kind:"title"},
{n:2,title:"Content (Part A / Part B)",kind:"title"},
{n:3,title:"Learning objectives",kind:"title"},
{n:4,title:"The formal and informal rules of the game",kind:"content",page:"ni",status:"covered",where:"ext 'What the lecture asks and why' (starting definition)"},
{n:5,title:"What are institutions?",kind:"content",page:"ni",status:"covered",where:"summary 1 + concept 'Institution vs organisation' (question answered; image is an illustration of a neighbourhood)"},
{n:6,title:"Institutions ≠ organization",kind:"content",page:"ni",status:"covered",where:"concept 'Institution vs organisation'; ext 'What the lecture asks and why'"},
{n:7,title:"Eurovision",kind:"content",page:"ni",status:"covered",where:"example 'Eurovision: organisation versus institutions' + lecture point 'Eurovision rulebook'"},
{n:8,title:"(image: plan / cadastre / aerial layers)",kind:"content",page:"ni",status:"covered",where:"added: point 'Layered map image (no text)'"},
{n:9,title:"Why do institutions matter to planning and planners?",kind:"content",page:"ni",status:"covered",where:"quotes (Savini 2019); figure 'The double life of institutions'"},
{n:10,title:"Institutions and planners (context / object)",kind:"content",page:"ni",status:"covered",where:"figure 'The double life of institutions'; ext 'Why institutions matter to planners'"},
{n:11,title:"E.R. Alexander (2005)",kind:"content",page:"ni",status:"covered",where:"added: point 'Alexander (2005): the full quote'"},
{n:12,title:"Part A: The origins of neo-institutional theory",kind:"title"},
{n:13,title:"Prisoners' dilemma",kind:"content",page:"ni",status:"covered",where:"figure 'The prisoners' dilemma' + point 'Prisoners' dilemma as the starting puzzle'"},
{n:14,title:"Hardin's tragedy of the commons",kind:"content",page:"ni",status:"covered",where:"concept 'Tragedy of the commons'; point 'Hardin: the lecturer's question'"},
{n:15,title:"Institutional-actor analysis and the commons (Ostrom)",kind:"content",page:"ni",status:"covered",where:"ext 'Part A: from the tragedy of the commons to Ostrom'; full reference added in point 'Full references cited on the slides'"},
{n:16,title:"IAD framework",kind:"content",page:"ni",status:"covered",where:"figure 'Ostrom's IAD framework'"},
{n:17,title:"IAD framework + Types of rules",kind:"content",page:"ni",status:"covered",where:"figure 'Ostrom's IAD framework' + table 'Ostrom's seven types of rules (IAD)'"},
{n:18,title:"Informal settlements (Bouwmeester & Hartmann 2021)",kind:"content",page:"ni",status:"covered",where:"added: point 'Informal settlements: rules without the state'"},
{n:19,title:"What characterizes neo/new-institutionalism?",kind:"content",page:"ni",status:"covered",where:"figure 'Institutions between structure and agency'; ext 'What neo-institutionalism is…'"},
{n:20,title:"Institutional arrangements affect morphology (Tennekes et al.)",kind:"content",page:"ni",status:"covered",where:"table 'Institutions visible in morphology'; example 'Housing morphology in three regions'"},
{n:21,title:"How do institutions influence social behaviour?",kind:"content",page:"ni",status:"covered",where:"ext 'What neo-institutionalism is and where the strands disagree' (Giddens, March & Olsen, Buitelaar, Morgan & Engwall)"},
{n:22,title:"Institutionalisms may disagree on…",kind:"content",page:"ni",status:"covered",where:"ext 'What neo-institutionalism is…'; point 'Sources behind the definitions'"},
{n:23,title:"Part B: Defining different institutionalisms",kind:"title"},
{n:24,title:"Most important paradigms (RC, sociological, historical)",kind:"content",page:"ni",status:"covered",where:"summary 3; ext 'Part B: rational choice, sociological and historical'"},
{n:25,title:"1. Rational-choice institutionalism",kind:"content",page:"ni",status:"covered",where:"figure 'Rational choice institutionalism: how institutions shape action'; table column 'Rational choice'"},
{n:26,title:"2. Sociological institutionalism",kind:"content",page:"ni",status:"covered",where:"ext 'Part B…' (all five bullets); quotes"},
{n:27,title:"Amsterdam-North and the political nature of symbols",kind:"content",page:"ni",status:"covered",where:"example 'Amsterdam-Noord's shipyard symbols' + added point 'Amsterdam-Noord slide: the three bullets'"},
{n:28,title:"3. Historical institutionalism / path dependence",kind:"content",page:"ni",status:"covered",where:"ext 'Part B…'; figure 'Path dependence in numbers: US mortgage interest deduction'"},
{n:29,title:"Path dependent participation (Holsen 2021)",kind:"content",page:"ni",status:"covered",where:"added: point 'Holsen (2021): the path-dependent explanation'"},
{n:30,title:"Conceptualizing institutional change",kind:"title"},
{n:31,title:"Planning as institutional design",kind:"content",page:"ni",status:"covered",where:"figure 'Planning as institutional design, and its limits'; ext 'Institutional change…'"},
{n:32,title:"The three articles (Dembski & Salet, Sorensen, Moroni)",kind:"content",page:"ni",status:"covered",where:"table 'Exercise: the quotes the lecturer picked per reading'; full titles on pages dembski, sorensen, moroni"},
{n:33,title:"Pick one of these articles (3 questions)",kind:"content",page:"ni",status:"covered",where:"ext 'Institutional change: can planners design institutions?'"},
{n:34,title:"Dembski & Salet quotes",kind:"content",page:"dembski",status:"covered",where:"verbatim quotes in dembski page (pp. 618, 621, 622); ni table 'Exercise: the quotes…'"},
{n:35,title:"Sorensen quotes",kind:"content",page:"sorensen",status:"covered",where:"verbatim quotes in sorensen page (pp. 1805, 1807, 1814); ni table 'Exercise: the quotes…'"},
{n:36,title:"Moroni quotes",kind:"content",page:"moroni",status:"covered",where:"verbatim quotes in moroni page (pp. 279, 282, 287); ni table 'Exercise: the quotes…'"},
{n:37,title:"Why does this matter?",kind:"content",page:"ni",status:"covered",where:"quotes; ext 'Why it matters and the take-home messages'"},
{n:38,title:"Housing is becoming unaffordable (homework)",kind:"content",page:"ni",status:"covered",where:"example box (HI / SI / evolutionary); ext 'Why it matters…'"},
{n:39,title:"Key take-home messages",kind:"content",page:"ni",status:"covered",where:"ext 'Why it matters and the take-home messages'"},
{n:40,title:"Break time",kind:"title"}
]}};
const SLX_4={ni:{figs:[],tables:[],points:[
{t:"Alexander (2005): the full quote",d:"\"If planning is the translation of ideas into action, and the planner's goal is the transformation of society (Friedmann, 1987), then institutional transformation must be a critical aspect of planning. That is because there is only one way to effect significant and lasting social change: changing the people who make up society. And there are only two ways of changing people: changing individuals, and changing institutions.\" The slide highlights 'institutional transformation must be a critical aspect of planning' and 'changing institutions'.",slide:"HC7 slide 11"},
{t:"Layered map image (no text)",d:"Slide 8 (and the agenda slide 2) show one area as three stacked layers: a coloured land-use/zoning map on top, a cadastral parcel map in the middle and an aerial photo at the bottom. The slide has no text; read it as the formal rules (zoning plan, property parcels) lying on top of physical space.",slide:"HC7 slides 2, 8"},
{t:"Informal settlements: rules without the state",d:"After the IAD rule types, the lecturer shows two photos of an informal settlement (corrugated-iron dwellings, an unpaved alley with an open drain) from her own work: Bouwmeester & Hartmann (2021), 'Unraveling the Self-Made City: The Spatial Impact of Informal Real Estate Markets in Informal Settlements', Cities 108: 102966. Point: even without formal planning, informal rules (an informal real estate market) shape how space is built.",slide:"HC7 slide 18"},
{t:"Amsterdam-Noord slide: the three bullets",d:"Savini & Dembski (2016): (1) 'Planning is about creating meaning and building consensus'; (2) 'Symbolic narratives, acts and artefacts play a role in institutional change by mobilizing consensus among actors'; (3) the new development agenda for Amsterdam-Noord was enabled by a 'set of symbols' linking the past (industrial shipyard manufacturing) to the future (creative economy). The photo shows a crowded event at a former shipyard hall.",slide:"HC7 slide 27"},
{t:"Holsen (2021): the path-dependent explanation",d:"The slide shows the abstract of Holsen, 'A path dependent systems perspective on participation in municipal land-use planning' (European Planning Studies 29(7), 1193–1210). Public participation 'cannot fully be understood without an equivalent understanding of the planning system supporting it'; the right of the public at large competes with more specifically designed rights of stakeholders, neighbours and sector authorities, shaped through several generations of planning legislation. 'In Norway, the safeguarding of property rights was a contingent occurrence'; more general participatory rights were developed later on that basis, so participation stayed relatively weak.",slide:"HC7 slide 29"},
{t:"Full references cited on the slides",d:"Ostrom, E. (1990) Governing the Commons: The Evolution of Institutions for Collective Action, Cambridge UP. Tennekes, J., Harbers, A. & Buitelaar, E. (2015) 'Institutional arrangements and the morphology of residential development in the Netherlands, Flanders and North Rhine-Westphalia', European Planning Studies 23(11): 2165–2183. Savini, F. & Dembski, S. (2016) 'Manufacturing the creative city: Symbols and politics of Amsterdam North', Cities 55: 139–147.",slide:"HC7 slides 15, 20, 27"}
]}};
