const EX_1={
 fw:[
  {t:"Reading housebuilding rates",d:"Rydin notes that the same data on housebuilding rates can support different narratives depending on whether you take a historical view, focus on housebuilders' behaviour, or on planners' decisions and their rationale. Shows why empiricism fails: data never 'speaks for itself', so a theoretical framing is needed to pick and defend one narrative.",src:"text",p:"p. 8"},
  {t:"Phronesis hides its theory",d:"If a phronetic researcher works with political leaders to change planning through dialogue, that assumes change comes via feedback or communicative action; if they help community groups in planning disputes, that assumes planning is a conflict-ridden political process. Shows Rydin's point that phronesis still relies on an unacknowledged theoretical choice.",src:"text",p:"p. 11"},
  {t:"Governance vs collaborative planning",d:"Governance theory (analytic, from political science) explains policy through stakeholder networks, while collaborative planning theory (normative) wants more communicative action between those same stakeholders. Shows that theory OF planning and theory FOR planning overlap even though Rydin's book stays on the analytic side.",src:"text",p:"pp. 12-13"},
  {t:"Metropolis housing plan case",d:"Lecture case: a landowner offers 2,000 market-rate homes that comply with the rules and need no subsidy, while the city considers 1,600 homes with 40% affordable, priority for low-income households and a EUR 50 million public contribution. Shows that normative commitments decide what counts as the problem and what you measure when judging which plan is better.",src:"slides"}
 ],
 buit:[
  {t:"Room stress and housing ratio",d:"To set a sufficiency threshold for housing, Buitelaar cites the room stress factor (rooms available divided by rooms required, minus 1; below 0 is inadequate) and the 30% housing ratio, which he says says little without absolute income, hence the 'budget approach'. Shows that in the Supportive City the key task is defining and measuring the threshold.",src:"text",p:"pp. 358-359"},
  {t:"Redlining as an unjust rule",d:"Refusing mortgages because a home is in a marginalised neighbourhood or postcode, regardless of the applicant's borrowing capacity, is unjust from a liberal view because it breaches equal rights. Shows the Free City's rules: negative and universal (Hayek's 'negative test of universality'), removing unjust conduct rather than steering outcomes.",src:"text",p:"p. 361"},
  {t:"The buy-to-let investor",d:"An investor who legitimately buys and rents out many properties ends up owning far more than owner-occupiers; eyebrows may be raised, but for liberalism this is no injustice. Shows Nozick's entitlement theory: a distribution is just if acquisition and transfer were legitimate, whatever pattern results.",src:"text",p:"p. 361"},
  {t:"Sen's bicycle",d:"A bike is a commodity, the pleasure of riding it is utility, but what counts is the capability to ride it or choose not to; for a disabled person the bike itself is of little use. Shows the capability approach (positive freedom) and why it departs from resource-based conceptions like Rawls's primary goods.",src:"text",p:"p. 362"}
 ],
 hall:[
  {t:"The graduate planner 1955-1975",d:"Hall's caricature: in 1955 the new planner sat at the drawing board drawing land uses, in 1965 analysed computer output of traffic patterns, and in 1975 talked late into the night with community groups. Shows the shift from craft to systems science to advocacy, and the loss of the planner's claim to unique expertise.",src:"text",p:"p. 400"},
  {t:"Altshuler's Minneapolis-St Paul",d:"Altshuler found the professional planner had no clout against the political machine, which backed the highway engineers; they won by stressing expertise and narrow goals. Shows the pluralist critique from the right: real decisions are political, far from the 'cool, rational, Olympian' style of the systems texts.",src:"text",p:"pp. 397-398"},
  {t:"Paris clearances, US zoning",d:"Marxists argued planning always solves one problem by creating another: 19th-century clearances in Paris created a working-class housing problem, and American zoning limited industrialists' most profitable locations. Shows the Marxist view that planning can modify but never remove the contradiction between private accumulation and collective action.",src:"text",p:"p. 403"},
  {t:"Berlage's Plan Zuid",d:"The knowledge lecture illustrates 'planning as a craft' with Berlage's Plan Zuid for Amsterdam (1904/1915): a detailed, aesthetic blueprint plan. Shows the pre-1955 design tradition where there was theory in planning but no theory of planning.",src:"slides"}
 ],
 know:[
  {t:"B, B1 and B2 in housing",d:"Rydin's own illustration: B is the expected housing shortage, B1 the planned match of supply and need, and B2 the actual result of profitable developments alongside continued overcrowding, housing stress and homelessness. Shows why planning needs outcome (B2) and process knowledge, not just knowledge of the goal.",src:"text",p:"MS p. 15"},
  {t:"Local ill-health vs risk experts",d:"Experts often present a community's view of an environmental risk as exaggerated, yet local experience such as episodes of ill-health can be a basis to challenge the expert assessment. Rydin adds that not all community risk perceptions are therefore knowledge, so shows the need to separate knowledge claims from other claims and test them (closing down).",src:"text",p:"MS pp. 9-10"},
  {t:"Market prices or child poverty",d:"Describing an area's affluence with market prices or with child poverty makes a difference. Shows that even descriptive (empirical) knowledge is value-laden in its framing and carries an implicit causal story.",src:"text",p:"MS p. 17"},
  {t:"Utrecht and Rijnenburg claims",d:"Lecture exercise: 'car ownership in Utrecht fell by 12% (2015-2023)' is empirical; 'housing demand in Rijnenburg will exceed supply by 2030' is predictive; 'densification near stations reduces car dependency' and 'participation produces better plans' are process claims; 'Rijnenburg should prioritise affordability over aesthetics' is normative. Shows how Rydin's typology tells you which arena and test each claim needs.",src:"slides"}
 ],
 marx:[
  {t:"Workers in the industrial revolution",d:"HC4 slides: with the shift from an agricultural to an industrial economy, workers no longer transformed matter for their own use but commodified their bodies for a small wage. Shows estrangement from the product and from the act of production.",src:"slides"},
  {t:"'Better pay for slaves'",d:"The slide quotes Marx: an enforced rise in wages would be nothing more than better pay for slaves and would not raise human significance or dignity. Shows the structural argument: fixing outcomes within wage labour and private property does not end alienation, only changing the base does.",src:"slides"},
  {t:"Lenin on the transitional state",d:"The slides quote Lenin that the state must persist until capitalist resistance is crushed and there are no classes, as the step from capitalist state to socialist state to stateless society. Shows the deliberate, structure-changing route to material equality in Marxist thought.",src:"slides"},
  {t:"Red Vienna's municipal housing",d:"Between the wars the Social Democratic city government of Vienna built tens of thousands of municipal flats at low rents, such as the Karl-Marx-Hof (1927-1930). Shows decommodified housing in the Madden and Marcuse sense, though as reform within capitalism rather than Marx's abolition of private property.",src:"similar"}
 ],
 hayek:[
  {t:"A journey with no destination",d:"People agreeing on central planning without agreeing on its ends are like a group committing to travel together without agreeing where to go, so most end up on a journey they do not want. Shows Hayek's claim that agreement exists only on the mechanism, which pushes decisions to experts.",src:"text",p:"p. 46"},
  {t:"The general vs the planner",d:"A general can be handed one supreme goal for a campaign, but an economic planner must choose between the conflicting ends of different people, so experts end up imposing their own scale of preferences. Shows why delegating planning is not just delegating technical detail.",src:"text",p:"p. 48"},
  {t:"Halevy's composite photograph",d:"Halevy suggested a composite photograph of Eustace Percy, Oswald Mosley and Stafford Cripps would show one shared feature: the belief that only dictatorial leadership could end economic chaos. Shows Hayek's 'cry for an economic dictator' as a stage on the road from planning to plebiscitarian dictatorship.",src:"text",p:"p. 50"},
  {t:"Zoning as a tax",d:"The HC4 slide pairs Hayek with Glaeser and Gyourko (2003): zoning strictness correlates with high prices, a few subsidised units barely affect prices, but cutting the 'zoning tax' on new construction could have a massive impact. Shows the liberal planner's role: set a level framework rather than limit supply or steer outcomes.",src:"slides"}
 ],
 cozz:[
  {t:"Standards forbid the old city",d:"Cozzolino notes that recreating the physical pattern of the traditional city today would be blocked by prescriptions such as minimum road widths, building distances, parking and green-space standards. Shows the shift from proscriptive rules ('thou shalt not') to prescriptive rules that lower adaptive capacity.",src:"text",p:"p. 207"},
  {t:"Self-build still rare",d:"In 2015, self-building made up only 10-15% of new housing in the Netherlands and the UK, even though they are seen as leading nations. Shows demand-driven development and distributed design control as the alternative to supply-driven, all-at-once large projects, and how marginal it still is.",src:"text",p:"pp. 214-215"},
  {t:"Historic quarters can lock in",d:"Because of preservation policies and restrictive rules, old historic quarters sometimes show the typical problems of an AAN. Shows that anti-adaptiveness comes from rules and design control, not from age or form, and raises the question whether preservation and adaptability can be reconciled.",src:"text",p:"p. 216"},
  {t:"Amsterdam's Bijlmermeer",d:"Listed by Cozzolino among Europe's AANs (note 1), the Bijlmermeer was built in one go from the late 1960s as high-rise honeycomb blocks with large collective green space; from the 1990s a top-down renewal demolished part of it and added low-rise, more often owner-occupied homes. Shows the lock-in and the costly central regeneration ('paternalistic circle') that AANs tend to need.",src:"similar"}
 ]
};
