const EX_2={
 gov:[
  {t:"Energy planning in Escamp, The Hague",d:"Hettinga et al. piloted a Geodesign decision support system in Escamp with 12 municipal sustainability officers, a touch table and real-time impact assessments, ending in three agreed boundary conditions and a neighbourhood energy plan. Shows the governmental model's decision-support theme: better data and tools help planners choose the best means, with stakeholders involved instrumentally.",src:"text",p:"pp. 26-28"},
  {t:"Chongming Eco Island evaluation",d:"The official self-assessment found 19 of 22 indicator targets for 2014 met, but Ma et al.'s broader evaluation matrix found no sustainable transport, poor waste sorting and little gain for residents. Shows implementation and evaluation research that still judges outcomes against the plan itself (plan implementation).",src:"text",p:"pp. 29-31"},
  {t:"Tourism scheme at Ria de Aveiro",d:"A 309-home tourism development on a lagoon sandbar in Portugal was scaled down after EIA negotiations, then refused when a new national government's commission raised coastal erosion. Pinho uses it to show discretion and negotiation inside the planning steps, and how separated procedures block the integrated, balanced view the model promises.",src:"text",p:"pp. 31-33"},
  {t:"Post-war housing norms (Voorschriften en Wenken)",d:"The lecture shows Dutch post-war social housing (1945-1965), when the ministry's 'Voorschriften en Wenken' decided centrally what a home should be. An example of the governmental model institutionalised: experts fix the right means for politically given housing goals.",src:"slides"}
 ],
 scott:[
  {t:"Brasília's unplanned city",d:"The construction workers (candangos) organised to claim land, services and title; by 1980, 75 percent of Brasília's population lived in settlements the plan never anticipated, while the planned city reached less than half its projected 557,000. Shows Scott's point that the legible, ordered centre depended on an unplanned city at the margins.",src:"text",p:"p. 134"},
  {t:"Chandigarh's empty monumental squares",d:"Le Corbusier replaced housing planned for the centre with an 'acropolis of monuments' on a 220-acre site, swapped crowded bazaars for huge squares that now stand largely empty, and street traders were banned from the centre. Shows functional segregation and order seen from above killing street life, again with an unplanned periphery.",src:"text",p:"pp. 112, 136"},
  {t:"The despised East Harlem lawn",d:"Jacobs describes a housing project lawn that residents treated with contempt, because in a project of strangers they could not get a newspaper, a coffee or borrow fifty cents. Shows the gap between visual order and experienced, functional order.",src:"text",p:"p. 137"},
  {t:"Eyes on Boston's North End",d:"Dense shops, bars and bakeries kept the North End busy all day, so shopkeepers, passers-by and elderly people at windows watched the street; on Jacobs's own street, neighbours and shopkeepers gathered to stop a possible abduction without any police. Shows informal, mixed-use order ('eyes on the street') that single-use planning cannot design.",src:"text",p:"p. 139"}
 ],
 davoudi:[
  {t:"DEFRA's definition of evidence",d:"DEFRA defined evidence as 'any information that helps turn DEFRA's strategic priorities into something concrete, manageable and achievable'. Shows Weiss's 'interests' and the political/tactical model: evidence is sought to justify priorities already decided.",src:"text",p:"p. 19"},
  {t:"Inconclusive evidence on high density",d:"Studies on the costs and benefits of high-density housing remained inconclusive and open to value-based readings, yet policy already treated high density as the route to sustainable communities. Shows that evidence is often incomplete or contested and that policy does not wait for it.",src:"text",p:"pp. 20-21"},
  {t:"PPS12 'test of soundness'",d:"The 2004 English reform required plans to rest on a 'robust and credible evidence base', but early practice made soundness a procedural tick-box exercise rather than a test of which growth strategy is better. Shows evidence used in a quasi-judicial sense (reasoned justification) instead of substantive knowledge of how cities work.",src:"text",p:"pp. 21-22"},
  {t:"Nobody knows where waste goes",d:"A House of Commons report said of hazardous waste flows that 'no-one seems to have a clue what is going where', because strategic waste planning had not been treated as a policy problem worth research. Shows that 'research for policy's sake' is selective: evidence exists mainly where policy already looks.",src:"text",p:"pp. 15-16"}
 ],
 alex:[
  {t:"The 'ritual response' in planning",d:"Alexander notes that much planning education and practice keeps following the rational model with only token acknowledgement of its anomalies. Illustrates why rationality survives as the normative basis of planners' claims to expertise even after the paradigm broke down.",src:"text"},
  {t:"Mediation: communicative or strategic?",d:"Mediation, conflict resolution and arbitration belong in the real, collective, consensus-oriented cell only when carried out by a neutral participant or a consensus-oriented group, which Alexander calls rare; once actors pursue their own goals, the same process is strategic action (bargaining, negotiation). Shows how the contingency framework sorts one practice by the actor's purpose.",src:"text"},
  {t:"Linear programming versus satisficing",d:"Formal optimisation such as linear programming and multi-objective decision-making sits in the ideal, individual cell, while satisficing, disjointed incrementalism and mixed scanning describe how individuals actually decide (real, individual cell). Shows the ideal/real split: rationality works as a norm, not as a description.",src:"text"}
 ],
 rc:[
  {t:"Coase's noisy factory",d:"Quiet is worth €1,000 to the homeowner and insulation costs the factory €700; whoever holds the right, bargaining leads to insulation and only who pays whom changes. Shows Coase's theorem, which holds only if rights are clearly defined and transaction costs are zero.",src:"slides"},
  {t:"Utrecht's short-stay rules (2018)",d:"Utrecht set a limit of 60 nights a year, a guest cap per m2, a registration number, a reporting duty and fines from €150 to €21,750. Rational choice scholars expect such one-size-fits-all rules to struggle with detection, platforms withholding data, enforcement transaction costs and waterbed effects.",src:"slides"},
  {t:"Swiss farmland law and densification",d:"Bouwmeester's hypothesis: Swiss law (BGBB) blocks farmland sales at more than 5-15 percent above agricultural value and bars non-farmers from buying farmland, so no speculative outsider lobby pushes for expansion and insider owners gain scarcity rents from inward growth. Shows property rules shaping incentives so that supporting densification becomes the rational strategy.",src:"slides"},
  {t:"Dutch planschade compensation",d:"Dutch owners can claim compensation (planschade, under the Omgevingswet 'nadeelcompensatie') when a new plan lowers their property's value, while value gains from upzoning are not taxed as such. A close case of the asymmetry on the slides: landowners keep betterment but claim planning damages.",src:"similar"}
 ],
 needham:[
  {t:"Covenants in US housing estates",d:"In the US (private community associations) and less often England, buyers sign covenants against changes that harm the estate and a residents' association enforces them; in the Netherlands this is not legally binding because owners cannot be obliged to join such an association. Shows an interest turned into a property right, and how national property law decides whether a market alternative to planning exists.",src:"text",p:"pp. 31-32"},
  {t:"Foundations versus clean air",d:"A neighbour damaging my foundations is covered by a property right (the right of support) because cause, culprit and victim are clear and few; clean air is protected by public law (permits, emission limits) because effects are diffuse and hundreds of victims cannot organise a court case. Shows the partly technical, partly political choice between private-law and public-law protection of interests.",src:"text",p:"p. 28"},
  {t:"Privately owned public spaces",d:"Shopping malls, and small housing developments where residents own and maintain shared spaces that stay open to all, operate under planning conditions on public access and maintenance. Shows property rights deliberately created to deliver a certain type of urban environment.",src:"text",p:"p. 33"},
  {t:"US conservation agreements",d:"A public or private trust buys a farmer's development rights and never uses them, so the land stays open while the farmer keeps ownership. Shows a public planning goal pursued with private-law tools where regional interests are too dispersed for a market in rights.",src:"text",p:"p. 34"}
 ],
 olson:[
  {t:"Five students sharing a flat",d:"Keeping the flat clean is a potential collective action problem, but if one student hates squalor enough to clean alone, the others can free-ride and the good is still provided. Shows Olson's 'privileged group'.",src:"text",p:"p. 115"},
  {t:"Unions and free legal help",d:"Workers may join a union for free legal representation (positive selective incentive) or to avoid being ostracised, 'sent to Coventry' (negative incentive). Hindmoor adds that this still leaves a second-order problem: who organised the union or does the ostracising in the first place?",src:"text",p:"pp. 116-117"},
  {t:"Gossip on Israeli kibbutzim",d:"Members get housing and food regardless of effort, yet work hard because shirkers become targets of vicious gossip, and gossiping is enjoyable in itself. Shows process benefits solving the second-order problem, helped by the fact that leaving a kibbutz is hard.",src:"text",p:"pp. 118, 120"},
  {t:"Cooperation in First World War trenches",d:"Soldiers facing each other for long periods evolved norms such as firing only at set times, once even playing football on Christmas day; commanders then rotated troops to erode that trust. Shows conditional cooperation needs stable membership and repeated interaction.",src:"text",p:"p. 120"}
 ],
 taylor:[
  {t:"Melbourne's 'liquid gold' fringe land",d:"Rural land around Melbourne worth $15,000 to $35,000 per hectare averaged $365,000 once inside the UGB and rezoned, and after the 2010 shift prices inside rose 89 percent relative to comparable land outside. Shows betterment, an unearned increment created by planning, which the GAIC ($95,000 per hectare) aimed to tax.",src:"text",p:"pp. 259, 261-262"},
  {t:"Grassland owners versus lifestyle homevoters",d:"21 owners whose land in the west was to become protected grassland called the rules unfair and wanted in, while hobby farmers argued to keep green wedge restrictions protecting their amenity. Shows Taylor's two rent-seeking interests: premium-seeking to unlock development value versus homevoters defending restrictions.",src:"text",p:"p. 268"},
  {t:"Owners with development plans stayed quiet",d:"Only 4 of 49 landowners with development plans objected to the GAIC, against 72 of 137 without such plans. Those who knew their development value saw the charge as small against the gain; opposition came from owners who framed it as a tax on existing value.",src:"text",p:"pp. 270-271"},
  {t:"Taxed Out! and 'purchaser pays'",d:"The Taxed Out! campaign cast the GAIC as a tax on existing land value; the bill was redrafted to exempt 0.41 to 5 hectare parcels (about 56 percent of liable parcels) and shift liability to purchasers, and in 2011 fully deferred to development. Shows insiders shifting the cost of value capture onto outsiders, future homebuyers.",src:"text",p:"pp. 269-273"}
 ],
 ni:[
  {t:"Eurovision: organisation versus institutions",d:"The European Broadcasting Union is the organisation; its statutes and the formal and informal rules of the contest are the institutions. Shows the neo-institutionalist distinction between the rules of the game and its players.",src:"slides"},
  {t:"Ostrom's rules for a fishery",d:"The IAD slide illustrates rule types with fishing: membership rules for the cooperative (boundary), permitted gear (choice), catch reporting (information), fines for breaking quotas (payoff), off-limits areas and protected species (scope). Shows rational choice institutionalism: users craft rules to avoid the tragedy of the commons.",src:"slides"},
  {t:"Housing morphology in three regions",d:"Tennekes, Harbers and Buitelaar (2015) link different institutional arrangements in the Netherlands, Flanders and North Rhine-Westphalia to different morphologies of residential development. Shows institutions as context and object of planning, visible in space.",src:"slides"},
  {t:"Amsterdam-Noord's shipyard symbols",d:"Savini and Dembski (2016): a new development agenda for Amsterdam-Noord was enabled by symbols linking the industrial shipyard past to a creative-economy future, which mobilised consensus. Shows sociological institutionalism: planning as creating meaning.",src:"slides"}
 ],
 dembski:[
  {t:"Pearl River Delta and Flemish Diamond",d:"Metaphors meant to express a coherent Hong Kong-Shenzhen-Guangzhou region and a polycentric Flemish city network had little effect: the first is 'mission impossible', the second stays an idea in planners' minds. Shows that symbolic markers are not self-mobilising without institutional embedding.",src:"text",p:"pp. 611-612"},
  {t:"Bilbao, Poitiers and 'silicon valleys'",d:"The Guggenheim has not yet turned industrial Bilbao into a cultural city, the Futuroscope has not made Poitiers a technology centre, and genuine silicon valleys are few. Shows landmarks detached from institutionalised practices failing to enhance social meaning.",src:"text",p:"p. 612"},
  {t:"Green Heart and London Green Belt",d:"These concepts are seen as successful on their own terms, but they aim at preservation, not transformation. Shows why the paper's puzzle is about markers of change: a symbol that confirms existing institutions has an easier job.",src:"text",p:"p. 612"},
  {t:"A master's degree as rite",d:"Following Bourdieu, ageing is gradual, but rites of institution consecrate an arbitrary boundary (child, adolescent, adult), and the social magic of an amulet does not differ from a master's degree. Shows how symbols institute new social meaning when the audience believes in them.",src:"text",p:"p. 620"}
 ],
 moroni:[
  {t:"Hume on property and language",d:"Hume describes the rule of stable possession as a convention that arises gradually from repeated experience of the costs of breaking it, 'without the interposition of a promise', just as languages do. Shows the evolutionary view: key institutions emerge from human action, not human design.",src:"text",p:"pp. 278-279"},
  {t:"Jacobs and Schelling as invisible hands",d:"Moroni cites Jacobs's account of what makes city places safe and Schelling's model of residential segregation as invisible-hand explanations: patterns produced by dispersed individual actions aimed at other ends. Shows why many social orders should not be explained, or reformed, as if someone designed them.",src:"text",p:"p. 281"},
  {t:"The Oracle of Delphi",d:"'The cryptic utterances of the Oracle of Delphi did not create effective institutions', and neither does obscure or short-lived legislation. Illustrates the principle of knowability: rules must be known in advance so people can act on them.",src:"text",p:"p. 284"},
  {t:"Bastiat's daily-fed metropolis",d:"Bastiat marvels that a city of a million people is supplied every day without anyone directing it, thanks to 'freedom in transactions'. Moroni uses it for the principle of modesty: recognise evolved institutions such as contract and ownership instead of inventing new ones.",src:"text",p:"p. 285"}
 ],
 sorensen:[
  {t:"Ontario's 1946 Planning Act",d:"Permissive conditions were weak regulation before an expected post-war boom, suburban debt (10 of 12 suburbs needed a provincial bailout in the Depression) and a wartime shift toward intervention; as productive condition, a new Conservative majority passed a more limited law than any proposal on the table. Shows a critical juncture whose ambiguities started a reactive sequence of contestation.",src:"text",p:"pp. 1809-1810"},
  {t:"Lot levies without legal basis",d:"The 1946 Act did not mention lot levies, but suburbs used their subdivision approval power to demand them; after court challenges and OMB appeals, the province amended the Act in 1959 and retroactively affirmed existing agreements. Shows incremental institutional change within a developmental pathway.",src:"text",p:"p. 1811"},
  {t:"Amalgamation: practice changed, rules not",d:"After the 1997 amalgamation and provincial cuts, Toronto began charging development charges in 2001 (from zero to almost $700 million in 2020) and negotiated 697 Section 37 agreements worth $744 million (1998-2018). Sorensen calls this a change of practice within existing formal institutions, not a critical juncture for value capture.",src:"text",p:"p. 1812"},
  {t:"Vancouver captures 70 percent",d:"Vancouver's community benefits agreements routinely capture 70 percent of rezoning uplift, while Toronto planners targeted 10 to 15 percent, now capped at 4 percent by recent legislation. Shows how locally contingent, path-dependent value capture institutions diverge.",src:"text",p:"p. 1815"}
 ]
};
