const EX_3={
 harvey:[
  {t:"The 1985 Orleans colloquium",d:"Academics, business people and policymakers from eight large cities in seven advanced capitalist countries agreed that city governments had to become more innovative and entrepreneurial; they disagreed only on how. Harvey uses it as a symptom of the shift from managerialism to entrepreneurialism, a consensus that holds across national borders, parties and ideologies.",src:"text",p:"p. 4"},
  {t:"Sheffield's Labour council",d:"David Blunkett, Labour leader in Sheffield, endorsed a local brand of entrepreneurship: support for small firms, public-private links and promotion to attract business. Harvey warns that inside zero-sum inter-urban competition even 'avantgarde municipal socialists' end up playing the capitalist game and disciplining the processes they try to resist.",src:"text",p:"pp. 4–5"},
  {t:"New Orleans versus Vancouver fairs",d:"New Orleans, already dependent on federal redistribution, staged a 'disastrous' World Fair that drove it deeper into the mire, while an already booming Vancouver hosted a very successful World Exposition. Shows the speculative, high-risk character of entrepreneurial projects and the instability that inter-urban competition brings to the urban system.",src:"text",p:"p. 13"},
  {t:"Festival marketplaces losing money",d:"A decade after being hailed as an 'Alladin's lamp' for struggling cities, Rouse projects in Richmond, Flint and Toledo were losing millions, and even South Street Seaport (New York) and Riverwalk (New Orleans) hit severe financial trouble. Illustrates serial reproduction: copied harbour places and malls make any competitive advantage ephemeral and risk a 'quagmire of indebtedness'.",src:"text",p:"p. 13"}
 ],
 fog:[
  {t:"Amsterdam's ground lease system",d:"Since 1896 Amsterdam has kept much of its land in municipal ownership and issued it on long-term ground lease (erfpacht) instead of selling it. A Dutch case of the property contradiction: the city treats land's value and use as socially produced and steers it publicly, while buildings and use rights remain private.",src:"similar"}
 ],
 hh:[
  {t:"State real estate companies, 1995",d:"Finland closed the National Board of Public Building and founded state real estate companies (Kapiteeli, Senaatti, Sponda) that seek to maximise land rent; one then demanded the price of developed land when selling state land to Helsinki, which defended its planning monopoly. Shows entrepreneurial public real estate policy at state level: the state became one market player among others and lost its impartial, mediating role.",src:"text",p:"p. 138"},
  {t:"Hunting 'good taxpayers'",d:"Real Estate Committee members said a main aim of the Eiranranta sale was to lure high-income residents from Espoo and Kauniainen so they would pay income tax to Helsinki, and to compete with Copenhagen, Stockholm and Tallinn for image. The authors read this, with Harvey, as inter-city competition pushing a shift from managerial to entrepreneurial strategies.",src:"text",p:"p. 140"},
  {t:"Apollo versus the household developers",d:"Newcomer investment company Apollo bid €3 million more than the established developers, whose bids were suspiciously close; the Real Estate Department preferred Skanska despite its lower bid. The authors suggest established developers routinely undervalue land to extract the value increase that belongs to the city, so the fight was really over who captures land rent from public development rights.",src:"text",p:"pp. 141, 143"},
  {t:"Dutch land write-offs after 2008",d:"Many Dutch municipalities ran an active land policy, buying land and selling serviced plots at a profit; when the market collapsed after 2008 they had to write off large sums on their land holdings. Same mechanism as in Helsinki: a municipality that acts as a land entrepreneur takes on market risk and lets revenue logic steer planning.",src:"similar"}
 ],
 savini:[
  {t:"PSTA: the locally embedded phase",d:"When steelmaking ended in 1994 the Falck site was first handled by a development company owned 80% by the municipality, 5% by the province and 15% by Falck, drawing on EU programmes to reconvert the site and save jobs; the booming housing market then pushed Falck to drop reindustrialisation and sell. Shows the starting point before de-contextualisation: a financial set-up tied to local actors and local economic needs.",src:"text",p:"p. 10"},
  {t:"Risanamento: clustering, then collapse",d:"In 2005 Risanamento (Gruppo Zunino) bought the SPV with little capital, bundled Falck with projects like Santa Giulia, and had Renzo Piano draw a plan with almost double the floor space, aiming at 15% gains on about €5 billion. In 2009 the credit crunch and Risanamento's heavy debt (part of its holding's €3 billion debt) triggered bankruptcy proceedings and a forced sale, events 'completely alien' to local planning. Illustrates clustering and how financial decisions made elsewhere drive the planning programme.",src:"text",p:"pp. 11–12"},
  {t:"Industrial firms turned land developers",d:"In Milan non-real-estate corporations that owned land in key locations became developers, for example Pirelli in Bicocca, alongside investors such as Hines at Garibaldi. Shows land becoming a financial asset for former industrial groups, part of the relocation and clustering trends the paper describes.",src:"text",p:"p. 9"},
  {t:"Approval bought with public money",d:"The council approved the Sesto Immobiliare masterplan in 2011 with more retail and offices and less high-end housing and manufacturing, while the regional government put €323 million into a health and research campus on the site. Illustrates instrumental planning: public tools and investment used to unlock a financially stuck project rather than to answer local needs.",src:"text",p:"p. 13"}
 ],
 rydin6:[
  {t:"Turin's post-industrial urban regime",d:"Ravazzi and Belligni trace a 'great alliance' of Centre-Left politicians, liberal business leaders (the Group of 70, led by a banker) and Politecnico academics that pushed Turin from a pro-welfare to a market-centred agenda of housing, infrastructure, a knowledge district and tourism. Shows Stone's urban regime as 'power to' act, built through naming, blaming and claiming.",src:"text",p:"pp. 113–114"},
  {t:"The Green Tea Coalition",d:"In Georgia, Tea Party conservatives and progressive groups including a Sierra Club chapter jointly opposed a transport sales tax and later backed solar power, while never agreeing on climate change. Trapenberg Frick uses such tactical coalitions to show agonism in practice: adversaries cooperate on points of convergence and agree to disagree on the rest.",src:"text",p:"pp. 119–120"},
  {t:"REDWatch in Sydney",d:"A community group in a low-income, public-housing area south of Sydney's CBD monitored state redevelopment plans and posted documents that vanished from government websites, acting as an 'inconvenient corporate memory'. Government planners then used its monitoring to argue internally for different outcomes, showing agonistic, informal action can gain influence alongside formal participation.",src:"text",p:"pp. 120–121"},
  {t:"Denniston Plateau coal mine",d:"Protests and a community 'Bioblitz' accompanied the consent process for a coal mine in Aotearoa New Zealand. Fougère and Bond find that antagonism dominated, that expert knowledge helped keep the process post-political, and that antagonistic conflict can still open up space for agonism.",src:"text",p:"pp. 121–122"}
 ],
 bossuyt:[
  {t:"Marisa Letícia",d:"A former warehouse site owned by the national social security institute (INSS), designated for social housing in the late 1990s but left idle; the ULC occupied it on and off through the 2000s until it joined MCMV-Entidades in 2013; it was completed in 2019 and occupied from 2020. Unlike Dandara, the state bought and donated the land and it became a condominium with individual titles: regularization protects against eviction but turns collective claims into private property, opening new routes to enclosure.",src:"text",p:"pp. 1028–1032"},
  {t:"Prestes Maia building",d:"A former textile factory that once housed 2,000 people in one occupation went through three occupations and two evictions before its renovation became possible in 2022 through the municipal Pode Entrar programme. Shows how precarious appropriation is without structural coupling to state programmes and property regimes.",src:"text",p:"p. 1028"},
  {t:"Wilton Paes de Almeida fire",d:"In 2018 a fire in this occupied building killed four people, with five more missing. The disaster highlights the precarity of long occupations, and the ULC has since shifted mostly to shorter, political occupations aimed at forcing negotiations rather than long-term shelter.",src:"text",p:"pp. 1026–1027"},
  {t:"Ideas from Uruguay's cooperatives",d:"Exchanges with the Uruguayan Federation of Housing Cooperatives in the 1980s shaped Brazilian movements' thinking on cooperative building and self-management. The authors use this as an example of 'ideation': commoning knowledge stored in movements that later materializes in projects like Dandara.",src:"text",p:"pp. 1034–1035"}
 ],
 pruijt:[
  {t:"Amsterdam: legalize and keep fighting",d:"Amsterdam bought about 200 squatted buildings and handed most to housing associations, which gave squatters leases; squatters also joined planning in areas like the eastern docklands. Yet the movement kept its disruptive repertoire (the 1980 coronation riots, defending warehouses in 2000), Pruijt's case of flexible institutionalization, where conventional tactics complement rather than replace disruption.",src:"text",p:"pp. 7–8"},
  {t:"Lower East Side legalization, 2002",d:"Eleven squatted buildings on the Lower East Side were legalized in 2002 through UHAB, with no direct talks between squatters and the city, and only once no squattable buildings were left. Pruijt classifies this as terminal institutionalization: integration that marks the end of the movement.",src:"text",p:"p. 11"},
  {t:"Tenant Interim Lease programme",d:"From 1976 New York let tenants self-manage tax-foreclosed city buildings with a route to cooperative ownership; nearly 1,000 buildings joined by 1996, but these projects got less than half the normal housing subsidy and keeping buildings afloat absorbed activists' energy. Illustrates the 'privatization of poverty': self-help as a cheaper substitute for state provision that turns organizers into managers.",src:"text",p:"p. 9"},
  {t:"The 1971 Supreme Court ruling",d:"In 1971 the Dutch Supreme Court applied 'house right' to squatters, so owners could no longer simply evict them from an unused building; later laws chipped away at this (for example making it illegal to squat buildings empty for under a year from 1994). Shows how legal protection of property shapes the opportunity structure: long-lasting, open squats were possible in Amsterdam but not in New York, where squatters hid and stuck to city-owned buildings.",src:"text",p:"pp. 14–15"}
 ],
 raco:[
  {t:"New Deal for the unemployed",d:"The New Deal combined counselling to raise self-esteem with training to build skills. Raco and Imrie cite it as a 'technology of citizenship': empowerment used to turn powerless subjects into active, self-governing citizens who take responsibility for their own welfare.",src:"text",p:"p. 2191"},
  {t:"Best Value and peer review",d:"Best Value required councils to adopt new disciplines of value for money and efficiency, with central action if they failed to act 'responsibly'; Best Practice guidelines made SRB bidders adjust their conduct to the scrutiny of other bidders. Governing at a distance: discipline that works through self-monitoring and peers rather than direct central orders.",src:"text",p:"p. 2199"},
  {t:"Tenant participation in social housing",d:"DETR guidance on tenant participation calls for a 'proper balance of rights and responsibilities', but tenants who gain a say must follow public service rules and accept the council's ultimate responsibility for strategic decisions. Communities of obligation: rights to take part come bundled with centrally defined duties.",src:"text",p:"pp. 2195–2196"},
  {t:"Dutch 'participation society' (2013)",d:"In the 2013 King's Speech the Dutch government announced a shift from the welfare state to a 'participatiesamenleving', in which citizens are expected to take more responsibility for their own lives and neighbourhoods. A close Dutch analogue of the rights and responsibilities agenda and the governmentality of active citizenship.",src:"similar"}
 ],
 gurran:[
  {t:"The shortage that social housing explains",d:"In 2008 the National Housing Supply Council estimated a shortfall of about 85,000 dwellings, yet also found that keeping social housing output at its 1996 level would have added about 90,000, a modest surplus. This undercuts the industry's 'regime of truth' that planning red tape is the main cause of the shortage.",src:"text",p:"p. 6"},
  {t:"Affordable housing quietly wound back",d:"Shelter NSW proposed levying developers for affordable housing where rezoning creates value uplift, but the draft Planning Bill actually cut existing affordable housing contribution provisions. The authors conclude affordability served as a 'semantic justification' for deregulation rather than a real policy aim.",src:"text",p:"p. 14"},
  {t:"The 'Hazzard tape' protest",d:"The Better Planning Network, a coalition of over 300 resident groups and local government representatives, wrapped Planning Minister Brad Hazzard in yellow 'Hazzard' tape, and by the end of 2013 the Bill stalled in parliament. Shows that the industry's discursive dominance inside formal consultation could still be blocked by electoral power and direct action outside it.",src:"text",p:"p. 15"},
  {t:"Record approvals, rising prices",d:"Under the unreformed planning system NSW housing approvals reached a 20-year high, almost doubling between December 2011 and 2014, while Sydney's median house price still rose from $535,000 to $735,000. Evidence against the claim that planning blocks supply and that more supply alone restores affordability.",src:"text",p:"pp. 15–16"}
 ]
};
