const EX_4={
 p1:[
  {t:"Greater Oslo travel gradient",d:"Survey data from Greater Oslo show that residents living further from downtown travel more by motorised modes, even after controlling for socio-economic factors (Figure 1). Næss uses this to back the compact city as the most energy-conscious urban form, a substantive planning goal rather than a procedural one.",src:"text",p:"pp. 508-509"},
  {t:"Nordic floor space doubled",d:"Each Norwegian and Dane has on average more than 50 m² of residential floor area, twice as much as 30 to 35 years earlier and about 70% more than affluent Japan. This is his core case for per-capita degrowth of the building stock: efficiency gains in new buildings are cancelled out by ever more floor space.",src:"text",p:"p. 512"},
  {t:"NAMIT trend vs environmental scenario",d:"The Norwegian research project 'Environmentally Sound Urban Development' (NAMIT) compared a 'trend' and an 'environmental' scenario for three urban areas; its dissemination raised planners' awareness and probably contributed to less sprawling development in Norway in the 1990s. It illustrates his proposal of scenarios as a way to make long-term sustainability goals concrete and debatable.",src:"text",p:"p. 519"},
  {t:"Aalborg: power beats good plans",d:"Næss cites Flyvbjerg's study of a prize-winning environmental project in Aalborg whose implementation was distorted, concluding that planners need influential alliance partners and strategic skills. This is why he prefers alliance-building among supporters of sustainability over consensus with all stakeholders, including those who profit from unsustainable development.",src:"text",p:"p. 519"}
 ],
 p2:[
  {t:"From Ecotopia to compact city",d:"Callenbach's novel Ecotopia (1975) imagined abolishing cars and economic growth altogether, while by 1985 Peter Calthorpe argued the city is 'the most environmentally benign form of human settlement' and in 1998 the Sierra Club cast sprawl as an ongoing catastrophe. This shows the sprawl root: the solution shifted from 'less city' (limiting growth) to 'more city' (density).",src:"text",p:"pp. 2205-2206"},
  {t:"'How slums can save the planet'",d:"In 2010 Stewart Brand called informal settlements 'unexpectedly green' because of their density, and places like Dharavi in Mumbai came to be celebrated as hotbeds of creativity; in 2016 Alejandro Aravena won the Pritzker Prize for housing based on informal settlements' incremental growth. This is the informal-settlement root: from environmental problem to model for sustainable urbanism.",src:"text",p:"p. 2207"},
  {t:"Chicago Climate Charter",d:"After Trump announced the US withdrawal from the Paris Agreement, mayors in Canada, Mexico and the USA signed the Chicago Climate Charter to uphold the Paris targets anyway. It shows the climate root: as multilateral treaties floundered, cities and mayors were cast as the climate protagonists.",src:"text",p:"p. 2209"},
  {t:"Austin's revanchist green clean-up",d:"Tretter (2013) showed how the growth machine in Austin, Texas used environmentalism for a 'clean-up' of downtown that shifted the costs of growth onto the city's homeless population. It illustrates the authors' political research agenda: urban sustainability has become pro-growth and system-affirmative, and can exclude poorer residents.",src:"text",p:"p. 2214"}
 ],
 p3:[
  {t:"Noxious land uses as 'jobs'",d:"Poor urban communities are often forced to choose between economic survival and environmental quality when the only economic opportunities offered are incinerators, toxic waste sites and landfills that richer neighbourhoods can afford to refuse. Campbell uses this to show the development conflict (equity vs environment) and why environmental racism lies at its heart.",src:"text"},
  {t:"'Trickle-down environmentalism'",d:"Campbell quotes the Brundtland Report's call to revitalise global economic growth and labels the logic 'trickle-down environmentalism': grow the economy to afford environmental protection. He argues it only works if growth is fairly distributed, so the development conflict can only be solved together with the property conflict.",src:"text"},
  {t:"Coachella lizard and New Jersey plan",d:"The Coachella Valley Fringe-Toed Lizard Habitat Conservation Plan was praised as a model process, yet may not adequately protect the lizard; New Jersey's State Development Plan was praised for its cross-acceptance procedure but arguably did not alter sprawl. Both show the limit of procedural paths: a good process does not guarantee a sustainable outcome.",src:"text"},
  {t:"New York greenways (Checker)",d:"The slides cite Checker (2011) on 'environmental gentrification' in New York City's greenway and brownfield-to-park conversions, where new green amenities concentrated benefits among those who could afford to live nearby. It is the development conflict in practice: an environmental gain that undermines equity.",src:"slides"}
 ],
 p4:[
  {t:"Houtrakpolder: three claims, one polder",d:"The province of North Holland reserves the Houtrakpolder as a possible expansion area for the Port of Amsterdam, the municipality of Haarlemmermeer contests this, and the same polder is also considered for excess rainwater storage. The reservation is linked to Amsterdam's Haven-Stad housing plan, which will cost 135 ha of port sites. This is 'more claims than land' at the port-region level: port economy, housing and climate adaptation compete for one site.",src:"text",p:"p. 8"},
  {t:"Amsterdam's fossil phase-out",d:"Amsterdam decided in 2008 to allow no new terminals for transport fuels, closed one of three coal terminals in 2023 by not renewing its leasehold, and aims to phase out fossil fuel handling by 2030, freeing about 370 ha for hydrogen, electricity and circular industries. It shows how energy-transition claims reshuffle port land internally, and how leasehold works as a land-policy instrument.",src:"text",p:"p. 8"},
  {t:"Westpoort runs out of noise",d:"The Port of Amsterdam had to insulate homes in Zaanstad after an expanded noise zone, and some vacant port plots could not be allocated because there was no noise capacity left; the 2016 annual report warned of insufficient environmental space across Westpoort. It shows that 'environmental space' (noise, safety, emissions) is itself a claim on land: land can be physically empty yet unusable.",src:"text",p:"p. 8"},
  {t:"Maasvlakte II nature compensation lags",d:"The Voordelta nature compensation for the Second Maasvlakte was agreed to happen alongside construction rather than before it, but monitoring shows it lags behind the economic targets, and in 2024 the nature organisations that signed the covenant threatened to go to court. It illustrates the growing tension between environmental and economic claims even in Rotterdam, where more 'puzzling space' exists.",src:"text",p:"p. 9"}
 ],
 p5:[
  {t:"Chemie-Pack to 'Moerdijk regulation'",d:"After the 2011 Chemie-Pack chemical fire, Moerdijk moved from strategic planning (Port Vision 2030) to compensation planning (the 'Moerdijk regulation'), with investments of €10 million plus €8 million following the Committee Nijpels. It shows compensation planning: mitigating harm to residents rather than preventing the conflict between port and village.",src:"slides"},
  {t:"The village that stayed after all",d:"The slides link a news item on Moerdijk making way for industry and a later one titled 'the village that stayed after all', followed by renewed debate in 2025 on the village's future under PowerPort and the energy transition. It shows that fight, flight or freeze is not a one-off decision: new land claims from the energy transition can reopen it.",src:"slides"},
  {t:"Pernis, Rozenburg, Heijplaat: fight",d:"Witte lists these Rotterdam villages as 'fight' cases where the village stays while the port grows around it, with Doel (Antwerp) and Ruigoord (Amsterdam) marked with a question mark. They show that a village surviving inside a port region is possible, but its future stays contested.",src:"slides"},
  {t:"Delfzijl villages that gave way",d:"Weiwerd, Oterdum and Heveskes near Delfzijl are classed on the slides under 'freeze' (the village disappears), alongside Nieuwesluis and Blankenburg (Rotterdam) and the Antwerp port villages. They are the counterpoint to 'fight': the 'greater good' of port and industrial development won over the village. 'Flight' (the village relocates) is reserved for Kiruna and Immerath.",src:"slides"}
 ],
 p6:[
  {t:"Delhi's evictions 'in the public interest'",d:"Bhan (2016) shows how courts in Delhi appropriated the planning concept of acting 'in the public interest' to justify evictions of basti residents, some from long-established settlements. It illustrates rationality as power: a familiar planning norm is redefined to legitimise excluding the poor.",src:"text",p:"pp. 17-18"},
  {t:"Bogotá BRT, Brazilian participatory budgeting",d:"South-South borrowing (bus rapid transit from Bogotá) and even South-North borrowing (participatory budgeting from Brazil) are growing. The authors warn this often falls into the old 'best practice' trap, transferring models without understanding the contextual preconditions for success.",src:"text",p:"p. 17"},
  {t:"'Government knows what people want'",d:"Officials on the N2 Gateway knew community engagement should take place, but found it too daunting, and higher levels of government discouraged it on the grounds that a democratic government 'knows what the people want'. It shows the techno-managerial state rationality that clashes with residents' rationalities, and why consensus-based participation was never really attempted.",src:"text",p:"p. 4"},
  {t:"Mozambique: 7% state-built housing",d:"Of 86,300 houses built in Mozambique from 1980 to 1997, only 7% were supplied by the state, while master planning approaches that 'do not fit the realities of urban development' persisted. It shows the mismatch between imported planning models and how cities are actually built, largely informally.",src:"slides"}
 ],
 p7:[
  {t:"Four ministries, four time horizons",d:"Land use, urban-rural construction, main functional zone and environmental protection planning were run by four different ministries, with planning periods of 15, 20, 10 and 5 years respectively. This shows the fragmentation the NTSP reform targets: plans that could not align in timing or content, resolved by moving these functions into the Ministry of Natural Resources in 2018.",src:"text",p:"p. 4"},
  {t:"Same field, different land classes",d:"Urban-rural construction planning used a three-level land classification while land use planning used a two-level one, so farmland, forest and grassland were identified differently in different plans. It shows why 'multiple plans in one' and a single 'One Map' data base are needed before control lines can be enforced.",src:"text",p:"p. 3"},
  {t:"A hundred villages lost daily",d:"China's natural villages fell from 3.77 million in 1990 to 2.61 million in 2016, on average more than 100 villages a day, while more than 10,000 towns and street offices lost population between 2000 and 2010. The authors use this to argue that the urban development boundary and village planning must plan for shrinkage, not only growth.",src:"text",p:"p. 7"},
  {t:"Sino-Singapore Tianjin Eco-City",d:"Planned in 2008 on 30 km² of unusable land as a joint venture between a Tianjin investment group and Singapore state-owned enterprises, it combines water-saving, solar and green-building technologies with housing and industrial development. The lecture asks whether such top-down experiments change the wider planning system or remain isolated showcases, the problem the integrated NTSP is meant to address.",src:"slides"}
 ],
 p8:[
  {t:"London's bike hire scheme",d:"Greater London's scheme (from 2010, about 8,000 bikes and 500 docking stations by 2014) was run by Serco for Transport for London, sponsored by Barclays, and learned from Paris's Vélib; it built on a 2001 cycling strategy, the 2003 congestion charge and bus lanes open to cyclists. The authors use it to show that the innovation is not the bike but the process of embedding and reconfiguring existing systems.",src:"text",p:"p. 9"},
  {t:"Oxford electric, Brighton cycling",d:"UK research found 'clear differences' between city trajectories: Oxford promoted electric mobility, Brighton cycling innovations. It shows that reconfiguration is place-specific, since innovations that are radical in one city are the norm in another.",src:"text",p:"p. 9"},
  {t:"UK bus deregulation",d:"Although buses are organised mostly at the city scale, the UK state's deregulation and liberalisation of buses in the 1980s shaped local systems from above. It illustrates the multi-level governance theme: urban experiments sit within national arrangements that cities do not control.",src:"text",p:"p. 8"},
  {t:"Home working reduces travel",d:"Almost 14% of the UK workforce are 'home workers', which reduces the need to travel, but this results from economic restructuring and ICT, not from purposive mobility experiments. It shows why competing conceptions of sustainable mobility (reduce need to travel, modal shift, shorter trips, efficiency) are hard to govern through experimentation alone.",src:"text",p:"p. 11"}
 ],
 p9:[
  {t:"Concept House Village, Heijplaat Rotterdam",d:"Started in 2011 by Rotterdam and Delft universities as a test bed for sustainable building and retrofitting, it got the site because the economic crisis had stalled redevelopment of Heijplaat; once the market recovered, the municipality moved the area into mainstream development ('you got it for five years'). It is the civic demonstration type and shows how contingent and temporary ULLs are.",src:"text",p:"pp. 16-17"},
  {t:"MK: Smart, Milton Keynes",d:"A consortium of the Open University and the council bundled separate smart energy, transport and data projects into one platform with a Data Hub and the OurMK ideas site (55 ideas, 11 citizen projects funded). It is a civic platform, formed partly as a tactic to gain resources and capacity under austerity.",src:"text",p:"p. 15"},
  {t:"Hållbarheten, Malmö",d:"In this custom-designed apartment house the energy company E.ON enrols residents to test energy-smart solutions to judge whether the technologies are viable at a larger scale. It is the strategic demonstration type: a corporate-led showcase for specific technologies.",src:"text",p:"p. 11"}
 ],
 p10:[
  {t:"Zwolle's inclusive mapping tool",d:"A collaborative mapping tool was co-designed with and for people with disabilities to plan accessible public spaces in Zwolle. The study found that inclusive digital planning depends not only on software but also on hardware and the setting in which a tool is used, which addresses the digital divide directly.",src:"text",p:"p. 4"},
  {t:"Guangzhou social media participation",d:"Third parties and citizens used social media to spread information fast and raise their voices in a Guangzhou planning practice. It supported informal participation and reshaped government-society relations, but new power inequalities appeared within and beyond online networks.",src:"text",p:"p. 3"},
  {t:"Sydney's political urban analytics",d:"A study of urban analytics in a major strategic planning process in Sydney found that political factors shaped every part of the system, from which data were available to how analytics were used. It shows that PSS and analytics are not neutral tools, the socio-political bias the editorial warns about.",src:"text",p:"p. 3"},
  {t:"Eindhoven VR co-design",d:"Immersive VR was used to involve citizens and local stakeholders in co-designing healthier urban spaces in Eindhoven, and most workshop participants were positive. The study still recommends better visuals and multi-user functions, which shows the usability and supply-demand gaps between tools and practice.",src:"text",p:"p. 3"}
 ],
 p11:[
  {t:"CAD and GIS kept planners",d:"Computer-aided design in the 1980s and GIS in the 1990s transformed how planners visualise and analyse data but left interpretation and negotiation to humans. The authors use this contrast to argue that urban AI is different, because it automates the critical-thinking tasks themselves, which drives deskilling.",src:"text",p:"p. 568"},
  {t:"Journalism and manufacturing precedent",d:"In journalism and manufacturing, technology introduced as a supportive tool evolved quickly towards partial or full replacement of human roles. The authors cite this against the 'AI only augments planners' view, because pressures for speed and cost savings can override longer-term social goals.",src:"text",p:"p. 569"},
  {t:"Clinical decision-support analogy",d:"Doctors interpret output from clinical decision-support systems yet keep ultimate responsibility, and the authors want planners to act the same way as 'sense-makers' of AI output. This answers the accountability gap: responsibility stays with a human professional, not the algorithm.",src:"text",p:"p. 569"},
  {t:"Dutch childcare benefits scandal",d:"The Dutch tax authority used a risk-classification model for childcare benefit fraud that included nationality as a risk indicator; many parents were wrongly treated as fraudsters, and the cabinet resigned in January 2021. Not a planning case, but the same mechanisms: algorithmic bias in public decisions and blurred accountability for automated outcomes.",src:"similar"}
 ],
 p12:[
  {t:"Sustainable beacon cities",d:"Cities that promote themselves as beacons of the sustainable transition may look far less exemplary once the consumption emissions of their residents' lifestyles are counted (Krähmer 2021). It illustrates why relative decoupling within city limits is not absolute decoupling, and why labelling more development as 'sustainable' is easy.",src:"text",p:"p. 289"},
  {t:"Amsterdam's holiday rental cap",d:"Amsterdam limits renting out a whole home to tourists to 30 nights a year (since 2019, down from 60). It is a real version of the post-growth tool Durrant et al. propose: restricting short-term lets so the existing stock serves housing needs instead of building more.",src:"similar"}
 ],
 p13:[
  {t:"Utrecht's guilds and budget cuts",d:"Utrecht created 'guilds' (gildes) to bring sectors such as urban development and green space planning together in new housing areas, and ran ten neighbourhood green plans under the slogan 'Together we make Utrecht'. Yet these neighbourhoods suffered significant budget cuts, which shows the paper's pattern: silos are overcome step by step, but funding and capacity limit transformation.",src:"text",p:"pp. 2414-2416"},
  {t:"Berlin splits planning and green",d:"A reorganisation in Berlin separated the urban planning and green space planning departments, even physically into different buildings; cooperation still worked thanks to long-standing working relationships, but the interviewee feared it would erode when staff retire. It shows how fragile integration is when it rests on people rather than structures, a form of path dependency.",src:"text",p:"p. 2414"},
  {t:"Aarhus exchange agreements",d:"Aarhus's Municipal Plan (2017) led to 'exchange agreements' in which developers contribute to the common good, for example by creating new green spaces, in return for their economic gain. It illustrates the ambiguous link between urban growth and green space: growth funds greening, but also ties it to development.",src:"text",p:"p. 2413"},
  {t:"Helsinki's Green Area Factor",d:"Climate adaptation led Helsinki to adopt a Green Area Factor that requires sufficient green space for ecosystem services within new urban developments. It is an example of deliberate change at the level of formal policy tools, one of the few regulatory rather than voluntary responses in the study.",src:"text",p:"pp. 2412-2413"}
 ]
};
