const EXT_3={
 taylor:{ext:[
  {h:"What the article asks and why",p:[
   "Melbourne's Urban Growth Boundary (UGB), a legal line separating land where urban development is allowed from land kept rural, was legislated in 2002 and expanded substantially in 2010 (p. 259). After the expansion the press reported 'instant millionaire' landowners, and one study found that per-hectare land prices inside the boundary rose by 89 percent relative to comparable land outside (p. 259). Yet during one window of time, just before the expansion, many of the same landowners argued the opposite: that being brought inside the boundary would not raise the value of their land at all. Taylor's article is about that reversal and about what it did to policy.",
   "The trigger was a new instrument that came with the expansion: the Growth Areas Infrastructure Contribution (GAIC). Taylor calls it in effect a 'hypothecated' tax (a tax whose revenue is earmarked for one purpose, here infrastructure in new suburbs) on betterment, the rise in land value caused by a public decision such as rezoning (pp. 259–260). She critically interprets 264 public submissions on the UGB expansion and the GAIC, and argues that the later changes to the GAIC, including the switch to a 'purchaser pays' model, are best understood as a response to rent-seeking pressure from existing landowners acting as 'insiders' (p. 260).",
   "Rent-seeking here means using political influence to secure or protect income from land that is not earned by productive effort. Taylor borrows two routes from Clingermayer: 'heresthetics', the intentional manipulation of an issue, and 'happenstance', where altruistic goals unintentionally line up with rent-seeking ones (p. 260). She also uses Evans' 'insider-outsider' problem: planning participation tends to be biased towards existing property owners, while future residents have no voice. Her position is careful: she does not claim all landowners were lying, but tests the assumption that at least part of their claims was driven by perceived economic self-interest, including a wish to avoid the GAIC (p. 260)."
  ]},
  {h:"Melbourne's boundary and the promise of windfall gains",p:[
   "The 2008 planning update 'Melbourne @ 5 Million' proposed to consider about 50,000 hectares of 'investigation areas' for inclusion in the UGB, justified by population projections and a stated need to keep land supply 'adequate and competitive' (p. 261). The same update introduced the GAIC, which Taylor notes was, 'probably tellingly', not named a betterment tax (p. 261). The state government presented it as only a small portion of the significant increase in land values that rezoning creates, to be used to offset the heavy costs of infrastructure in growth areas.",
   "The charge rested on concrete estimates. The Growth Areas Authority cited research that rural land around Melbourne was typically worth $15,000 to $35,000 per hectare, but that rural land brought inside the UGB and rezoned rose to an average of $365,000 per hectare, within a range of $225,000 to $450,000 (p. 261). Planners and developers interviewed in another study agreed that land inside the UGB had become much more expensive, though they blamed each other. One developer put it bluntly: “People that are inside the UGB, the farmers and the owners, believe their land is liquid gold” (p. 261).",
   "The GAIC design mattered for what followed. It was a flat, one-off charge of $95,000 per hectare on land over 0.41 hectares (one acre) brought inside the UGB, payable at the sale or subdivision of the land, whichever came first (p. 261). This meant it could hit ordinary vendors who were simply selling, not only developers at the point of development. Development gains in Victoria had never been directly taxed; the 1971 metropolitan plan had discussed and rejected a betterment tax (p. 262). A landowner group, Taxed Out!, campaigned against the proposal throughout 2009 and early 2010."
  ]},
  {h:"The economics: why a boundary creates betterment",p:[
   "Taylor then sets out the economic logic. A UGB is part of an urban containment strategy, which typically aims at a more compact city, higher densities near public transport and the preservation of rural landscapes (p. 262). Whatever their goals, they affect land and housing markets. Farmland near cities tends to gain value as demand for building land grows, and planning rules sharpen the gap between agricultural and urban land. Citing Jun, she notes that although the evidence is not overwhelming, many studies find that containment raises land prices by limiting the supply of developable land (p. 262).",
   "Price differences at the boundary can come from the supply side (less land allowed) or from the demand side (the certainty and amenity a boundary creates). For economists this distinction matters because it decides whether a boundary is efficient; for fringe landowners, Taylor remarks, what counts is simply that land outside is worth less than land inside (p. 262). Figure 1 shows the mechanism: without a boundary, urban and rural land prices meet at a point c. A binding boundary drawn before c splits the price at the line into a higher urban price (d) and a lower rural price (e). The gap f between them is the betterment, which is unlocked for any parcel the boundary is moved to include (p. 263).",
   "Betterment goes by many names: development gain, windfall, planning gain (p. 263). The political case for taxing it is that the owner has made an unearned gain that arises largely from community or government action. Impact fees and inclusionary zoning are related forms of land value taxation (p. 263). The GAIC rested on exactly this assumption: that inclusion within the UGB brings a substantial rise in land value."
  ]},
  {h:"Two opposing interests landowners can have",p:[
   "Planning is an intervention in property rights, which it limits, allocates and reallocates, and these allocations have economic value that invites 'capture' (p. 264). Taylor highlights the idea of 'dual predictability': containment makes it more certain which land can and cannot be developed, while also making clear that land inside the boundary is exhaustible (p. 264). This gives owners outside the line a strong incentive to lobby to be included and harvest the expected betterment. She calls this premium-seeking behaviour.",
   "But some landowners want the opposite. Owners of lifestyle properties in low-density communities near cities often value the aesthetic or symbolic quality of rural land, and the scarcity and value stability that planning controls give them (p. 264). Here Taylor uses Fischel's term 'homevoters': owner-occupiers whose political choices are driven by protecting their property values. Their interests mix sometimes noble, altruistic intentions with inevitable property market consequences. So theory predicts two, sometimes opposite, kinds of rent-seeking: avoiding controls that limit future development value, and preserving restrictions on growth to protect a home and a landscape (p. 264).",
   "Either way, if the boundary moves and urban values are unlocked, a tax on the betterment is unwelcome. How costly it really is depends on who ends up bearing it, its 'incidence', which is disputed: some research suggests landowners receive slightly lower prices but homebuyers ultimately bear most of the cost (p. 264). This is why Taylor focuses on what landowners claimed about incidence: who they said would really pay."
  ]},
  {h:"Evidence and cases: what the submissions show",p:[
   "The material is the public inquiry into 'Delivering Melbourne's Newest Sustainable Communities' (2010), which received 1,411 individual and 503 organisational submissions (p. 265). Taylor took the first 20 percent received from each group; because code numbers were assigned randomly, this is effectively a random sample. From 382 coded submissions she removed those dealing only with other proposals and those that were confidential, duplicates or empty, leaving 264 (218 individuals, 46 organisations). As a rent-seeking perspective would predict, 186 of them (70 percent) came from fringe landowners directly affected, including 26 commercial farmers, 28 'lifestyle' residents and 49 owners with plans to develop (p. 265).",
   "On the expansion 'in principle', most comments were objections (83 of 111) (p. 265). Objections from non-landowners, often inner-Melbourne residents and environmental groups, referred to urban consolidation in general and to high-value areas such as the Merri Creek and western grasslands. Landowners who objected instead talked about local amenity (the rural feel, birdlife, lack of noise) and their rural lifestyle, often in terms that fit Hubbard's 'self/other' contrast between rural and urban (p. 266). Taylor stresses that such owners may argue in good faith, but their altruistic arguments unavoidably align with their property interests.",
   "Views on owners' own land sorted neatly by interest (Table 2, p. 267). Thirty-three owners inside the new UGB were happy to be included, 52 outside wanted in, and 11 inside wanted to stay out. Those happy to be in were mainly broad-hectare farmers or owners of vacant land, suggesting plans to sell and move. Those wanting out were mostly lifestyle owners and businesses such as a winery, valuing land use over development. Twenty-one owners in the west, whose land was to be protected grassland, called the rules unfair; Taylor reads this as premium-seeking objection to planning restrictions, in stark contrast to non-landowners who supported grassland protection (p. 268)."
  ]},
  {h:"Discrediting betterment: the campaign against the GAIC",p:[
   "The GAIC itself was almost universally unpopular with the people who would pay it: 83 sampled submissions objected, 76 of them from impacted individual landowners, and only four supported it (Table 3, p. 268). Crucially, objectors treated the charge as a tax on their existing land value, not on a future windfall. About a third claimed it would hurt their existing values and home equity, and about a third called it unfair, undemocratic or immoral, often in emotional terms about years of hard work (p. 269).",
   "Taylor identifies three ways in which submissions doubted and ultimately discredited the windfall premise (pp. 269–270). First, some owners simply did not understand, or ignored, the betterment logic, calculating the charge as a share of their current property value (one concluded he would lose more than half his home). Second, some openly disbelieved that inclusion would raise values at all, or mocked the idea, asking who would guarantee the increase. Third, some accepted that values might rise elsewhere but not on their own land for some years. This framing was central to the Taxed Out! campaign (p. 270).",
   "She connects these reactions to the power of perceived property rights, which can gain political traction even when they contradict the legal basis of property (p. 270), and to a strong political aversion to any tax on owner-occupation. The most telling pattern comes from owners with development plans (Table 4, p. 271): only 4 of these 49 (8 percent) objected to the GAIC, against 72 of the 137 (53 percent) who mentioned no plans. Owners who knew what development would earn them saw the charge as affordable. Taylor concludes that opposition was driven by landowners, not developers, who tend to accept charges that are transparent and can be passed on to buyers (p. 271)."
  ]},
  {h:"From vendor tax to 'purchaser pays'",p:[
   "The most common alternative proposal (32 submissions, 42 percent of landowner objectors) was that developers, not landowners, should pay, since they could pass the charge on to the eventual home purchasers (p. 271). Submissions called this 'user pays' or 'purchaser pays' and presented it as fairer and more traditional. Taxed Out! also wanted the charge applied only at subdivision or development, not at sale. A key concern was lifestyle properties with houses on them, whose dwelling value would not count for a developer buying the land (p. 272).",
   "Policy followed these pressures. The GAIC bill was first blocked by the opposition, which supported the expansion but not the charge (p. 272). As Taylor puts it, “landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill” (p. 272). It was redrafted twice and approved in mid-2010 with sales of parcels between 0.41 and 5 hectares exempted (an estimated 56 percent of formerly liable parcels) and formal liability moved in most cases to purchasers or developers, who would pay 30 percent at purchase and the rest at development. In June 2011 a new minister made the charge fully deferred until development (pp. 272–273). The minister said this protected hobby farmers and lifestyle owners: a 'homevoter' effect (p. 273)."
  ]},
  {h:"Conclusions and what the author wants",p:[
   "Taylor's central finding is that landowners managed to discredit the idea that windfall profits would result from moving the boundary, and on that basis escaped formal liability for the charge (p. 273). This is at odds with what happened next: the press soon reported a 64-hectare farm selling for $36 million, and a 10-hectare site bought for $50,000 in 1983 selling for $7.54 million (p. 273). She admits limits: not every owner would have gained so much, and the GAIC's survival shows stakeholder influence has limits (p. 273).",
   "Still, the adjustments are revealing because they seem to legitimise landowners' misinterpretation, wilful or otherwise, of what the charge was for. They show how “the representation of perceived self-interest can, through the political discourse around planning, come to be taken at face value as more equitable” (p. 273). The broader lesson is that policies with wide implications survive or fail depending on conflict with groups who have an existing economic stake. In Melbourne, unlike the UK, property speculation generally overrides preservationist interests, but in both cases outcomes follow the pressure of existing owners (p. 274).",
   "Her final picture is a cycle: containment creates price premiums in the land market, these are redistributed through the lobbying of 'insiders', and the costs are likely passed on to housing consumers as 'outsiders' (p. 274). That is a concern in a city with long-standing problems of affordability, planning efficiency and infrastructure for new suburbs. The article is a single-case content analysis of what people claimed; it does not measure who actually bore the GAIC, and Taylor herself calls the 'purchaser pays' incidence an assumption (p. 272)."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis, not Taylor's claim. The article applies rational choice theory, specifically public choice ideas about rent-seeking and 'capture', to planning politics. Actors are treated as pursuing economic self-interest within a set of rules, and the interesting question is how they use participation and political pressure to shift those rules in their favour. In the terms of the neo-institutionalism lecture, it sits close to rational choice institutionalism: institutions (the UGB, the GAIC) create value and incentives, and organised interests then fight to change them.",
   "On the course dimensions: agency is strong but structured, since landowners act strategically within a boundary regime that creates the rent in the first place. The outcome is reproduction rather than transformation: existing owners protect their advantage and costs shift to future buyers. Change is deliberate lobbying, but the final policy is no one's design. Knowledge is situated in one Melbourne episode, though Taylor draws a general implication about insiders and outsiders. Her normative commitment is visible in the concern for affordability and for capturing unearned gains for public infrastructure.",
   "Useful contrasts: Sorensen's Toronto study shows land value capture as a long, contested institutional pathway (historical institutionalism), while Taylor zooms in on one moment of interest-group pressure. Moroni would read the protection of property rights more positively, as a valuable evolved institution. A Marxist reading, such as Foglesong's property contradiction, would link the fight over betterment to the tension between the social production of land value and its private ownership. Communicative planning ideals also look different here: open participation mainly amplified those with a stake."
  ]}
 ],
 table:{head:["Group (in submissions)","Main interest in the UGB","Stance on the GAIC","Evidence (pages)"],rows:[
  ["Lifestyle and hobby-farm owners ('homevoters')","Keep rural status, amenity and stable equity; some inside the new UGB wanted out","Strongly opposed; wanted rural-residential sales exempt","11 inside wanting out, 8 of them lifestyle owners; 15 wanting restrictions kept (pp. 267–268, 272)"],
  ["Commercial farmers and vacant-land owners","Get included to sell or develop (premium-seeking)","Less opposed when development value was clear","33 inside and happy; 52 outside wanting in; 21 grassland objectors (pp. 267–268)"],
  ["Owners with stated development plans","Unlock development value quickly","Rarely objected: 4 of 49 (8%)","Table 4; 13 via professional representatives (p. 271)"],
  ["Owners with no stated plans","Keep or sell land in current use","Often objected: 72 of 137 (53%)","Table 4 (p. 271)"],
  ["Non-impacted individuals and environmental groups","Oppose sprawl; protect Merri Creek and grasslands","Largely silent","38 in-principle objections from non-landowners, 11 from groups (pp. 265–266)"],
  ["Housing developers","Access to new urban land","Cautious acceptance if transparent and passed on to buyers","Opposition 'driven by landowners rather than housing developers' (p. 271)"]
 ]}},

 ni:{ext:[
  {h:"What the lecture asks and why",p:[
   "This is a walk-through of the lecture slides (Josje Bouwmeester, 'Neo-institutionalism & planning', 29 September), not of an article; the slides are the only source here, so some points are brief where the slides are brief. The lecture has two parts. Part A goes 'beyond rational choice theory' via Elinor Ostrom and rational choice institutionalism. Part B defines the other institutionalisms (sociological, historical and evolutionary) and discusses institutional change. The learning objectives are to identify neo-institutionalist theories in planning, understand how they developed, and compare the philosophical and epistemological assumptions (assumptions about what exists and how we can know it) behind the different institutionalist paradigms.",
   "The starting definition is short: institutions are 'the formal and informal rules of the game'. The first point the lecture hammers home is that institutions are not organisations. Institutions are a system of established rules and norms which guide, constrain and regulate the behaviour of actors; organisations are concrete entities with a specific purpose. The Eurovision example makes this concrete: the European Broadcasting Union is the organisation, while its statutes and the formal and informal rules of the contest (the slide asks students to think of examples) are institutions."
  ]},
  {h:"Why institutions matter to planners",p:[
   "The slides quote Savini (2019): “Institutions are ontologically both the context and object of planning practices from a relational perspective”. Institutions as context means the framework within which planning decisions are made: laws, procedures, norms of what is appropriate. Institutions as object means they are also the outcome of planning processes: planners produce new rules, plans and arrangements. The lecture calls this the double life of institutions: they constrain actors, but they are also the outcome of human action.",
   "Alexander (2005) pushes the point further. If planning is the translation of ideas into action and its goal is the transformation of society, then institutional transformation must be a critical aspect of planning, because there are only two ways of changing people: changing individuals, and changing institutions. This sets up the tension that runs through the whole lecture: if institutions shape us, how far can planners deliberately reshape them?"
  ]},
  {h:"Part A: from the tragedy of the commons to Ostrom",p:[
   "The origins story starts with Hardin (1968). The 'tragedy of the commons' occurs when individuals acting in rational self-interest overuse and deplete a shared resource such as a pasture, a fish stock or the atmosphere. Each user gains from taking a bit more, while the cost of depletion is spread over everyone, so the rational individual choice produces a collectively bad outcome. The classic answers were privatisation or state control.",
   "Elinor Ostrom's work (Governing the Commons, 1990) asked a different question: how do self-interested people self-organise and create norms to prevent economically suboptimal outcomes? Her answer is institutions that overcome 'the problem of commitment': rules that make it credible that others will also hold back. She developed the Institutional Analysis and Development (IAD) framework, a structured way to analyse how rules shape an 'action situation' in which actors interact and produce outcomes.",
   "The IAD framework distinguishes seven types of rules. Position rules define the roles available; boundary rules specify how actors enter or leave a position (membership of a fishing cooperative); choice rules say what actions are allowed, obliged or forbidden (only certain gear); aggregation rules combine individual actions into collective decisions (majority voting in a village council); information rules regulate what must or may be shared (reporting catches); payoff rules assign rewards and sanctions (fines for breaking quotas); and scope rules define which outcomes are affected (off-limits areas, protected species). The slides link this to Bouwmeester and Hartmann (2021) on informal real estate markets in informal settlements."
  ]},
  {h:"What neo-institutionalism is and where the strands disagree",p:[
   "New or neo-institutionalism, according to the slides, offers three things: an explanatory theory of how institutions shape behaviour; an understanding of how institutions arise and transform; and a way of answering and reconciling the relationship between structure and agency, referring to Giddens. The planning example is Tennekes, Harbers and Buitelaar (2015), who show that institutional arrangements affect the morphology (physical form) of residential development in the Netherlands, Flanders and North Rhine-Westphalia.",
   "How do institutions influence behaviour? The slides stack several definitions. They constrain the set of possible actions and have a normative capacity to orient how agents interact (Giddens 1984); they define what is 'appropriate for actors to do within a given setting' (March and Olsen 2010); they 'guide and give meaning to human interaction' (Buitelaar 2014); and they are formal and informal norms and expectations about how to act in particular social contexts (Morgan and Engwall 1999). Following Sorensen (2017), the lecture then names three questions on which institutionalisms disagree: what institutions are, what they do, and how they transform, including their origins and whether they can be designed."
  ]},
  {h:"Part B: rational choice, sociological and historical institutionalism",p:[
   "Following Salet (2018), the lecture lists the three most important paradigms. Rational choice institutionalism uses North's (1990) definition: institutions are the formal and informal rules of the game, humanly devised constraints that shape human interaction. They coordinate effects and provide certainty, information and credible commitment, and they change when rational, self-interested actors create rules to enhance cooperation. Ostrom's commons work belongs here.",
   "Sociological institutionalism goes deeper into the mind. A slide quote (dated 1991) says “Institutions do not just constrain options: they establish the very criteria by which people discover their preferences.” Key ideas are 'goodness-of-fit', the reproduction of arrangements seen as legitimate because they fit established templates (DiMaggio and Powell 1983); institutions as symbol systems, cognitive scripts and moral templates that provide 'frames of meaning' (Hall and Taylor 1996); an internalised rather than external understanding; and the hegemonic character of norms and values. The example is Savini and Dembski (2016): the new development agenda for Amsterdam-Noord was enabled by a set of symbols linking the industrial shipyard past to a creative-economy future, showing planning as creating meaning and building consensus.",
   "Historical institutionalism, again via Hall and Taylor (1996), sees institutions as formal or informal procedures, routines, norms and conventions embedded in the organisational structure of the polity or political economy. Its key concepts are path dependency and critical junctures, with an emphasis on structural elements. The example is Holsen (2021), who asks why public participation in Norwegian land-use planning has remained relatively weak despite decades of legislation meant to strengthen it, and answers with a path-dependent explanation. The evolutionary strand is not given its own definition slide; it enters through Moroni in the exercise and in the take-home messages."
  ]},
  {h:"Institutional change: can planners design institutions?",p:[
   "The discussion part starts from 'planning as institutional design'. Alexander (2005, p. 210 on the slide) notes that much planning involves institutional transformation, and that some have even suggested that 'planning is institutional design' (Innes 1995). The slide draws the implied chain: planners design institutions, institutions shape behaviour, and behaviour reshapes society and space. This is the most optimistic view of planning agency in the lecture, and the three readings that follow can each be read as a qualification of it.",
   "Students then pick one of three readings and answer: how does the author explain the limits of deliberate, top-down design; what mechanisms of change are emphasised; and what role do planners have compared with the view of planners as intentional designers. The slide quotes act as an answer key. For Dembski and Salet: symbolic markers cannot be used voluntaristically, new institutions emerge through new cultural practices that become institutionalised, institutionalisation is ongoing normalisation and habituation, and “The art of planning is to find niches of underinstitutionalised space.” (p. 622 on the slide).",
   "For Sorensen: critical junctures are short periods with a heightened probability that agents' choices affect the outcome; path dependence is usually not 'lock-in' but continuous contestation within a relatively constrained range of options; and critical juncture analysis shows how actors use conjunctural crises to push particular changes. For Moroni: most institutions are the unintentional outcome of slow evolution, so they cannot be designed like organisations, but acknowledging this does not prevent intervention; it calls for an approach different from the 'taxis-oriented' (engineering) one."
  ]},
  {h:"Why it matters and the take-home messages",p:[
   "The closing argument returns to Savini's phrase and adds: “How we conceptualize institutions shapes how we conceptualize planning agency”. If institutions are external rules, planners can redesign them; if they are internalised meanings, planners must work with symbols and practices; if they are path-dependent, planners wait for and use junctures; if they are evolved orders, planners should be modest. The homework makes this concrete: for the problem 'Housing is becoming unaffordable', define the problem and likely solution from a historical, a sociological and an evolutionary institutionalist perspective, and post it to the discussion forum.",
   "The take-home messages are fourfold. Institutions are not the same as organisations in new institutionalism. They are defined differently depending on the tradition, but generally refer to systems of embedded rules and norms. The institutionalisms rest on different underlying assumptions about agency and structure and about institutional change. And the family consists of rational choice, sociological, historical and evolutionary institutionalism. The lecture ends, with a wink, on the break as 'an institution we all fully support'."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis, not the lecturer's claim. The lecture is essentially a map for placing the week's readings. Taylor's rent-seeking landowners and Ostrom's commons fit the rational choice corner: individuals with given preferences, institutions as external constraints and incentives. Dembski and Salet use Table 1 in their article to place themselves in the sociological, 'in action' quadrant. Sorensen is the historical institutionalist, and Moroni the evolutionary (Hayekian) voice.",
   "On the course dimensions, the strands spread across structure and agency: rational choice leans to agency within rules, historical institutionalism to structure with moments of agency, sociological institutionalism to internalised structure that is re-enacted in practice. On deliberate versus emergent change, the range runs from 'planning is institutional design' (Alexander, Innes) to Moroni's claim that planning in the strict sense cannot be applied to institutions. The recurring question for exams is therefore not only what an institution is, but what that definition implies for how much planners can deliberately change."
  ]}
 ]},

 dembski:{ext:[
  {h:"What the article asks and why",p:[
   "Planners, designers, developers and civic groups increasingly mark urban change with symbols: landmarks, design objects, planning metaphors, marketing images, new public spaces and big events (p. 611). The aim is to enhance the social meaning of transforming spaces, to make them mean more than is now apparent. But this often fails. Dembski and Salet list examples: the Pearl River Delta suggests a coherent metropolitan region but is 'mission impossible', the Flemish Diamond has little effect on policy, Bilbao has not yet become a cultural city, and genuine silicon valleys are few (p. 612). Successful concepts such as the London Green Belt or the Dutch Green Heart aim at preservation, not transformation.",
   "Their central question is: why does the symbolisation of new urban spaces strengthen social meaning in some cases, while in others the symbols remain powerless or even backfire (p. 612)? Communicative planning theory has studied discourse, narrative and metaphor, but the authors want to find the institutional conditions that enable effective mobilisation. Their thesis is that success does not lie in the quality of the symbol itself: “It is in the institutional embedding in the mental maps of humankind that the success or failure of symbolic communication lies” (p. 612). Planners who see a symbol fail tend to redesign the symbol, which misses the point.",
   "This creates a theoretical problem they must solve first. Most institutional research stresses path dependency and durability; planners often see institutions as 'rusty old fixtures' that block solutions (p. 612). So why use institutions to explain dynamic change? The authors answer that “Institutions are not carved in stone” (p. 613): norms must be validated and reproduced in every new situation, and this ongoing affirmation and contestation opens room for innovation. The paper is conceptual: it reappraises institutional theory, links it to symbolic theory, and proposes a research model (p. 613)."
  ]},
  {h:"Cities in transition: why new symbols are sought",p:[
   "The authors first describe the urban change that prompts symbolic planning. The classic pattern of a central city with decreasing density outward began to crack in North America in the 1960s: Friedmann and Miller's 'urban field', Fishman's end of suburbia, Garreau's 'Edge City' and Soja's 'mass regional urbanisation' all describe dispersed, non-hierarchical urban regions (p. 613). In Europe, containment policies slowed this but did not prevent it. Ascher's 'métapolis' and Sieverts' 'Zwischenstadt' (the in-between city that is neither compact city nor countryside nor classic suburb) named the new reality in the 1990s (p. 613).",
   "These changes cross administrative and cultural boundaries (p. 614). Urban sprawl ignores municipal borders, the town-countryside dichotomy has disappeared into a patchwork, and urban activities pop up in unexpected places such as offices at highway junctions. The new landscape is perceived as a 'nonplace' without deeply rooted meaning, which creates a quest for new identity. The fragmented city-regional archipelago needs integration and legitimacy for city-regional arrangements (p. 614). The authors suggest the regional city may be the appropriate form for contemporary Western societies, but whether perceptions follow is uncertain, which is why they study how new symbols are made to serve as vehicles for identifying new qualities of life (p. 614)."
  ]},
  {h:"Choosing a position in institutional theory",p:[
   "Institutions are 'simply defined' as 'patterns of social rules', and most institutional approaches try to explain how social rules enable collective action in a world of individual choices (p. 615). To select a paradigm, the authors use two dimensions (Table 1, p. 615). First, the position of institutions: are they external constraints on individuals, or internalised in human agency? Second, their validation: do institutions exist 'prior to action', or must they be validated 'in action'? This gives four quadrants: rational choice institutionalism (external, prior to action), historical institutionalism (internalised, prior to action), political or actor-centred institutionalism such as Ostrom and Scharpf (external, in action), and sociological institutionalism (internalised, in action).",
   "On the first dimension, the external view has the advantage of clearly separating rules from individual choices and is widely used in economics (p. 615). Rational choice institutionalism sees rules as reducing uncertainty and solving collective action dilemmas, where individual maximisation leads to collectively poor outcomes (p. 616). Actor-centred institutionalism adds power and interest in change, but still treats institutions as external. The authors need internalisation, because they expect symbols to work through the meaning people attribute to them. In this view people follow institutions not from strategic calculation but from an assumed imperative, and institutions shape basic preferences: “the logic of appropriateness ranks higher than efficiency” (p. 616)."
  ]},
  {h:"Institutions as validated in action, not fixed in advance",p:[
   "The second dimension concerns change. Historical institutionalism stresses path dependency and the legacy of history, which is valuable in comparative politics but weak in explaining change; some historical institutionalists therefore turn to critical junctures, but innovation remains a historical particularity rather than the core of the theory (pp. 616–617). Following Friedland and Alford, the authors criticise the absence of 'living society' in both rational choice and deterministic historical accounts (p. 617).",
   "Their alternative, following Weber, is to define institutions as the 'chance (or possibility)' of validating patterns of social rules (p. 617). Institutions have to be confirmed repeatedly in everyday practice to have real meaning. Their meaning may be neglected, latent or manifest, contested between conflicting institutions, or interpreted differently by different norm holders, and this is the rule rather than the exception. Norms usually change gradually, not because they are fixed, but because it is unlikely that everyone changes their interpretation at once (p. 617). In transforming cities, many people cling to old perceptions while new practices institutionalise new meanings. Hence institutional innovation is 'deliberate change', requiring a sound grasp of existing norms (p. 617). This places them in the fourth quadrant: internalised and validated in action."
  ]},
  {h:"Instituting social meaning: habitualisation and habitus",p:[
   "Drawing on Berger and Luckmann, institutionalisation is described as an ongoing process of normalisation or 'habitualisation' (p. 618). Codes gain institutional depth when a 'reciprocity of expectations' grows among norm holders: everyone expects everyone else to act in the typical way. Institutions evolve over long periods; even formal legislation takes shape gradually and must be validated in practice after it is enacted. Their main control is reciprocal recognition, with sanctions reserved for those who fail to recognise the norm. Mary Douglas' analysis of a meal as a set of coded messages shows that such structures are expressed and reproduced in daily life (p. 618).",
   "To avoid a purely subjective reading, the authors use Bourdieu's 'habitus': durable dispositions through which people internalise their position in social space, so that practice is neither a mechanical reaction to structure nor independent of it (p. 618). Bourdieu's card game image helps: the cards (material capital) have values set by the rules, which limit strategies, but players' skill still matters. These patterns must be constantly reconstructed, and Bourdieu stresses the active verb 'instituting' (pp. 618–619). Institutions, in short, are made and remade in practice."
  ]},
  {h:"How symbols can enlarge social meaning: rites of institution",p:[
   "A symbol refers to something wider that is not in the symbol itself (p. 619). With Geertz, culture is a pattern of meanings embodied in symbols; his Balinese cockfight shows spectators cheering not for the birds but for their own status groups. Institutions need reaffirmation through symbolic objects and rituals, and in fact 'institutions are symbolic systems' (p. 619). Institutions such as religion or land property are real only to those who believe in them; voting makes sense only if one believes in democracy (p. 619).",
   "The key mechanism comes from Bourdieu's 'rites of institution' (p. 620). Ageing is continuous, but rites mark sharp passages between childhood, adolescence and adulthood and legitimise those differences: “The rite is thus one not of passage but of instituting” (p. 620). Such 'social magic' produces discontinuity out of continuity: a master's degree, like an amulet, changes how others treat a person and how the person sees themself. But it works only if the meaning is inculcated in, and guaranteed by, the audience. That is the Achilles heel: if the institutional condition is not met, symbolic mobilisation stays powerless (p. 620).",
   "Applied to regions, instituting a high-technology city-region is more than developing technology; it must be believed, inside and outside (p. 620). Following Paasi, regional identity has an internal and an external side, and a material, institutional shape as well as a symbolic shape. Those who impose norms must be recognised as legitimate 'knowers'. Billig's 'banal nationalism' (the everyday flag, not the big moment) shows that regions must be reaffirmed through conscious and especially unconscious remembrance, or their mobilising power fades (p. 621)."
  ]},
  {h:"Evidence and cases: a research model rather than a case study",p:[
   "The paper has no empirical case; it proposes an eight-step research strategy (Box 1, pp. 621–622). Steps 1 and 2 identify the symbolic markers (metaphors, landmarks, icons, model projects) and diagnose the encoded message: does it symbolise past social relations, transformation, or the past 'bent' towards a new future? Steps 3 to 5 cover the field of power: who the symbolisers are and whether they are authoritative (subjective context), what social structure is reproduced and whether the symbols are genuine (objective context, e.g. via habitus), and which audience is addressed.",
   "Step 6 adds time: how symbols change, conflicting interpretations, and the role of claim-makers, drawing on framing literature. Step 7 examines internalisation: inculcation, habituation, rites of institution, consecration and the making of discontinuity out of continuity. Step 8 analyses sanctions for misrecognition and who the sanctioners are (p. 622). The warning for practice is clear: “Symbolic markers cannot be used in a voluntaristic manner” (p. 621), meaning planners cannot simply will a new reality into being. Cultural symbols used by planners are often detached from institutionalised practices and fall on fallow ground (p. 621)."
  ]},
  {h:"Conclusions and what the authors want",p:[
   "Institutional change happens through new practices that deviate from existing practices without ignoring evolved meaning (p. 621). Where evolved and emerging appropriateness meet, conflict is manifest; new institutions arise through new cultural practices that become institutionalised, gradually or in what Hajer called an 'institutional void' (p. 622). Hence: “The art of planning is to find niches of underinstitutionalised space (social as well as spatial)” (p. 622), places not dominated by power struggles over the norm, such as forgotten industrial sites, opencast pits or dilapidated estates. In a fragmented institutional order, planning can build on the accepted practices of particular groups.",
   "The conclusion restates the argument (p. 623): institutions are internalised patterns whose existence is continually validated in practice, so their meaning is never fixed; transforming reality requires a sound notion of existing norms and norm holders; symbolic mediation is essential to reaffirm institutional meaning; and symbols work their social magic only when their meaning is inculcated by the audience. The authors admit the internalised approach is analytically harder, since it is not easy to investigate what is internalised in people's minds (p. 616), and the paper offers no test of its model."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis, not the authors' claim. The article is the course's clearest statement of sociological institutionalism, and its Table 1 is the map the lecture uses. It rests on Berger and Luckmann's social constructionism, Geertz's interpretive anthropology and Bourdieu's theory of practice. It also speaks to communicative planning theory: it shares the interest in meaning and metaphor but argues that communication alone cannot explain success.",
   "On the course dimensions, it is a structuration-type middle position: habitus is internalised structure, yet it is re-enacted and can shift in action. It aims at transformation, but only transformation that connects with existing norms, so it sits between reproduction and radical change. Change is 'deliberate' yet not voluntaristic; planners can steer but not decree. Knowledge is situated, since meaning depends on audience and place. It is pluralist in recognising many groups with different norms, and its normative commitment is modest: effective, legitimate mobilisation rather than a specific social goal.",
   "Contrasts: Moroni shares the scepticism about top-down design but grounds it in evolved rules and dispersed knowledge rather than meaning, and draws more liberal conclusions. Sorensen's historical institutionalism, which the authors criticise as better at continuity than change, answers with critical junctures and ongoing contestation. Taylor's rent-seeking actors are the kind of strategic, external-rule actors Dembski and Salet set aside."
  ]}
 ]},

 moroni:{ext:[
  {h:"What the article asks and why",p:[
   "Many social sciences have taken an 'institutional turn', recognising that the institutional framework is central to social and economic life, and planning theory has followed, from Alexander and Bolan in the early 1990s to Healey, Salet and Faludi, Gualini and Verma (pp. 275–276). Moroni welcomes this as a real change of focus, since early 20th-century planning was hostile to stable frameworks and general rules and favoured case-by-case administrative intervention (p. 276). But he sees a problem: the move from recognising that institutions matter to proposing how to design and change them is often “overly simplistic and still somewhat ‘engineeristic’” (p. 276).",
   "His key term is the 'taxis-oriented approach'. In Greek, 'taxis' means a made, exogenous order and 'kosmos' a grown, endogenous order, terms Hayek revived (note 3, p. 288). A taxis approach treats social problems like an engineer's: a complete problem, one aim, full control over means and all relevant data in one mind (p. 276). This fails for society because social problems are 'incomplete' and involve practical knowledge that exists only in use and cannot be written down (Oakeshott). Many institutionalist planners reject taxis-style land-use planning, yet Moroni argues the same attitude resurfaces 'higher up' when they treat institutions as just another object to redesign (p. 276).",
   "The article does two things (p. 277): it outlines an evolutionary theory of how institutions emerge and work (section 2, descriptive), and it shows how this theory supports a more humble and dynamic approach to reform (section 3, prescriptive). The focus is on land-use institutions. In a note he admits that an evolutionary view does not logically imply normative conclusions, but makes some more plausible than others (note 5)."
  ]},
  {h:"First: institutions are not organisations",p:[
   "Before anything else Moroni insists on a distinction that planning literature often blurs (p. 277). Institutions do two basic things: they coordinate patterns among individual actions, and they are a fund of knowledge accumulated over centuries and available to all. He defines institutions as sets of basic rules of conduct, acknowledged by a community and usually enforced by some sanction; organisations are systematic arrangements of resources for achieving explicit, shared goals (p. 277).",
   "He adopts North's image: both give structure to interaction, but institutions are the rules of the game, organisations are the teams. In his words, “the former represent the rules of the game, while the latter represent its players” (p. 277). Rules also exist inside organisations, but they are of a totally different kind (Hayek). This distinction does a lot of work later: much of his critique rests on the claim that designing an organisation and changing an institution are different enterprises."
  ]},
  {h:"The evolutionary view: from the Scottish Enlightenment to Hayek",p:[
   "Moroni traces the evolutionary theory of institutions to the Scottish Enlightenment: Hume, Ferguson and Smith stressed both the central role of institutions and their unintentional, emergent character, and hence the limits of institutional design (p. 277). Ferguson's famous line is that nations stumble upon establishments that are “the result of human action, but not the execution of any human design” (p. 278). Ferguson warns against crediting legendary founders with designs that were really the product of experience. Hume explains property rules as conventions that arise gradually from repeated experience of the inconvenience of breaking them, like language (p. 278). This line was continued by the Austrian School (Menger, Hayek) and the Neo-Austrians (p. 279).",
   "The theory has two core ideas (p. 279): first, “most social institutions that have reached us are the unintentional outcome of a slow and lengthy evolution over time”; second, evolved institutions embody the knowledge of many generations, a 'distillate' of successful experimentation that no individual mind could hold. Evolution is trial and error in three steps: generation of variety (of practices and rules), competition and selection among them, and propagation and persistence of the selected rules (p. 279). Institutions are thus emergent social structures, a new level of reality produced by a creative selection process."
  ]},
  {h:"Features of institutional evolution and invisible-hand explanations",p:[
   "Like biological evolution, cultural evolution follows no inevitable laws or stages and aims at no final state; it is open-ended, contingent and unpredictable in detail (p. 279). It also produces sub-optimal results, since it works on chance variations rather than all possible options, yet it achieves things other mechanisms cannot (pp. 279–280). There are two key differences from biology: cultural evolution passes on acquired characteristics, since rules are learnt, not innate, and from countless predecessors rather than only parents; and its variation comes from human trial and error, intentional agents tackling problems, not random mutation (p. 280). Humans appear as 'rule-following' rather than 'rational-maximizing' animals, and institutions help ignorant individuals use more knowledge than any one of them has (p. 280).",
   "Evolutionary explanations explain the principle, not the detail (p. 280). They belong to 'invisible-hand explanations', which account for an ordered pattern without an 'ordinator' who deliberately produced it (p. 280). Following Koppl, such explanations show that phenomena appear designed but are not; tell a process story over time; show how dispersed individuals pursuing their own ends produce the pattern; and involve an element of surprise (p. 281). Jane Jacobs on what makes streets safe and Schelling's model of residential segregation are urban examples (p. 281). The aim is to downsize visible-hand or conspiratorial explanations that always look for a responsible actor. Moroni favours a position between methodological individualism and collectivism (p. 281)."
  ]},
  {h:"Against 'institutional design': three kinds of phenomena",p:[
   "Section 3 turns prescriptive. Moroni engages Alexander, who defines institutional design as devising and realising rules, procedures and organisational structures that enable and constrain behaviour, at macro (whole societies), meso (inter-organisational networks, new organisations) and micro (intra-organisational) levels (pp. 281–282). Moroni's objection: if institutions and organisations differ, there is no continuum between these levels but 'a breach along the line' between meso and macro (p. 282). And if institutions are complex, largely unintentional emergent realities, we cannot design them in the same way as organisations.",
   "Alexander replies that institutional evolution also involves design, since it results from intentional decisions, even with unforeseen consequences (p. 282). Moroni answers by distinguishing two meanings of 'artificial'. The ancient Greek dichotomy of natural versus artificial confused 'by convention' with 'by deliberate decision' (p. 282). We need three categories (p. 283): natural phenomena, unrelated to human action; artificial phenomena that are the direct result of deliberate design, such as an organisation; and artificial phenomena that are the unintended result of many intentional actions, such as most institutions. He therefore proposes to speak of 'organizational design' for the former and 'institutional intervention' for the latter (p. 283)."
  ]},
  {h:"First-order and second-order taxis thinking",p:[
   "Moroni argues that taxis thinking is still present in land-use planning, despite claims to the contrary (p. 283). A 'first-order' taxis approach seeks detailed coordination of urban activities through end-state plans. His new point is a 'second-order' taxis approach: applying the same engineering mindset to the basic rules of society, reshaping institutions strictly to serve specific goals and redesigning them according to someone's end-state model (p. 283).",
   "He quotes Hayek on the error behind this: the belief that nothing not consciously designed can be useful leads easily to the belief that, since all institutions are man-made, we must have complete power to refashion them as we wish (p. 284). For Moroni, this second-order ambition repeats the mistake that institutionalists criticised in orthodox planning, only at a higher level where the risks are larger."
  ]},
  {h:"The kosmos-oriented approach: ten principles for reform",p:[
   "Combining evolutionary theory with the idea of 'radical ignorance' (not just limited rationality but ignorance that cannot be overcome in a complex world), Moroni proposes a 'kosmos-oriented approach' to reforming formal institutions (p. 284). It is a stance against the pretence of knowledge. The first principles are: peculiarity (organisations serve specific ends through commands; institutions are rules with 'meta-ends' such as peaceful coexistence, and cannot be subordinated to preferred outcomes); knowability (rules must be clear and known in advance, unlike the Oracle of Delphi); and sense-making (rules must make sense to actors and cannot get meaning by administrative fiat, since institutions live both outside and inside people's heads) (pp. 284–285).",
   "Next come motivational realism (institutions must work even when people and politicians are not virtuous); non-tabula-rasa (we never start from zero; reformed institutions are 'successor institutions'); and modesty (recognise and implement institutions that have proved beneficial rather than invent new ones) (p. 285). Moroni's examples are property and freedom of contract, which he defends at length with quotes from Bastiat and Spencer Heath as key to urban prosperity (pp. 285–286). Then robustness (frequent changes destroy the information rules provide) and gradualism (change must be gradual, remedying recognisable defects) (p. 286).",
   "The last two are central. Adaptive efficiency, from North: the goal is not an efficient allocation of known resources, since neither resources nor preferences are given, but rules that support continuous discovery, so that the urban system can find the best uses through regulated competition (p. 286). Openness: institutions should be universal rules for an indeterminate number of future cases, avoiding case-specific rules, and should guarantee 'pattern-predictability', not detailed prediction (p. 287)."
  ]},
  {h:"Conclusions and what the author wants",p:[
   "Moroni concludes that institutions are qualitatively different objects from other things we manage: not only more complex, but not producible like a public good or other human artefacts, so a taxis approach risks perverse effects (p. 287). He does not argue for doing nothing: “I think that actively acknowledging the evolutionary nature of institutions does not prevent us from intervening upon them, but simply calls for an approach that is quite different from the taxis-oriented one” (p. 287).",
   "The kosmos approach means accepting openness and our unavoidable ignorance, to “'learn' rather than to 'educate', to 'recognize' what is successful rather than to 'invent' optimal solutions”, to improve rather than reconstruct, to prefer indirect over direct intervention, and to leave room for ongoing competition rather than seek final integration (p. 287). He stresses that the issue is not conservatism versus change; the answer lies somewhere in between. His sharpest claim is that the task is not to extend planning to institutions but to understand that 'planning strictu senso cannot be applied to institutions' (pp. 287–288). The article is theoretical and offers no empirical cases beyond brief illustrations."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis, not Moroni's claim. The article is the evolutionary strand of new institutionalism, rooted in Hayek, the Austrian School and the Scottish Enlightenment, with North's distinction between rules and players. It is also a liberal normative position: its defence of property rights, freedom of contract, general rules and market competition links it to Hayekian arguments against comprehensive planning and to the 'Free City' logic of liberal justice.",
   "On the course dimensions, Moroni stresses emergent over deliberate change and reproduction through gradual evolution, although evolution also produces novelty. He downplays individual agency in explaining institutions (invisible hand) while valuing individual freedom normatively. His epistemology stresses situated, practical and dispersed knowledge that no planner can gather, which is a strong argument against universal blueprints. He is pluralist about individual ends but sceptical of collective end-states.",
   "Contrasts: Alexander and Innes see planning as institutional design, the view Moroni attacks. Dembski and Salet share his limits on voluntarism but locate them in meaning and habitus, and still allow deliberate symbolic change. Sorensen's historical institutionalism would see Toronto's property and value-capture rules as the product of power struggles and critical junctures, not a benign selection of efficient rules. Taylor and Foglesong would both question whether property institutions really serve 'the welfare of everyone', as Moroni suggests."
  ]}
 ],
 table:{head:["Aspect","Taxis-oriented (made order)","Kosmos-oriented (grown order)"],rows:[
  ["View of institutions","Instruments to be designed for specific goals, like organisations","Largely unintended, evolved rules of conduct with 'meta-ends' (pp. 279, 284)"],
  ["Knowledge","One mind can grasp all relevant data (engineer's view)","Radical ignorance; knowledge is dispersed and practical (pp. 276, 284)"],
  ["Aim of reform","Rebuild society to an end-state model (second-order taxis)","Improve existing rules; reformed institutions are 'successor institutions' (pp. 283, 285)"],
  ["Mode of intervention","Direct, comprehensive, frequent redesign","Indirect, gradual, modest; recognise what works (pp. 286–287)"],
  ["Efficiency","Allocative: optimal use of given resources","Adaptive: rules that support ongoing discovery (p. 286)"],
  ["Type of rules","Case-specific, detailed, outcome-oriented","General, open, known in advance; pattern-predictability (pp. 284, 287)"],
  ["Planner's role","Designer of institutions ('planning is institutional design')","Keeper and careful reformer of rules; 'organizational design' only for organisations (p. 283)"]
 ]}},

 sorensen:{ext:[
  {h:"What the article asks and why",p:[
   "Land value capture (LVC) means using public powers to recover part of the land value increases created by public decisions and infrastructure, for example by taxing uplift or requiring developers to contribute to infrastructure (p. 1804). Sorensen notes great variety worldwide: impact fees and tax increment finance in the US, planning gain in the UK, land readjustment, density bonuses, auctioned density permits in São Paulo, and huge differences in how much is captured, from Japan where most developments contribute nothing to the Netherlands where municipalities long captured all rural-to-urban uplift by buying land cheaply and selling serviced plots (p. 1804). Why such variation, and what shapes a jurisdiction's capacity to do LVC?",
   "He makes three contributions (pp. 1804–1805). First, LVC is at its core an attempt to purposefully shift the distribution of the costs and benefits of property development between public and private actors in the interest of social equity, and should be a key metric of the fairness of development. In Ontario the principle is that “growth should pay for growth” (p. 1804): buyers of new homes are on average wealthier than existing residents, so if development contributes nothing, lower-income residents subsidise either the newcomers or developers' profits. LVC rules are therefore important 'rules of the game' of capitalism, and contested.",
   "Second, he connects conjunctural analysis, an approach from Gramsci and Stuart Hall that reads how political, economic, social and ideological processes combine at a historical moment, with historical institutionalism (HI), which studies how institutions emerge and change over time (p. 1805). He argues HI adds midlevel concepts and methods for analysing contests over specific institutions: “Critical juncture analysis in this way helps to explain the processes through which political actors take advantage of conjunctural crises to further particular institutional changes” (p. 1805). Third, he applies this to Toronto, whose LVC has been contested since 1946 (p. 1805)."
  ]},
  {h:"Two traditions of conjunctural analysis",p:[
   "In critical urban studies, conjunctural analysis follows Stuart Hall's idea that crises arise when forces and contradictions in different practices and sites 'come together or con-join' in one moment (p. 1806). Peck's Transatlantic City papers revived it, calling for attention to contextual specificity and for 'midlevel' theory, but offered few details of method (p. 1806). Inch and Shepherd used it to analyse shifting planning ideologies in the UK housing crisis, and Leitner and Sheppard 'spatialised' it via land assetisation in Jakarta and Bangalore, but said nothing about specific institutional change (p. 1806). In all of these, the focus is on how hegemonic economic and ideological change affects local processes.",
   "HI, Sorensen argues, has long had robust concepts and methods for conjunctures and critical junctures (p. 1807). Most HI scholars see both as times when a confluence of events heightens the potential for major institutional change; Mahoney uses the terms interchangeably. The core definition, from Capoccia and Kelemen, is that critical junctures are “relatively short periods of time during which there is a substantially heightened probability that agents' choices will affect the outcome of interest” (p. 1807). They matter because of path dependence: institutions are hard to change, especially where 'positive feedback' reinforces them, and once an option is chosen it becomes progressively harder to go back (p. 1807)."
  ]},
  {h:"The critical juncture method",p:[
   "HI treats institutions as unequally distributive, produced by and constitutive of unequal power relations, and contested (p. 1807). Sorensen quotes North's 'rules of the game' and his own definition of planning institutions as 'collectively enforced rules and expectations' about the creation, management and use of urban space and property (p. 1807). For cities, it makes sense to focus on formal rules that shift costs and benefits of development between actors, like LVC, because they strongly affect land values and profits.",
   "Major change is analysed as a sequence (Figure 1, pp. 1807–1808). A crisis or confluence of events creates 'permissive conditions' that make institutions more open to change; during the critical juncture, actors fight for alternatives and a choice is made; a 'reactive sequence' follows in which the choice is contested and refined; eventually comes a period of relative stability. Following Soifer, permissive conditions raise the causal power of agency and contingency, while 'productive conditions' (engaged actors, political and legal structures, available change mechanisms, ideology, economics, and the timing of events) shape the specific outcome (pp. 1807–1808). Both are needed; neither alone is sufficient.",
   "Urban governance institutions are, he argues, especially prone to critical junctures: they sit in multi-level systems where senior governments can trigger change through legislation, disasters prompt new institutions, and urban systems face a constant stream of new challenges (p. 1808). He adds Fligstein and McAdam's 'Strategic Action Field', a meso-level order where actors interact under shared understandings of the field's purpose, power relations and rules (p. 1808). Those who benefit from an institution tend to defend it; those disadvantaged seek change."
  ]},
  {h:"Evidence and cases: method and the Toronto setting",p:[
   "The case is presented as a historical narrative using process tracing (following causal chains through a sequence of events) and reactive sequence analysis (p. 1808). It covers all significant changes to Ontario planning law, value capture and infrastructure finance since 1946, based on an exhaustive review of secondary literature and primary documents such as parliamentary debates and City reports, two sets of financial data on LVC revenues and Section 37 benefits (1998–2020), and eleven interviews in 2022–2023 with planners, councillors and consultants (pp. 1808–1809).",
   "Context matters. The Toronto metropolitan area grew from 1.1 million people in 1951 to 6.2 million in 2021 (p. 1809). Canadian provinces are constitutionally powerful, while municipalities are 'creatures of the province' with little legal autonomy; provinces can and often do unilaterally change planning law, boundaries and municipal taxation (p. 1809). Over 2009–2018 Toronto collected over C$490 million through 'Section 37' density agreements (extra density in exchange for community benefits) and C$2.29 billion in development charges (DCs, fees on new development similar to impact fees) (p. 1805)."
  ]},
  {h:"Critical juncture 1: the Planning Act of 1946",p:[
   "Three permissive conditions paved the way (pp. 1809–1810). Planning powers were weak: the 1917 Act let cities comment on subdivision plans but not require changes, contributions or even zoning, and a draft law with a betterment tax, proposed in 1916, was rejected. Infrastructure finance was a sore point: after Toronto stopped annexing suburbs in 1914, small suburban municipalities borrowed heavily in the 1920s, and ten of twelve could not service their debts in the Depression, forcing a provincial bail-out. And the war shifted attitudes towards intervention: the federal Curtis report recommended master plans, subdivision control and developers paying for streets and sewers, and the 1943 Ontario election crushed the Liberals and boosted the left (p. 1810).",
   "The Progressive Conservatives won a majority in 1945 and in 1946 passed a Planning Act that was far more limited than any proposal debated during the election (p. 1810). Still, it was the first law to give municipalities meaningful power over subdivision and zoning, a major limitation of property rights. Sorensen stresses contingency: no one expected the approach chosen. Crucially, the Act was ambiguous: it rejected making subdividers pay for services but gave local governments real discretion to refuse subdivision plans (only 42 percent of proposed lots approved in 1954–57), which gave suburbs bargaining power over developers (pp. 1810–1811).",
   "A reactive sequence followed. Metropolitan Toronto (a new upper tier of regional government) secured suburban infrastructure finance by requiring developers to provide on-site infrastructure and pay 'lot levies' for off-site works, which the 1946 Act never mentioned but subdivision powers made possible (p. 1811). After court challenges and appeals to the Ontario Municipal Board, the province amended the Act in 1959 to confirm the levies retroactively. This system lasted three decades (p. 1811)."
  ]},
  {h:"Critical juncture 2: the Development Charges Act of 1989",p:[
   "In the 1970s a suburban boom and new regional governments nearly doubled lot levies, and developers organised against them, arguing municipalities used them to keep property taxes artificially low (p. 1811). A 1983 revision added Section 36 (later 37), allowing extra density in return for local contributions, though this was little used until after 2000, but failed to settle levies, now called development charges. Municipalities (AMO) lobbied for DCs, developers (UDI, OHBA) opposed them, and a provincial working group could not agree (p. 1811).",
   "A Liberal minority government passed the Development Charges Act in 1989, giving clear statutory authority for DCs, linking them to building permits rather than subdivision plans, specifying which hard and soft services could be included and how to calculate charges, and letting school boards levy them too (pp. 1811–1812). Sorensen calls this a second critical juncture: it ended a long period of contention and launched a new legislative framework with its own reactive sequence (p. 1812).",
   "That sequence included a 1997 Conservative revision limiting DCs to hard infrastructure and requiring existing taxpayers to cover at least 10 percent, alongside amalgamation into a new City of Toronto and deep cuts to provincial transfers that caused a financial crisis (p. 1812). Under budget pressure and a construction boom, Toronto began collecting DCs in 2001 and used Section 37 far more: DC revenue grew from zero to almost C$700 million a year by 2020, and 697 Section 37 agreements yielded C$744 million in cash between 1998 and 2018 (p. 1812; Figure 2). Sorensen classes this as a change of practice within existing institutions, not a new critical juncture for LVC, even though amalgamation was one for governance (p. 1812)."
  ]},
  {h:"A possible third juncture: rolling back value capture since 2018",p:[
   "The Liberal government from 2003 supported intensification through a greenbelt and growth mandates but did not change DC or Section 37 rules (pp. 1812–1813). The Progressive Conservative government elected in 2018 aimed at deregulation and lower LVC revenue to boost housing supply. Bill 108 (2019) limited DCs and replaced Section 37 with a limited 'Community Benefits Charge'; Toronto protested that lower DCs would simply raise developer profits in a tight market (p. 1813). Opposition was so wide that Bill 197 (2020) walked back several changes. Bill 23 (2022) cut revenues further, to about 28 percent of what the pre-2018 system would have produced, and Bill 97 (2023) increased provincial ministers' powers over planning policy (pp. 1813–1814).",
   "Sorensen is cautious about calling this a third critical juncture because the consequences are not yet clear, but finds it hard to imagine it will not be seen that way (p. 1814). The continuing battles, with heavy lobbying by developers and municipalities, show that LVC is still intensely contested and that the main target is the rules of the game in provincial legislation (p. 1814)."
  ]},
  {h:"Conclusions and what the author wants",p:[
   "Sorensen's first conclusion is methodological: HI critical juncture analysis complements conjunctural analysis by specifying institutions, actors, change mechanisms and patterns, and by offering a comparative method (p. 1814). The Toronto pattern of critical juncture and reactive sequence is typical of planning laws created in response to crises. The ambiguity of 1946 about who pays for urbanisation is still at the centre of today's debate (p. 1814).",
   "Second, on path dependence: “In most cases path dependence is not a matter of 'lock-in,' as for many important institutions contestation is continuous and incremental change constant, but within a developmental pathway representing a relatively constrained range of options” (p. 1814). Critical junctures set the terrain of debate, which institutions are contested, the rules for changing rules, and the degree of ambiguity. In Fligstein and McAdam's terms, 1946 created a Strategic Action Field; even the recent radical changes alter amounts, timing and names, but keep density bonuses and DCs (pp. 1814–1815). Vancouver, by contrast, routinely captures about 70 percent of rezoning uplift, while Toronto planners aimed for 10–15 percent, now capped at 4 percent (p. 1815).",
   "Third, each juncture coincided with a housing crisis: the postwar shortage, the late-1980s price bubble and the current affordability crisis. Yet the first two strengthened LVC and the latest weakened it: “A housing crisis contributed to 'permissive conditions' in each case, but differing 'productive conditions' determined the outcome” (p. 1815). Variation in LVC between places is thus the product of contingent historical processes and the timing of change (pp. 1815–1816). He leaves open whether reduced LVC will lower housing prices or raise profits and land values, calling it a question for future research (p. 1815)."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis, not Sorensen's claim. The article is the course's main example of historical institutionalism: institutions as distributive, power-laden and contested, analysed through path dependence, critical junctures and reactive sequences. By linking HI to Gramscian conjunctural analysis, it also builds a bridge to critical political economy, so it is not purely an institutionalist 'middle range' text. It also shows how a planning-law history can be used to test theory about institutional change.",
   "On the course dimensions, structure dominates most of the time (the developmental pathway), but agency matters strongly in junctures, when choices are contingent. It explains both reproduction (bounded pathways) and transformation (junctures and cumulative incremental change). Change is deliberate in each political battle but the long-term pathway is emergent. Knowledge is situated: Sorensen stresses locally specific, contingent outcomes and warns against reading off global trends. His normative commitment is explicit: LVC as social equity, 'growth should pay for growth'.",
   "Contrasts: Taylor shows the same kind of contest from the landowner side in Melbourne, using rent-seeking theory. Moroni would see frequent rule changes as undermining robustness, while Sorensen treats contestation as normal and valuable. Dembski and Salet criticise HI for explaining continuity better than change; Sorensen's reply is precisely the juncture-plus-reactive-sequence model and the claim that path dependence is rarely lock-in."
  ]}
 ],
 table:{head:["Phase","What changed","Conditions and actors","Effect on value capture"],rows:[
  ["Critical juncture 1: Planning Act 1946","First meaningful municipal powers over subdivision and zoning; ambiguous on who pays","Permissive: weak rules, 1930s suburban debt crisis, wartime pro-planning shift; productive: PC majority chose an unexpected, limited law (pp. 1809–1810)","Discretion over subdivision gave suburbs bargaining power (p. 1810)"],
  ["Reactive sequence 1950s–1983","Lot levies spread; 1959 amendment legalised them; 1983 added Section 36/37 density bonuses","Metro Toronto, court cases, OMB appeals, developer lobbying (p. 1811)","Levies became standard infrastructure finance"],
  ["Critical juncture 2: DC Act 1989","Statutory development charges, tied to building permits, with set calculation methods","Levy boom, late-1980s price bubble, AMO vs UDI and OHBA; Liberal minority government (pp. 1811–1812)","Clearer, wider LVC framework"],
  ["Reactive sequence 1997–2018","1997 revision limits DCs; Toronto starts DCs (2001) and expands Section 37","Amalgamation, provincial cuts, budget crisis, condo boom (p. 1812)","Change of practice within existing rules: DCs to almost C$700m a year by 2020"],
  ["Possible critical juncture 3: 2018–2023","Bills 108, 197, 23 and 97 cut DCs, cap community benefits, centralise power","PC deregulation agenda, affordability crisis (pp. 1813–1814)","Revenues to about 28% of pre-2018 system; basic tools kept"]
 ]}},

 fog:{ext:[
  {h:"What the reading asks and why",p:[
   "This extended summary is written from general knowledge of Foglesong's argument, not from the assigned excerpt, so check every point against the reading on Brightspace (Campbell and Fainstein, Readings in Planning Theory); it contains no quotes and no page numbers. Foglesong's excerpt comes from his 1986 book Planning the Capitalist City, a history of US urban planning from the colonial era to the 1920s. His starting question is why planning exists at all in capitalist societies that are built on private property and markets, and why it takes the limited form it does.",
   "He is dissatisfied with two common answers. Mainstream accounts treat planning as a neutral, technical pursuit of the public interest, or as a correction of market failures, without asking whose interests planning serves. Some Marxist accounts, on the other hand, treat planning simply as a tool of capitalists, which cannot explain why capitalists and landowners often resisted it. Foglesong proposes a Marxist political-economy account that explains planning through the contradictions of capitalist urbanisation, while leaving room for conflict and contingency."
  ]},
  {h:"The property contradiction",p:[
   "The first and best-known idea is the 'property contradiction'. Urban land and the built environment have a social character: their value and usefulness depend on collective investments such as streets, sewers and transit, on what happens on neighbouring plots, and on the needs of the economy as a whole, for example housing workers and moving goods. Yet land is privately owned and controlled, and each owner pursues their own return. The result is congestion, incompatible land uses, poor housing and threats to property values that no single owner can solve.",
   "Capital as a whole therefore needs some socialisation of control over land, through public works, zoning and planning. But the same socialisation threatens the rights and profits of individual owners and developers, who resist it. Planning is thus both necessary for capitalism and constrained by it: it can coordinate land use only as far as it does not undermine private property itself."
  ]},
  {h:"The capitalism-democracy contradiction",p:[
   "The second idea is a contradiction between capitalism and democracy. Socialising control over land means handing decisions to the state, and in a democracy the state is open to popular pressure. The risk for property owners and capital is that democratic control over land could go further than they want, for example towards public housing, redistribution of land values or stronger limits on property rights. Planning therefore has to be organised so that it serves capital's collective needs while containing democratic demands.",
   "In this reading, it is no accident that early planning institutions were often insulated from direct democratic control, through expert commissions, technical procedures and independent boards. Planning appears as a managed compromise: enough public control to keep the city working for capital, not so much that it becomes a vehicle for popular redistribution. Check whether the excerpt develops this point with concrete examples."
  ]},
  {h:"Planning as a contradictory, contested response",p:[
   "Foglesong positions himself in Marxist debates about the state. Instrumentalist theories see the state as directly controlled by capitalists; structuralist theories stress the state's relative autonomy and its role in securing capital's long-term, collective interests, even against individual capitalists. He leans towards a structural, contradiction-based view, but insists that outcomes are shaped by struggles between fractions of capital, property owners, reformers and working-class movements. In the book he traces this through episodes such as housing reform, the City Beautiful movement and the rise of zoning.",
   "The takeaway is that planning should be seen neither as neutral public-interest expertise nor as a simple capitalist tool, but as a contradictory response to tensions built into capitalist urbanisation, whose form reflects the balance of political forces at a given time. Check on Brightspace how much of the historical material and the state-theory discussion actually appears in the excerpt."
  ]},
  {h:"Connecting it to the course",p:[
   "This section is my synthesis. Foglesong belongs to the Marxist political-economy tradition in planning theory. On the course dimensions, he stresses structure (contradictions of capitalism) while allowing agency through class and political struggle; planning mainly reproduces capitalist relations, though conflict creates openings for change. His knowledge claim is general about capitalist cities but grounded in US history, and his normative stance is critical of planning's role in protecting property.",
   "Links with other readings: Taylor's Melbourne landowners fighting a betterment levy illustrate the property contradiction in a concrete case, and Sorensen's Toronto struggle over who pays for growth can be read the same way, although Sorensen uses historical institutionalism rather than Marxist state theory. Moroni offers the opposite normative view, treating private property as a beneficial evolved institution rather than a source of contradiction."
  ]}
 ]}
};
