const EXT_4={
harvey:{ext:[
{h:"What the article asks and why",p:[
"Harvey opens by placing this paper inside his long-running project: understanding how urbanisation shapes social change under capitalism. His starting point is dialectical. Cities are shaped by the logic of capital circulation and accumulation, but what gets built (roads, office districts, institutions) then constrains what capitalists and everyone else can do later. Capitalists, like workers, find themselves dominated and constrained by their own creations (p. 3). He also complains that studies of economic and social change too often treat urbanisation as a side-show. This paper tries to correct that by asking what role the urban process plays in the radical economic restructuring and uneven geographical development of the 1970s and 1980s (pp. 3–4).",
"The concrete puzzle is a shift in how cities are governed. The abstract states it plainly: urban governance has become 'increasingly preoccupied with the exploration of new ways in which to foster and encourage local development and employment growth' (p. 3), whereas earlier decades focused on the local provision of services, facilities and benefits. Harvey calls the first stance entrepreneurialism and the second managerialism. He wants to know why this shift happened, how inter-urban competition shapes its outcomes, and what its macro-economic consequences are. His position in the debate is Marxist political economy, but, as the ending shows, not a purely pessimistic one."
]},
{h:"The shift from managerialism to entrepreneurialism",p:[
"Harvey's first piece of evidence is a colloquium in Orleans in 1985, which brought together academics, business people and policymakers from eight large cities in seven advanced capitalist countries (p. 4). There was a strong consensus that urban governments had to become much more innovative and entrepreneurial; the only disagreement was about how. Should cities create or rescue firms themselves, or confine themselves to offering infrastructure, sites, tax baits and cultural attractions? For Harvey this is symptomatic of a wider reorientation: the 'managerial' approach of the 1960s gave way to 'entrepreneurial' forms of action in the 1970s and 1980s, and remarkably the consensus seemed to hold across national boundaries and even across parties and ideologies (p. 4).",
"He illustrates this from Britain and the United States. British local authorities became directly involved in economic development from the early 1970s, encouraged by central government; even David Blunkett, Labour leader in Sheffield, endorsed a kind of local entrepreneurship (p. 4). In the US, where boosterism (aggressive local promotion) had a long tradition, the cut in federal redistributions after 1972, when President Nixon declared the urban crisis over, revived boosterism so strongly that state and local governments were described as 'the last entrepreneurs' (p. 4). The shift was not complete: New Orleans remained a 'ward' of the federal government, dependent on redistribution, and the record was full of failures as well as successes (pp. 4–5).",
"Why did it happen? Harvey lists a backdrop rather than a single cause: the recession of 1973, deindustrialisation, seemingly 'structural' unemployment, fiscal austerity at national and local levels, and a rising tide of neoconservatism with its appeal to market rationality and privatisation (p. 5). The nation state's declining power to control multinational money flows also meant that investment increasingly took the form of a negotiation between international finance and local powers trying to make their site attractive. He suggests that urban entrepreneurialism may have helped the transition from a Fordist-Keynesian regime of accumulation (mass production backed by the welfare state) to 'flexible accumulation' (more mobile, market-based production). He also warns that if cities are locked in zero-sum competition, even radical 'municipal socialists' will end up playing the capitalist game (p. 5)."
]},
{h:"Conceptual groundwork: process, things and governance",p:[
"Before going further, Harvey clears up two conceptual problems. The first is reification: talking about 'cities' as if they act. That language makes it seem as if cities are active agents when they are really things (p. 5). Urbanisation should rather be seen as 'a spatially grounded social process' in which many actors with different goals interact. Under capitalism the class practices linked to capital circulation and the reproduction of labour are hegemonic, although spatial practices also have gender, racial and bureaucratic contents. The process produces artefacts (built form, institutions, legal and administrative systems) that then dominate later action, so there is a permanent tension between process and thing (pp. 5–6). He adds that the shift must be studied at several scales, from neighbourhood to nation state (p. 6).",
"The second point is that urban 'governance' means much more than urban 'government' (p. 6). The real power to reorganise urban life often lies in a broader coalition in which local government only facilitates and coordinates. Harvey lists the usual members: chambers of commerce, financiers, industrialists, property developers (the 'growth machine' in Molotch's term), but also universities, religious institutions, unions, parties, social movements and the many parts of the local state. Building such coalitions is delicate, which opens space for individuals with vision: a charismatic mayor such as Schaeffer in Baltimore, or private entrepreneurs in Halifax or Gateshead (pp. 6–7). So entrepreneurialism is not simply what city hall decides; it depends on class alliance formation."
]},
{h:"Three features of the new entrepreneurialism",p:[
"Using Baltimore as his main case, Harvey makes three broad assertions (p. 7). First, the centrepiece is the 'public-private partnership': traditional local boosterism combined with local government powers to attract external funding, direct investment and jobs. In Baltimore the turning point can be dated exactly: a narrowly passed 1978 referendum allowed city land to be used for the private development that became Harborplace, after which partnership had a popular mandate. Harvey notes that in the 1960s US cities had instead used redistribution (housing, education, health care for the poor) to regain social control after urban unrest, and that the role of the local state as facilitator of capitalist development had then declined (p. 7).",
"Second, the partnership is entrepreneurial because it is speculative in design and execution, with all the dangers that brings compared with rationally planned development. Often 'the public sector assumes the risk and the private sector takes the benefits' (p. 7), though not always (the private risk taken in Gateshead's Metrocenter shows the exception). What is new, Harvey suspects, is risk absorption by the local rather than the national public sector. Third, entrepreneurialism focuses on the political economy of place rather than territory (pp. 7–8). Territorial projects such as housing and education improve conditions within a jurisdiction. Place projects (a civic centre, an industrial park, a waterfront) have indirect benefits that may be wider or narrower than the jurisdiction, and they tend to divert attention and resources from the region's broader problems. Baltimore's harbour could benefit the metropolitan region; New York's South Street Seaport mainly served local developers and financiers (p. 8)."
]},
{h:"Four strategies for competing cities",p:[
"Harvey then describes four basic options, which cities combine (pp. 8–10). First, competing in the international division of labour: creating or exploiting advantages for producing goods and services, such as resources, location, infrastructure, subsidies, labour quality and cost, and agglomeration economies (benefits of clustering many activities close together), as in Bologna and Emilia Romagna. Local wage control is easier when local bargaining replaces national bargaining. Second, competing in the spatial division of consumption: tourism, retirement, gentrification, cultural innovation, postmodern design, stadia, convention centres, marinas and spectacles. 'Above all, the city has to appear as an innovative, exciting, creative, and safe place to live or to visit, to play and consume in' (p. 9). Baltimore expanded tourist employment from under one to over fifteen thousand jobs in less than two decades.",
"Third, cities compete for control and command functions in finance, government and information processing, which need expensive infrastructure such as airports, teleports and well-linked offices, and where established centres like New York and London have strong monopoly power (pp. 9–10). Fourth, they compete for redistributions from central (or US state) government, for example military contracts that sustained Bristol and Long Beach-San Diego (p. 10). The strategies are not exclusive, and uneven growth comes partly from synergy between them; Los Angeles grew through the interaction of defence spending, command functions and consumption activities (p. 10).",
"This competition has a disciplining effect. As inter-urban competition becomes more potent it acts as an 'external coercive power' over individual cities, bringing them into line with the logic of capitalist development and forcing 'serial reproduction' of the same forms: world trade centres, waterfronts, cultural centres, postmodern shopping malls (p. 10). Falling transport costs make small differences between places (labour, infrastructure, taxation, regulation) matter more to mobile capital, so urban governance becomes oriented to a 'good business climate' (p. 11). Speculation follows because no one can predict which package will succeed, producing upward and downward spirals that leave the urban system more, not less, vulnerable (p. 11)."
]},
{h:"Macro-economic and social consequences",p:[
"Section 4 asks what all this means beyond individual cities (pp. 11–14). Paradoxically, public risk absorption and public infrastructure provision lower the cost of relocating for multinational firms, making them more rather than less mobile. Localities become sites for regulating labour relations, supporting flexible management strategies. Harvey therefore argues that urban entrepreneurialism facilitated the move from rigid Fordism to flexible accumulation, and links it to postmodern design: 'urban fragments' rather than comprehensive planning, ephemerality, and 'image over substance' (pp. 12–13).",
"The distributive effects are regressive. Much of the US public-private partnership amounts to a subsidy for affluent consumers, corporations and command functions to stay in town, at the expense of collective consumption for the working class and poor (p. 12). Jobs polarise into low-paid and very high-paid positions, and informal work grows. Even progressive councils struggle, because competition works 'not as a beneficial hidden hand, but as an external coercive law forcing the lowest common denominator of social responsibility and welfare provision' (p. 12). Imitation makes any advantage ephemeral: how many convention centres and harbour places can there be? Instability follows: Houston, Dallas and Denver collapsed after 1980, New Orleans' World Fair was a disaster, credit-financed malls and stadia feed overaccumulation, and several 'festival market places' lost millions (p. 13).",
"Why do such projects stay attractive? Because selling the city depends on an attractive urban image, and image has internal political uses (pp. 13–14). It counters alienation, creates civic pride and a sense of belonging, and so opens mechanisms of social control: the Roman formula of bread and circuses reinvented. Baltimore is the case in point: the harbour earned it the title of renaissance city while local studies found serious decay behind the glitter and accelerating decline. The image consolidated the power of the public-private partnership that built it. Harvey's verdict: 'The circus succeeds even if the bread is lacking. The triumph of image over substance is complete' (p. 14)."
]},
{h:"Autonomy, competition and the critical perspective",p:[
"In the final section Harvey addresses a theoretical debate on the 'relative autonomy' of the local state (pp. 14–15). Entrepreneurialism looks like considerable local autonomy, and he explicitly does not claim that urban governance is automatically captive to capitalist class interests. The key is timing. Following Marx, competition is the 'bearer' of capitalist social relations: its coercive laws discipline firms, states and cities, but the forcing occurs after the event rather than before (p. 15). Cities, like firms, experiment speculatively, and inter-urban competition then sorts winners from losers. Relative autonomy in this sense is fully consistent with capital accumulation. The managerial era of the welfare state and Keynesian compromise was the exception; the revival of civic boosterism, a tradition going back to the Hanseatic League, moves urban governance closer to the naked requirements of capital accumulation (p. 15).",
"A critical perspective should therefore contrast the surface vigour of regeneration projects with underlying trends, notably a 'dual city' of inner-city regeneration surrounded by a sea of impoverishment, and should expose regressive distribution, volatility and ephemeral benefits (p. 16). Yet Harvey sees something positive too: the idea of the city as a collective corporation with democratic decision-making, with the Paris Commune as the paradigm case. The problem is less boosterism itself than the generality of inter-urban competition, which makes 'bad' projects drive out 'good' and forces well-meaning coalitions to be 'realistic' and 'pragmatic' (p. 16)."
]},
{h:"Conclusions and what the author wants",p:[
"Harvey concludes that 'Socialism within one city is not, of course, a feasible project even under the best of circumstances' (p. 16), but cities remain important power bases. What he wants is a geopolitical strategy of inter-urban linkage that mitigates competition and shifts political horizons from the locality towards a broader challenge to capitalist uneven development. Working-class movements have commanded the politics of place before, but have been vulnerable to the greater command over space of an internationalised bourgeoisie. Hence his hope for 'a progressive urban corporatism' that builds alliances across space (p. 16).",
"Harvey is open about limits. His three assertions are true for Baltimore and only may be more generally applicable (p. 7); the history of outcomes is yet to be properly recorded (p. 5); and a full analysis of the welfare state's role in local autonomy is left for elsewhere (p. 15). The evidence is illustrative (Baltimore, British cities, press reports, secondary studies) rather than systematic, which is typical of a theoretical essay."
]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not Harvey's claims. The article rests on Marxist political economy, and on the course's dimensions it leans towards structure: agents experiment, but competition disciplines them after the event. It explains mostly reproduction (entrepreneurialism deepens uneven development), with a thin opening for transformation through inter-urban alliances. Change here is largely emergent: nobody designed the global shift; it results from many speculative local moves filtered by competition. Knowledge claims are universal in ambition (laws of capital accumulation), though grounded in Baltimore. Normatively Harvey is explicit: he wants redistribution and a progressive, anti-capitalist urban politics.",
"It is the reference point for the week 6 readings. Hyötyläinen and Haila explicitly borrow Harvey's managerial/entrepreneurial pair to describe Helsinki selling public land, and Savini and Aalbers build on Harvey's work on land as a financial asset and 'capital switching'. Compared with regime theory or growth coalitions in Rydin's chapter, which emphasise how local actors assemble 'power to' govern, Harvey places the same coalitions inside a structural competitive logic. Against collaborative planning or pluralist views, he would argue that consensus-building locally cannot escape the coercive laws of inter-urban competition."
]}
]},

hh:{ext:[
{h:"What the article asks and why",p:[
"Finnish cities own a lot of land (Helsinki owns 60% of its land area, p. 138) and traditionally allocated it free of charge for schools, day-care centres and libraries, and leased rather than sold land for development. Since the 1990s they increasingly sell land or charge market rent. Hyötyläinen and Haila call this 'entrepreneurial public real estate policy': a rent-maximising policy carried out not by private landlords, developers or REITs (real estate investment trusts) but by municipalities and the state (p. 137). It is neoliberal in the sense of introducing a market logic into the use of public land.",
"The article asks three things (p. 137): how this policy was justified and why cities adopted a business model for public land; what conditions enabled it; and what kind of built environment it produced. The case is Eiranranta, a residential area on Helsinki's prestigious southern shore, where the city sold land to private developers who built a fenced neighbourhood for wealthy owners. The authors position themselves in debates on the political economy of urban land and neoliberal urban policy (Brenner and Theodore, Harvey, Peck), and claim three contributions: analysing land policy by the state and municipalities, analysing property and development rights, and analysing the inequalities neoliberal real estate policy produces in a Nordic welfare city (p. 138)."
]},
{h:"From leasing to selling: the new real estate policy",p:[
"Section 2 sets the background (p. 138). Leasing had given Finnish cities control over land use now and in the future, and keeping planning power with town planners helped create a socially sustainable, heterogeneous urban fabric without glaring concentrations of wealth or poverty. In Helsinki this changed in 1993, when the city began selling land. From 1994 the Real Estate Department managed all city land and started calculating 'shadow rents' for city services, which the authors describe as a way of getting used to the market game. In 2005 the city created the Premises Centre, which charges its own departments market rent.",
"The state went first. Until 1995 a National Board of Public Building managed state property, funded from the budget; it was then replaced by state real estate companies (Kapiteeli, Senaatti, Sponda). The early-1990s recession was both an excuse and an opportunity: the state had taken over property from bankrupt banks and firms and adopted a new rationality of using public resources as efficiently as possible (p. 138, citing Haila 2008). The state companies then clashed with cities. One case: the state company demanded the price of developed land for land sold to Helsinki, while the city insisted on raw-land prices, because Finnish cities hold the 'planning monopoly' (sole right to assign development rights), so value increase from development belongs to them (p. 138)."
]},
{h:"Scaling down land use decisions",p:[
"Section 3 explains the enabling conditions: three changes gave cities a new environment for land decisions (pp. 138–139). First, a new state urban policy from the mid-1990s. Instead of financing all municipal services and reducing regional inequality, the Ministry of the Interior asked cities to draw up 'urban programmes' (modelled on British and French urban policy) and funded only some of them. This made cities compete for subsidies, encouraged partnerships with private actors and ceded planning responsibility to ad hoc project organisations and public-private partnerships. In Finland, the authors stress, it was the state that pushed cities towards new public management and competition (p. 139).",
"Second, a new redistribution policy after the deep recession. The state cut spending, preached 'the necessity to save' and shifted social service provision to municipalities; the welfare state began turning into welfare cities (p. 139). Third, the Land Use and Building Act (MRL, 1999) gave cities more autonomy: their plans no longer needed state ratification. That removed the state's role as independent mediator between conflicting interests, a role it could no longer play anyway because it had become a real estate player itself. MRL also legalised 'development areas' and development contracts (agreements between a municipality and a private landowner about a plan and its implementation). Critics recalled that such contracts in the 1960s and 1970s produced poor-quality, peripheral housing estates. Selling land, the authors conclude, gave developers more power in planning (p. 139)."
]},
{h:"How the policy was justified",p:[
"Section 4 identifies four justifications (p. 139): put public assets to work, make land use efficient, increase transparency, and create diversity. Politicians repeated 'the necessity to save' and Prime Minister Sipilä's slogan that public assets have to be put to work, meaning they should be assessed by market value. The authors, using Bourdieu, call this a 'strong discourse' that made market rule seem natural. The newspaper Helsingin Sanomat asked why land should be given at discount to developers of rental housing instead of sold at the highest price, and state researchers argued that without market prices the costs of land use are opaque. The Premises Centre claimed rents make costs more transparent and use efficient, without explaining what those words meant.",
"The authors also criticise fellow academics. Urban scholars who celebrate residents' free choice and neighbourhood diversity end up accepting privatisation of public land. One Finnish scholar is quoted saying that a good city can have both luxury and rough areas. Such statements, the authors argue, justify a two-sided policy: let some areas become rough and develop owner-occupied housing on privatised land (pp. 139–140). The empirical question then becomes whether selling land really saves money, creates efficiency and transparency, and produces diverse neighbourhoods."
]},
{h:"The Eiranranta deal and its motives",p:[
"Eiranranta was originally a rocky shore next to the old working-class district Punavuori, later used for light industry, waste water and a city depot; it was rezoned as residential in 2001 (p. 140). In 2004 the Real Estate Committee (REC, a politically elected body) decided to sell four sites, with the highest offer winning, provided bidders showed exceptional building expertise. This shows what 'efficiency' meant in practice: land should go to its highest-paying use. REC members explained the motives. The city budget contained massive sales goals for the Premises Centre. Deputy Mayor Pekka Korpinen, an economist, brought an economist's mindset and argued shorelines should be sold to maximise revenue rather than used for social housing. Even the name was strategic: 'Even the name was changed to Eiranranta with marketing in mind', linking it to the prestigious Eira district (p. 140).",
"The deeper motive was competition. Land policy became a 'strategic' tool, and 'coordination' now meant competing with neighbouring municipalities rather than balancing development (p. 140). Helsinki feared that Espoo and Kauniainen would attract the 'good taxpayers', since municipal income tax is the main local revenue. The city also wanted to look like a 'global city' against Copenhagen, Stockholm and Tallinn, and here the authors explicitly borrow Harvey's (1989) terms: managerial strategies were being replaced by entrepreneurial ones (p. 140). Developers and firms insisted there was demand for luxury housing and that Anglo-American companies want to own, not lease, land (p. 141)."
]},
{h:"The controversy over Apollo",p:[
"When the bids were opened in 2005 the price hit a Finnish record: €2,621 per square metre, €54 million in total (p. 141). The four winners were three established 'household developers' (SRV, NCC, Tarkala) and Apollo, an investment company new to Helsinki, which bid three million euros more than the others, whose bids were surprisingly close together. The Real Estate Department wanted to reject Apollo and sell to Skanska instead, even though Skanska bid lower, arguing Apollo lacked experience; the Deputy Mayor and City Council backed Apollo. One REC member suspected a kind of cartel among established developers (p. 141). Apartments later sold at €10,000 to €16,000 per square metre.",
"The authors read this as more than a dispute about experience. Established developers probably knew they could extract land rent and the value increase created by public development rights from the city; Apollo may simply have bid the market value (pp. 141, 143). Meanwhile nobody questioned selling public land itself: REC members agreed unanimously, and only one councillor opposed the deal. As one member said, land ownership had become secondary and 'Those are the rules of the game today' (p. 141). The new policy had become common sense."
]},
{h:"Not for social housing, and a gated community?",p:[
"Section 7 confronts Eiranranta with Helsinki's official social-mix policy, agreed with neighbouring cities to prevent segregation by building social housing in all neighbourhoods (p. 141). Eiranranta had no social housing and the city's highest prices. REC members did not see this as a problem: 'Not every place needs to be mixed' (p. 142). They opposed concentrations of social housing in stigmatised areas like Jakomäki, but not concentrations of wealth. The authors explain this inability to spot the warning signs of segregation by the members' focus on real estate business; Eiranranta was treated as a disconnected project, something MRL made possible (p. 142).",
"Section 8 describes the built result (pp. 142–143). The master plan required that 'the blocks are to be bordered with 1.2 m high fences, which prevent visibility and the entrances are to be gated'. Adverts stressed alarms, camera gate phones, private housekeeping space and the fact that 'no common laundries are needed'. The architecture is inconspicuous; the public street between the eight buildings feels empty and uninviting, in contrast with the busy public beach, park, skate area and needle exchange next door. Brokers pictured residents as highly paid academics, option millionaires and CEOs around 50 without children. Is it a gated community? The authors say no: residents still pay city taxes, use public services, and the fences allow right of passage (p. 143). But it is an exclusive enclave, new for a Nordic welfare city."
]},
{h:"Conclusions and what the authors want",p:[
"The conclusions (pp. 143–144) return to the three contributions. On policy: by corporatising its own real estate, the state gave cities a model, and through urban policy, subsidy rules and planning law it pushed them to treat land as a strategic, revenue-raising tool. Uniquely, the Finnish state thereby lost its impartiality and its ability to manage the contradictions of marketisation. On property rights: selling sites also meant privatising development rights, making it harder for the city to implement future plans there, and even common laundries became private space. Selling to an investment company might break developers' monopoly, but might also start a phase in which Helsinki property becomes a pure financial asset, bought and sold for its rent (Harvey 1982).",
"On inequality: Helsinki has avoided the distress of large European and American cities through social policy, social housing and tenure mix; entrepreneurial land policy contradicts these instruments. Eiranranta was 'an experiment by the City to test the upper end of the housing market', and the authors end by hoping it does not lead to more selling off of public land (p. 144). The limits are visible in the method: policy documents, five of nine REC members interviewed (others could not be reached or refused), and field observation (pp. 137–138). Some explanations, such as why Apollo bid more, are explicitly offered only as plausible."
]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The article applies political economy of urban land and neoliberal urbanism, and borrows Harvey's managerial/entrepreneurial distinction directly. On structure versus agency it sits in between: state restructuring and inter-city competition create pressure, but named actors (Korpinen, the REC, developers) make choices and hold ideologies. It describes transformation of Helsinki's institutions but reproduction of class advantage. The change is partly deliberate (state policy pushed cities) and partly emergent (a first deal makes the next easy). Knowledge is situated in a Nordic welfare context, and the normative commitment is clear: public land, social mix and equality.",
"Compared with Harvey, the case shows entrepreneurialism working through land ownership rather than flagship spectacle, and in a strong welfare state. Compared with Savini and Aalbers, Helsinki is a strong, land-owning municipality rather than a weak one, yet it still hands over planning power; the closing worry about investment companies and liquidity links directly to their financialisation argument. For a Dutch reader, the story invites comparison with debates on municipal land banking and erfpacht (ground lease) versus sale in Amsterdam and Utrecht."
]}
]},

savini:{ext:[
{h:"What the article asks and why",p:[
"Savini and Aalbers study how financialisation affects land use planning. Financialisation here means the growing role of financial actors, motives and instruments; for land, it means land is treated as a financial asset that can be bought, sold, bundled and borrowed against. Finance increasingly penetrates real estate and land development, but the authors note that in-depth case studies of the actual mechanisms are rare (p. 2). They want a fine-grained view of how the organisation of credit in the development industry shapes what gets built. Their key concept is 'de-contextualisation': investment decisions about land are increasingly made by investors at other scales and detached from the local planning process and local needs (p. 1).",
"They start from Harvey's idea of 'capital switching': financial capital keeps inventing ways to reconnect global strategies to local built environments (p. 1). Cities, meanwhile, try to anchor mobile capital through urban projects, which have become a key space of confrontation between global markets and local socio-economic demands (p. 2). Their position in the debate is explicit: Weber (2010) argued that local governments are not passive recipients and can use financial markets to push their own agenda, but the authors are more sceptical than Weber about whether most municipalities can do so (p. 2). The paper first sets out three trends, then analyses the Falck site near Milan, then draws conclusions."
]},
{h:"Three trends: relocation, clustering, instrumental planning",p:[
"Real estate is a commodity in tension: immobile, yet tradable on global markets as a liquid asset (p. 3). Cheap money, regulation favouring economies of scale, long-term guarantees and flexible land-use rules institutionalised a cycle of production, leverage and exchange. The first trend is investment relocation. In the 1980s and 1990s capital concentrated on downtown renewal and waterfronts; then big players moved to riskier out-of-prime locations such as brownfields in urban belts and peri-urban areas. These have high initial costs (soil remediation, weak land pressure, little infrastructure) but promise higher long-term yields, so they suit large consortia that can repackage risk and deal directly with banks (p. 3).",
"The second trend is clustering and enlargement. Investors concentrate on specific catchment areas and combine projects into larger programmes to dissolve fluctuations in demand. Projects become 'creators of growth' rather than responses to local demand, smaller investors are bought out, and projects become standardised (star architects, recognisable symbolism) to increase liquidity (pp. 3–4). The third trend is instrumental land use planning: planning geared to facilitating this process. Financial capital is ultimately bound by local zoning, fees and building rights, so municipalities matter. But fiscal stress and social problems can make them dependent on incoming capital, pushing profit-oriented planning in the hope that public benefits trickle down (p. 4). Local governments are not passive: they try hub planning, value capture incentives and flexible contracts."
]},
{h:"De-contextualised land capital",p:[
"The core argument follows (pp. 4–7). As land becomes a (quasi-)financial asset managed in portfolios together with other assets elsewhere, decisions on its use are disconnected from local cultural values, norms and meanings. 'In becoming liquid, land is decontextualised from the local' (pp. 4–5). Values rest on simplified calculations of expected yields that ignore the complexity and uncertainty of urban projects; in recent years such estimates were excessive. Decision-making splits: land use programming tries to match local needs, while investment decisions follow shareholder profit expectations. Between them sit many layers: a local project team, a development firm, a holding company, investors ranging from individuals to pension funds, plus consultants and fiscal advisors (p. 5). Where the mid-1980s were dominated by locally embedded developers, today's developers can be completely extraneous to the local context (p. 5).",
"Land markets changed too. Former industrial groups began valorising their land from the mid-1980s, and land is now also used as collateral: something you borrow against to finance investments elsewhere (p. 6). The authors cite Harvey's 1982 warning that an open land market lets surplus money capital build pyramids of debt claims. The key organisational tool is the special-purpose vehicle (SPV): a separate company set up for one project, linked to a 'generator' company or holding. It isolates the project's risk, can be sold between holdings, works locally with architects and planners, and passes gains to shareholders. 'SPVs are therefore both separators and connectors between the land use planning process and investment strategies' (p. 6). Programmes tend to be supply-driven: calculate, build, then sell.",
"This creates problems for governments trying 'value capture' (recovering part of the land value increase for public benefit, p. 6). Tools include strict regulation, betterment levies, public land development and mixed corporations, project bonds and tax increment financing (pp. 6–7). But when investment is detached from land use decisions, cities, especially small and weak ones, poorly understand the economic calculations and cannot judge what programme is viable. Overregulation might scare off investors, cause long-term vacancy or encourage speculation (p. 7)."
]},
{h:"The Falck site: setting and method",p:[
"The Falck site is a 150 hectare former steelworks in Sesto San Giovanni, a municipality of over 80,000 inhabitants in Milan's industrial belt, well connected by rail (p. 7). About a quarter of the city's area is vacant industrial land, so it urgently needs investment in infrastructure, social housing and public facilities. The site is heavily polluted and has valuable industrial heritage. Planning happens under the PII regime (Programmi Integrati di Intervento), which requires close negotiation between municipal executives and the developer. For 15 years these negotiations produced no agreement, while the land was sold four times at steadily rising prices (p. 7).",
"The data come from city council decisions, 20 stakeholder interviews, participation in discussion groups, designers' and managers' documents, the economic sections of successive masterplans, and documents from the Milan attorney general and legal appeals (p. 8). Table 1 (p. 9) summarises four periods by owner, financial model, programme, expected return and land cost. The Milan context matters: in the 1990s specialised financial players, landowning non-real-estate corporations (such as Pirelli at Bicocca) and institutions clustered around planned developments, outplaying smaller investors (p. 9)."
]},
{h:"Four periods of ownership",p:[
"First period (1990s): the Falck Steel Corporation, once Italy's largest industrial company, stopped production in 1994 and turned the brownfield into a project as part of corporate restructuring (p. 10). A joint-stock development agency (PSTA, later ASNM) was owned 80% by the municipality, 5% by the province and 15% by Falck, and drew on European programmes. Its aim was transition to 'innovative' production and saving jobs. High costs and a booming housing market led Falck to drop reindustrialisation and sell. Second period (2000–2005): a local real estate investor bought the site (for €180 million according to the text; Table 1 lists a €140 million land cost) and created an SPV, Immobiliare Cascina Rubina, financed by a large Banca Intesa loan (p. 10). Negotiations were direct between owner and Deputy Mayor, about jobs; the 2002 plan was mainly residential with a modest 9% return, but was never approved.",
"Third period (2005–2010): rising interest rates led to the SPV's sale to Risanamento, owned by Gruppo Zunino, a holding active in Milan, New York and Paris, which bought with little capital, inherited the debt and issued stock for 25% of the value (p. 11). Falck was clustered with other projects such as Santa Giulia. Renzo Piano's masterplan almost doubled the built surface, with 50% high-end housing at around €4,500 per square metre, and aimed at a 15% gain on about €5 billion. Fourth period (2010 onward): after the credit crunch, Milan's prosecutor started bankruptcy proceedings against Risanamento in 2009 (p. 12). A new SPV, Sesto Immobiliare, with a complex set of investors (including Korean investors), bought the land for €405 million, largely by transferring ownership to creditor banks, on condition that the municipality approve a masterplan of at least 962,000 square metres within two years (p. 12)."
]},
{h:"How finance reshaped the plan",p:[
"In this last phase everyone depended on everyone else. The SPV pressed for quick approval to cover inherited debt; the municipality felt pressure to approve and secure public gains. The programme grew to almost 1.2 million square metres, while lower equity use allowed expected earnings of 12% (pp. 12–13). The project was split into economically independent compartments, each financed from the previous one's earnings, with about 25% of costs expected from buyers' cash advances, uncertain after the housing bubble burst. Any public demand for more facilities could further jeopardise the project (p. 13). In September 2011 the council approved a plan with more retail and offices and less high-end housing and manufacturing, boosted by the regional government's €323 million for a health and research campus (p. 13).",
"The authors explain the outcome by two concurrent trends (pp. 13–14). First, growing institutional 'distance' between developer and financiers: each transfer bound the project more tightly to financial returns and to promises of future yields from a project not yet materialised, and the programme had to be intensified to realise larger profits. The land generated credit through company bonds, yet no brick had been laid (p. 14). Second, and decisive, Sesto became dependent on the project's yields. Too small to take on the risk of active partnership, it regulated and waited. Planning became 'functional to the urgent need to unlock capital for realisation, rather than being a tool to respond to particular local needs' (p. 14), and zoning did not stop speculation but allowed higher volumes."
]},
{h:"Conclusions and what the authors want",p:[
"The conclusion names three features of de-contextualisation: separation between ownership and planning responsibility; intermediate levels (SPVs) that insulate risk; and complex, nested property structures of international scope (p. 14). Theoretically they claim that financialisation goes 'one step further than Harvey foresaw in 1982': land is not only a spatial fix for overaccumulation elsewhere, but is itself used as collateral to create credit for investment elsewhere; only now does the full meaning of land as fictitious capital become apparent (pp. 14–15). For local government this creates a trade-off: capture as much value as possible, yet excessive demands may kill the project, so cities tend to rely on strong regulation (p. 15).",
"They stress that gridlock is not inevitable. The complexity of financial constructions and the regulatory position of public authorities are what differentiate outcomes: the more complex the ownership and the less proactive the government, the more de-contextualisation (p. 15). Chicago in Weber's work may be the exception; Sesto 'is being shaped and constrained by finance without being able to give shape to financial markets' (p. 15). Their recommendation: combine strong regulation with proactive capacities to intervene in land development. Limitations they admit: Falck is one particular extreme case (p. 14), outcomes need not be the same elsewhere, and at the time of writing the project's realisation remained uncertain (p. 7)."
]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The article combines Harvey's political economy (capital switching, land as fictitious capital) with an institutional view of local government capacity. On structure versus agency it is more balanced than Harvey: financial structures push, but the municipality's choice to regulate rather than intervene proactively shapes the outcome, and the authors reject inevitability. It describes emergent rather than deliberate change: nobody planned the gridlock; it grew from successive ownership deals. Its knowledge claims are situated (one extreme Italian case, explicitly contrasted with Weber's Chicago) but generalised through a mechanism. Normatively it defends local socio-spatial equity and public steering of development.",
"Within week 6 it pairs well with Harvey (entrepreneurial speculation with public risk becomes, a generation later, financialised speculation with layered private risk) and with Hyötyläinen and Haila, who worry that selling Helsinki land to an investment company could start creating liquidity out of spatial fixity (their phrase, borrowed from Gotham). For Dutch planning, the call for proactive public land development connects to the tradition of active municipal land policy and its retreat after 2008, which would make a good comparison case (again, a link I am drawing, not the authors)."
]}
]},

rydin6:{ext:[
{h:"What the chapter asks and why",p:[
"This chapter from Rydin's textbook Theory in Planning Research introduces the urban politics perspective as a framework for doing planning research. It starts from the insight that conflict is unavoidable in planning, quoting Trapenberg Frick: 'Turbulent debates between politically divergent actors are part of the fiber of planning' (p. 105). The contrast is with the governance framework of the previous chapter, which assumes conflicts can be handled to reach effective and even agreed outcomes. Urban politics instead sees power at work in planning processes and inequality in their outcomes. Its focus is equity, equality and power in how planning handles conflict (p. 105).",
"This makes the perspective challenging and potentially normative. 'Planners cannot be neutral in this conceptual context' (p. 105): if planning may disadvantage the dispossessed, planners must act more like advocates than neutral technocrats, and justice becomes central. The perspective studies both elites and non-elites, because the position of those who gain little can only be understood by looking at those who gain most (pp. 105–106). The chapter follows a standard structure: framing the research, key concepts (growth coalitions and regimes, urban social movements, agonism), then worked examples of research papers, and conclusions on method."
]},
{h:"Beyond pluralism: activism, justice and the right to the city",p:[
"Rydin first distinguishes urban politics from pluralism, the view that groups form whenever there is demand to address an issue, so activism follows demand (p. 106). By the late twentieth century pluralism was seen as naïve: groups differed hugely in power and resources, some issues never became the focus of activism, and pluralism in effect legitimated a focus on middle-class pressure groups. Urban politics instead looks at activism outside institutionalised participation (petitions, meetings, lobbying), including non-violent occupations and even violence against property, which it treats as legitimate forms of protest by the disempowered (p. 106).",
"A strong concern with justice runs through this work, especially environmental justice, which grew from US cases where toxic sites were placed near communities of colour, such as Love Canal (p. 106). Rydin summarises Agyeman's four aspects of justice (pp. 106–107): recognition of all groups as self-determined groups, not just giving them voice; fair processes, especially open-ended visioning; just exercise of procedures such as regulation and implementation; and fair outcomes. A second justice theme is the Right to the City movement, protesting limited access to the city and the inequitable use of its assets, for example the Occupy movement after 2008 (p. 107). Because these conflicts are linked to wider power and inequality, the perspective is more modest about what planning alone can achieve: justice may require wider political change (p. 107)."
]},
{h:"Key concepts 1: growth coalitions and urban regimes",p:[
"The research question for planning is whether planning processes support capitalist interests (facilitating development) or middle-class interests (protecting areas from it), and whether they fail other groups and social movements (p. 107). The task is not sociological but about how planners and planning systems respond to conflicts. The first concept is the growth coalition, proposed by Molotch in the 1970s: a coalition of those with most to gain from land and development decisions comes together to secure the political conditions for property-led growth, often with close links to local government (p. 108). It was a reaction against technocratic views of planning. Critics from political economy found it too agent-based; others found it too simple, since coalitions are fragmented, unstable, not only local, and not always growth-oriented (p. 108).",
"From these critiques came urban regime theory, introduced by Stone in his study of Atlanta (p. 108). A regime emerges because local government cannot implement its agenda alone; actors pool resources because they are interdependent. The power involved is 'power to' achieve goals, not 'power over' others, and it works alongside formal politics, often invisibly. Stone defined a regime as 'an informal yet relatively stable group with access to institutional resources that enable it to have a sustained role in making governing decisions' (p. 108). Dowding et al. list eight empirical criteria, including a distinctive, long-lived agenda, a boundary-crossing coalition, survival of personnel changes, strong leadership and public-private partnerships (p. 109). Stone identified four regime types: maintenance or caretaker, development, middle-class progressive, and lower-class opportunity expansion (p. 109).",
"Regime theory still has a corporate bias: to access the systemic power of business, political leaders must cater to corporate interests (Pierre, p. 109). This was typical of US cities, which rely on local property taxes and have much autonomy from central government, so transferability is questioned. Holman identifies four obstacles for comparative use: more diverse actors, national differences in local autonomy, different incentives for business to engage in city politics, and globalisation (p. 109). Much research therefore asks how the concept must be amended to travel."
]},
{h:"Key concepts 2: urban social movements",p:[
"The second concept came from left-leaning theorists disheartened by political economy's message that structural change requires crisis and revolution (p. 109). They sought a more incremental path by treating politics as having some autonomy from capitalist structures. Gramsci was the key inspiration: the working class and the disempowered can perceive their own interests and develop programmes without a vanguard (p. 110). The word 'movement' signals more than a pressure group: it represents a fundamental social cleavage.",
"Castells theorised urban social movements (USMs) around 'the means of collective consumption': the public services needed to reproduce the labour force, such as housing and transport, which households cannot provide alone (p. 110). Movements resist both middle-class appropriation of services and their reduction to capitalist needs. Later work, for example Nicholls, linked USMs to cities as spaces of difference and freedom, and hence to identity politics and control over local spaces (pp. 110–111). Mayer describes four phases: industrial crisis (1960–1980), welfare state erosion and collective consumption (1980–1990), gentrification and regeneration (1990–2000), and globalisation and financialisation since 2000 (p. 111). Critiques note neglect of gender and a bias towards North America and Northern Europe. What remains distinctive is a physical base in a specific place (p. 111)."
]},
{h:"Key concepts 3: agonism and the persistence of conflict",p:[
"The third concept starts from a practical planning problem: civil society is diverse, so who represents 'the community' in governance networks (p. 111)? Planners tend to include self-organised groups, labelling others 'hard to reach' or 'silent', as if they were recalcitrant. Rydin asks what counts as a group at all: economic classes, self-identities (ethnicity, sexuality, status, politics), identities imposed and then reclaimed, and place-based interests. The term 'place attachment' is used partly to resist the pejorative label NIMBY (pp. 111–112).",
"Drawing on Mouffe, agonism rejects governance claims that deliberation can move towards consensus as misleading (p. 112). Conflict is seen as inevitable and even productive; the us-and-them division remains, but the aim is for groups to co-exist with respect. 'In essence, agonism involves a willingness to agree to disagree' (p. 112): opponents become adversaries who recognise each other's point of view, which Mouffe sees as more democratic than the false promises of deliberation. It has attracted attention as a possible new normative theory after collaborative planning, and links to critiques of post-political planning (Raco). Critics ask whether agonism simply accepts existing power inequalities (Yamamoto), which has spurred research on how conflicts are handled in practice (p. 112)."
]},
{h:"Research in practice: regimes and racism",p:[
"Rydin then reviews example studies. Ravazzi and Belligni (Turin) used regime theory with Kingdon's agenda-setting ideas, 50 interviews over seven years, network analysis and process sequencing (p. 113). A 'great alliance' of centre-left politicians, liberal business (the Group of 70 led by a banker) and Politecnico academics shifted Turin from pro-welfare towards market-centred policy through naming, blaming and claiming; after a narrow election win the regime opened up to a wider 'city dialogue' (pp. 113–114). Li and Liu (Guangzhou's 'Three Old Redevelopment' policy: old towns, villages and factories) preferred regime theory to growth coalitions but added 'fragmented authoritarianism' and 'strategic selectivity' because business is weaker and civil society thin in China (p. 114). Regime building occurred in some villages (Pazhou) but not in old towns, and long-term trust was often missing (p. 115).",
"On racism, Uysal studied Sulukule in Istanbul, a largely Romani area targeted in 2006 for state-led, tourism-oriented regeneration and demolition (pp. 115–116). The Sulukule Platform, a coalition of NGOs, Romani residents and outside activists, used meetings, festivals and an alternative plan (STOP), framed as a Castells-style USM. It failed to stop demolition; the text announces three reasons but lists six, including unclear property rights, speculation, lack of public support due to prejudice, lack of resources, fragmentation and counter-pressure from the council (p. 117). Miller Cantzler and Huynh examined Native American fishing rights in the Pacific Northwest since the 1974 Boldt decision, using distributive, procedural and recognition justice, and showed the role of Indigenous agency in challenging racial inequality (pp. 117–118)."
]},
{h:"Research in practice: managing conflicts",p:[
"The fastest-growing strand concerns agonism (p. 118). Trapenberg Frick studied tactical coalitions between Tea Party activists and progressive groups against sustainable infrastructure projects in three US cases, with 39 interviews (pp. 118–119). They cooperated while agreeing to disagree on fundamentals, for example on public transit or climate change. She distinguishes ephemeral, emergent and established coalitions (the Green Tea Coalition in Georgia being established), showing coalitions are pragmatic rather than cohesive (pp. 119–120).",
"Rogers studied REDWatch in Sydney, a community group that monitored government redevelopment plans rather than seeking consensus (pp. 120–121). Its website preserved documents that vanished from state websites, acting as an inconvenient corporate memory (p. 121), and government planners used its monitory status to argue internally for different outcomes; this informal agonism worked alongside formal participation. Fougère and Bond studied the consenting of a coal mine on the Denniston Plateau in New Zealand, including protests and a community 'Bioblitz' collecting ecological data (pp. 121–122). The most antagonistic moments occurred inside formal hearings; agonistic moments arose around shared conservation concerns, but expert technocratic knowledge limited their influence. They conclude that antagonism can create the space for agonism (p. 122)."
]},
{h:"Conclusions and what the author wants",p:[
"Rydin concludes that the strength of urban politics is bringing inequality, conflict and power to the fore, alongside cases of resistance to unjust planning (p. 123). It has a strong community focus and may lead into action research, offering perhaps a more critical perspective than the earlier frameworks. Methodologically it relies mainly on qualitative methods, although statistics can help show inequalities. Its normative dimension often pushes researchers from a detached analyst stance towards supporting the groups studied. Essential is the 'emic' perspective (the insiders' own view): understanding the situation from the viewpoint of disempowered groups through interviews, focus groups, observation or action research (p. 123).",
"As a textbook chapter, Rydin mainly reports rather than argues. The limitations she flags belong to the concepts: growth coalitions are too simple, regimes may not travel beyond the US, USM research neglects gender and the Global South, and agonism may accept existing inequalities (pp. 108–112). Note also what the chapter does not include: no discussion of Lukes' dimensions of power, and Lefebvre appears only in a reference title; the Right to the City gets one paragraph."
]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not Rydin's claims. The chapter is a map of agency-oriented theories: regimes and social movements explain how actors assemble 'power to' act, in contrast to the structuralist political economy of Harvey (which Rydin herself notes criticised growth coalitions as too agent-based). On reproduction versus transformation, regimes often reproduce corporate bias, while social movements and agonism hold out transformation. Most cases describe deliberate coalition-building within emergent contexts. The perspective is pluralist in method yet critical of pluralism as a theory, situated in its knowledge (emic perspective, transferability debates), and openly normative about justice.",
"Useful contrasts: Harvey's growth coalitions and public-private partnerships are the same actors that regime theory studies, but Harvey subordinates them to inter-urban competition; the Helsinki REC in Hyötyläinen and Haila looks like a development-oriented governing coalition without real contestation. Agonism positions itself against collaborative planning (Healey, Innes), which Rydin treats as governance theory in the previous chapter. For exam answers, keep 'power to' (Stone) distinct from 'power over', and do not attribute Lukes or Lefebvre to this chapter."
]}
]}
};
