const EXT_5={
bossuyt:{ext:[
{h:"What the article asks and why",p:[
"The article starts from a blunt observation: the global housing crisis shows that private markets fail to guarantee adequate and affordable housing, and in response the 'commons' has emerged as a way of thinking about reclaiming housing (p. 1021). In central São Paulo, housing movements occupy vacant buildings, both to shelter people and to assert rights. Earlier research read these occupations through the lenses of citizenship and urban reform; a newer strand reads them as 'urban commoning', the collective practice of producing and managing a shared resource. Bossuyt and D'Ottaviano join that newer strand but push it in one specific direction.",
"Their puzzle is about time. Most work on urban commons focuses on loss and reclamation: how a resource is taken back from state or market. Much less is known about reproduction, meaning how a commons survives once it exists. Ostrom's work on common-pool resources (fisheries, forests) studied stability extensively, but the urban literature has 'somewhat overlooked' this dimension (p. 1021). Because capitalist urbanization and state cooptation keep threatening to take commons back, the authors argue that understanding how housing commons endure is just as important as understanding how they are won.",
"The article therefore asks: through which mechanisms are housing commons protected, and what role do social movements and property claims play in that protection? The empirical answer comes from two occupations in central São Paulo, Dandara and Marisa Letícia, that were turned into permanent self-managed housing. The authors identify five 'patterns of protection': regularization, restoration, integration, ideation and federation (p. 1021). They also show that each of these protections is partial, which becomes the most interesting and uncomfortable part of the argument."]},
{h:"Housing as a commons and the threat of enclosure",p:[
"The authors first define their terms. 'The commons' refers to resources that are collectively produced, shared and used for their use value; 'commoning' refers to the active practices of sharing and managing them (p. 1022). Two traditions meet here. Institutionalist scholars (Ostrom) see commons as sets of rules that communities create to manage resources without relying on state or market. Neo-Marxian scholars (Caffentzis and Federici, Dardot and Laval) see commoning as a political principle opposed to capitalism. The article builds on Massimo de Angelis, for whom commons are social systems of shared resources, sustained and reproduced by a group through commoning practices. Housing is not a commons by nature; it becomes one through an open-ended interaction of practices and rules.",
"Housing commons have three dimensions (p. 1022). First, use value is prioritized over exchange value: housing is for living in, not for making profit, which the authors call a degree of 'decommodification'. Second, self-governance: residents themselves decide the collective-choice rules (who decides and how) and the operational rules (daily management). Third, solidarity and active participation grow through living together. Maintaining these three is a continuous struggle, because members, for example of limited-equity cooperatives, face a constant temptation of individual financial gain.",
"The opposite of a commons is 'enclosure', the loss of commons leading to dispossession and market dependency (p. 1023). In housing, enclosure has three forms. Commodification happens when residents sell their homes individually for profit, as when a cooperative is dissolved. Marginalization happens when a self-selecting commons shuts out outsiders through exclusive use, membership or access. Cooptation happens when the state undermines self-governance, for example by slowly absorbing cooperatives into statist logics. In each case value ends up with a single party while the people who live in, rely on or work for the commons lose out. The authors add that Ostrom's principles, designed for natural resources threatened by overuse, risk depoliticizing housing if protection is seen only in material terms."]},
{h:"The property debate and the analytical framework",p:[
"Theorists disagree on how commons should be protected, and the question of property sits at the heart of that disagreement (p. 1023). Dardot and Laval argue that commons cannot be objects of property at all, because property implies exclusion. Harvey, by contrast, considers 'some degree of closure' necessary to protect commons in a commodified world. De Angelis and Stavrides take a middle ground: commons survive through porosity (open, permeable boundaries) and proliferation (spreading beyond their own boundaries). Savini adds that fragile cooperatives rely on 'nesting and federating', creating networks of commons so that single projects do not become, in Vidal's phrase, 'islands in commodified waters' (p. 1023).",
"Rather than deciding in theory whether commons and property are compatible, the authors propose to look at the concrete strategies people actually use to protect housing as a collectively managed, decommodified good (p. 1023). Their framework follows de Angelis' three-part view of a commons. The common good is the pooled resource, here understood through a relational concept of property: property as a bundle of claims, rights and obligations, shaped by legal frameworks. Such property relations can shield a commons, but they can also become a tool of enclosure when they take the 'ownership model' that vests power in one entity. The community consists of the commoners who make political claims about housing use. The practices are commoning itself: collective labor, decision-making, maintenance and cohabitation (pp. 1023–1024)."]},
{h:"Method and the São Paulo context",p:[
"The research is qualitative and longitudinal (p. 1024). Between 2016 and 2021 the team did participatory action research, which began because one team member worked as an architect on Dandara's retrofit plans. This follows the Brazilian model of 'extensão', in which public universities collaborate with societal actors such as social movements. The team attended assemblies, subcommittee meetings and site visits, and conducted 19 interviews: ten residents, three movement leaders, three policymakers, two social workers and an architect. Policy documents, laws and federal housing statistics complemented this material. The two cases were chosen precisely because they succeeded, so that the protective mechanisms that let them persist could be studied.",
"São Paulo is marked by strong socio-spatial inequality and acute shortages (p. 1025). Public programmes long favored homeownership for formal-sector workers, so low-income groups built for themselves on the periphery. The democratization struggles of the 1980s produced the 1988 Constitution and the 2001 City Statute, which enshrined the right to housing and the 'social function of property'. Meanwhile, the city center emptied out: a 2022 census counted roughly 590,000 vacant properties against about 29,500 homeless families. Many low-income inner-city residents rent overcrowded tenements (cortiços), while the center itself has excellent infrastructure (pp. 1025–1026).",
"The movement studied is the ULC (Unification of Tenement Struggles), founded in 1991 and part of the umbrella UMM (Union of Housing Movements), founded in 1987 (p. 1026). The UMM is organized in neighborhood 'origin groups' federated up to state, federal and international networks. Compared to some other movements, UMM and ULC are less confrontational and legitimize occupations through citizenship and social rights. Because prolonged occupations are precarious (a 2018 fire in an occupied building killed four people), the ULC has mostly shifted toward shorter, political occupations, although these can still last years (pp. 1026–1027)."]},
{h:"The legal contradiction behind occupations",p:[
"Occupations exploit a contradiction in Brazilian law between two principles: the social function of property and the right to private property (p. 1027). The social function principle says that private property carries an obligation to be used in ways that benefit the collective; it restricts owners' rights for the social good and rests on a relational view of property associated with the legal scholar Léon Duguit. Because municipal governments are often entangled with local 'growth machines' (coalitions pushing real estate development), they implement this principle poorly, so movements take matters into their own hands.",
"Movements therefore deliberately target vacant buildings: property that fails its social function. The UMM, for instance, chooses buildings whose owners have not paid taxes for long periods, or public buildings the state has neglected (p. 1027). Yet occupations remain disruptive, sometimes violent, and they infringe on a strongly valued principle. The authors add a point that becomes important later: many residents themselves aspire to homeownership, which in Brazil is seen as a precondition for full citizenship and a symbol of stability. Repression has also hardened; former president Bolsonaro called occupiers 'terrorists' (pp. 1027–1028)."]},
{h:"The two cases: from occupation to condominium",p:[
"Dandara is a retrofit of a former state court in the Sé district, occupied in 2009 and renovated from 2014 to 2018; Marisa Letícia is a newly built complex on a former warehouse site in Brás, finished in 2019 (p. 1028). As of 2023 they were the only occupations in central São Paulo completed as permanent housing through self-management. The authors follow them through four stages.",
"Appropriation. Occupiers force entry into vacant public buildings and immediately start caring for them: changing locks, cleaning, removing waste, setting rules of access (p. 1029). This care is also strategic, because any sign of degradation feeds hostile politicians. Residents insist that they occupy, not 'invade'; as one resident put it, 'we occupy a place where no one has it' (p. 1029). Legitimacy, following de Angelis, is a critical resource against eviction.",
"Regularization. Movements then negotiate with the state for funding and formal status, using 'autogestão' (collective self-management) (pp. 1029–1030). Because movements lack money, they rely on the state. A federal ordinance (SPU 179) opened Dandara to negotiation, and Marisa Letícia entered the MCMV-Entidades programme, which for the first time gave movements direct access to federal housing funds. The federal cap of BRL 76,000 per unit was insufficient in the expensive center, so state and municipal top-ups were needed. The authors call this 'structural coupling': commons align with state systems to stabilize their claims (p. 1030).",
"Renovation and moving in. Residents contributed labor ('mutirão') and joined committees for purchasing, security or finance (pp. 1030–1031). Units were allocated through an effort-based points system rewarding participation in meetings, occupations and marches, which prevented free-riding. One resident recalled: 'We built our social fabric over two years during the construction phase, getting to know one another so that by the time we moved in, we were no longer strangers' (p. 1031). Before move-in, residents guarded the sites day and night; afterwards, gates and doormen controlled access, and social workers taught courses on condominium life (p. 1032). The property outcomes differed: Marisa Letícia became an individual condominium with private titles and mortgages, while Dandara received an unusual use-right concession. In both, selling or subletting is forbidden by the movements, but they cannot enforce it. As the authors put it, 'Regularization, therefore, transforms collective use claims to buildings into state-sanctioned private legal claims' (p. 1033)."]},
{h:"Five patterns of protection at three levels",p:[
"The core contribution is a typology of five patterns operating at three levels (pp. 1033–1034). Together they help maintain the three principles of a housing commons: use value over exchange value, self-governance and solidarity. At the level of the housing development itself, the patterns are regularization and restoration (p. 1034). Regularization is legal recognition, the main defense against eviction. But because cooperative or collective property regimes are uncommon in Brazil, regularization usually means condominium property with individual titles; out of necessity it may 'reproduce a hegemonic property regime'. Restoration is material: making the building habitable, livable and safe, including night vigils and physical barriers. Protection is thus both legal and physical.",
"At the level between the development and the movement, the patterns are integration and ideation (pp. 1034–1035). Integration embeds residents in the wider housing struggle; the entidades (residents' organizations) are the entry point, and the points system encourages contribution, although it can clash with homeownership aspirations. Integrating new members also counters marginalization. Ideation, a term from Varvarousis, describes how commons ideas formed in one place later materialize elsewhere; the authors point to exchanges between Uruguayan housing cooperatives and Brazilian movements in the 1980s, and argue that technical know-how stays 'stored' in movements until a favorable political moment arrives.",
"At the interface between movements and the state, the pattern is federation (p. 1035). Commoning is layered: floor committees, resident committees, entidades, movements and finally federations that lobby for political change. This echoes de Angelis' 'common ecologies'. Federation made it possible to insert autogestão into state policy, amending the market-led MCMV programme so that both projects could be built at all."]},
{h:"Why protection is only partial",p:[
"The authors stress that these protections are 'inherently partial' (p. 1035). Regularization and renovation convert public property, claimed collectively, into individual private titles. Private ownership plus individual mortgages turns households into 'indebted subjects' who could face foreclosure, and the conversion of collective political claims into personal debt relationships erodes collective action. Renovation also makes residents less dependent on the movement for tenure and habitability. So while regularization protects against eviction, it opens new avenues of enclosure; late in fieldwork, a unit appeared on a subletting platform (pp. 1035–1036).",
"Theoretically, this means institutionalist approaches are 'only of partial use' because they miss the political dimension (p. 1036). The authors propose a relational perspective, patterns of protection, that follows how political claims and property regimes evolve together. Commoning appears as a pragmatic practice that takes different organizational forms over time and contains contradictions that should not be dismissed just because they do not fit an ideal type. Against earlier work stressing Brazilian public law (the City Statute), they highlight the mediating role of private law, concluding that 'Social rights help to create and reclaim housing as commons, but may not be enough to sustain them' (p. 1036)."]},
{h:"Conclusions and what the authors want",p:[
"The conclusion restates two contributions (pp. 1036–1037). First, the article combines institutionalist and neo-Marxian understandings of the commons, by linking residents' values, property claims and patterns of protection. Second, it underlines the progressive potential of private law, not only public legislation. The lack of collective property arrangements in Brazil means legal reform is needed to create frameworks that support housing commons and guard against marketization.",
"The authors admit limits and open questions. The cases are two successes, chosen to see what makes survival possible. They call for longitudinal work on how market logics infiltrate such buildings, in particular how digital subletting platforms mediate commercialization and affect a community's collective ethos. And they ask for further theorizing and mapping of an 'archipelago of the commons': linked commons that support each other rather than standing alone (p. 1037)."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The article rests on commons theory, explicitly bridging Ostrom-style institutionalism (rules, collective-choice arrangements) and neo-Marxian thinking (commons against capital, enclosure). You can link the institutional side to the week 4 neo-institutionalism readings: property regimes and state programmes enable or constrain action, and 'structural coupling' is close to the idea that institutions can be transformative (Dembski and Salet). The Marxian side connects to Harvey and to Madden and Marcuse's critique of commodified housing.",
"On the course dimensions: agency is prominent (movements, residents, mutirão), but always within legal and financial structures, so the article sits in the middle of structure and agency. It is about transformation (decommodifying buildings) yet shows how transformation slides back into reproduction of private ownership. Protection is partly deliberate (points systems, federations) and partly emergent (ideation). Knowledge is situated: the patterns come from São Paulo's specific legal contradiction. Normatively, the authors are committed to use value, self-management and solidarity. A useful contrast is Pruijt: both study occupations and cooptation, but Pruijt asks whether movements survive integration, while Bossuyt and D'Ottaviano ask whether the housing itself stays common after integration."]}
]},

pruijt:{ext:[
{h:"What the article asks and why",p:[
"Pruijt begins with a simple condition: a housing shortage combined with abundant empty property is the basic precondition for squatting, but like any social movement, squatting operates within an 'opportunity structure' that determines whether and how it can develop and how effective it is (p. 1). He compares Amsterdam and New York City, two cities that both had shortages and many vacant buildings, but very different urban regimes. Squatting was extensive in Amsterdam and much more limited in New York, yet there was enough in New York to draw conclusions.",
"The aim is to see whether opportunities for effective squatting depend on the urban regime: whether a city relies on market forces or on state intervention and redistribution (p. 2). Pruijt defines effective squatting ambitiously: viable models exist for squatting every type of empty building (tenements awaiting demolition, speculative luxury housing, offices, warehouses), and squatters contribute to a lively city that is friendly to low-income people. By 'viable model' he means a sustainable way to repair, heat and maintain buildings and to deal with owners, authorities and neighbors.",
"The title question challenges a dominant view in the literature: that urban movements follow a life cycle ending in institutionalization and loss of identity. Pruijt's answer, built up step by step, is that this end is not inevitable, and that the type of movement matters as much as the regime. Note that page numbers here refer to the author's preprint, not the journal pagination."]},
{h:"Repression, institutionalization and cooptation",p:[
"Following Castells, Pruijt notes that states respond to radical urban movements with both repression and integration (p. 2). Repression shows in laws closing legal loopholes for squatters, but in the UK, the Netherlands and Germany these measures never fully stamped squatting out. Often the two were combined: Berlin authorities eliminated squatting between 1981 and 1984 through a mix of repression and legalization, and Platt observes that in the UK organized squatting declined more because of concessions than because of repression (p. 3). Integration comes in two forms, which he carefully separates.",
"The first is institutionalization: a movement is channeled into a stable pattern based on formal rules and laws, with defined expectations and sanctions (pp. 2–3). For squatters it usually takes the form of legalization, as with the 'amnesty' for some 5,000 London squatters in 1977. Authorities may prefer legalization because squatting enjoys some legitimacy and because eviction can be too costly; squatters are drawn to it because squatting is also an economic activity (meeting housing needs), and repression pushes them to negotiate (p. 3). Castells held that institutionalization, with its identity loss, is inevitable, and protest-wave theory places it near the end of a cycle (p. 4). But other authors show that movements can be partly integrated while a radical wing keeps disrupting. Pruijt therefore distinguishes two types: 'Terminal institutionalization implies that, in the repertoire of action, convention replaces disruption; in flexible institutionalization, conventional tactics complement disruptive ones' (p. 4).",
"The second form is cooptation. Building on Selznick, Pruijt defines it as a process in which the co-opting organization 'embraces certain ideas from the movement, while redefining problems in such a way that solving them does not threaten its own stability' (p. 4). The co-opting body gives activists a role within its own framework. The UK's 'licensed squatting' is the classic example: squatters' groups became offices managing short-life public housing and had to stop organizing squatting, which split the movement (pp. 4–5). Pruijt takes a neutral stance: the costs and benefits of cooptation must be judged case by case."]},
{h:"Post-Fordism and the privatization of poverty",p:[
"Why would the regime matter? Pruijt draws on post-Fordist theory (p. 5). As welfare costs grow, governments cut spending, criticize bureaucratic redistribution as inefficient and strengthen the ethos of competition. Yet they still aim to reduce poverty, so they face conflicting demands. The logical response is to support self-help: the 'privatization of poverty'. Neighborhood groups are co-opted to plug holes left by the retreating state; in the US they took on management roles, became financially dependent and bureaucratized, and sometimes came into conflict with their own tenants (pp. 5–6).",
"So the hypothesis is that a market-oriented regime creates stronger pull factors toward cooptation (the state needs service providers) and also stronger push factors in the form of repression, because cities competing for visitors and business want a clean, safe image (p. 6). Pruijt summarizes three ways integration can complement repression: flexible institutionalization, which keeps squatting effective; terminal institutionalization, which ends the movement; and cooptation, in which oppositional groups become service providers, more likely under a market-oriented regime (p. 6)."]},
{h:"Evidence and cases",p:[
"The case choice follows a most-different logic on regime with similar preconditions (pp. 6–7). New York in 1983 had thousands of people on the streets while whole buildings stood empty; Amsterdam had about 50,000 people on the social housing waiting list. Using Esping-Andersen, the US is a 'liberal' welfare regime that encourages the market, while the Netherlands has 'social democratic' traits. Amsterdam housed around 9,000 squatters in 1981 with a rich infrastructure of advice desks, media, bars, workshops and even a bureau investigating speculators; New York's movement peaked at 500 squatters in 20 buildings (p. 7).",
"The data differ per city (footnote, pp. 6–7). For New York, Pruijt used 278 news articles, web documents by squatters, interviews with activists in 2000 and 2001, conversations at organizations such as UHAB and ACORN, and community board archives. For Amsterdam he drew on his own interviews and archive work from 1980 to 1984, squatters' periodicals, and an extensive existing literature."]},
{h:"Amsterdam: flexible institutionalization without cooptation",p:[
"The Amsterdam municipality bought about two hundred squatted buildings, legalizing them, and handed most to housing associations that signed leases with individual squatters (p. 7). Squatters took part in construction planning and city planning, for example in the eastern docklands, and politicians mediated in many conflicts. Outside legalization, too, contacts were dense: the city repaired some squats slated for demolition to keep them habitable, and subsidized neighborhood centers and church groups represented squatters' views. Soja labels the policy 'slightly repressive tolerance' (pp. 7–8).",
"Yet, contrary to much of the movement literature, there was no loss of willingness to disrupt (p. 8). Squatters kept defending buildings the city would not buy, raised bridges to defend warehouses as late as 2000, rioted at the 1980 coronation, and joined protests against the new town hall and the Olympic bid. Disruptive and conventional tactics existed side by side, and legalization in the early 1980s was not an end-of-cycle event, since squatting continued two decades later. So Amsterdam shows that flexible institutionalization is possible. And contrary to post-Fordist expectations, there was hardly any cooptation: squatters' groups did not become providers of services the state neglected, and the third-sector housing associations did not originate in the movement (p. 8)."]},
{h:"New York: cooptation of the housing movement",p:[
"In New York the pattern fits the theory (pp. 8–11). A 1970 squatting wave died out quickly: the New York Times reported 13 squatting articles in 1970, three in 1971 and 1972, then none until 1980. Repression played a role, but so did a shift from confrontation to cooperation. Organizers and supporters such as UHAB moved into city programmes like Tenant Interim Lease (TIL), in which tenants managed tax-foreclosed buildings with the prospect of cooperative ownership. TIL illustrates the ambiguities of the privatization of poverty: it received less than half of normal subsidies, and the struggle to keep buildings afloat absorbed activists' energy, even though it served real needs (p. 9).",
"Official 'homesteading' programmes tried to 'tame' squatting: groups renovated abandoned city buildings with 'sweat equity' in return for eventual ownership (p. 9). Renovation took six to ten years, sometimes thirteen, and homesteaders gradually came to see themselves as homeowners opposed to squatters, splitting the anti-displacement movement (p. 10). Organizations that had used squatting as a tactic transformed too: ACORN received 58 buildings only after promising to abandon squatting, and Banana Kelly evolved from squatting to renovation to becoming an award-winning service provider before collapsing in scandal and poor maintenance (pp. 10–11). Pruijt concludes that squatting was marginalized as organizers turned to the city and organizations became service providers, consistent with post-Fordist theory, but adds that this is not inevitable (p. 11)."]},
{h:"Two types of squatting",p:[
"The puzzle is that after 1983 a genuine squatters' movement emerged on the Lower East Side that was neither co-opted nor repressed out of existence; only in 2002, when no squattable buildings were left, were eleven squats legalized through UHAB mediation, which Pruijt classifies as terminal institutionalization (p. 11). City officials consistently refused to negotiate with squatters. The explanation cannot be that the city lost interest in cooptation, because in 1992 it offered a Bronx group legalization of three buildings if all other squatters left and it became a service provider (pp. 11–12). The explanation must lie in the movement itself.",
"Pruijt therefore distinguishes a housing movement, for which squatting is one possible means to house poor people, from a squatters' movement proper, in which 'squatting itself is means and primary goal at the same time' (p. 12). A squatters' movement is a bottom-up, network-structured community with informal leadership, a do-it-yourself ethic, an ideology of self-determination, and participants often rich in social and cultural capital (p. 12). Motives such as autonomy or counterculture are not enough to explain the difference (pp. 12–13). The crucial point is about goals: cooptation works when officials can claim to share the movement's ultimate goal (housing the poor) and offer support if activists switch to state-approved means. When squatting is itself the goal, officials cannot credibly claim to share it (p. 13). The New York movement also had a partly external origin: European squatters brought ideas and practices, showing that a pre-existing oppositional identity can partly override the local opportunity structure (pp. 13–14)."]},
{h:"Property protection, building condition and gentrification",p:[
"Once a squatters' movement exists, it still faces different opportunity structures. Property protection is stricter in the US: squatting is trespassing (p. 14). In the Netherlands a 1971 Supreme Court ruling extended the 'house right' to squatters, which made quick evictions impossible and enabled long-lasting squats; later laws eroded this, and the erosion after 1986 coincided with the movement's decline (pp. 14–15). New York squatters coped through concealment, which isolated them (one squatter did not even know that what he did was called squatting), and by targeting only city-owned buildings, which left speculators untouched (pp. 15–16).",
"Technical conditions were far worse in New York, because of a US cycle of disinvestment: owners milked buildings, banks redlined, arson and abandonment followed, and the city took over for tax arrears (p. 16). Amsterdam never saw comparable disinvestment, since state-led urban renewal intervened early. New York manuals prepared squatters for holes in roofs and missing stairs; Amsterdam manuals hardly mentioned construction (pp. 16–17).",
"Does squatting cause gentrification, which would be self-defeating? Pruijt finds overlaps (pioneering newcomers rich in cultural capital) but notes that squatting does not create luxury housing, and that squatters often sided with residents against developers (pp. 17–18). Views differ on whether they slowed gentrification on the Lower East Side; one squatter's verdict was 'you can only slow it down' (p. 18)."]},
{h:"Squatters versus the low-income housing industry",p:[
"The one area where a market-oriented regime seems to give squatters more room is low-income housing rehabilitation (p. 19). In New York, squatters were repeatedly locked in conflict with non-profit groups claiming the same buildings for affordable housing; six of nine documented Lower East Side conflicts involved such competing claims (pp. 19–20). In Amsterdam such conflicts were rare: squatters in old working-class neighborhoods usually left voluntarily when demolition and new social housing were scheduled (p. 20).",
"Pruijt explains this through a broad Amsterdam consensus based on five features (pp. 21–22): affordability ('building for the neighborhood', subsidized rents, a right to rehousing); a clear demarcation between for-profit and non-profit development; reliable and transparent plans; democratic planning with future tenants; and recognition of squatters' own housing needs. In New York, 'low-income' rents were often out of reach, non-profits worked in partnerships with profit-oriented firms (squatters called them 'poverty pimps'), and plans often failed to materialize. This gray zone made the 'poverty industry' vulnerable to squatter criticism, giving radicals a watchdog role; but it also kept conflict confined to a local arena, shielding politicians, banks and big real estate (p. 22)."]},
{h:"Conclusions and what the author wants",p:[
"Pruijt's main conclusion is that, 'perhaps paradoxically, a market-oriented regime with little redistributive and regulative commitment to low-income housing offers less opportunities for squatting than a regime that is much more based on redistribution and planning' (pp. 22–23). The comparison confirms that market-oriented regimes encourage cooptation of movement groups as service providers, which means abandoning squatting. A squatters' movement proper is immune to cooptation because squatting is both means and end; that such a movement arose in New York against the structural trend shows that diverse causal chains can lead to similar outcomes (p. 23).",
"New York was less favorable in property protection, access to officials and building condition, but offered leeway in the disorganized low-income renovation sector (p. 23). Pruijt admits the obstacles for US squatters are formidable, and notes that Amsterdam's movement took thirteen years to develop, fed by a 'lost generation' of young people with time, welfare payments and student grants (p. 23). He leaves open whether US movements could escape the low-income housing arena and push for serious redistributive investment. His final message is that post-Fordist theory sees only one scenario (being co-opted by the retreating state), whereas third-sector disorganization opens opportunities for movements that keep an oppositional identity (p. 24)."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not Pruijt's claims. The article belongs to urban social movement theory and uses political opportunity structure, which is a structural idea: the regime shapes what movements can do. But Pruijt's key twist is agency and identity: a squatters' movement can partly override its opportunity structure. So he sits between structure and agency, closer to structure than activists might like but explicitly rejecting pure structural determinism.",
"On reproduction versus transformation, the article shows how states absorb movements (cooptation reproduces the regime) but also how flexible institutionalization keeps transformative pressure alive. His knowledge claims are situated and comparative: two cities, with regime types borrowed from Esping-Andersen. Normatively he values effective squatting and a low-income-friendly city. Compare Bossuyt and D'Ottaviano: they see structural coupling with the state as a necessary protection, while Pruijt treats integration as a risk that only some movements survive. Raco and Imrie add a Foucauldian reading: what Pruijt calls cooptation into service provision looks, through their lens, like governing through the self-governing capacities of communities."]}
]},

raco:{ext:[
{h:"What the article asks and why",p:[
"Around 2000, citizenship was a central theme in British urban policy. Government documents called for 'a new brand of involved and responsible citizenship', and Tony Blair summarized the ethos as 'It is something for something. A society where we play by the rules. You only take out what you put in. That's the bargain' (p. 2187). Raco and Imrie want to understand this 'rights and responsibilities' agenda: citizens receive rights, but only in exchange for duties.",
"The idea of the 'active citizen' was not new; Thatcherism also encouraged voluntary and community action while the state shrank (p. 2188). What is new, the authors argue, is that active citizenship moves to the centre of the relationship between state and civil society. Citizens are no longer defined mainly as consumers or voters but as democratic agents who empower themselves by challenging institutions that shape their lives.",
"The authors use Michel Foucault's concept of 'governmentality' to argue that this shift is part of a wider transformation in how government thinks and works (p. 2188). Following Nikolas Rose, they call it 'advanced liberalism': strategies that treat citizens, individually and collectively, as potentially 'active' in their own government, and that govern by using the self-governing properties of the governed. The argument has three parts: a justification of the Foucauldian framework; an empirical analysis of the Single Regeneration Budget (SRB), organized around government through community and the shaping of subjectivity and expertise; and conclusions on why this framework matters."]},
{h:"Why a Foucauldian lens: governmentality explained",p:[
"The authors start from claims by Beck, Giddens and others that globalization and the end of Keynesian welfare systems have shifted risk from collective, state-led provision to 'individualisation', where people must take more responsibility for their own welfare (p. 2188). Class politics dissolves into identity politics, and people reject the paternalistic postwar state (p. 2189). Government then takes on an enabling role: helping citizens become 'more responsible' and more capable.",
"For Foucault, such changes point to new 'mentalities of government' concerned with shaping, channeling and guiding 'the conduct of others' (p. 2189). The object of government is the population, managed as a resource to be fostered and optimized. Crucially, power is exercised through many agencies, not only the state; the state is not a unified actor but one institution among many. This differs from Marxist, pluralist or elitist theories that treat the state as a single actor, though the authors note parallels with neo-Gramscian and regulationist views (p. 2189).",
"Governmentality has three linked elements (p. 2190). Political rationalities are ways of thinking about which problems authorities should address, underpinned by moral justifications and a picture of who is to be governed. Programmes are the purposive attempts to reorganize institutions and conduct, visible in white papers and inquiries; government is a 'problematising' activity that keeps trying to fix its own failures. Technologies of government are the practical tools that make programmes work: legal, architectural, financial and administrative devices, from auditing and benchmarking to devolved budgets, which create 'calculable spaces' where conduct can be measured against authoritative criteria."]},
{h:"Advanced liberalism: governing through freedom",p:[
"Advanced liberalism, in Dean's summary, includes marketized welfare, audit and consumerism, fragmented collective welfare, a reinvented notion of 'community', and strong discipline for deviant performance (p. 2190, note 2). Its core is the demise of social collectivities and the spread of self-management: government through the governed. Rose describes 'rationalities and techniques that seek to govern without governing society, to govern through regulated choices made by discrete and autonomous actors in the context of their particular commitments to families and communities' (p. 2191).",
"The paradox is that the free, self-determining individual is at the centre, yet this freedom must be shaped, guided and moulded through authority (p. 2191). Dean's 'new prudentialism' ties risk management to self-care; Cruikshank calls empowerment a 'technology of citizenship' that transforms powerless people into active citizens. The New Deal for the unemployed, with counseling for self-esteem and training, is an example. Less state intervention thus does not mean less government; it means new ways of acting on people so that they govern themselves in line with government aims (p. 2191)."]},
{h:"The SRB as a window on urban policy",p:[
"The SRB, established in April 1994, was the most important English urban policy initiative since the mid-1990s (p. 2191). It replaced a patchwork of earlier schemes with a single funding source, distributed competitively to locally defined public-private partnerships that develop 'bottom-up strategies'. Some welcomed it as a break toward community focus; others saw 'managerial localism', reduced resources distributed through competition with strong managerial controls (pp. 2191–2192).",
"The authors treat the SRB as a heuristic vehicle for analyzing the 'governmentalisation' of UK urban policy (p. 2192). Their method is a critical reading of official policy documents and bidding guidance, secondary evidence from SRB programmes, and related policy areas. They keep in mind Foucault's warning that the dilemma of modern government is that 'if one governs too much one finishes by not being able to govern at all' (p. 2192). Their claim is that discourses of empowerment, social inclusion and active citizenship represent new forms of governmentalisation rather than greater autonomy for the people targeted by policy."]},
{h:"Government through community",p:[
"Policy documents of the time present communities as both subjects and objects of policy (pp. 2192–2193). The Commission for Social Justice wanted to build local capacities so people could shape their own futures; ministers spoke of giving communities 'responsibility', 'skills and confidence' and 'power'. SRB bidders had to 'involve the community fully at all stages', on the assumption that place-based communities hold unique local knowledge without which policy fails (p. 2193).",
"The authors read this as a rescaling of government from society and the nation-state to community and locality (p. 2194). The local is given an ontological status: it is treated as the natural place where effective government happens. Ten percent of SRB funding had to go to community 'capacity building', and bids had to make capacity building a key objective (p. 2194). So community involvement was not optional but a funding requirement.",
"Behind the moral language of participatory democracy lies what the authors call 'directed self-government' (p. 2194). The SRB requires the marginalized and poor to act so that government becomes effective. Following Rose, they speak of 'communities of obligation': communities get more rights to define agendas but must accept wider responsibilities for implementing them. Community enterprises and credit unions are promoted precisely where services are 'unattractive to the private sector', so the SRB rests on discourses of public and private abandonment and echoes Thatcherite ideas of self-reliance (p. 2195).",
"Bids also had to fit national frameworks and 'add value' to other programmes, which places responsibility for policy coherence on recipients rather than policymakers (p. 2195). The result is an 'empowerment' that brings no quantitative increase in power for communities but 'a qualitative transformation of forms of subjectivity to make government work' (p. 2195). Conditionality dominates: communities must accept centrally defined parameters and act 'responsibly', which limits the emancipatory potential while the state's capacity to shape conduct grows (p. 2196)."]},
{h:"Technologies of performance and the reshaping of expertise",p:[
"The second dimension concerns technologies of government (pp. 2196–2197). Responsibility is presented positively, as social connectedness ('Social responsibility is for all', in Blair's words), but it functions as a discourse of control. The key technique is spreading financial calculation and budgetary obligations into areas previously run by professional or bureaucratic norms. Bidders must address codified expert questions about quantified impacts, risk, financial management and monitoring. The authors summarize: 'Local subjects are given a little extra freedom in return for closer monitoring, scrutiny, and subjection to new discourses and the disciplines of external expertise' (p. 2197).",
"Evidence from Foley et al.'s evaluations shows surveillance replacing trust (pp. 2197–2198). SRB managers submit quantitative progress reports every three months against targets set in advance; as Foley et al. put it, 'An inspection mentality can start to dominate' (p. 2198). Accountability is vertical, toward funders, not horizontal toward communities, and monitoring data were used to check targets rather than to improve policy. Underperforming schemes risked intensive review or loss of funding, and project funding depended on rigorous appraisal (pp. 2198–2199).",
"Parallel disciplines apply to local authorities through 'Best Value', which presents itself as non-ideological empowerment of residents as consumers but works as disciplinary power from the centre (p. 2199). 'Best Practice' guidance adds peer review: bidders adjust to the scrutiny of other bidders, another form of government at a distance (pp. 2199–2200). Finally, expertise itself is reshaped (pp. 2200–2201). Community knowledge is formally privileged, yet communities are seen as lacking technical skill, so representatives are trained by professionals to implement government objectives and monitoring. Communities must build their own statistical baselines and milestones. Even professional experts become subordinated to performance mechanisms (p. 2201)."]},
{h:"Conclusions and what the authors want",p:[
"The authors conclude that a Foucauldian approach links the mentalities and actions of the population with the objectives and techniques of advanced liberal government (p. 2201). Urban policy illustrates the paradox that, in return for a little more freedom, subjects come under greater monitoring and surveillance. Rationalities of government and state sovereignty are not pregiven but constructed through techniques of government (p. 2201).",
"The SRB, in their summary, identifies and institutionalizes communities of action, gives them a minimum of competitively allocated resources, encourages local policies within rigid managerial frameworks, and reshapes expertise around cost minimization and the shifting of responsibility onto trained local representatives (p. 2202). Policy documents say little about local electoral accountability. They grant that policymakers may genuinely believe in empowerment, but argue that the frameworks are as much about control as about community mobilization.",
"The authors do not end in pure pessimism. If the art of government is politically constructed, it can also be reconstructed on different principles (p. 2202). Reflexive government may open space for a 'subpolitics' of identity and difference from which advanced liberalism can be challenged, and the balance of rights and responsibilities will be crucial to any future politics. Note that their evidence is mainly documentary and secondary; they do not present their own fieldwork on how communities experienced or resisted the SRB."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The theory is Foucauldian governmentality, the course's main example of a post-structuralist view of power: power is not held by a single sovereign state but works through discourses, techniques and the formation of subjects. This contrasts with Marxist readings (Harvey, Foglesong), where the state serves capital, and with rational choice or public administration models (Rydin's governmental models), where the state is a unitary actor pursuing goals.",
"On the course dimensions: the analysis stresses structure in a special sense; agency is real but produced and channeled by government. It focuses on reproduction: participation and empowerment reproduce central control rather than transforming it, though the conclusion leaves room for resistance. Governing appears deliberate at the level of programmes but diffuse in its effects. The knowledge claim is critical and situated in New Labour Britain. Normatively, the authors favour genuine local accountability. Useful contrasts: communicative or collaborative planning (Healey is quoted at the start) sees participation as empowering, whereas Raco and Imrie see it as a technology of government. Pruijt's cooptation of movements into service providers and Gurran and Ruming's 'regimes of truth' are close cousins of this argument."]}
]},

gurran:{ext:[
{h:"What the article asks and why",p:[
"Gurran and Ruming start from the contradictory position of planning under neoliberal reform (p. 1). Planning systems have proved remarkably resilient to deregulation and remain a key form of state intervention, and in some countries (the UK, the Netherlands, many US cities) planning tools even help secure affordable homes within market developments. Yet over the past decade, amid anxiety about housing production and affordability, the legitimacy of planning has been questioned: critics point to slow and complex processes, restrictive controls, and residents using planning rules to block development (pp. 1–2).",
"Planning is thus expected to support economic growth by facilitating big development, while also protecting the property interests of established suburbs; wider public goals such as environmental protection or better housing for the poor get squeezed between these interests (p. 2). The article examines these tensions in Australia, one of the world's most expensive housing markets, where prices rose fast after mortgage deregulation and home ownership fell from about 71% in the mid 1980s to 68% in 2012 (p. 2).",
"The authors' question is how particular interests shape urban policy debate and reform. Their case is the planning system review in New South Wales (NSW), Australia's most populous state, between 2011 and 2014 (pp. 2–3). They compare written submissions from industry, residents and professionals with the government's responses and find that the government mostly echoed industry narratives. In that setting, housing development is framed as the engine of economic growth and the planning system as the constraint holding it back, while community worries about affordability and new development are reframed to fit the growth agenda (p. 1)."]},
{h:"Discourse as power: the method's theory",p:[
"The approach is discourse analysis, which the authors describe as broadly Foucauldian (p. 3). Language is not just a medium for communication but central in 'producing or constructing reality', including what we know and the meanings we give to the world (quoting Hastings). Following Jacobs, politics is seen as an arena where groups try to establish a particular narrative of events to pursue their objectives.",
"The key concept is the 'regime of truth' (Foucault). The power of a group lies in its ability to promote and sustain its version of reality as the 'objective truth' through speech, text and images (p. 3). Once established, such discourses become fairly static representations that define which formulations of problems and solutions are acceptable. Discourse is therefore not the product of neutral, rational deliberation but a messy site of power struggles, where dominant regimes of truth can also be challenged. The authors want to show how one set of narratives about planning's problems, objectives and solutions became a regime of truth reflected in the government's draft legislation (p. 3)."]},
{h:"Neoliberalism, housing and planning",p:[
"The authors place their case in a broader literature (pp. 3–4). Neoliberalism, emerging in the 1970s and 1980s, opposes state intervention in markets and challenges the legitimacy of planning regulation of private developers. Its effects on housing vary by context, but typically include more support for home ownership and private investment, rent subsidies instead of public housing, and quasi-market management of social housing. In the UK, Thatcherism shifted social housing to tenants and housing associations, but councils could still use 'section 106' agreements to secure land for social housing; in the US, inclusionary zoning emerged alongside tax credits.",
"These approaches have limits (p. 4). Home ownership policies for low-income groups were questioned after the global financial crisis; rent subsidies expose vulnerable groups to insecurity; and inclusionary schemes depend on buoyant markets. Still, planning is an important mechanism for making sure affordable housing is well located near jobs and services. In Australia, however, attempts to require affordable housing through planning have been resisted by industry and governments fearing higher prices and less development, and by resident groups; the dominant rhetoric stresses the negative effects of planning on the housing market (p. 4)."]},
{h:"The Australian context",p:[
"Both major parties have applied neoliberal reforms since the 1980s (p. 4). Public housing investment was replaced by subsidies for private renters: social housing approvals in NSW fell from around 15% of dwellings in 1983 to less than two per cent in 2014 (Figure 1). Unusually, most postwar public dwellings were later sold off, so by 1981 only about 120,000 of 840,000 remained public rentals (p. 5). Public infrastructure investment also declined, replaced by user-pays charges and public-private partnerships.",
"Planning is a state and territory responsibility, with local councils handling detailed land allocation and assessment (p. 5). By the 1990s planning had narrowed to a local battle between established homeowners and developers, sharpened by 'urban consolidation' (Australia's term for growth management and densification). Industry criticized consolidation for limiting greenfield land, while homeowners feared density. From the 2000s, states tried to cut 'red' and 'green' tape, and COAG, the council of federal, state and local governments, put planning deregulation on its national competition agenda (pp. 5–6).",
"Housing affordability became the main rationale for these reforms (p. 6). Yet the authors point to a telling finding by the former National Housing Supply Council: Australia's estimated shortage of about 85,000 dwellings in 2008 would have been a modest surplus if social housing production had kept pace with its 1996 level, which would have added about 90,000 dwellings. By 2011/2012 only 3.9% of households lived in social housing. In short, the supply gap could be read as a retreat of public provision rather than a failure of planning, but the national agenda still framed it as a planning problem (pp. 6–7)."]},
{h:"The NSW reform process and the data",p:[
"NSW's Environmental Planning and Assessment Act 1979 was Australia's first to promote wide environmental and social equity goals, but the past decade had seen these protections wound back, including 2005 reforms giving the Minister absolute discretion over major projects (p. 7). After a change of government in 2011, a comprehensive review began: over 100 public meetings, a 96-page Green Paper in July 2012, then a White Paper and draft Planning Bill in April 2013 (p. 7).",
"The Green Paper drew over 1,200 submissions (Table 1, p. 8). The community (individuals, residents' groups and community organizations) accounted for 72%, peak bodies 6%, and the development industry only 1%. The authors selected a set of submissions covering the main interests (Table 2): six industry submissions (including the Property Council of Australia, the Urban Development Institute of Australia, the Urban Taskforce, the builder Australand and two housing industry associations), the Planning Institute, two environmental organizations, the housing advocacy group Shelter NSW, local government associations, and the resident group Friends of Ku-ring-gai Environment (FOKE), located in the then Premier's electorate (p. 9). They close-read, coded themes and used keyword searches in NVivo to compare the submissions with the White Paper and draft Bill (p. 9)."]},
{h:"Framing the problem and the objectives",p:[
"The submissions frame the problem very differently (p. 10). Industry presents a 'regime of truth' in which planning is dysfunctional, overly bureaucratic and designed to block development, causing lost growth, sluggish supply and poor affordability; local residents are cast as part of the problem. Local governments and community groups instead stress distrust: a sense that developers can buy their way through the system, fed by corruption investigations (p. 10).",
"On objectives there is a stark dichotomy. The Property Council states: 'The new planning system needs a purpose. In our view, it should be geared towards delivering an economic dividend for NSW' (p. 10). Local government and residents want existing social and environmental goals, including heritage, retained (pp. 10–11). The government's White Paper echoes industry: 'The main purpose of the planning system is to promote economic growth and development in NSW for the benefit of the entire community, while protecting the environment and enhancing people's way of life' (p. 11). The draft Bill treats housing as an 'economic activity'. The authors' close reading of the grammar is instructive: 'Environmental and social concerns are thus relegated to secondary or ancillary positions through terms such as 'while' and 'having regard to'' (p. 11)."]},
{h:"Six specific reforms",p:[
"The authors then trace six reform areas (pp. 11–14). Spot rezoning: the Green Paper made it easier for developers to obtain rezonings and to appeal refusals; councils and communities opposed this, industry supported it, and the White Paper adopted it in the name of housing supply (p. 11). Community participation: the government claimed to put 'people and their choices at the heart of planning', but the Bill added no consultation rights and curtailed statutory consultation in development assessment; Australand urged communities to move from 'an antidevelopment culture to a progressive development culture' (p. 12).",
"Decision speed and red tape: environmental groups accepted simplification but warned against fast approvals of poor development; the Property Council demanded a 40% cut in red-tape costs without evidence, and the draft Bill barred local plans from 'onerous' controls affecting financial viability (p. 12). Infrastructure: industry, usually anti-intervention, called for infrastructure to be funded from general taxation; this is the one area where the government resisted, keeping developer contributions (p. 13). Affordable housing: Shelter NSW and planners proposed value capture and inclusionary zoning, yet existing affordable housing provisions were wound back (p. 14). The authors conclude that 'housing affordability problems are used as a semantic justification for a wider deregulatory agenda' (p. 14)."]},
{h:"Conclusions and what the authors want",p:[
"The conclusion returns to the international comparison (pp. 14–15). Elsewhere, planning has sometimes softened the transition to market provision of low-cost housing and acted as a lever for affordable homes. In Australia, however, the dominant representations of planning are either a mechanism for 'bulldozing the beautiful' (FOKE's phrase) or a constraint on supply and affordability (pp. 14–15). Both have given developers new ways to contest sustainability and containment policies. The analysis shows that industry discourses were the ones most closely adopted by government, aligned with neoliberal ideology (p. 15).",
"But the authors warn against oversimplification (p. 15). By the end of 2013 the Bill stalled in the state's Legislative Assembly, where the government lacked a majority. The Better Planning Network, a coalition of over 300 resident groups and local councils, mobilized outside the formal consultation, including a widely publicized stunt wrapping the planning minister in 'Hazzard' tape. The latent electoral power of conservative homeowners preserved the status quo. Ironically, housing approvals then reached a 20-year high under the old system, while Sydney's median house price still rose from about 535,000 to 735,000 Australian dollars between 2011 and 2014 (pp. 15–16). More supply did not ease affordability.",
"The authors' main message is that development interests can shape policy by mobilizing regimes of truth that cast planning as a drain on growth and the cause of unaffordability (p. 16). Alternative discourses about genuine participation, environmental impacts or direct support for affordable housing get little traction. They expect the same arguments to return in the next downturn and ask whether planning debates keep distracting from the real pressures on low-income renters and aspiring owners. They acknowledge that their analysis is only a snapshot of a longer process."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The article combines Foucauldian discourse analysis with a political economy critique of neoliberal planning reform. Unlike Raco and Imrie, who use Foucault to study how subjects are formed, Gurran and Ruming use 'regimes of truth' more instrumentally: discourse is a resource that interest groups deploy, which brings them closer to interest-group and political economy explanations. The Property Council's call for an 'economic dividend' connects to Harvey's entrepreneurial city and to Savini and Aalbers on how finance reshapes planning.",
"On the course dimensions: structure matters (neoliberal ideology, national reform agendas), but agency is visible in lobbying and especially in the resident backlash. The reform attempt aimed at transformation (deregulation) but ended in reproduction of the existing system, through contingent, emergent politics rather than deliberate design. The knowledge claim is situated in NSW. Normatively, the authors value planning's social and environmental goals and direct support for affordable housing. A useful contrast is Hayek, whose case against planning resembles the industry discourse the authors criticize, and Taylor's work on rent-seeking in Melbourne, which offers a rational choice lens on similar Australian conflicts."]}
]}
};
