const EXT_7={
p8:{ext:[
{h:"What the article asks and why",p:[
"Cities, and the transport, energy, water and waste infrastructures that keep them running, are widely seen as crucial sites for a more sustainable future. Yet Hodson, Geels and McMeekin start from a puzzle: although there are many plans and a wide range of possible infrastructural innovations, the realisation of sustainable urban infrastructure on the ground is uneven (p. 1). Why do some cities end up with thriving cycling systems and others with electric cars, and why does so much stay the same? The paper does not answer this with a new case study. It is a conceptual paper: it reviews the literature on urban sustainability transitions and builds a preliminary framework, using examples from urban mobility (mostly in the UK) as a reference point.",
"The authors sit at the meeting point of two fields. Socio-technical transitions research studies how whole systems of technology, practices and institutions change over decades, usually at the national level. Urban geography studies space, place and scale. The authors want to 'extend and deepen' the dialogue between the two through three themes (pp. 1–2): moving the focus from national systems to the urban context; taking governance seriously without reducing it to the city level alone; and asking which innovations, in the plural, get selected and combined, a choice shaped by contested ideas of 'sustainability'. The risk, they admit, is that urban transitions then look like almost limitless combinations. Their answer is to focus on contextual forms of 'reconfiguration'.",
"Their core claim, stated in the abstract, is that urban transitions are not about technological or social innovation as such, but about how multiple innovations are experimented with, combined and reconfigured in existing urban contexts, and how that is governed: \"Innovation is in the particular form of reconfiguration rather than individual technologies\" (p. 1). The rest of the paper builds towards this claim in three steps: a review of how transitions research and geography have been combined, an extension of that work through mobility examples, and a preliminary framework for comparing how cities reconfigure."]},
{h:"The starting point: the multi-level perspective and its geographical critics",p:[
"The paper first summarises the Multi-Level Perspective (MLP), the dominant model in transitions research (pp. 2–3). The MLP sees a transition as a multi-decade shift from one system to another and uses three levels. The 'socio-technical landscape' is the broad outside context that usually changes slowly (demographics, ideologies, climate change, macro-economics, the material form of cities) but can change quickly (wars, recessions, oil price shocks). The 'regime' is the set of rules, routines, regulations and standards that structure, but do not determine, what actors do in an existing system. 'Niches' are protected spaces where radical innovations are nurtured. In the classic story, landscape pressure cracks the regime and opens a window for a niche innovation that has built up momentum. Later work showed these mechanisms are far more complex, with several possible pathways.",
"Geographers criticised the MLP because its case studies were mostly national and treated space as given, underplayed or ignored (p. 3). For them, space and scale are actively and relationally produced: niche, regime and landscape are made by actors operating across space and time. This has consequences. A regime may be territorially uneven, and the 'same' niche can look very different in different places because the institutions and networks embedding it differ. A geographical view therefore asks about spatial difference and the co-existence of multiple transition pathways, not just about speed and timing (pp. 3–4). Cities became a key focus: eco-cities, retrofitting existing cities, building new ones, and the governance coalitions (local, national and international) that try to steer all this."]},
{h:"Experimentation, and why a looser view is needed",p:[
"A newer strand of work looks at urban transitions through 'experimentation' (pp. 4–6). Under deep uncertainty, and with governing capacity spread over many actors and scales, it is hard to know what to do and how to do it, so attention shifts to processes in which technologies and social interests are assembled, tried out and learned from in a place. The concept has often been used loosely. Some authors therefore call for structured 'laboratory' spaces with instruments, control and measurement, such as Urban Living Laboratories. Drawing on Bulkeley and Castán Broto, the authors distinguish governance experiments (restructuring the local state to tackle urgent problems, claim resources or expand authority), socio-technical experiments (close to the MLP's niche) and strategic experiments in purposive urban labs. The first two are usually implicit, and these are the paper's focus (pp. 4–5).",
"Experiments are also shaped by wider forces and crises (p. 5). Economic, environmental and social crises trigger experiments with new governance rationalities, and researchers ask whether these reinforce neoliberal restructuring or produce something new. So a city's experimental development is not only an 'endogenous' search for local autonomy but also part of 'exogenous' global urban restructuring. Different visions of sustainability are mobilised in these struggles: a local, circular, self-sufficient city, or the city as a node in wider infrastructure networks, and both can co-exist as contradictory strategies. Since there is no single way to understand experimentation, the authors opt for a looser view: uncertain attempts to reconfigure infrastructures in place, shaped by governance experimentation (pp. 5–6).",
"From this review they draw three issues (p. 6). First, the material relationship between what is being embedded and the pre-existing infrastructure: experiments do not happen in 'hermetically sealed laboratories'. Second, the relationship between existing governance arrangements and the new networks formed around experiments. Third, how multiple conceptions of sustainability (air quality, carbon, congestion, local economy) shape experiments. The method is 'propositional and generative': examples come from existing mobility studies, not new fieldwork, and the claim to general relevance lies in the three propositions, which should also work for energy, waste and water (pp. 6–7)."]},
{h:"Systems meet cities: why a bike is not the innovation",p:[
"Section 4 starts with how transport systems relate to the city as a scale of organisation (pp. 8–9). This 'correspondence' varies. Automobility has weak correspondence: it is governed by global car manufacturers, their alliances with national governments and oil interests, and roads and fuel stations are organised nationally. Aviation treats cities as nodes in a global system. Rail is partly urban but sits within a national system. Buses, light rail and cycling correspond more strongly, because most trips are local, though national decisions still matter, as the UK's bus deregulation of the 1980s shows. The practical implication: a city can shape some systems far more than others.",
"The London bike-sharing scheme illustrates the argument (p. 9). Bike sharing is a 'generic' intervention: bikes, smartcards, electronic payment, docking stations, GPS tracking. London learned from the Paris Vélib scheme; its scheme started in 2010, had around 8,000 bikes and 500 docking stations by 2014, was run by Serco for Transport for London, sponsored by Barclays and expected to cost £140m over six years. It was embedded in a longer policy trajectory: a 2001 cycling strategy, the 2003 congestion charge, bus lanes open to cyclists, and a £62m walking and cycling budget by 2008/9, with cycling trips up 79% between 2001 and 2011. As the authors put it: \"There is nothing particularly novel and innovative about a bike or a credit card-sized piece of plastic\" (p. 9). The innovation lies in the process of embedding.",
"This is why innovations that are radical in one city are normal in another; UK work shows Oxford promoting electric mobility and Brighton cycling (p. 9). It also challenges the MLP's typical image of one niche fighting one regime. A city usually hosts many innovations at once, where several regimes (auto-, bus- and velomobility) 'compete, coexist and complement' (they replace the fuzzy 'intermingle' with 'complement'; pp. 9–10). Transitions are then more open-ended than a decisive switch, and choosing the unit of analysis becomes a strategic, partly normative choice for which the researcher is responsible."]},
{h:"Governance beyond the city",p:[
"Section 4.2 argues that the city may be where a transition becomes visible, but wider global flows set the conditions: economic restructuring, replicable global infrastructures, carbon agreements (p. 10). These possibilities are filtered by the institutions that claim to speak for a city, or for a zone, corridor or region. \"Cities are not bounded containers but embedded, territorial contexts within wider relational networks of flows\" (p. 10). Neoliberalism has shaped the parameters of urban restructuring for decades without determining local outcomes. 'Solutions' such as battery electric vehicles, self-driving cars or bike hire circulate between cities, but they are not simply replicable: they are embedded differently in each place.",
"The national state plays an active role too. Citing work on UK energy and carbon, the authors list five modes through which the state enrols cities (pp. 10–11): classic fiscal and regulatory levers; 'calculative instrumentalism' through spatial emissions targets; selectively enabling place-based entrepreneurial activity; 'marketised individualisation' in which state measures bypass city institutions and target individuals and communities directly; and building new energy communities through nationally promoted experiments. The result can be atomised, fragmented experimentation. The lesson is that we need a dialogue between institutional analysis and the study of experiments, not a choice for one of them (p. 11)."]},
{h:"What counts as sustainable mobility is contested",p:[
"Section 4.3 asks whether all this adds up to a transition to sustainable mobility or merely a change in transport systems (p. 11). The term hides a basic disagreement: should reliance on the car be reduced, or can automobility itself be made sustainable? Following Banister's 'sustainable mobility approach', the authors list four sets of actions: reducing the need to travel (teleworking, online shopping); modal shift away from the car (slowing traffic, reallocating road space, walking, cycling, trams); reducing trip lengths through urban form (compact, smart or even traffic-free cities); and greater efficiency through new engines, fuels and standards. Each pathway involves several systems at once, and each is contested.",
"Two examples show this (pp. 11–12). Almost 14% of the UK workforce are 'home workers', but this results from economic restructuring and the information society, not from purposeful mobility experiments. The compact city aims to shorten trips, yet there is no accepted definition and the evidence is mixed; the 'compact city paradox' is that compaction concentrates people and functions while liveability calls for lower densities, and polycentric regions complicate the question of scale. Sustainability gains in one place may be losses elsewhere. The conclusion: \"Sustainable urban mobility provides orientation and a suite of possibilities rather than a prescribed route map\" (p. 12)."]},
{h:"The framework: three entry points, three kinds of relationship",p:[
"Section 5 turns the argument into a framework (pp. 12–13, Table 1). Reconfiguration combines old and new, so its forms are 'by definition emergent' and uneven between places. The analysis should look at the relationship between existing configurations (old) and experimental assemblages (new) through three entry points: socio-technical arrangements, forms of urban governance, and conceptions of urban sustainability. For each, the authors describe a focus, the analytical challenge and research needs. The recurring device is a threefold distinction: relations can be competing, co-existing or complementary.",
"For socio-technical arrangements the question is: what do all these experiments add up to in a city (p. 14)? Researchers should look at how experiments connect to each other (UK evidence suggests many are episodic, with little strategic connection) and to existing systems. Competing means struggles of new against new or new against old; co-existing means parallel, largely independent arrangements; complementary means productive fusions. For governance, fragmented capacity produces multiple modes that may be mutually hostile, loosely coupled, or symbiotic, creating hybrid forms that do not fit existing typologies (pp. 14–15).",
"For sustainability, the authors note that 'urban sustainability' has become even slipperier since the 2007–08 financial crisis, jostling with smart, eco-, green and resilient cities, each of which relates economy, environment and society differently (p. 15). What sustainability means in practice (how much growth, carbon versus growth, social cohesion) is negotiated between actors. Accounts may compete, co-exist, or reinforce each other through issue linkage. The central question: which accounts of sustainability become dominant in shaping reconfiguration, and who promotes them?"]},
{h:"Conclusions and what the authors want",p:[
"The conclusion names the core tension: the possibilities for change through technological and social innovation are many, but the grounded capacity to shape change is fragmented (pp. 15–16). Rather than be overwhelmed by multiplicity, the authors 'embrace' it through the concept of reconfiguration and three common themes that make cities comparable. They are open about the limits: this is a preliminary framework and a first step, there was no space to apply it, and the categories are unstable. The danger is that this instability leads researchers to not know how to study such complexity at all.",
"What they call for is empirical work in two forms. First, theoretically informed ethnography in individual cities, looking at all three themes together to see what reconfiguration adds up to there. Second, comparative work across cities to build typologies of forms and processes of reconfiguration, in mobility but also in energy, water, waste and 'nexus' approaches that integrate them. These findings should then feed back into the framework."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The paper rests on socio-technical transitions theory (the MLP) combined with relational geography. On structure versus agency it sits in the middle: experiments are acts of agency, but they are shaped, not determined, by multi-scalar structures such as neoliberal restructuring and state enrolment. On reproduction versus transformation it is sceptical of clean breaks: reconfiguration mixes old and new, and outcomes are open-ended. It is both deliberate (purposive experiments) and emergent (forms of reconfiguration are 'by definition emergent'). Knowledge is situated ('epistemology of the particular') yet aimed at comparability. It is pluralist about sustainability, and its normative stance is thin: it asks on whose behalf experiments work but does not choose an answer.",
"Links to earlier lectures: the paper explicitly cites Angelo and Wachsmuth's critique of 'methodological cityism' (L2) when arguing that wider global-urban flows frame what happens in cities. Its competing conceptions of sustainability echo Campbell's conflicts (L3), though Hodson et al. treat them as negotiations to be mapped rather than a triangle to be resolved. Næss (L1) would likely object to leaving sustainability this open: he wants substantive goals, while Hodson et al. study whatever sustainabilities actors mobilise. The idea of variable 'correspondence' between systems and cities is useful for the Dutch system (L4): national rail versus municipal cycling policy.",
"Forward links: Bulkeley et al. (L9) study exactly the explicit, purposive laboratories that Hodson et al. set aside, and ask the same question of how experiments add up to transitions. Banister's 'efficiency' pathway versus 'reducing the need to travel' prefigures the post-growth argument of Durrant et al. (L12), who would favour phase-outs over adding innovations. Hansen et al. (L13) find mostly incremental change, which fits Hodson et al.'s expectation of messy reconfiguration rather than a sharp switch."]}
],
table:{head:["Entry point","Focus","Competing","Co-existing","Complementary"],rows:[
["Socio-technical arrangements","How many innovations compete, coexist and complement in one city: what do all the experiments add up to?","Struggles of new vs new, or new vs old arrangements","Parallel, largely independent arrangements","Productive fusions of new and new/old arrangements"],
["Forms of urban governance","How multiple, multi-level governance modes condition and shape experiments","Fragmented, mutually hostile or contradictory arrangements","Fragmented, distinct, autonomous or loosely coupled arrangements","Symbiotic, mutually reinforcing: new hybrid governance"],
["Conceptions of urban sustainability","Which accounts of sustainability become dominant, and who promotes them?","Competing understandings and goals","Parallel, largely non-conflictual understandings","Mutually reinforcing through issue linkage"]]},
fig:`<svg viewBox="0 0 620 270" role="img" aria-label="Hodson et al.: old configurations and new experiments are reconfigured through three entry points into competing, co-existing or complementary forms"><defs><marker id="h8A" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="22" width="160" height="68" rx="8" class="bx"/><text x="90" y="44" text-anchor="middle" font-weight="bold">Existing (old)</text><text x="90" y="62" text-anchor="middle">systems, governance,</text><text x="90" y="78" text-anchor="middle">sustainabilities</text>
<rect x="10" y="122" width="160" height="68" rx="8" class="bxw"/><text x="90" y="144" text-anchor="middle" font-weight="bold">Experiments (new)</text><text x="90" y="162" text-anchor="middle">embedding multiple</text><text x="90" y="178" text-anchor="middle">innovations in place</text>
<rect x="215" y="14" width="190" height="56" rx="8" class="bxi"/><text x="310" y="37" text-anchor="middle" font-weight="bold">1 Socio-technical</text><text x="310" y="55" text-anchor="middle">arrangements</text>
<rect x="215" y="82" width="190" height="56" rx="8" class="bxi"/><text x="310" y="105" text-anchor="middle" font-weight="bold">2 Urban governance</text><text x="310" y="123" text-anchor="middle">multi-level</text>
<rect x="215" y="150" width="190" height="56" rx="8" class="bxi"/><text x="310" y="173" text-anchor="middle" font-weight="bold">3 Sustainability</text><text x="310" y="191" text-anchor="middle">conceptions</text>
<rect x="450" y="40" width="160" height="140" rx="8" class="bxg"/><text x="530" y="66" text-anchor="middle" font-weight="bold">Form of</text><text x="530" y="82" text-anchor="middle" font-weight="bold">reconfiguration</text><text x="530" y="112" text-anchor="middle">competing</text><text x="530" y="132" text-anchor="middle">co-existing</text><text x="530" y="152" text-anchor="middle">complementary</text>
<line x1="170" y1="56" x2="212" y2="100" class="ln" marker-end="url(#h8A)"/><line x1="170" y1="156" x2="212" y2="116" class="ln" marker-end="url(#h8A)"/>
<line x1="405" y1="42" x2="447" y2="80" class="ln" marker-end="url(#h8A)"/><line x1="405" y1="110" x2="447" y2="110" class="ln" marker-end="url(#h8A)"/><line x1="405" y1="178" x2="447" y2="140" class="ln" marker-end="url(#h8A)"/>
<rect x="10" y="222" width="600" height="38" rx="8" class="bx"/><text x="310" y="245" text-anchor="middle" font-size="11">Shaped but not determined by global flows and national state enrolment (pp. 10–11)</text>
</g></svg>`,
cap:"Hodson, Geels & McMeekin (2017): reconfiguration as the relation between old configurations and new experiments, analysed through three entry points (Table 1, p. 13)."},

p9:{ext:[
{h:"What the article asks and why",p:[
"Bulkeley and seven co-authors (including Frantzeskaki, who teaches this lecture) start from the rise of the 'experimental city': the idea that urban sustainability is increasingly governed through experiments, from new governance arrangements and demonstration projects to transition management and grassroots innovation (pp. 1–2). Experimentation appeals where the capacity to govern is fragmented and where what counts as improving the city is uncertain and contested. But as research grew, it became clear that experimentation is not one phenomenon that a single concept can capture. So the authors zoom in on one mode: the urban living laboratory (ULL). (Page numbers refer to the 1–19 pagination of the online-first version provided.)",
"In descriptive terms ULLs share five features: they are embedded in a specific urban place, have an explicit learning function, involve participation and users, use alternative forms of leadership and ownership, and aim at evaluation and ongoing improvement (p. 3). They are promoted by EU 'lighthouse' programmes and national funders, used in partnerships between municipalities and universities, and used by community groups to secure legitimacy and resources. Yet the literature remains broad-brush, relying on a few emblematic examples. Two questions are open: why ULLs emerge and who is involved (and excluded), and how they actually work in practice and with what outcomes.",
"The theoretical lens is pragmatist. Following John Dewey, experimentation is a form of 'inquiry': a situation is problematised as undetermined and then given a determination and a solution (p. 3). ULLs are therefore part of a politics of deciding which problems need solving and how. The authors develop a typology along two axes, how ULLs are designed and practised, and what 'disposition' towards the laboratory they take, and apply it to 40 European ULLs."]},
{h:"What makes something a laboratory",p:[
"Laboratories have long been seen as uncontaminated spaces where science is done, but science studies shows they are historically contingent and take many forms (p. 4). The authors highlight two sets of relations. First, laboratories are spaces of 'improvement': an enhanced environment in which phenomena are manipulated towards desired characteristics, combining intervention with observation. That combination is what distinguishes a laboratory from other forms of novelty. Second, laboratories have a 'disposition' towards control and contingency. Borrowing from Easterling, a disposition is 'a propensity within a context' that lies not in the separate parts but in the relationships between them. A lab must be flexible enough to allow reconfiguration yet controlled enough to hold together (p. 4).",
"ULLs can be read as governance in two ways (p. 5). From an institutional angle they are new governance arrangements. From a Foucauldian angle they are a form of 'governmentality': they manipulate socio-material conditions to shape conduct. Either way, their politics lie in how intervention and observation are designed and practised, and how the balance between control and contingency is set. The typology that follows is a heuristic of 'ideal types'; any real ULL will show features of several types and change over time (p. 5)."]},
{h:"Three designs: strategic, civic and organic",p:[
"The design axis draws on Karvonen and van Heur's notions of situatedness and change orientation (pp. 5–6). Situatedness refers to who leads and how the urban is positioned relative to the lab: a lab must be grounded in a particular place, yet its results are meant to be valid anywhere (a 'placelessness'). On change orientation the authors disagree with Karvonen and van Heur, who see labs as intentionally radical. They \"suggest that such goals for urban improvement are not necessarily radical in nature and indeed can seek to reinforce the status quo\" (p. 6). Instead they study the 'politics of improvement': how priorities are set, which techniques of change dominate, and how it is financed.",
"This yields three ideal types (Table 1, pp. 6–7). Strategic ULLs are steered by national or regional government and involve large corporate partners, modelled on national innovation programmes (Innovate UK, FFG, RVO, Vinnova, JPI Urban Europe). The city is a live 'test-bed' for other national and corporate priorities, often won through competitions and funded by a one-off lump sum. Civic ULLs centre on municipal priorities, civic universities and local firms: economic performance, jobs, fixing local infrastructure. They are typically co-funded by the municipality and partners, and to get national money must rework local priorities through national ones.",
"Organic ULLs respond to specific needs of communities or neighbourhoods, such as unemployment, pollution or fuel poverty (p. 7). Civil society organisations lead: NGOs, charities, grassroots and community groups. This resonates with the grassroots innovation literature. Budgets are limited, depend on competitive bidding and are matched by volunteer time, so activities tend to be one-off projects or, at best, a programme sustained over time. (The paper uses 'organic' and 'grassroots' interchangeably for this type.)"]},
{h:"Four dispositions: from control to contingency",p:[
"The second axis orders ULLs along a spectrum from tightly controlled to highly contingent, with four ideal-type dispositions (pp. 7–9). The trial is the most controlled: it tests products or processes under 'real world' conditions by limiting indeterminacy, confining the ULL in space and time. \"It is at heart a form of disciplinary power\" (p. 8), and it usually needs the market protection and political support associated with innovation niches. The enclave is also controlled but allows some contingency: it draws a spatial boundary around an experimental neighbourhood or district, treated as a microcosm of the whole yet set apart from it. The boundary becomes an 'obligatory passage point': any lesson must cross it before it can be replicated elsewhere.",
"Where contingency outweighs control, the demonstration appears (p. 9). It is a showcase or exhibition of what the city could look like under the right conditions. Power works not through discipline but through 'government', shaping the 'conduct of conduct' (Foucault). It establishes potential without determining how it is used. The platform is the most contingent disposition. It does not fix relations but creates conditions under which many new relations can form, removing frames between the 'inside' and 'outside' of the experiment. Like digital platforms, it curates connectivity: previously disconnected actors are brought together on a shared stage, and boundaries are only loosely maintained (p. 9)."]},
{h:"Evidence: 40 European living labs",p:[
"The empirical base comes from the GUST project (JPI Urban Europe). Each partner compiled ten two-page 'snapshot' cases for its country (Austria, the Netherlands, Sweden, the UK) from policy documents, websites and academic sources; some became in-depth studies with fieldwork, interviews, focus groups and workshops (pp. 9–10). Cases had to show the five ULL features, whether or not they used the label. The team assigned each case to the type and disposition it most resembled, deliberating over mixed cases. The authors acknowledge the sample comes from four countries 'quite advanced' in urban experimentation.",
"The findings (Table 2, pp. 10–12): national patterns differ. Austria and Sweden show the full range; the UK has variety but no trials; in the Netherlands ULLs are mostly civic. Trials are rare, even though living labs originated in corporate testing of technologies. Design and disposition are linked: strategic ULLs are mostly demonstrations (E.ON's Hållbarheten apartment house in Malmö) or platforms (Future by Lund); organic ULLs are enclaves or platforms (Stapeln in Malmö); civic ULLs use all four. The platform appears across all three types, reflecting dispersed resources and cross-cutting challenges. Most common of all is the civic demonstration, which lets coalitions 'lead by example', move prototypes into real contexts and put their city 'on the map' (p. 12)."]},
{h:"Four emblematic cases",p:[
"Aspern Urban Lakeside, Vienna, is a strategic demonstration (pp. 12–13): one of Europe's largest development projects, a 'city within a city' on a 240-hectare former airfield, run by the city and the development agency Wien 3420 AG, with roughly €5 billion of public and private money over 2010–2028. The agency acts as 'bridge builder', attracting partners and marketing the site; smart grids, e-bikes and smart housing are showcased. The Aspern Citylab adds some circumscribed contingency through participatory design. Stapeln (STPLN), Malmö, is a community platform (pp. 13–14): a cultural house with maker workshops, started by the municipality and transferred to an NGO. Funding is patched together from the municipality (premises, 2.75 salaries), foundations and fees. The platform lets a resource-poor initiative link one-off activities into a programme.",
"MK: Smart, Milton Keynes, is a civic platform (pp. 15–16). It began with a 2013 HEFCE call; lead shifted from the municipality to the Open University, a tactical move under austerity. A Data Hub curates real-time data across energy, transport and ICT projects, and the OurMK platform and a citizens' ideas competition funded 11 projects. Concept House Village, Rotterdam, is a civic demonstration (pp. 16–17): started in 2011 by universities in Heijplaat, a marginal area left open by the economic crisis, to test sustainable building and retrofit. As the economy recovered, the municipality wanted to move the site back into the mainstream: 'You got it for five years'. Lesson: ULLs often achieve different things than planned, and \"new thinking about their 'failure' will be needed\" (p. 17)."]},
{h:"Conclusions and what the authors want",p:[
"The first conclusion is that ULLs lean towards contingent rather than controlled dispositions: demonstrations and platforms, not formal trials (p. 17). This reflects how governing capacity is configured. Municipalities, knowledge institutions and community groups work with limited autonomy and resources, while strategic political and economic actors lack legitimacy or capacity to enrol everything needed on the ground. It also reflects the open-ended nature of sustainability transformations. ULLs are thus a form of pragmatic 'inquiry' under indeterminacy, where varied and contested urban futures are in play.",
"The second conclusion is more critical (p. 18). Most ULLs have an ambiguous relation with the idea of a transition pathway. Demonstrations offer a 'pre-figurative display' of a sustainable future in a building or district, with little attention to scaling up or rolling out. Platforms prioritise the capacity to run programmes of experiments rather than translating learning into wider transitions. \"The transformative potential of these dominant dispositions of ULLs seems to be much more modest than the claims made, and the links with radical visions of transition pathways somewhat limited\" (p. 18). Future research should study ULLs elsewhere, including outside Europe; how different types co-exist in one city; and whether ULLs can think beyond dominant visions and the interests of the most powerful actors."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The paper combines science and technology studies (the laboratory), pragmatism (Dewey's inquiry), Foucauldian governmentality and transitions thinking. On structure versus agency it shows agency (actors designing labs) strongly conditioned by resources and austerity. On reproduction versus transformation it is sceptical: labs 'can seek to reinforce the status quo' and their transformative potential is modest. It favours emergent, contingent learning over deliberate control, and it is situated: the same label covers very different practices. Normatively it raises inclusion and power (who leads, who is excluded) without prescribing one right type.",
"Links: Hodson et al. (L8) explicitly set aside purposive 'laboratory' experiments to focus on implicit ones; Bulkeley et al. fill that gap and reach a similar worry about how many experiments add up to systemic change. The municipal-university partnerships connect to the digital planning editorial (L10), whose case studies (VR co-design in Eindhoven, inclusive mapping in Zwolle) are small-scale experiments that face the same scaling question. Hansen et al. (L13) show co-governance often stuck at information and consultation, a reminder that 'participation and user involvement' in ULLs can be shallow.",
"Earlier lectures: Angelo and Wachsmuth (L2) explain why cities became the place to 'solve' sustainability; ULLs are one practical expression of that belief. Concept House Village shows the Dutch planning system (L4) at work: the municipality lends land temporarily and then reclaims it for regular development. And the question of who leads (strategic, civic or organic) links to Campbell's and de Satgé and Watson's (L3, L6) concern with whose rationality and interests planning serves."]}
],
table:{head:["Type","Leading actors","The urban is...","Priorities and techniques","Finance","Dispositions found and example"],rows:[
["Strategic","National or regional state, EU programmes, large corporates","A backdrop or test-bed for strategic actors' aims","Mobile exemplar, global best practice or products; competitive","One-off, usually external lump sum","Demonstration and platform (aspern Vienna; Future by Lund)"],
["Civic","Municipality, civic universities, local firms","A public or civic domain built through the partnership","Urban transformation, economic performance, jobs; developmental","Co-funding by municipality and civic partners","All four; civic demonstration dominates (Concept House Village); civic platform (MK: Smart)"],
["Organic (grassroots)","Civil society: NGOs, charities, community groups","The context in which experimentation grows","Locally contingent, diverse community well-being; bespoke","Improvised and incremental; bids plus volunteer time","Enclave and platform (Stapeln, Malmö)"]]}
},

p10:{ext:[
{h:"What the editorial asks and why",p:[
"This is the editorial to a special issue of Computers, Environment and Urban Systems, written by four planners, three of them from Utrecht University (Lin, Geertman, Witte) and one from Manchester (Pinto). It is short (five pages) and programmatic rather than empirical: it sets out what 'digital planning' is, how it differs from related concepts, what the special issue articles found, and what should happen next. It starts from the problems cities face: climate change, ageing, social polarisation, unaffordable housing and mobility issues, combined with conflicting stakeholder interests and citizen activism (p. 1).",
"Governments are responding with digitisation. Several European countries have built national digital plan registers and digitised municipal land-use planning; the UK set up a Digital Taskforce for Planning; the Netherlands' new Environment and Planning Act (Omgevingswet) emphasises digital participation and planning; similar moves are under way in Finland, Australia, Switzerland, the US, China and Singapore (p. 1). The editorial's aim is to frame the variety of ideas in this new field, with particular attention to inclusive participation and sustainable urban futures."]},
{h:"Promise and problems",p:[
"The promise is broad (p. 1). Planning support systems (PSS), urban analytics and city information modelling have enabled a transformative digitalisation of planning; newer tools include digital twins, AI, virtual and augmented reality, gamification platforms, public participation GIS (PPGIS) and the Internet of Things. Some tools collect citizen feedback or help understand problems; others support interaction between authorities, professionals, firms and citizens. Social media (Twitter, Facebook, Weibo) let civil society and marginalised groups voice their views. Machine learning and social network analysis are used to analyse social media data, and digital twins combine geospatial, remote sensing and IoT data with AI to build scenarios that support consensus-building.",
"The problems are just as real (p. 1). Technology supply and planning demand often do not match, interfaces are user-unfriendly, and tools carry socio-political bias. Digital tools can reshape power relations and create new inequality and exclusion. Planning authorities and universities have a large digital skills gap, integration is uneven and fragmented, and there are new risks such as the digital divide and cybersecurity. Hence the editorial's central warning: \"Digitalization of planning is not just the straightforward implementation and use of new technologies\" (p. 1). It demands new ways of planning, proper methods and adjusted communication, and a two-way exchange between academia and practice."]},
{h:"Digital planning versus Planning Support Science",p:[
"Section 2 separates digital planning from the older field of planning support systems (p. 2). Britton Harris defined PSS in 1989, arguing that GIS could loosely integrate computer techniques to generate, evaluate and test plans. Since then PSS have been understood as computer-based tools that help planners and stakeholders with scenario building, forecasting, participation and trend analysis, evolving from GIS, land-use models and decision support systems towards digital twins, AI, VR and data infrastructures. As the field matured, Geertman and Stillwell proposed reading PSS as Planning Support Science, echoing Klosterman's point that \"planning support should start from the peculiarities of the planning activity itself, and not from the characteristics of the technology\" (p. 2).",
"The relationship is layered (p. 2). PSS are tools that can be used within digital planning. Planning Support Science is scientific: it asks how instruments can be fitted to the governance and application at hand in a specific context. Digital planning asks the follow-up question of how those instruments contribute to inclusive and effective planning, and is application-oriented, focused on results in practice. One is a prerequisite for the other. Delivering it requires a 'quadruple' collaboration between government, market parties, societal organisations and individuals, and education and research institutes."]},
{h:"Smart cities and platform urbanism",p:[
"Section 3 compares digital planning with two other concepts (pp. 2–3). The smart city debate is younger; it started academically with Giffinger et al.'s six smart city domains (2007) but was driven mainly by business. Technology companies built entire smart city ecosystems, such as Songdo in South Korea; Barcelona, Amsterdam and Helsinki are often cited as European best practice. The concept was long fuzzy; one durable definition (Caragliu et al.) links investment in human and social capital and infrastructure to sustainable growth, quality of life and participatory governance. Critics stress its technocratic nature and weak link to the real problems of citizens.",
"Platform urbanism is 'a mode of urbanization that is deeply shaped by the conditions and affordances of platforms' (Barns), driven by smartphones and 4G/5G (p. 2). It includes everyday platforms (Uber, Airbnb, Alibaba, Facebook) and government and business initiatives such as Mobility-as-a-Service or Alibaba's City Brain traffic platform. The authors conclude that digital planning includes both as potential tools, but differs in being strategic, procedural and operational, more government-led and more consciously guided by policy goals of sustainable and inclusive development (pp. 2–3). Because smart city applications and platforms often develop without any planning intervention, poor alignment can hinder digital planning, so data governance becomes critical."]},
{h:"A definition and three principles",p:[
"Section 4 reviews definitions (p. 3). Potts and Webb see digital planning as integrating ICT into engagement, decision-making, daily practice and strategy. Hersperger et al. find that digitalisation in land-use planning makes administrative processes more efficient and supports government-citizen interaction and transparency, but does less for innovation. Nummi et al. show that dominant planning styles and institutions can block technological innovation, so digital transformation needs cultural change in organisations. Batty and Yang propose a cyclic system with two loops: an evidence analytics loop driven by data, and a democratic decision-making loop of argument, discussion, design and politics.",
"The authors then define digital planning as \"the application of digital technologies and data-driven approaches to enhance efficiency, effectiveness, and inclusivity in planning processes at different scales to improve social, economic, and environmental outcomes for achieving a more sustainable urban future\" (p. 3). Each term is explained. Efficiency means efficient use of resources and faster, better-coordinated decision-making, including real-time monitoring. Effectiveness means better strategies and policies based on data analytics and prediction, and wider support through participation. Inclusivity means participation, engagement and empowerment, including marginalised groups in formal and informal channels."]},
{h:"What the special issue shows",p:[
"The contributions span the field (pp. 3–4). Geertman and Witte link Planning Support Science to the digital planning agenda. Nurminen et al. found that planners valued a PPGIS tool in nine Finnish projects and that it could improve data representativeness, equality and quality. He et al. show that social media in Guangzhou supported informal participation and reshaped government-society relations, but also produced new power inequalities within and beyond online networks. Daniel and Pettit found that political factors shaped every aspect of urban analytics in Sydney's strategic planning, from data availability to use.",
"Several papers study co-design of tools (pp. 3–4). In Finland, Nummi and Hapuoja found a technology-driven culture dominating national development, though co-development benefited both developers and planners. Dane et al. used immersive VR to co-design healthier spaces in Eindhoven, with mostly positive participant experiences. Flacke et al. co-designed a mapping tool with people with disabilities in Zwolle and argue that digital, physical, social and procedural accessibility are all needed. The authors suggest a future typology should classify approaches by purpose, users, level of digitisation, type of technology, level of complexity and environment (analog, VR/AR, metaverse), warning that \"Any typology should also encompass more than the narrow operational objectivity of digital planning as a set of tools\" (p. 4)."]},
{h:"Recommendations",p:[
"The conclusion is that realising digital planning requires more than technology adoption (p. 4). Tools should be co-developed with planners, citizens and technical experts, and research should explore how to scale co-design from experiments to widespread practice. Attention is needed to power: how existing structures shape tool design and how new tools reshape those structures. Governance must adapt through institutional reform, new policies, a culture supportive of innovation, training of officials, and digital participation. Citizens and marginalised groups should be engaged in formal and informal processes, supported by uniform data standards and integration of social sensing data and local knowledge.",
"Two further warnings stand out (pp. 4–5). AI is shifting from a tool that supports humans to an autonomous, 'agentic' decision-maker, raising concerns about democratic representation, ethics, privacy and justice, especially as politicians with tight budgets may be tempted to substitute human-centred processes with AI tools. Governance should keep AI transparent, inclusive and human-centred, while not forgetting 'low-tech' tools such as social media. Finally, planners need digital literacy and interdisciplinary skills, curricula should cover participatory technology, data analytics and digital ethics, and a systematic review of definitions should prevent the conceptual fragmentation that weakened the smart city concept."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The editorial is broadly optimistic and pragmatic: technology can improve planning if it is embedded in context, co-designed and governed well. It treats power and exclusion as risks to be managed rather than as the core of the story. On deliberate versus emergent change it is strongly deliberate (government-led, policy-informed). Its knowledge stance is mixed: it values data-driven evidence but also local knowledge and 'social sensing', and it keeps the planning process (Batty and Yang's democratic loop) alongside analytics. Normatively it commits to efficiency, effectiveness and inclusivity for a sustainable city, three goals that could conflict with each other.",
"Links: Li and Dang (L11) take the editorial's final warning about agentic AI much further and are far more pessimistic about whether regulation and augmentation can hold. The emphasis on co-design and scaling echoes Bulkeley et al.'s urban living labs (L9), where scaling beyond the demonstration was the weak point. Campbell's planner's triangle (L3) is a useful check: efficiency and effectiveness can serve growth while inclusivity serves equity, so digital tools do not escape the conflicts of sustainable development. The Omgevingswet reference ties the topic to the Dutch system (L4), and He et al.'s Guangzhou case to the Chinese governance context (L7)."]}
],
table:{head:["Concept","Origin","Orientation","Relation to digital planning"],rows:[
["Planning Support Systems / Science","Harris (1989); later reinterpreted as Planning Support Science (Geertman & Stillwell)","Scientific: how instruments fit the governance and context at hand","PSS are tools within digital planning; PSScience is its prerequisite"],
["Smart city","Mostly business-initiated; academic debate from Giffinger et al. (2007)","Technology- and business-driven; criticised as technocratic","Applications can be incorporated as tools"],
["Platform urbanism","Smartphones and 4G/5G; defined by Barns (2020)","Algorithms and real-time data reshaping labour, mobility and consumption","Platforms can be incorporated, but need alignment and data governance"],
["Digital planning","No accepted definition; the editorial proposes one (p. 3)","Application-oriented, government-led, guided by sustainability and inclusion goals","The overarching concept: strategic, procedural and operational"]]},
fig:`<svg viewBox="0 0 620 250" role="img" aria-label="Lin et al.: digital technologies and data-driven approaches serve efficiency, effectiveness and inclusivity for sustainable outcomes, with risks"><defs><marker id="l10A" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="14" width="180" height="104" rx="8" class="bxi"/><text x="100" y="36" text-anchor="middle" font-weight="bold">Means</text><text x="100" y="56" text-anchor="middle">digital technologies</text><text x="100" y="74" text-anchor="middle">PSS, twins, VR, apps</text><text x="100" y="92" text-anchor="middle">data-driven methods</text><text x="100" y="110" text-anchor="middle" class="mut" font-size="11">big data, AI, analytics</text>
<rect x="220" y="14" width="180" height="104" rx="8" class="bxw"/><text x="310" y="36" text-anchor="middle" font-weight="bold">Principles</text><text x="310" y="58" text-anchor="middle">efficiency</text><text x="310" y="78" text-anchor="middle">effectiveness</text><text x="310" y="98" text-anchor="middle">inclusivity</text>
<rect x="430" y="14" width="180" height="104" rx="8" class="bxg"/><text x="520" y="36" text-anchor="middle" font-weight="bold">Outcomes</text><text x="520" y="58" text-anchor="middle">social, economic,</text><text x="520" y="76" text-anchor="middle">environmental</text><text x="520" y="96" text-anchor="middle">sustainable future</text>
<line x1="190" y1="66" x2="217" y2="66" class="ln" marker-end="url(#l10A)"/><line x1="400" y1="66" x2="427" y2="66" class="ln" marker-end="url(#l10A)"/>
<rect x="10" y="140" width="600" height="56" rx="8" class="bxa"/><text x="310" y="160" text-anchor="middle" font-weight="bold">Risks (p. 1)</text><text x="310" y="176" text-anchor="middle">supply-demand mismatch, usability, bias, power shifts,</text><text x="310" y="191" text-anchor="middle">digital divide, skills gap, fragmentation, cybersecurity</text>
<text x="310" y="222" text-anchor="middle" class="mut">Needs new ways of planning, co-design and education,</text><text x="310" y="238" text-anchor="middle" class="mut">not just new tools (pp. 1, 4)</text>
</g></svg>`,
cap:"Lin, Geertman, Witte & Pinto (2025): the editorial's definition of digital planning (p. 3) and the risks it must manage."},

p11:{ext:[
{h:"What the comment argues and why",p:[
"This is a short opinion piece (a 'Comment' of about three pages in Nature Cities) by two planners from Tsinghua University. The printed text does not show page numbers, so none are given here. Its claim is simple and strong: AI is not just another planning tool but a disruption that forces planners to reconsider the profession's core values. Planning has relied on empirical judgement, public participation and incremental adaptation; AI's data-driven analytics, automated decisions and predictive models challenge all three. By reducing the planner's role in negotiating complex interests and obscuring who is responsible for outcomes, AI \"threatens to erode public trust and professional legitimacy\". Harnessing it responsibly, the authors argue, requires critical engagement with its ethical, democratic and equity implications."]},
{h:"From CAD and GIS to 'urban AI'",p:[
"Planning has faced technological disruptions before: computer-aided design in the 1980s and GIS in the 1990s. These changed how planners visualise and analyse data but largely preserved the human role of interpretation and negotiation. Earlier 'smart city' paradigms mostly added incremental ICT solutions. 'Urban AI', by contrast, uses machine learning that can shape governance and physical planning more autonomously. Examples: Singapore optimises traffic signals with AI, Copenhagen forecasts energy use to cut emissions, and Los Angeles is exploring machine learning to allocate housing more fairly.",
"The decisive difference: \"Rather than just supporting planners, AI stands apart by automating critical thinking tasks that were once exclusive to human professionals.\" The question is no longer whether AI can help with data, but whether it replaces deliberation, negotiation and contextual knowledge, the core of the planner's craft. Large language models sharpen this, because they can reason about broader context and value frameworks, not just domain-specific datasets."]},
{h:"Four disruptive factors",p:[
"The authors name four disruptions. First, erosion of planners' judgement and expertise. Planners build judgement by interpreting community values, reconciling conflicts and adapting policies to context. Once validated, algorithms tend to become authorities: if an AI suggests an 'optimal' zoning mix, human intervention may be sidelined in the name of efficiency. \"In effect, the profession risks deskilling as reliance on algorithmic outputs displaces accumulated practitioner wisdom.\" Second, algorithmic bias. AI is sold as impartial, but real datasets carry social, economic and historical biases; deployed uncritically, AI can reinforce redlining, marginalise under-represented voices and ignore cultural or community values that numbers do not capture.",
"Third, diminishing democratic engagement. Especially in the US, planning rests on public participation; automated, 'optimal' solutions can short-circuit slower deliberation, leaving stakeholders fewer opportunities or reasons to engage and cutting out voices that cannot be quantified. Fourth, blurred accountability. Planners balance technical feasibility, law and moral responsibility, but AI puts distance between a recommendation and its human overseers. If an automated site selection triggers gentrification, who is responsible? Without transparent design, open data and a clear chain of accountability, errors are hard to trace, producing a crisis of professional legitimacy."]},
{h:"Why the disruption is unavoidable, and the counter-arguments",p:[
"Even if planners resist, market forces and public enthusiasm push AI forward. Developers use AI analytics to optimise returns, transport companies pilot AI routing, and politicians who want an 'innovative' city sponsor AI pilots from traffic signals to land-use compliance checks. Agencies that do not keep up risk becoming uncompetitive. Generative AI extends the reach beyond numbers to text analysis of policy documents, generative design and real-time sentiment analysis, so AI enters every level of practice.",
"The authors engage two counter-arguments. One says AI augments rather than replaces planners, freeing them for strategy, facilitation and value judgements. The other says AI can be regulated through transparent algorithms and oversight committees. Both have merit but understate AI's disruptive force: in journalism and manufacturing, supportive tools evolved towards partial or full replacement, and the promise of speed and savings can override longer-term social goals. Agencies often lack the resources and skills for rigorous algorithmic audits, especially under political pressure to innovate. So balanced 'augmentation' is precarious."]},
{h:"Lessons for practice and the foundations of planning",p:[
"If disruption is unavoidable, the profession should set the terms. The authors propose five lessons. Reclaim interpretive agency: planners as 'sense-makers' who interpret AI outputs in light of local histories, cultures and values, with ethical frameworks similar to doctors using clinical decision-support. Embed community values: involve diverse stakeholders from the start, with marginalised groups in data collection, model building and validation ('community-in-the-loop'). Strengthen regulatory oversight: standards for algorithmic transparency and bodies that audit and certify AI tools, as in finance and healthcare. Redefine education: digital literacy, AI basics, data science and ethics alongside policy, design and engagement skills. Resist over-reliance: 'slow planning' based on face-to-face deliberation as a counterweight to computational speed.",
"Finally, the authors return to planning's foundations: balancing individual and collective interests, shaping space according to democratic values and anticipating the future ethically. \"AI disrupts these foundations by recasting city-making as a purely technical optimization problem.\" They grant that AI might help balance interests, provided humans keep oversight. AI is thus the profession's 'starkest crossroads' in decades: a chance to reinvent planning's relevance, or a crisis that reduces humans to an afterthought. The aim is not rejecting AI but deliberately rethinking its integration, so that it remains a tool serving human aspirations, which requires alliances among communities, academics, policymakers and software developers."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The comment defends a communicative, deliberative view of planning (judgement, negotiation, participation) against what it sees as a return of technical, optimising rationality. On structure versus agency it stresses structural pressures (markets, budgets, political branding) that make disruption 'unavoidable', while calling for professional agency to set the terms. Its knowledge stance is situated: local histories and values matter more than 'optimal' outputs. Normatively it commits to equity, democracy and stewardship.",
"Compared with Lin et al.'s editorial (L10), Li and Dang are much more sceptical: the editorial trusts co-design, governance and education to keep digital tools inclusive, while Li and Dang doubt that audits and augmentation will hold under budget pressure. The bias argument links to justice debates in L3 (green gentrification) and L6 (de Satgé and Watson's conflicting rationalities, where techno-managerial state planning meets marginalised communities). Durrant et al. (L12) offer a contrast in roles: they want planners to use expertise to voice uncomfortable truths, whereas Li and Dang fear expertise is being displaced altogether."]}
],
table:{head:["Disruptive factor","What happens","Why it matters"],rows:[
["Erosion of judgement and expertise","Validated algorithms become authorities; 'optimal' outputs sideline human intervention for efficiency","Deskilling: accumulated practitioner wisdom and value reconciliation are displaced"],
["Algorithmic bias and equity","Datasets carry historical biases; unquantified cultural and community values are ignored","Can reinforce redlining and marginalise under-represented voices; planning's integrity at stake"],
["Diminishing democratic engagement","Fast automated decisions bypass slower deliberation","Fewer chances or reasons to engage; voices that cannot be quantified are cut out"],
["Blurred accountability","Distance between an AI recommendation and its human overseers","Unclear who is responsible (e.g. site selection that triggers gentrification); legitimacy crisis"]]},
fig:`<svg viewBox="0 0 620 285" role="img" aria-label="Li and Dang: urban AI and unavoidable pressures produce four disruptions that erode trust and legitimacy; five lessons in response"><defs><marker id="ld11A" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="100" y="12" width="190" height="62" rx="8" class="bxi"/><text x="195" y="34" text-anchor="middle" font-weight="bold">Urban AI</text><text x="195" y="52" text-anchor="middle">automates critical</text><text x="195" y="67" text-anchor="middle">thinking tasks</text>
<rect x="330" y="12" width="190" height="62" rx="8" class="bxw"/><text x="425" y="34" text-anchor="middle" font-weight="bold">Unavoidable push</text><text x="425" y="52" text-anchor="middle">markets, politicians,</text><text x="425" y="67" text-anchor="middle">generative AI</text>
<line x1="195" y1="74" x2="250" y2="104" class="ln" marker-end="url(#ld11A)"/><line x1="425" y1="74" x2="370" y2="104" class="ln" marker-end="url(#ld11A)"/>
<rect x="10" y="108" width="140" height="56" rx="8" class="bxa"/><text x="80" y="131" text-anchor="middle" font-weight="bold">Deskilling</text><text x="80" y="149" text-anchor="middle">judgement erodes</text>
<rect x="165" y="108" width="140" height="56" rx="8" class="bxa"/><text x="235" y="131" text-anchor="middle" font-weight="bold">Algorithmic bias</text><text x="235" y="149" text-anchor="middle">inequity repeated</text>
<rect x="320" y="108" width="140" height="56" rx="8" class="bxa"/><text x="390" y="131" text-anchor="middle" font-weight="bold">Less democracy</text><text x="390" y="149" text-anchor="middle">debate bypassed</text>
<rect x="475" y="108" width="135" height="56" rx="8" class="bxa"/><text x="542" y="131" text-anchor="middle" font-weight="bold">Accountability</text><text x="542" y="149" text-anchor="middle">who is responsible?</text>
<line x1="310" y1="164" x2="310" y2="184" class="ln" marker-end="url(#ld11A)"/>
<rect x="110" y="186" width="400" height="32" rx="8" class="bxa"/><text x="310" y="207" text-anchor="middle">Eroding public trust and professional legitimacy</text>
<line x1="310" y1="218" x2="310" y2="234" class="ln" marker-end="url(#ld11A)"/>
<rect x="40" y="236" width="540" height="42" rx="8" class="bxg"/><text x="310" y="254" text-anchor="middle">Response: sense-makers, community-in-the-loop, audits,</text><text x="310" y="270" text-anchor="middle">new curricula, 'slow planning'</text>
</g></svg>`,
cap:"Li & Dang (2025): why urban AI disrupts planning, and the five lessons they propose."},

p12:{ext:[
{h:"What the article asks and why",p:[
"Durrant (UCL), Lamker (Groningen) and Rydin (UCL) write a short 'Comment' in Planning Theory & Practice. They start from the revived debate on whether pursuing economic growth is compatible with meaningful cuts in greenhouse gas emissions and resource use, a debate labelled 'degrowth' or 'post-growth' (p. 287). Their question is practical: what do these debates mean for planning, and how could its existing instruments and tools be adapted, in quite radical ways, for a post-growth future? They use two core planning tasks as examples: housing and infrastructure.",
"They deliberately narrow the scope (p. 287). They distinguish structural constraints on planning, the wider planning system, and the instruments and tools planners use, and focus on the last. Structural reform of societies and economies is left to a broader post-growth debate. They also set aside, 'for now', the relationship between lower- and higher-income countries, although rich countries may need to shrink their biophysical footprint by 40 to 50 percent. They argue their focus on what planners can do today is relevant in both the Global North and South."]},
{h:"Planning's bond with growth",p:[
"Since 19th-century industrialisation, planning tools were developed to cope with, organise and even foster growth (pp. 287–288). In Europe and North America planning grew out of public health, housing conditions and infrastructure for growing cities; in colonial contexts it served economic growth through exploitation of colonised places and people. Recently economic growth has moved to the core of planning globally. The impetus for the paper is the recognition that \"planning has bound itself into a pro-growth agenda that is mentally and institutionally hard to overcome\" (p. 288). Instruments now facilitate development to achieve other goals, through direct benefits (infrastructure provision) or indirect ones (a bigger tax base), and success is usually expressed in money, as with GDP.",
"The authors grant that GDP says something about livelihoods and wellbeing, and that the only experience of shrinking economies is recession, with unequal harm (p. 288). But they reject the idea that criticising growth means a forced recession: a planned restructuring focused on environmental and spatial change is different, and would reuse and adapt existing planning tools. The sharpest point concerns sustainability: \"It is particularly worrying to see how the pursuit of sustainability has been subsumed to the pro-growth agenda\" (p. 288). Planning embraced eco-modernism (eco-cities, carbon-neutral developments, renewable energy infrastructure), making it 'almost always possible' to label more development as sustainable. Trading off environmental, social and economic dimensions has avoided the deeper conflicts over resource use that Campbell identified."]},
{h:"Post-growth, degrowth and the decoupling problem",p:[
"The authors distinguish the two labels (pp. 288–289). Degrowth is more rooted in economics, more structural and theoretical, and gives voice to North-South inequality and different development pathways. Post-growth is an interdisciplinary and pragmatic search for radical alternatives within existing structures, so it suits an analysis of today's planning tools while still aiming to transform planning itself. Both share one empirical core: the question of decoupling, meaning breaking the link between economic activity and resource use. Historically, growth has come with rising resource use and emissions despite efficiency gains, and reducing resource consumption matters as much as reducing emissions.",
"Decoupling can be relative (the economy grows faster than resource use, thanks to efficiency) or absolute (resource use plateaus or falls while the economy grows) (p. 289). Most analysts say absolute decoupling is needed, but there is little evidence it is happening or even possible in a pro-growth world. The reasons: rebound effects (the Jevons paradox: efficiency does not reduce total consumption), technological change that misses high-consumption areas or shifts the problem elsewhere, an overestimated potential of recycling and the circular economy, and underestimated impacts of the service economy and of shifting consumption across the globe. Cities that market themselves as sustainability beacons may look worse once their residents' consumption emissions are counted (p. 289)."]},
{h:"What post-growth planning would do for housing",p:[
"The central aim is stated plainly: \"The aim of post-growth planning is to delink planning policy and practice from the reliance on growth and ever-continuing new urban development to achieve public goals\" (p. 290). Planning should encourage resource efficiency, set a built environment that allows slower growth elsewhere in the economy, and fit a slower pace of development. At the same time, economic activity is a prerequisite for livelihoods, so planning should support sufficient activity and help redress the uneven spatial distribution of too little and too much, within absolute ecological limits. The toolbox considered: plan-making at several scales, regulation, taxation and incentives, information and assessments, public land ownership and direct development.",
"One tool is explicitly excluded: land value capture, because it depends on creating more monetised development value, often in expensive locations, to fund other goals, which is inherently pro-growth (p. 290). Planning should also make literal space for low-value and non-commercial activities such as care and the social economy. For housing, post-growth planning rejects the idea, 'for which there is no foundation', that affordability can be solved by more market-led housebuilding in high-price areas. A first step is to diversify tenures and use site allocations to protect land for public, social and community housing, with ambitious targets for self-build and community-built housing, rather than tying social housing to a share of market housing."]},
{h:"Efficiency, ceilings, shrinkage and the existing stock",p:[
"Two further pathways are needed (pp. 290–291). The first is regulating new development for the highest resource efficiency and circularity. Many systems already do this, but it needs better information: life cycle analysis and carbon accounting should be standard for every proposal, with attention to cumulative impacts at local, regional and national level so that individually 'good' projects do not add up to boundary-busting totals. More contentious: both minimum and maximum space standards. The second, more challenging pathway addresses the Jevons paradox: slowing and redistributing development. That means absolute limits, with ceilings and not only floors or targets, ideally framed nationally, and diverting activity from high-price, high-demand areas to lower-price, high-need areas.",
"This implies abandoning the idea of growth engines, growth nodes in polycentric plans and competition between localities, which leads to over-supply (p. 291). Plans should consider the whole range from shrinkage through no or low growth to limited development. Shrinking areas could be testbeds for post-growth ideas, but shrinkage is not in itself success, and responsibility should not be pushed onto them alone; fast-growing areas may be better placed to lead. Planning should also make courageous use of the existing stock: requiring reuse where the carbon analysis supports it, using fiscal tools against excessive use of space, and restricting second homes and short-term lets."]},
{h:"Infrastructure: planning for phase-out",p:[
"Infrastructure shapes the environmental impact of mobility, energy and water use, and building and maintaining it is resource-intensive (pp. 291–292). There can be strong post-growth arguments for replacing infrastructure to enable more efficient patterns, but also for working within existing networks rather than expanding them indefinitely, since they embody sunk resources and financial and political capital. Decisions will be delicate and context-specific. Better knowledge of embedded carbon and cumulative impacts is needed, along with critical scrutiny of the 'do nothing' scenarios that often justify new projects.",
"Above all, new infrastructure should be coordinated with the planned replacement or shrinkage of existing infrastructure (p. 292). Investment in renewable energy should go with phasing out carbon-based infrastructure; expanding cycling and walking networks should take space from roads and car-based spaces; investment in long-distance rail should be coordinated with reduced air travel capacity. The authors admit this goes beyond tools and needs a new vision for planning. For now they seek 'hacks' that permit change from within. The main obstacle is that pro-growth thinking grips planners' imagination so strongly that alternatives seem inconceivable."]},
{h:"Frameworks and the planner's role",p:[
"Post-growth planning needs supportive frameworks, especially nationally (p. 292). Planners have skills at community and neighbourhood level and can leverage local civil society; freed from pressure to accommodate market-led growth, these capacities could grow. But control over finance and land must be devolved within supportive regional, national and ideally international frameworks, for instance to meet housing needs through public, social or community schemes. On responsibility, the authors are careful (p. 293). Academics should show future practitioners that growth-based development is often incompatible with addressing the environmental crisis. Yet most planners are employees, often under elected politicians, so the authors question how far individual planners can legitimately promote a new agenda.",
"Their answer is to ground the role in expertise rather than values (pp. 293–294). Planners know more than ever about resources and impacts, so instead of promoting market-led development with cursory impact assessment, they should spell out the medium- to long-term environmental and social consequences of plans, including the trade-offs and compensation usually offered. They should speak to the infeasibility of plans that presuppose growth, rather than follow standard 'best practices' of green growth. Just as it is unethical to propose an unimplementable plan, it is unethical to advise action known to be disastrous: \"Planners should consider part of their role to voice uncomfortable truths and to avoid the easier path or discourse of growth-dependence\" (p. 293). Planners might turn to supporting community initiatives, re-tooling towards community building and skills, and becoming holders of shared leadership (p. 294)."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The paper sits in the critical, post-growth strand of sustainability thinking. On reproduction versus transformation it wants transformation but through pragmatic reform ('hacks') of existing tools, not revolution. It is deliberate and planner-centred, though it leans on national frameworks and civil society. On structure versus agency it acknowledges structural limits (employment, politicians, property interests) yet gives professionals real agency. Its knowledge stance is interesting: it bases the planner's legitimacy on expert knowledge of consequences rather than on values, while being clearly normative (absolute ecological limits, sufficiency, needs over market growth).",
"Links: this is the most direct heir to Næss (L1), who argued that continuous growth of building stock in rich countries is incompatible with sustainability and that planning needs substantive goals. It uses Daly's distinction between growth and development (L1) and the efficiency versus sufficiency debate: ceilings and maximum space standards are sufficiency tools. It explicitly cites Campbell (L3), arguing that trade-offs have hidden fundamental conflicts over resources, and Krähmer (L3) on labelling development as sustainable. Angelo and Wachsmuth (L2) show why cities became 'solutions'; Durrant et al. add that 'sustainable' cities may still have large consumption footprints.",
"Contrasts: Hodson et al. (L8) treat competing sustainabilities as something to map; Durrant et al. take a side. The Dutch context (L4, L5) is a good test: 'more claims than land' in port-cities and the national housing targets are classic growth-framed planning, where ceilings and redistribution would be a radical shift. Hansen et al. (L13) show how hard even incremental change is inside municipal administrations, which tempers expectations about post-growth re-tooling."]}
],
table:{head:["Domain","Growth-dependent default","Post-growth re-tooling"],rows:[
["Purpose of instruments","Facilitate development and growth to fund other goals; success measured in money (p. 288)","Delink public goals from growth and ever-continuing new development (p. 290)"],
["Value capture","Land value capture as predominant instrument","Excluded: it needs more monetised development value, so is inherently pro-growth (p. 290)"],
["Housing","More market-led housebuilding, especially in high-price areas","Diversify tenures; protect land for public, social, community and self-build housing (p. 290)"],
["Assessment and regulation","Cursory impact assessment or sustainability appraisal (p. 293)","Standard LCA and carbon accounting; cumulative impacts; minimum and maximum space standards (p. 291)"],
["Amount and location of development","Floors and targets; growth nodes; localities competing for development","Ceilings; redistribute from high-price to high-need areas; plan for no growth or shrinkage (p. 291)"],
["Existing stock","Excessive use of space; second homes and short-term lets","Reuse existing stock; fiscal disincentives; restrict second homes and short-term lets (p. 291)"],
["Infrastructure","Expansion justified against 'do nothing' scenarios","Coordinate new build with phase-outs: cycling vs roads, rail vs air (p. 292)"],
["Planner's role","Neutral managers, process designers, 'master planners' (p. 294)","Voice uncomfortable truths; supportive holders of shared leadership (pp. 293–294)"]]},
fig:`<svg viewBox="0 0 620 285" role="img" aria-label="Durrant et al.: pro-growth planning, failure of absolute decoupling, post-growth planning and its pathways"><defs><marker id="d12A" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="14" width="180" height="84" rx="8" class="bxa"/><text x="100" y="36" text-anchor="middle" font-weight="bold">Pro-growth planning</text><text x="100" y="56" text-anchor="middle">tools foster growth;</text><text x="100" y="72" text-anchor="middle">success = money</text><text x="100" y="89" text-anchor="middle" class="mut" font-size="11">(p. 288)</text>
<rect x="220" y="14" width="180" height="84" rx="8" class="bxw"/><text x="310" y="36" text-anchor="middle" font-weight="bold">Decoupling?</text><text x="310" y="56" text-anchor="middle">relative: some</text><text x="310" y="72" text-anchor="middle">absolute: little evidence</text><text x="310" y="89" text-anchor="middle" class="mut" font-size="11">(p. 289)</text>
<rect x="430" y="14" width="180" height="84" rx="8" class="bxi"/><text x="520" y="36" text-anchor="middle" font-weight="bold">Why not absolute</text><text x="520" y="54" text-anchor="middle">rebound (Jevons),</text><text x="520" y="70" text-anchor="middle">problem-shifting,</text><text x="520" y="86" text-anchor="middle">recycling overrated</text>
<line x1="190" y1="56" x2="217" y2="56" class="ln" marker-end="url(#d12A)"/><line x1="400" y1="56" x2="427" y2="56" class="ln" marker-end="url(#d12A)"/>
<line x1="520" y1="98" x2="440" y2="120" class="ln" marker-end="url(#d12A)"/>
<rect x="110" y="122" width="400" height="40" rx="8" class="bxg"/><text x="310" y="140" text-anchor="middle" font-weight="bold">Post-growth planning</text><text x="310" y="155" text-anchor="middle">delink public goals from growth (p. 290)</text>
<line x1="200" y1="162" x2="105" y2="182" class="ln" marker-end="url(#d12A)"/><line x1="310" y1="162" x2="310" y2="182" class="ln" marker-end="url(#d12A)"/><line x1="420" y1="162" x2="515" y2="182" class="ln" marker-end="url(#d12A)"/>
<rect x="10" y="184" width="190" height="64" rx="8" class="bx"/><text x="105" y="204" text-anchor="middle" font-weight="bold">Housing</text><text x="105" y="222" text-anchor="middle">protect land: social,</text><text x="105" y="238" text-anchor="middle">community, self-build</text>
<rect x="215" y="184" width="190" height="64" rx="8" class="bx"/><text x="310" y="204" text-anchor="middle" font-weight="bold">Pathway 1</text><text x="310" y="222" text-anchor="middle">efficiency: LCA,</text><text x="310" y="238" text-anchor="middle">carbon, space caps</text>
<rect x="420" y="184" width="190" height="64" rx="8" class="bx"/><text x="515" y="204" text-anchor="middle" font-weight="bold">Pathway 2</text><text x="515" y="222" text-anchor="middle">ceilings, redistribute,</text><text x="515" y="238" text-anchor="middle">plan for shrinkage</text>
<text x="310" y="272" text-anchor="middle" class="mut">Infrastructure: plan phase-outs alongside new build (p. 292)</text>
</g></svg>`,
cap:"Durrant, Lamker & Rydin (2023): from the failure of absolute decoupling to re-tooling planning instruments (pp. 288–292)."},

p13:{ext:[
{h:"What the article asks and why",p:[
"Green and blue spaces are increasingly treated as solutions to climate adaptation, biodiversity loss, public health and social cohesion (p. 2402). EU policy frames them as 'green infrastructure', 'ecosystem services' and 'nature-based solutions': the Green Deal, the Biodiversity Strategy 2030 calling for greening in every European city, the Green City Accord, and the New Leipzig Charter, which also asks for citizen participation and co-creation. Citizens press politicians to act, and research has turned to justice issues such as the effects of greening on vulnerable groups. With policy, research and society all pushing, green space planning has 'tailwind'. But is there evidence that it has actually improved in European cities over the past decade?",
"Hansen and 26 co-authors answer with a longitudinal study (p. 2403). In 2014 the EU project GREEN SURGE studied green space planning in 20 European cities. This follow-up returns to eleven of them and asks two questions: how have urban green space planning and governance changed, and what influenced these changes? And what is the contribution of current green space planning and governance to urban transformations? The title states the tension: are the changes transformative, or piecemeal?"]},
{h:"Planning, governance and what counts as transformation",p:[
"The authors first define terms (p. 2403). Green space planning means formal, government-led processes to protect, enhance and create public green and blue space using instruments such as strategic plans, regulations and action programmes. Green space governance stresses the involvement of multiple actors, often decentralised, networked and participatory. Following Arnouts et al., there is a continuum from hierarchical government-led planning, via co-governance, to self-governance. The analysis of change uses three clusters inherited from GREEN SURGE: contextual factors (planning system, politics, resources), planning approaches (themes and instruments), and governance and participation, plus a question on COVID-19 (pp. 2403–2404).",
"To judge whether changes are transformative, the paper draws on transformation theory (p. 2404). Transformative change is \"intentional, actively pursued, radical and systemic\" and requires breaking through path dependencies and changing or replacing institutions, structures and practices. Municipal politicians and officials can steer such change, but planning is also constrained by established paradigms, multi-level legal frameworks, siloed institutions, routines and past investments, and municipalities often lack resources and knowledge. The authors note that many transformation frameworks do not fit easily with planning's traditional rationale of stability and rational land-use guidance (pp. 2404–2405). (They use 'transformation' for both the transitions and transformations literatures.)",
"Their yardstick is the four targeted outcomes of urban transformation from Wolfram, Borgström and Farrelly (p. 2405). Innovation: creating, nurturing and anchoring novelties. Exnovation: exposing and dismantling path dependencies ('unlocking'). Co-governance (originally 'collective stewardship'): enabling and aligning diverse actors across sectors and scales. Social justice: ensuring diversity and contestation, since technocratic decisions often unintentionally reinforce inequities, which calls for redistributing resources and decision-making power (pp. 2405–2406). A deliberate transformation should aim at least one of these."]},
{h:"Method: re-interviewing eleven cities",p:[
"The study used structured expert interviews with open and closed questions, mirroring the 2014 approach (p. 2406). There was no funding, so researchers took part voluntarily and case selection was pragmatic: volunteers were found for eleven of the 20 cities. Interviewers knew the local language and context. In seven cities the same person was interviewed as in 2014, typically a municipal official leading green space planning; in four a person in a similar role. Interviews ran from August 2020 to March 2021, lasted 60 to 130 minutes, and were done face-to-face (two), by phone (three) or online (six). Results represent the interviewee's view.",
"Analysis had three phases (pp. 2406–2407): an overview of the extent of change using mainly closed answers; an inductive, in-depth coding of open answers compared with the 2014 'case study portraits', condensed into four trends (global trends and disruptive events, urban growth, integrated planning, governance); and a discussion against the four transformation outcomes. The cities, which include Aarhus, Barcelona, Berlin, Bristol, Edinburgh, Helsinki, Linz, Lisbon, Ljubljana, Malmö and Utrecht, cover five European planning clusters and range from about 200,000 inhabitants (Linz) to over 3.6 million (Berlin) (pp. 2407–2408). They are not a random sample: many are EU research partners and sustainability champions, and so good cases to look for orchestrated transformation."]},
{h:"Results: more attention, more plans",p:[
"Contextual change was mostly seen as positive (pp. 2408–2409). National political change was positive in six of eleven cities (new environmental laws, ecological issues in land-use planning), as was local change in six, sometimes due to new political leadership. Resources were mixed: positive in three cities, ambivalent in three, negative in two, with budget cuts and maintenance budgets not keeping pace with new green space. Five cities reported greater awareness of climate change or of green space's value for health, well-being or justice; three reported tension between greening and densification.",
"In planning approaches (pp. 2409–2411), the most important instruments were unchanged in eight of eleven cities, often statutory master plans or green space plans. Almost all themes grew in relevance: climate change in ten cities, biodiversity and human health in eight each. Climate adaptation sparked the most new policies, partly after floods and heat waves, and biodiversity concern led to new plans. For other themes, no new instruments were reported. Awareness of social cohesion rose in seven cities, but only two reported more awareness of cultural diversity. Ecosystem services and green infrastructure were more integrated in seven cities each; action plans such as tree planting programmes improved in six. In governance (p. 2411), municipal participation efforts increased in nine cities, interest from non-governmental actors in eight, and cross-departmental cooperation in nine."]},
{h:"Trends and tensions",p:[
"Four deeper trends emerged. First, responses to global developments and disruptions (pp. 2411–2413): Barcelona's Green Infrastructure and Biodiversity Plan, Bristol translating the SDGs into its One City Plan, flooding in Aarhus, many non-statutory strategies (climate adaptation, stormwater, green roofs, a bee strategy in Berlin), climate or ecological emergency declarations, and regulation such as Helsinki's Green Area Factor. COVID-19 raised appreciation of green space, but only Barcelona reported concrete acceleration. Awareness of social cohesion grew, but specific green space actions for disadvantaged areas were few. Second, urban growth was ambiguous (p. 2413): densification brought resources for green space but also conflicts with affordable housing, sharpened by tourism in Berlin and Barcelona. Aarhus used 'exchange agreements' in which developers fund green space.",
"Third, steps towards integrated planning (pp. 2413–2415). Climate adaptation and, in Berlin, sustainable mobility created opportunities; Utrecht described a shift from parks and peri-urban landscapes to connectivity and neighbourhood access, especially in lower-income areas, and created 'guilds' (gildes) linking urban development and green space planning. Helsinki and Linz merged units; Linz involved experts and stakeholders early. But Berlin separated urban and green space planning, even physically, and Malmö's integration increased workloads. Fourth, participation 'between tokenism and co-governance' (pp. 2415–2416): Ljubljana's NGOs mainly opposed projects; Berlin, Helsinki and Lisbon mostly involved citizens in government-led planning; Bristol struggled to meet demands for participation. Aarhus, Bristol, Edinburgh and Utrecht stood out, with Aarhus creating a sub-department for citizenship and cultural change, Utrecht's slogan 'Together we make Utrecht', and Friends of Parks groups in the UK."]},
{h:"Discussion: four lenses on transformation",p:[
"The overall verdict is sober (p. 2416). Many changes were incremental, others ambiguous, so \"these championing cases of sustainable urban development in Europe cannot be classified as radical urban transformations\". Integration brought influence and resources but also trade-offs; higher budgets did not solve long-term maintenance; even COVID-19 produced only short-term change in one city. That cities struggled to use windows of opportunity shows the power of structural conditions and path dependencies in formal administrations. Through the four lenses: innovation took the form of new strategies and systems thinking, anchored in policy, though new strategies may also reveal that old instruments are inflexible and stuck on recreation and access (pp. 2416–2417).",
"Exnovation was rare (p. 2417). The Aarhus unit for participation and cultural change was the clearest case, a form of change management; more cooperation between green space, planning, water and transport units may be a path towards dismantling silos. Co-governance increased, but participation mostly stayed at the lower rungs of information and consultation, partly due to lacking capacity and flexibility; where co-creation was embedded in high-level policy, perspectives of citizens and officials changed (pp. 2417–2418). Social justice was the weakest lens: awareness grew, but specific approaches were rare, and even in the one city whose new policies centre on social cohesion and equality, these goals had not yet reached green space planning. \"Compared to the wide range of planning responses dealing with ecological issues this lack of consideration of social issues in spatial planning is a considerable disparity\" (p. 2418)."]},
{h:"Conclusions and what the authors want",p:[
"The conclusion balances progress and limits (pp. 2418–2419). Green space gets more attention, several cities are overcoming path dependencies such as policy silos, and some co-create green infrastructure with businesses and civil society. Deliberate transformative change happened at high levels of local policy-making, through new policies and organisational cultures for co-governance, and incremental changes (citizen interest, systems thinking, integrated planning) may seed future transformations. But long-term maintenance, funding and organisational culture remain challenges, and cultural diversity and other justice aspects are poorly recognised.",
"Fundamentally, the authors write, the problem is limited resources and staff capacity caused by system-level conditions beyond the control of green space departments or even municipalities (p. 2419). They call for multi-scale policy frameworks supporting nature-based innovation and new partnerships, change management and training on social aspects, incentives from political or administrative leaders to identify and 'exnovate' lock-in practices, and putting social and environmental justice at the heart of green space planning to avoid technocratic, unjust outcomes. They admit a key limitation: the study relies on officials who may be either preservers of the status quo or agents of change. Future research should include other stakeholders, especially active citizen groups."]},
{h:"Connecting it to the course",p:[
"This section is my synthesis, not the authors' claims. The paper applies transformation theory (Wolfram's transformative capacity and outcomes) to public administration. On structure versus agency it finds structure winning: officials see what is needed but 'often lack the means to act'. On reproduction versus transformation, the answer is mostly reproduction with incremental change. It focuses on deliberate, orchestrated change, yet notes that disruptive events rarely produce lasting change. Its data are situated (the view of one official per city), and its normative commitment is clear: justice should be central, not an add-on.",
"Links: the justice gap connects directly to green gentrification in Campbell's triangle and the L3 lecture: greening that ignores social effects can displace the people it is meant to serve. Hodson et al. (L8) would read the findings as reconfiguration: many experiments and strategies that co-exist without systemic change. Bulkeley et al. (L9) found that labs rarely scale; Hansen et al. find a similar gap between promising projects and structural transformation. The move from tokenistic participation to co-governance echoes Lin et al.'s (L10) call for inclusive digital participation (several cities used digital tools and participatory budgeting).",
"Further contrasts: Durrant et al. (L12) would note that densification here partly funds green space (Aarhus's exchange agreements), a growth-dependent mechanism like land value capture. Utrecht's shift to neighbourhood-level access for lower-income areas and its 'guilds' are close to home and link to the Dutch planning system (L4). Næss (L1) and Angelo and Wachsmuth (L2) remind us to ask whether urban greening in 'champion' cities addresses non-local impacts or mainly improves liveability locally."]}
],
table:{head:["Outcome (Wolfram et al. 2019)","Meaning","What the eleven cities showed","Verdict"],rows:[
["Innovation","Creating, nurturing and anchoring novelties","New adaptation and biodiversity strategies (e.g. Barcelona's GI and Biodiversity Plan, Helsinki's Green Area Factor); systems thinking via ecosystem services","Anchored policy innovation, though new strategies may reveal inflexible old instruments (pp. 2416–2417)"],
["Exnovation","Exposing and dismantling path dependencies","Aarhus's unit for participation and cultural change; merged units (Helsinki, Linz); Utrecht's 'guilds'; but Berlin separated departments","Only a few deliberate cases (p. 2417)"],
["Co-governance","Enabling and aligning diverse actors","Participation efforts up in 9 of 11; participatory budgeting (Helsinki); Friends of Parks (UK); 'Together we make Utrecht'","Mostly information and consultation, except where embedded in high-level policy (pp. 2417–2418)"],
["Social justice","Ensuring diversity and contestation","More awareness, few specific actions; cultural diversity rarely addressed","Underrepresented: a 'considerable disparity' with ecological responses (p. 2418)"]]},
fig:`<svg viewBox="0 0 620 262" role="img" aria-label="Hansen et al.: most changes piecemeal, some seeds, few deliberate transformations, constrained by structural factors"><defs><marker id="hn13A" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<text x="20" y="22" font-weight="bold">Piecemeal / incremental</text><text x="600" y="22" text-anchor="end" font-weight="bold">Transformative</text>
<line x1="20" y1="36" x2="598" y2="36" class="ln" marker-end="url(#hn13A)"/>
<rect x="10" y="52" width="190" height="96" rx="8" class="bx"/><text x="105" y="74" text-anchor="middle" font-weight="bold">Most changes</text><text x="105" y="94" text-anchor="middle">new strategies,</text><text x="105" y="110" text-anchor="middle">tree programmes,</text><text x="105" y="126" text-anchor="middle">consultation</text>
<rect x="215" y="52" width="190" height="96" rx="8" class="bxw"/><text x="310" y="74" text-anchor="middle" font-weight="bold">Seeds</text><text x="310" y="94" text-anchor="middle">systems thinking,</text><text x="310" y="110" text-anchor="middle">integrated planning,</text><text x="310" y="126" text-anchor="middle">citizen interest</text>
<rect x="420" y="52" width="190" height="96" rx="8" class="bxg"/><text x="515" y="74" text-anchor="middle" font-weight="bold">Deliberate change</text><text x="515" y="94" text-anchor="middle">high-level policy,</text><text x="515" y="110" text-anchor="middle">co-governance culture</text><text x="515" y="126" text-anchor="middle">(e.g. Aarhus unit)</text>
<rect x="10" y="166" width="600" height="48" rx="8" class="bxa"/><text x="310" y="186" text-anchor="middle">Constraints: maintenance, funding, organisational culture, staff</text><text x="310" y="203" text-anchor="middle" class="mut" font-size="11">structural, beyond green-space departments (p. 2419)</text>
<text x="310" y="240" text-anchor="middle" class="mut">Social justice and cultural diversity: least addressed (p. 2418)</text>
</g></svg>`,
cap:"Hansen et al. (2022): where the observed changes in eleven cities sit between piecemeal and transformative (pp. 2416–2419)."}
};
