const READINGS = [
/* ================= WEEK 1 ================= */
{id:"fw", wk:1, title:"Course framework: four dimensions & normative commitments", cite:"Lecture 8 Sept (Bossuyt & Bouwmeester) + Rydin (2021) Introduction: Theory and Planning Research, pp. 1–17", theory:"Meta-framework", status:"slides",
statusNote:"Lecture slides on file. Rydin (2021) ch.1 itself is NOT on file (your Rydin upload starts at ch.2); content here comes from the slides that quote it.",
one:"Every planning theory takes a position on four dimensions (structure/agency, reproduction/change, knowledge, normative commitments). Those positions shape which research questions and designs make sense.",
summary:[
"Theory is 'a body of assumptions, of which the mutual relations have been made explicit' (Føllesdal et al. 1990) and, for Rydin (2021, p. 9), 'a heuristic aid to understand a situation, a way to try to know what is essentially unknowable in its completeness'. Ontology + epistemology + values together make up a theory, and a theory steers research design, questions and analysis.",
"The course compares theories on four dimensions: (1) sources of planning outcomes (structure ↔ agency); (2) reproduction and change (reproduction ↔ transformation; deliberate ↔ emergent); (3) knowledge and expertise (universal ↔ situated; monist ↔ pluralist; plus realism ↔ relativism added in the knowledge lecture); (4) normative commitments (efficiency, democracy, equity, sustainability, justice).",
"Theories make three kinds of claims: explanatory (how does planning work, why do outcomes occur), evaluative (which processes/outcomes are fair or good) and prescriptive (what should planners do). Normative commitments are the underlying values used to evaluate planning. They shape what we see as a problem, what planning should achieve, and what we measure in research."],
concepts:[["Theory","A coherent set of assumptions/knowledge claims whose relations are explicit; a heuristic aid, never complete (Rydin 2021)."],["Ontology","What reality is and what exists to be known."],["Epistemology","What knowledge is, who can produce it, how claims are judged."],["Structure","Recurrent, patterned arrangements that limit the choices and opportunities available."],["Agency","The capacity of individuals to act independently and exercise free will."],["Reproduction vs transformation","Does the theory explain why arrangements persist, or how they change?"],["Deliberate vs emergent","Is change designed on purpose, or does it emerge from many interacting actions?"],["Explanatory / evaluative / prescriptive claims","How it works / whether it is good / what to do."],["Normative commitment","Assumption about what ought to be valued, pursued, protected."]],
fig:`<svg viewBox="0 0 640 250" role="img" aria-label="Four dimensions of the course framework"><g font-size="13">
<text x="10" y="22" font-weight="700">1 · Sources of outcomes</text><line x1="230" y1="18" x2="620" y2="18" class="ln" stroke-width="2"/><text x="230" y="36" class="mut" font-size="11">structure</text><text x="620" y="36" class="mut" font-size="11" text-anchor="end">agency</text>
<text x="10" y="72" font-weight="700">2a · Reproduction/change</text><line x1="230" y1="68" x2="620" y2="68" class="ln" stroke-width="2"/><text x="230" y="86" class="mut" font-size="11">reproduction</text><text x="620" y="86" class="mut" font-size="11" text-anchor="end">transformation</text>
<text x="10" y="112" font-weight="700">2b · How change happens</text><line x1="230" y1="108" x2="620" y2="108" class="ln" stroke-width="2"/><text x="230" y="126" class="mut" font-size="11">deliberate</text><text x="620" y="126" class="mut" font-size="11" text-anchor="end">emergent</text>
<text x="10" y="152" font-weight="700">3 · Knowledge</text><line x1="230" y1="148" x2="620" y2="148" class="ln" stroke-width="2"/><text x="230" y="166" class="mut" font-size="11">universal · monist · realist</text><text x="620" y="166" class="mut" font-size="11" text-anchor="end">situated · pluralist · relativist</text>
<text x="10" y="200" font-weight="700">4 · Normative</text><g font-size="12"><rect x="230" y="184" width="70" height="24" rx="12" class="bxa"/><text x="265" y="200" text-anchor="middle">efficiency</text><rect x="308" y="184" width="82" height="24" rx="12" class="bxa"/><text x="349" y="200" text-anchor="middle">democracy</text><rect x="398" y="184" width="58" height="24" rx="12" class="bxa"/><text x="427" y="200" text-anchor="middle">equity</text><rect x="464" y="184" width="96" height="24" rx="12" class="bxa"/><text x="512" y="200" text-anchor="middle">sustainability</text><rect x="568" y="184" width="52" height="24" rx="12" class="bxa"/><text x="594" y="200" text-anchor="middle">justice</text></g>
<text x="10" y="240" class="mut" font-size="11">Place any author on these lines, then ask: what does this position make visible, and what does it hide?</text></g></svg>`,
cap:"The four dimensions you use to position every author in the course.",
example:"A thesis asking 'which municipal instrument best raises housing output?' assumes a deliberate, planner-centred, universal-knowledge view (governmental model). A thesis asking 'how do tenant groups' experiences of renovation differ?' assumes situated, pluralist knowledge.",
quotes:["\"a heuristic aid to understand a situation, a way to try to know what is essentially unknowable in its completeness\" (Rydin 2021, p. 9)"],
dims:null,
exam:"Expect MCQs that give a quote or case and ask where it sits on a dimension. The trap: a survey of 1,000 residents does NOT make an approach pluralist (see Knowledge)."},

{id:"buit", wk:1, title:"Buitelaar (2026) Making sense of The Just City", cite:"Buitelaar, E. (2026). Making sense of The Just City. Defining, choosing, and applying different conceptions of urban justice. Planning Theory. doi:10.1177/14730952261415602", theory:"Normative / political philosophy", status:"partial",
statusNote:"Abstract + lecture slides only. The article is open access (CC BY) but I could not download the PDF from here; see Missing PDFs.",
one:"'The Just City' means four different, partly incompatible things: the Happy, Equal, Supportive and Free City. Planners must choose explicitly.",
summary:["Few people oppose the idea of a just city, but once you look at distribution, people disagree about what it looks like. Buitelaar draws on political and economic philosophy to build four ideal types, each translating into different planning policies. They can look sympathetic at first sight, yet they do not all go together and some are incompatible. Being precise about what urban (in)justice means is necessary for effective and legitimate policy.",
"In the lecture: the Supportive City is illustrated with room-stress (adequacy thresholds) and Vienna's social housing; the Free City with Houston (no zoning) and Almere Oosterwold (framework rules, organic development). The Metropolis case (2,000 market homes with no subsidy vs 1,600 mixed homes with 40% affordable and a €50m contribution) shows how each conception picks a different plan."],
concepts:[["Happy City (utilitarianism)","A city is just when total (or average) well-being is maximised; distribution matters only via the sum."],["Equal City (egalitarianism)","A city is just when goods/opportunities are distributed (more) equally; inequality itself is the problem."],["Supportive City (sufficientarianism)","A city is just when everyone reaches a threshold of 'enough' (adequate housing, e.g. room-stress ≥ 0); above it inequality is acceptable."],["Free City (liberalism)","A city is just when individual liberty and equal rights are protected; fair procedures, not end-state patterns (Houston, Oosterwold)."],["Room stress factor","Rooms available ÷ rooms required − 1; below 0 = inadequate housing (Jonkman 2019)."]],
fig:`<svg viewBox="0 0 640 230" role="img" aria-label="Four just cities judge the same five households differently"><g font-size="12">
<text x="10" y="18" font-weight="700">What each city looks at (5 households, bars = housing quality)</text>
${[["Happy · sum",20,[60,80,30,90,70],"maximise the total"],["Equal · gap",180,[60,62,58,61,59],"shrink the differences"],["Supportive · floor",340,[32,95,45,70,52],"everyone above the line"],["Free · rights",500,[30,90,55,75,65],"fair rules, any pattern"]].map(([t,x,v,s],k)=>`<text x="${x}" y="45" font-weight="600">${t}</text>`+v.map((h,i)=>`<rect x="${x+i*24}" y="${170-h}" width="18" height="${h}" class="${k==2&&h<40?'fw':'fi'}"/>`).join('')+(k==2?`<line x1="${x-4}" y1="130" x2="${x+118}" y2="130" class="accs" stroke-width="2" stroke-dasharray="4 3"/><text x="${x+118}" y="58" class="acc" font-size="10" text-anchor="end">- - threshold</text>`:'')+`<text x="${x}" y="190" class="mut" font-size="11">${s}</text>`).join('')}
<text x="10" y="220" class="mut" font-size="11">Same city, four verdicts: the conceptions can be incompatible (Buitelaar 2026).</text></g></svg>`,
cap:"The criterion changes the verdict, not the data.",
table:{head:["Conception","Philosophy","'A city is just when…'","Metropolis case would pick"],rows:[["Happy","Utilitarian","…aggregate welfare is highest","Probably 2,000 market homes (more homes, no €50m cost), unless welfare gains of the poor weigh heavily"],["Equal","Egalitarian","…differences between groups are smallest","Mixed plan (40% affordable, priority to low incomes)"],["Supportive","Sufficientarian","…nobody falls below a decent minimum","Mixed plan, judged on how many of the 2,000 inadequately housed get adequate homes"],["Free","Liberal","…rights are equal and people are free to use property","Market plan: it complies with the rules and needs no coercion or subsidy"]]},
example:"Amsterdam's 40-40-20 rule (40% social, 40% mid, 20% free sector) mixes Equal and Supportive thinking. Houston's lack of zoning is the textbook Free City.",
quotes:[],
dims:{sa:null,rt:null,de:null,us:null,mp:null,norm:"Explicitly about normative commitments: utility, equality, sufficiency, liberty."},
exam:"Match a policy to a conception, or say which conception a Marxist (Equal) vs a Hayekian (Free) planner would hold."},

/* ================= WEEK 2 ================= */
{id:"hall", wk:2, title:"Hall (2014/2020) The City of Theory", cite:"Hall, P. (2020). 'The City of Theory', from Cities of Tomorrow (4th edn, 2014), in The City Reader, pp. 440–453", theory:"Intellectual history of planning thought", status:"full",
statusNote:"Full chapter on file (your scanned PDF; I ran OCR on all 29 pages).",
one:"After 1955 planning became an academic discipline and swung from craft (design) to science (systems/rational planning), then fragmented (Lindblom, Davidoff, Marxists, communicative theory), and in the process lost its 'priestly clothing'.",
summary:["Before 1955 planning was an extension of architecture and engineering: design-based, blueprint end-state plans, survey–analysis–plan (Geddes), with 'theory in planning but no theory of planning'. Goals were implicit, the planner 'would get it right first time', and the political environment was passive: Batty calls it planning's golden age (e.g. Abercrombie's static city with a green belt).",
"The 1950s baby boom, economic boom and mass car ownership overwhelmed that static system. At the same time a 'quantitative revolution' (location theory: von Thünen, Weber, Christaller, Lösch; Isard's regional science) and cybernetics (Wiener) arrived. 1960–70: the systems revolution. Cities are systems to be modelled, monitored and controlled (McLoughlin, Chadwick; transportation studies Detroit 1955, Chicago 1956; Lowry model). Rational planning is the theory of the process (Faludi), systems planning the theory of the object. Planning becomes a science, not an art.",
"From 1965 to 1975 critiques 'stripped the planner of whatever priestly clothing' he or she had: from the right/pluralists (Lindblom's muddling through; Meyerson & Banfield; Altshuler) and from the left (Davidoff's advocacy planning; Arnstein). Rittel & Webber's wicked problems undercut optimal solutions. Then came the Marxist ascendancy (Harvey, Massey, Castells, Lefebvre): planning serves the reproduction of capital and labour, so planning theory is a product of social forces, a logic Hall calls 'strangely quietist'. Forester tries to resolve it with Habermas: communicative action. Hall's jab: stripped of its philosophy, it is 'good old-fashioned democratic common sense', i.e. Davidoff again. Theory and practice: honeymoon in the 1960s, tiffs in the 1970s, divorce in the 1980s."],
concepts:[["Planning as craft","Pre-1955: design-based, blueprint, end-state plans, intuitive expert goals."],["Theory in vs theory of planning","Borrowed snippets of theory about cities vs a theory of what planning (the process) is."],["Systems planning","Theory of the object: the city as a system of interrelated activities in flux, monitored and controlled (cybernetics)."],["Rational (process) planning","Theory of the process: goals → inventory → model → forecast → alternatives → evaluation → choice → monitoring (Faludi 1973)."],["Priestly clothing","The planner's special status and mystique as expert, lost 1965–75."],["Marxist critique","Planning is a function of the capitalist state: it secures accumulation and reproduction of labour, and always solves one problem by creating another."],["Communicative turn","Forester (via Habermas): planning as communicative action that can distort or reveal; later Healey, Innes. Rydin (2007) calls it the 'new orthodoxy'."],["Planning graduate 1955/1965/1975","Drawing board → analysing computer output → talking to community groups in the evenings (Hall, p. 386)."]],
fig:`<svg viewBox="0 0 660 200" role="img" aria-label="Timeline craft to positivism to fragmentation to communicative consensus"><g font-size="12">
<line x1="20" y1="80" x2="640" y2="80" class="ln" stroke-width="2"/>
${[[20,"<1955","Craft","design, blueprint, expert intuition","bxw"],[175,"1960s","Positivism","systems + rational models, computers","bxi"],[330,"1965–85","Fragmentation","Lindblom, Davidoff, Rittel & Webber, Marxists","bxa"],[485,"1990s→","Communicative 'consensus'","Forester, Healey, Innes; many knowledges","bxg"]].map(([x,y,t,s,c])=>`<rect x="${x}" y="95" width="148" height="78" rx="8" class="${c}"/><circle cx="${x+10}" cy="80" r="6" class="acc"/><text x="${x}" y="68" class="mut" font-family="IBM Plex Mono" font-size="11">${y}</text><text x="${x+8}" y="116" font-weight="700">${t}</text><foreignObject x="${x+6}" y="122" width="138" height="50"><div xmlns="http://www.w3.org/1999/xhtml" style="font:11px/1.3 Public Sans,sans-serif;color:var(--muted)">${s}</div></foreignObject>`).join('')}
<text x="20" y="30" font-weight="700">Where does the planner's authority come from?</text><text x="20" y="48" class="mut" font-size="11">design skill → scientific method → (contested) → facilitating many knowledges</text></g></svg>`,
cap:"Lecture 15 Sept's reading of Hall: craft › positivism › fragmentation › consensus(?).",
example:"The Dutch Vinex-era models and MKBA practice are the 1960s systems/rational legacy still alive; a participatory 'omgevingsdialoog' under the Omgevingswet is the communicative legacy.",
quotes:["\"there was some theory in planning but there was no theory of planning\"","\"within a decade, from 1965 to 1975, these approaches together neatly stripped the planner of whatever priestly clothing, and consequent mystique, she or he may have possessed\"","\"planning was a science, not an art\" (Taylor, quoted by Hall)"],
dims:null,
exam:"Link a skill to a period and knowledge type: design judgement = craft (situated expert, monist); modelling = positivist (universal, monist); facilitation = communicative (situated, pluralist)."},

{id:"know", wk:2, title:"Rydin (2007) Re-examining the role of knowledge within planning theory", cite:"Rydin, Y. (2007). Planning Theory, 6(1), 52–68 · + lecture 'Knowledge in planning theory' (15 Sept) + exit-ticket answers", theory:"Epistemology of planning", status:"slides",
statusNote:"Article NOT on file. Built from the knowledge lecture and the exit-ticket document, which reproduce its core (Figure 1, opening up/closing down, Collins & Evans). Please upload the PDF.",
one:"Planning links knowledge to action. After the communicative turn we accept many knowledges, but not all claims are equally valid: planners must open up to claims AND close down by testing them, and they co-produce knowledge in the process.",
summary:["Planning = linking knowledge to action, in the governing of shared spaces, for desirable futures (Friedmann 1987; Healey 1997). Planning's authority always rested on a claim about knowledge. Rydin defines knowledge as knowledge claims specifying causal relations: if we do X, then Y follows.",
"The communicative turn is a 'new orthodoxy': knowledge is held by residents and other groups, not only planners. But deliberation has limits: knowledges are not additive (Evans & Marvin 2006), consensus does not guarantee the best knowledge won, and consensus fits cases of fully shared information or very high uncertainty, while planning deals with wicked problems.",
"Rydin distinguishes types of knowledge claims (Figure 1): empirical (the situation now, A), predictive (what happens without planning, B2), processual (the causal links between states, how intervention leads to outcomes) and normative (the desired planned future, B1). Each needs a different test. Opening up gives voice to many actors and claims; closing down tests claims and decides which count as knowledge for this decision. Experience 'is not of itself a sufficient condition for it to be knowledge' (p. 56, after Collins & Evans).",
"Her own position: knowledge is socially constructed (soft relativism), many actors can bring valid knowledge (pluralist), yet claims can be ranked against each other (not strong relativism)."],
concepts:[["Universal ↔ situated","Does the validity of a claim depend on who produced it and from where? Universal: no. Situated: yes. Positionality is the tell-tale sign."],["Monist ↔ pluralist","How many independent sources can give a claim the status of knowledge? Monist: one (the scientific method, 'the scientific prism'). Pluralist: several (local, experiential, lay)."],["Realism ↔ relativism","Can competing claims be judged against each other? Realist: yes, about a real world. Relativist: only within frameworks. Soft relativism: knowledge is produced in contexts. Strong relativism: no claim is better."],["Positivism","Universal + monist; one method for nature and society; value-free science; bias = error to remove."],["Post-positivism","Situated + pluralist; science never fully value-free; many shades of grey."],["Empirical / predictive / processual / normative claims","What is / what will be without planning / how X causes Y / what should be."],["Opening up & closing down","Invite many claims, then test which count as knowledge for this decision."],["Co-production","Planners don't just manage claims; they co-produce knowledge in the process."],["Multi- vs transdisciplinary","Multi = several academic disciplines (can still be monist). Trans = non-academics as knowledge producers (pluralist)."]],
fig:`<svg viewBox="0 0 620 250" role="img" aria-label="Rydin 2007 Figure 1 redrawn: where knowledge claims sit"><g font-size="12">
<rect x="20" y="100" width="150" height="56" rx="8" class="bxi"/><text x="95" y="124" text-anchor="middle" font-weight="700">A · situation now</text><text x="95" y="142" text-anchor="middle" class="mut" font-size="11">EMPIRICAL claims</text>
<rect x="430" y="20" width="170" height="56" rx="8" class="bxa"/><text x="515" y="44" text-anchor="middle" font-weight="700">B1 · planned future</text><text x="515" y="62" text-anchor="middle" class="mut" font-size="11">NORMATIVE claims</text>
<rect x="430" y="100" width="170" height="56" rx="8" class="bx"/><text x="515" y="124" text-anchor="middle" font-weight="700">B · without planning</text><text x="515" y="142" text-anchor="middle" class="mut" font-size="11">PREDICTIVE claims</text>
<rect x="430" y="180" width="170" height="56" rx="8" class="bxg"/><text x="515" y="204" text-anchor="middle" font-weight="700">B2 · what happens</text><text x="515" y="222" text-anchor="middle" class="mut" font-size="11">EMPIRICAL (later)</text>
<path d="M170 118 L430 50" class="ln" stroke-width="1.5"/><path d="M170 128 L430 128" class="ln" stroke-width="1.5"/><path d="M170 138 L430 206" class="ln" stroke-width="1.5"/>
<text x="300" y="110" text-anchor="middle" class="acc" font-weight="700">PROCESSUAL claims</text><text x="300" y="175" text-anchor="middle" class="mut" font-size="11">the causal links between states</text><text x="300" y="190" text-anchor="middle" class="mut" font-size="11">("if we do X, then Y")</text></g></svg>`,
cap:"Redrawn after Rydin (2007) Fig. 1, as in the lecture. Practice: 'Car ownership in Utrecht fell 12% 2015–2023' = empirical; 'Rijnenburg demand will exceed supply by 2030' = predictive; 'densification near stations reduces car use because it changes relative costs' = processual; 'Rijnenburg should prioritise affordability' = normative.",
table:{head:["Position","What is knowledge?","Who produces it?","Judging claims","Planning style"],rows:[["Positivism","Universal","Monist (science)","Realist","Rational/systems planning, MKBA, models"],["Rydin 2007","Situated (socially constructed)","Pluralist","Soft relativist, claims can be tested","Opening up + closing down, co-production"],["Strong relativism","Situated","Pluralist","No claim better than another","(rarely held in planning)"],["Communicative theory","Situated","Pluralist","Consensus/deliberation","Healey, Innes, Forester"]]},
example:"Grenfell Tower: the Grenfell Action Group's warnings (local experiential knowledge) were ignored. Opening up would have heard them; closing down would have tested them against fire-safety evidence.",
quotes:["\"The experience of local stakeholders may be an important basis for claiming local or experiential knowledge but [..] such experience is not of itself a sufficient condition for it to be knowledge\" (Rydin 2007, p. 56)"],
dims:{sa:null,rt:null,de:null,us:75,mp:80,norm:"Better decisions through tested, co-produced knowledge; democratic inclusion balanced by validity."},
exam:"Classic traps from the lecture: (1) a survey of 1,000 people is not pluralism; (2) a positivist can admit bias but treats it as error; (3) situated ≠ anything goes (that is the realism/relativism axis)."},

{id:"marx", wk:2, title:"Marx (1844) Estranged Labour", cite:"Marx, K. (1844). Economic and Philosophic Manuscripts of 1844: Estranged Labour. Marxists Internet Archive · + lecture 17 Sept", theory:"Marxism / historical materialism", status:"partial",
statusNote:"Public-domain text, read via the web (not a PDF on file) + lecture slides. Link: marxists.org/archive/marx/works/1844/manuscripts/labour.htm",
one:"Under capitalism workers are estranged from their product, their activity, their species-being and each other. History is driven by class struggle over the means of production, so real change needs a structural change of the base: abolition of private property.",
summary:["Humans realise themselves through labour, their transformative relation with nature. Under private property and wage labour this relation is inverted: 'The worker becomes all the poorer the more wealth he produces.' Marx names four estrangements: from the product (it confronts him as an alien power), from the act of production (labour is 'not voluntary, but coerced; it is forced labor'), from species-being (conscious creative activity reduced to a means to survive) and from other humans.",
"Private property is the 'product, the result, the necessary consequence, of alienated labor', though it then reproduces it. A higher wage alone would be 'better pay for slaves' without restoring human significance (quoted on slide).",
"Lecture framing: Marx adapts Hegel's dialectic but replaces 'the Spirit' with material relations (historical materialism). The base (means and relations of production) determines the superstructure (values, norms, ideology). This is a deterministic view: humans are subject to, not actors of, broad change. Politically this becomes revolution: abolish private property, pass through a socialist state towards a stateless society. For planning: markets produce material inequality by design, so the progressive planner plans for the poor and the working class through decommodified models (Madden & Marcuse 2016)."],
concepts:[["Estranged/alienated labour","Four forms: from the product, from the labour process, from species-being, from other people."],["Species-being","The human capacity for conscious, free, purposeful creative activity."],["Historical materialism","The material base (means and relations of production) drives history and shapes the superstructure."],["Base / superstructure","Economy and property relations / ideology, law, culture, norms."],["Dialectic","History as the clash of opposites: owners vs the disowned (class struggle)."],["Means of production","Land, factories, tools; ownership defines class."],["Commodification","Turning things (labour, housing, land) into goods produced for exchange value, not use value."]],
fig:`<svg viewBox="0 0 620 230" role="img" aria-label="Marx base and superstructure"><g font-size="12">
<polygon points="310,20 520,110 100,110" class="bxi"/><text x="310" y="70" text-anchor="middle" font-weight="700">SUPERSTRUCTURE</text><text x="310" y="90" text-anchor="middle" class="mut" font-size="11">law · planning · ideology · norms · culture</text>
<rect x="100" y="140" width="420" height="60" class="bxa"/><text x="310" y="165" text-anchor="middle" font-weight="700">BASE</text><text x="310" y="185" text-anchor="middle" class="mut" font-size="11">means + relations of production (owners ↔ workers)</text>
<path d="M310 138 L310 114" class="accs" stroke-width="3"/><polygon points="303,118 317,118 310,108" class="acc"/>
<text x="540" y="170" font-size="11" class="mut">determines</text><text x="20" y="222" class="mut" font-size="11">Change = transform the base (abolish private property); planning inside capitalism mostly reproduces it.</text></g></svg>`,
cap:"Structure dominates: planning sits in the superstructure.",
example:"Madden & Marcuse: overcrowding and unaffordable homes 'are not market failures, they are how the market works'. The answer is decommodified housing (public, cooperative), not a tweak of zoning.",
quotes:["\"The worker becomes all the poorer the more wealth he produces\"","\"Private property is thus the product, the result, the necessary consequence, of alienated labor\""],
dims:{sa:15,rt:80,de:35,us:30,mp:25,norm:"Material equality through shared ownership of the means of production."},
exam:"Contrast with Hayek. Marx: structure, determinism, material equality, the state redistributes. Hayek: agency, indeterminism, equality of rights, framework rules. Both are ontological realists (exit ticket)."},

{id:"hayek", wk:2, title:"Hayek (1944) Planning and democracy", cite:"Hayek, F.A. (1944). Planning and democracy. In Hillier & Healey (eds) (2008) Critical Essays in Planning Theory Vol. 1, pp. 42–53 (ch. 5 of The Road to Serfdom)", theory:"Liberalism / Austrian economics", status:"slides",
statusNote:"Chapter NOT on file. Built from the lecture (17 Sept) plus my general knowledge of The Road to Serfdom ch. 5; check against the text.",
one:"Central planning needs agreement on a complete scale of values that does not exist. Assemblies cannot agree on detail, so power slides to experts and ultimately to dictatorship. No one can know enough to plan society; spontaneous order under general rules works better.",
summary:["Context: the Great Depression and WWII made central (economic) planning look inevitable. Hayek argues that directing the economy towards a single social goal requires a 'complete ethical code' ranking all ends. No such agreement exists in a free society. Democratic assemblies can agree that there should be a plan but not on its content, so planning is delegated to experts, democracy becomes a talking shop, and the demand for a strong man grows (the road to serfdom).",
"Epistemologically (and in 'The theory of complex phenomena', 1989 per the lecture): total understanding of society is unknowable. Knowledge is dispersed among individuals, local and often tacit. So stop trying to steer phenomena to a desired end-state. A spontaneous order, decentralised and emerging from individuals acting under general rules, is more efficient and adaptable than any central plan.",
"For planning: set framework conditions (equality of rights, the rule of law) and let order emerge. Intervention may still be justified for conflicting land uses, poor quality space and locational matters (Glaeser & Gyourko on the liberal side of the lecture)."],
concepts:[["Spontaneous order","Order that emerges from decentralised actions under general rules, not from a designer's plan."],["Dispersed knowledge","Knowledge of particular circumstances is spread over many people; no planner can collect it."],["Indeterminism","Social events are not fully determined or predictable (vs Marx's determinism)."],["Individualism","The individual, not the collective, as the basis of ends and values."],["Equality of rights","Formal equality before general rules (vs material equality)."],["Road to serfdom","Central planning leads, via delegation to experts, to loss of freedom."]],
fig:`<svg viewBox="0 0 620 220" role="img" aria-label="Central plan versus spontaneous order"><g font-size="12">
<text x="150" y="20" text-anchor="middle" font-weight="700">Taxis: central plan</text><text x="470" y="20" text-anchor="middle" font-weight="700">Kosmos: spontaneous order</text>
<circle cx="150" cy="110" r="18" class="acc"/>${[0,1,2,3,4,5,6,7].map(i=>{const a=i*Math.PI/4,x=150+75*Math.cos(a),y=110+70*Math.sin(a);return `<line x1="150" y1="110" x2="${x}" y2="${y}" class="accs" stroke-width="1.5"/><circle cx="${x}" cy="${y}" r="8" class="fm"/>`}).join('')}
${(()=>{const p=[[400,60],[440,90],[500,55],[540,100],[420,150],[480,130],[530,165],[460,180],[390,110],[560,140]];const e=[[0,1],[1,2],[2,3],[1,5],[0,8],[8,4],[4,5],[5,6],[6,7],[4,7],[3,9],[9,6],[5,3]];return e.map(([a,b])=>`<line x1="${p[a][0]}" y1="${p[a][1]}" x2="${p[b][0]}" y2="${p[b][1]}" class="ln"/>`).join('')+p.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="8" class="fi"/>`).join('')})()}
<text x="150" y="208" text-anchor="middle" class="mut" font-size="11">one mind, one goal, needs all knowledge</text><text x="470" y="208" text-anchor="middle" class="mut" font-size="11">many minds, general rules, dispersed knowledge</text></g></svg>`,
cap:"Hayek's core contrast, which Moroni (week 4) calls taxis vs kosmos.",
example:"Glaeser & Gyourko (2003): strict zoning acts like a tax on new construction and raises prices, so reform the rules instead of building a few subsidised units.",
quotes:[],
dims:{sa:80,rt:40,de:85,us:70,mp:75,norm:"Liberty; equality of rights; efficiency through spontaneous order."},
exam:"Hayek on knowledge is subtle: knowledge is dispersed and local (situated/pluralist-ish), but his claims about markets and order are general. The exam may ask 'emergent or deliberate?' → emergent."},

{id:"cozz", wk:2, title:"Cozzolino (2020) The (anti) adaptive neighbourhoods", cite:"Cozzolino, S. (2020). Environment and Planning B: Urban Analytics and City Science, 47(2), 203–219 · Tutorial 1 slides", theory:"Complexity / liberal (Hayek–Moroni line)", status:"slides",
statusNote:"Article NOT on file. Built from the Tutorial 1 slides (which quote pp. 205–206) plus my knowledge of the paper; please upload it.",
one:"Many recent neighbourhoods are anti-adaptive: their design, ownership and rules block small, incremental changes by residents. Planners should distribute design control and use simple framework rules so neighbourhoods can keep adapting.",
summary:["A conceptual article with illustrative examples (Bergamo; Almere Oosterwold), no empirical test. Aims: 'characterizing the causes behind the formation and perpetuation of AANs' and 'providing policy and design implications' (p. 205).",
"Problem: anti-adaptive neighbourhoods (AANs) resist the ordinary, incremental change that made traditional cities rich and diverse. Causes: large-scale, one-shot, top-down production by a single developer/designer; over-detailed plans and regulations; ownership forms (large plots, condominium or collective ownership) that concentrate or freeze design control. Mechanism: residents and small actors cannot modify, add or replace, so change needs costly big interventions. Alternative: adaptive neighbourhoods have small plots, many owners, distributed design control and simple, general rules (Oosterwold: framework rules, organic development). Implication: plan the conditions and rules, not the end-state.",
"Tutorial analysis: normative preference for individual autonomy, distributed control, diversity, anti-paternalism, which fits the Free City. On structure/agency: 'action (as the main source of urban change)' (p. 206), while acknowledging the 'institutional framework that shaped [the city's] evolutionary process' (p. 206), so it leans to agency with institutions enabling or constraining."],
concepts:[["Anti-adaptive neighbourhood (AAN)","Neighbourhood whose physical, ownership and regulatory set-up blocks incremental change."],["Adaptability","Capacity of the built environment to change gradually through many small actions."],["Distribution of design control","Many actors each controlling small parts vs one actor controlling everything."],["Framework rules","Simple general rules within which people build freely (Oosterwold)."],["Incremental development","Small, step-by-step change over time."]],
fig:`<svg viewBox="0 0 620 220" role="img" aria-label="Adaptive versus anti-adaptive neighbourhood plots"><g font-size="12">
<text x="150" y="20" text-anchor="middle" font-weight="700">Adaptive: many small plots</text><text x="470" y="20" text-anchor="middle" font-weight="700">Anti-adaptive: one block, one owner</text>
${Array.from({length:24},(_,i)=>{const c=i%6,r=Math.floor(i/6);const w=[40,34,44,38,30,42][c];const x=40+[0,44,82,130,172,206][c];return `<rect x="${x}" y="${40+r*38}" width="${w}" height="32" class="${[3,8,14,19].includes(i)?'bxa':'bxg'}"/>`}).join('')}
<rect x="360" y="40" width="220" height="146" class="bxi"/><text x="470" y="110" text-anchor="middle" font-weight="600">single developer</text><text x="470" y="128" text-anchor="middle" class="mut" font-size="11">detailed plan · covenants · shared ownership</text>
<text x="150" y="208" text-anchor="middle" class="mut" font-size="11">red = plots that changed; each owner can adapt</text><text x="470" y="208" text-anchor="middle" class="mut" font-size="11">change needs one big, costly intervention</text></g></svg>`,
cap:"Grain of control decides whether a neighbourhood can evolve.",
example:"Oosterwold (Almere): buyers get a plot and a short list of rules (build on max. 20%, grow food, arrange your own road and utilities) instead of a master plan.",
quotes:["\"action (as the main source of urban change)\" (p. 206)","\"institutional framework that shaped [the city's] evolutionary process\" (p. 206)"],
dims:{sa:70,rt:75,de:80,us:null,mp:null,norm:"Individual autonomy, diversity, anti-paternalism: the Free City."},
exam:"Tutorial critique angles: actors are unequal (tenants can't adapt), markets are power structures (what emerges may serve exchange value for owners), and the traditional city is romanticised (overcrowding, poor quality)."},

/* ================= WEEK 3 ================= */
{id:"gov", wk:3, title:"Rydin (2021) Governmental models: the hope of rational public administration", cite:"Rydin, Y. (2021). Theory in Planning Research, ch. 2, pp. 19–40. Springer · + lecture 22 Sept", theory:"Rational-comprehensive planning (governmental model)", status:"full",
statusNote:"Full chapter on file.",
one:"The governmental model frames planning as a rational, linear (with feedback) process in which politicians set goals and expert planners choose the best means. Research within it becomes policy evaluation: 'a critical friend shadowing the steps'.",
summary:["Justification comes from welfare economics: markets fail through externalities, missing markets (information), public and merit goods and monopoly (including landowners'), so the public sector intervenes in the public interest. The public interest in this view is the greatest net benefit to society, and planning is welfare optimisation.",
"In the Weberian tradition goals 'stand outside the planning process'. Politicians set ends; public administration brings 'expert knowledge to bear on the options available'. The ideal process is Lichfield et al.'s (1975) eleven steps, from problem definition to review. Four features: (1) evidence-based planning, where knowledge 'can be gathered and made available to the planning process in a positive way' (p. 22); (2) a comprehensive synthesis across all dimensions (triple bottom line, systems thinking à la McLoughlin); legitimacy 'comes from the rationality of the analysis' (p. 24); tools such as EA/SEA, CBA, MCA and GIS inform but do not decide; (3) formulation to implementation, with policy instruments (direct investment, strategic spatial planning, regulation, fiscal measures, tradeable permits, information/nudges); (4) implementation studies show how tools are used matters, planners exercise discretion and negotiate, and the politics/administration line blurs.",
"Critiques from the lecture: wicked problems (Rittel & Webber 1973), incrementalism/muddling through (Lindblom 1959), advocacy planning (Davidoff 1965). Its ideal-typical assumptions are complete information, clear agreed goals, and objective value-free decisions separated from politics. Yet 'rationality is dead but keeps showing up' (Brooks 2002): e.g. the Dutch MKBA (social cost-benefit analysis) of the toll-free Westerscheldetunnel (net welfare gain €27–39m, ratio 1.5, but 'the feeling of injustice about the toll' could not be priced)."],
concepts:[["Instrumental rationality","Choosing the most efficient means for given ends; planning = optimisation."],["Weberian separation","Politicians set goals; trained officials apply impersonal rules and expertise to choose means."],["Market failure","Externalities, missing markets, public goods, merit goods, monopoly; justifies planning (welfare economics)."],["Lichfield's 11 steps","Problem definition → decision to act → data/forecast → constraints/objectives → criteria → design → test alternatives → evaluate → decide → implement → review."],["Comprehensive synthesis","Integrating all dimensions of a problem into one balanced view; source of legitimacy."],["Evidence-based planning","'we can make policies work better if we understand how policy mechanisms bring about change' (Sanderson 2002)."],["Implementation studies","How tools are used; discretion and negotiation; goals reformulated during implementation."],["Critical friend","Research within this model mirrors the model: evaluation of steps, goals taken as given."],["MKBA","Dutch social cost-benefit analysis: compares options with a no-policy future, in euros where possible."]],
fig:`<svg viewBox="0 0 640 250" role="img" aria-label="Rational planning cycle with politics setting goals"><g font-size="11">
<rect x="230" y="8" width="180" height="36" rx="8" class="bxa"/><text x="320" y="31" text-anchor="middle" font-weight="700" font-size="12">Politics sets goals</text>
<path d="M320 44 L320 64" class="accs" stroke-width="2"/>
${["problem","goals & constraints","data + forecast","alternatives","test & evaluate (MKBA)","decide","implement","monitor & review"].map((s,i)=>{const a=-Math.PI/2+i*2*Math.PI/8,x=320+230*Math.cos(a)*0.95,y=150+75*Math.sin(a);return `<rect x="${x-62}" y="${y-13}" width="124" height="26" rx="13" class="bxi"/><text x="${x}" y="${y+4}" text-anchor="middle">${i+1}. ${s}</text>`}).join('')}
<text x="320" y="146" text-anchor="middle" font-weight="700" font-size="12">Planner = expert</text><text x="320" y="162" text-anchor="middle" class="mut">chooses means, value-free</text></g></svg>`,
cap:"Linear with feedback loops (after Lichfield et al. 1975 / CATS steps). Goals come from outside the process.",
table:{head:["Assumption","Challenged by"],rows:[["Complete, accurate information","Wicked problems (Rittel & Webber); Lindblom's bounded knowledge; Hayek's dispersed knowledge"],["Clear, agreed goals","Lindblom (means and ends chosen together); Davidoff (plural interests); Buitelaar (conflicting justice)"],["Objective, value-free, politics separate from administration","Davidoff (planners aren't neutral); implementation studies (discretion); Marxists (serves capital)"]]},
example:"Westerscheldetunnel toll: MKBA says abolishing the toll gives a net gain of €27–39m (B/C 1.5), but it cannot price the felt injustice, so politicians still decide.",
quotes:["\"the assumption is that knowledge can be gathered and made available to the planning process in a positive way, supporting decision-making\" (p. 22)","\"the legitimacy of plans and planning decisions comes from the rationality of the analysis and propositions that are put forward by planners and planning agencies\" (p. 24)","\"It becomes a critical friend shadowing the steps set out in the rational planning model\" (p. 38)"],
dims:{sa:65,rt:55,de:10,us:10,mp:10,norm:"Public interest as net welfare / efficiency; effectiveness of planning."},
exam:"Know how to RECOGNISE it in research: problem-solving, instrumentalist wording ('effectiveness', 'implementation gap', 'evidence'), the case is a planner or planning organisation, goals taken for granted, missing power/conflict."},

{id:"scott", wk:3, title:"Scott (1998/2020) The high-modernist city", cite:"Scott, J.C. (2020). Seeing Like a State, ch. 4 'The High-Modernist City: An Experiment and a Critique', pp. 103–146. Yale UP", theory:"Critique of authoritarian high modernism", status:"full",
statusNote:"Full chapter on file (from your book text).",
one:"High-modernist planning (Le Corbusier, CIAM, Brasília, Chandigarh) imposed a legible, geometric, functionally segregated order seen from above. It produced visual order but social failure, and an unplanned city at the margins. Jane Jacobs's street-level view shows real order is complex and experienced.",
summary:["High modernism = a strong belief in scientific and technical progress, rational design of the social order, and state power to impose it (with a weak civil society). Le Corbusier's 'total city planning': a tabula rasa, geometry and standardisation (right angles, the straight line), strict functional segregation (work, home, leisure, traffic), and 'rule by the plan, the planner, and the state': the plan is to be imposed, with no consultation. He saw the city from the air; the plan was a utopian project, legible and easy to police.",
"Brasília (Costa and Niemeyer, under Kubitschek) is 'the closest thing we have to a high-modernist city'. It was built from zero on state land as a 'utopian miniaturization' meant to transform Brazil. Residents got 'brasilite': no street corners, no crowds, uniform superquadra blocks, disorientation. Legibility for administrators meant confusion for residents. By 1980, 75% of the population lived in unplanned settlements; the planned city depended on the unplanned one ('symbiotic'). Chandigarh (Le Corbusier) repeated this: monumental axes, empty squares, hawkers banned.",
"Jacobs (1961) critiques from street level: visual order ≠ experienced order; function, not surface regularity, defines order; mixed use and complexity ('cross-use') are functionally superior; single-use zoning simplifies for planners. Planning as 'urban taxidermy': cities treated as works of art instead of living systems. Scott's wider point (ch. 9) is that high modernism ignores practical, local knowledge (mētis)."],
concepts:[["High modernism","Faith in science/technology and state power to rationally redesign society and space."],["Legibility","Making society readable and controllable from the centre through simplification and standardisation."],["Functional segregation","Separating work, housing, leisure and traffic into zones."],["Utopian miniaturisation","Building a model city from scratch to demonstrate a new society."],["Brasilite","Residents' 'disease' of anonymity and missing street life in Brasília."],["Unplanned Brasília","Squatter and satellite settlements housing most people, symbiotic with the planned core."],["Visual vs experienced order","Jacobs: tidy geometry ≠ a well-functioning, lived environment."],["Mētis","Practical, local, experience-based knowledge high modernism ignores."]],
fig:`<svg viewBox="0 0 620 240" role="img" aria-label="Planned Brasília core and unplanned periphery"><g font-size="11">
<circle cx="200" cy="125" r="95" class="bxa" fill-opacity=".35"/><circle cx="200" cy="125" r="40" class="bxi"/><text x="200" y="122" text-anchor="middle" font-weight="700" font-size="12">Plano Piloto</text><text x="200" y="138" text-anchor="middle" class="mut">legible, geometric</text>
${[[70,40],[330,50],[340,200],[60,210],[200,20],[20,125],[380,125]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="16" class="bxw"/>`).join('')}
<text x="200" y="232" text-anchor="middle" class="mut">satellite / squatter towns (75% of residents by 1980)</text>
<text x="420" y="60" font-weight="700" font-size="12">Seen from the air (Le Corbusier)</text><text x="420" y="78" class="mut">order = visual geometry</text>
<text x="420" y="130" font-weight="700" font-size="12">Seen from the street (Jacobs)</text><text x="420" y="148" class="mut">order = complex mixed use,</text><text x="420" y="163" class="mut">sidewalk life, cross-use</text></g></svg>`,
cap:"Scott: the cost of order at the centre required an unplanned city at the margins.",
example:"Dutch post-war 'wijkgedachte' neighbourhoods (Bijlmermeer: high-rise, separated traffic levels) are a local high-modernist case, and its 1990s partial demolition a Jacobs-style correction.",
quotes:["\"the cost of this kind of order and legibility at the center of the plan virtually required that it be sustained by an unplanned Brasília at the margins. The two Brasílias were not just different; they were symbiotic.\"","\"there is no necessary correspondence between the tidy look of geometric order on one hand and systems that effectively meet daily needs on the other\" (on Jacobs)"],
dims:{sa:40,rt:60,de:70,us:80,mp:80,norm:"Scott's own view: respect for local practical knowledge, livability, humility about state planning."},
exam:"Careful: high modernism itself is universal/monist/deliberate; Scott's critique of it is situated/pluralist (mētis) and shows emergent, unplanned outcomes. An MCQ may ask about either."},

{id:"davoudi", wk:3, title:"Davoudi (2006) Evidence-based planning: rhetoric and reality", cite:"Davoudi, S. (2006). DisP – The Planning Review, 42(165), 14–24", theory:"Post-positivist critique of evidence-based policy", status:"missing",
statusNote:"NOT on file. Your seminar team led this article on 24 Sept, so you probably have it: upload it and I'll check this card. Built from the lecture/exit ticket plus my knowledge of the paper.",
one:"The 'evidence-based' turn in (UK New Labour) policy assumes a linear, rational link from research to decision. In planning, evidence is contested, value-laden and used selectively, so we should speak of evidence-informed planning and recognise knowledge use as an interactive, 'enlightenment' process.",
summary:["Evidence-based policy became a mantra ('what matters is what works') and revived the rational model's hope that better knowledge produces better decisions. Davoudi questions this: the rhetoric assumes a hierarchy of evidence with quantitative, generalisable research at the top and a direct, instrumental use of research in decisions.",
"In reality planning deals with contested values and wicked problems; evidence can become 'policy-based evidence', gathered to justify decisions already made. Research influences policy in several ways (after Weiss): instrumental/problem-solving, but more often conceptual or enlightenment (gradually changing how problems are framed), interactive and political/tactical.",
"She argues for evidence-informed rather than evidence-based planning, a broader, pluralist notion of what counts as evidence, and attention to how knowledge is interpreted in practice. The lecture and exit ticket add Hoch's image, which Davoudi uses: planners do not uncover facts like geologists, but, like lawyers, organise facts as evidence within arguments. That is a post-positivist position."],
concepts:[["Evidence-based planning/policy","The rational-model hope that research evidence directly determines 'what works'."],["Policy-based evidence","Evidence selected or produced to justify a decision already made."],["Evidence-informed planning","Evidence as one input among values, politics and judgement."],["Instrumental vs enlightenment use","Direct problem-solving use vs gradual reframing of how problems are understood (Weiss)."],["Planners as lawyers (Hoch)","Organising facts as evidence in arguments, not discovering facts like geologists."]],
fig:`<svg viewBox="0 0 620 200" role="img" aria-label="Linear versus interactive model of evidence use"><g font-size="12">
<text x="20" y="22" font-weight="700">Rhetoric: linear model</text>
${["research","evidence","decision","outcome"].map((s,i)=>`<rect x="${20+i*150}" y="34" width="110" height="34" rx="6" class="bxi"/><text x="${75+i*150}" y="56" text-anchor="middle">${s}</text>${i<3?`<path d="M${130+i*150} 51 L${170+i*150} 51" class="ln" stroke-width="2"/>`:''}`).join('')}
<text x="20" y="110" font-weight="700">Reality: interactive, value-laden</text>
<circle cx="310" cy="150" r="30" class="bxa"/><text x="310" y="154" text-anchor="middle" font-size="11">decision</text>
${[["research",130,130],["values",200,185],["politics",430,185],["local knowledge",500,130],["interests",310,105]].map(([s,x,y])=>`<rect x="${x-55}" y="${y-14}" width="110" height="28" rx="14" class="bx"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="11">${s}</text><line x1="${x}" y1="${y}" x2="310" y2="150" class="ln" stroke-dasharray="3 3"/>`).join('')}</g></svg>`,
cap:"From evidence-based to evidence-informed.",
example:"A municipality commissions a housing-demand study after it has already chosen a location: policy-based evidence.",
quotes:[],
dims:{sa:null,rt:null,de:null,us:70,mp:70,norm:"Legitimate, transparent use of knowledge; humility about evidence."},
exam:"Positions Davoudi as a critic of the rational model's knowledge assumptions (post-positivist), not as an opponent of evidence as such."},

{id:"alex", wk:3, title:"Alexander: after rationality (contingency theory)", cite:"Alexander, E.R. (2017/orig. 1990s). After Rationality: Towards a Contingency Theory for Planning · + his 2000 definition of rationality in the 22 Sept lecture", theory:"Rationality debate / contingency theory", status:"full",
statusNote:"Chapter on file (the PDF's text layer was scrambled; I decoded it, so punctuation and numbers are lost, but the argument is readable). Note: this chapter is not listed in the syllabus week plan.",
one:"Rationality has broken down as planning's single paradigm, but nothing has replaced it. Alexander proposes a contingency framework: classic rationality (individual deliberation) and Habermas's communicative action (interaction) are mirror images, each valid in its own domain.",
summary:["Rationality plays two roles: a descriptive model (explaining decisions as if actors are rational) and a normative paradigm (analytic standard and prescription), and it remains the basis of planners' claims to expertise.",
"Responses to its breakdown: ritual (keep using it with token acknowledgment of anomalies), avoidance (swap in descriptive models such as Simon's satisficing or Lindblom's disjointed incrementalism), abandonment (drop process models for intuition, or for a substantive ideology such as neo-Marxism or public choice) and search (new paradigms, contingency models). The procedural-vs-substantive debate is sterile: it is really about level of abstraction (two dimensions: procedural↔structural focus; concrete↔abstract).",
"Critical theory/TCA (Habermas) adds reflexive consciousness and the shift from decision to interaction, but it is normative, procedural, and ignores the pre-interactive deliberation by which actors decide what to pursue. Most real interaction is strategic, not communicative. Rationality ignores interaction; TCA ignores deliberation. 'One paradigm cannot supplant another', so a contingency framework combines them.",
"Lecture use: rationality is 'no more than a more sophisticated word for reason' (Alexander 2000, 4): having reasons (linking means to ends) and giving reasons (justification). The midterm example question also quotes Alexander's institutional design: 'the deliberate creation of institutions by planners to achieve politically defined societal goals', which Moroni criticises (week 4)."],
concepts:[["Rationality (Alexander 2000)","Having reasons (means-ends) + giving reasons (justification)."],["Four responses","Ritual · avoidance · abandonment · search."],["Contingency theory","Different models are valid under different conditions; a framework assigns domains."],["Communicative vs strategic action","Oriented to consensus through argument vs to success through power and manipulation."],["Institutional design (Alexander 2005)","Devising rules, procedures and organisational structures to achieve held values/objectives; at macro, meso and micro levels."]],
fig:`<svg viewBox="0 0 620 170" role="img" aria-label="Rationality and communicative action as mirror images"><g font-size="12">
<rect x="20" y="30" width="260" height="110" rx="10" class="bxi"/><text x="150" y="55" text-anchor="middle" font-weight="700">Classic rationality</text><text x="150" y="78" text-anchor="middle" class="mut" font-size="11">individual deliberation</text><text x="150" y="96" text-anchor="middle" class="mut" font-size="11">utilitarian consequences</text><text x="150" y="120" text-anchor="middle" class="acc" font-size="11">misses: interaction</text>
<rect x="340" y="30" width="260" height="110" rx="10" class="bxg"/><text x="470" y="55" text-anchor="middle" font-weight="700">Communicative action</text><text x="470" y="78" text-anchor="middle" class="mut" font-size="11">interaction, consensus</text><text x="470" y="96" text-anchor="middle" class="mut" font-size="11">normative, procedural</text><text x="470" y="120" text-anchor="middle" class="acc" font-size="11">misses: deliberation</text>
<text x="310" y="90" text-anchor="middle" font-size="20">⇄</text><text x="310" y="162" text-anchor="middle" class="mut" font-size="11">contingency framework = assign each its domain</text></g></svg>`,
cap:"Each paradigm focuses on exactly what the other neglects.",
example:"A municipality internally ranks options with an MCA (deliberation, rational), then negotiates with developers and residents (interaction, strategic or communicative).",
quotes:["\"One paradigm cannot supplant another\""],
dims:null,
exam:"Know the midterm sample: a sociological institutionalist critiques Alexander's institutional design by saying institutions are embedded in cultural norms and cognitive scripts that shape planners' own perceptions (answer B)."},

{id:"rc", wk:3, title:"Rational choice & self-interest (lecture) + Coase", cite:"Lecture 24 Sept (Bouwmeester): rational choice, property rights, rent-seeking, Airbnb, Coase (1960), Gurran et al. (2018)", theory:"Rational choice theory", status:"full",
statusNote:"Lecture slides on file. Needham, Hindmoor and Taylor have their own cards.",
one:"All actors (citizens, developers, municipalities) maximise self-interest; property rights and institutions shape their incentives. Planning faces both market failure and state failure, and can work by clarifying rights and cutting transaction costs.",
summary:["Rational-comprehensive planning is an ideal standard for planning decisions (expert, value-free welfare optimisation). Rational choice theory is an analytical framework for how planning works: rational decision-making by ALL actors, market and state failure, emulating market rationality in state processes.",
"Public interest has no objective, universal goal; it is the aggregate of private interests (agency-focused). Land-use planning is limited: landowners have a de facto veto ('Land-use planning will only succeed if it can influence private decisions', Needham 2012, p. 24). Rent = income from owning land above the cost of production (Ricardo). Asymmetry: when planning raises land values owners keep the betterment; when it lowers them (downzoning, heritage, regulatory takings) they claim compensation. Landowner strategies (Rijnenburg, Buitelaar et al. 2025): framing ('low-hanging fruit'), collaborating (consortium), lobbying, negotiating. Swiss hypothesis: the peasant land law bars outsiders buying farmland and caps price gains, so there is no speculative expansion lobby and insiders gain from densification.",
"Airbnb: incentives differ (hosts, guests, neighbours, planners). Under-regulation is a collective action problem (Olson): small concentrated interests organise; large diffuse groups free-ride. Regulation (Utrecht 2018: 60 nights, guest cap, registration, fines €150–€21,750) suffers from enforcement, data, transaction costs, legal challenges and waterbed effects. Coase (1960): with clearly defined property rights and zero transaction costs, bargaining yields the efficient outcome regardless of who holds the right. Since transaction costs are never zero (information, bargaining, enforcement, holdouts, many parties), design Coasean interventions: clarify rights and cut transaction costs (tradable hosting permits, VvE negotiation, hosting tax into a neighbourhood fund, platform monitoring).",
"Core assumptions: self-interest maximisation (not only economic); applies to all actors; property rights/institutions shape incentives and can be deliberately changed; outcomes judged in costs and benefits; knowledge mostly positivist (models, game theory, CBA). Can explain reproduction (insiders protect interests) and transformation (deliberate redesign of rules). Critiques: over-simple human model, ignores power and inequality, too agency-focused, limiting assumptions, reverse nirvana fallacy."],
concepts:[["Self-interest","Actors weigh costs and benefits to pursue their own interests (not only money)."],["State failure","Government also fails: rent-seeking, capture, information and incentive problems."],["Externality","Effect of one actor's action on others not reflected in prices (noise, safety, housing pressure)."],["Collective action problem","Individually rational free-riding leads to collectively suboptimal outcomes."],["Coase theorem","Clear property rights + zero transaction costs → efficient bargaining outcome, whoever holds the right."],["Transaction costs","Information, bargaining, enforcement, strategic behaviour (holdouts), many parties."],["Rent / rent-seeking","Unearned income from land; efforts to capture it via the political process."],["Betterment / compensation asymmetry","Owners keep planning gains but claim planning losses."],["Regulatory taking","Public regulation that reduces the value of private property."]],
fig:`<svg viewBox="0 0 620 210" role="img" aria-label="Coase noisy factory example"><g font-size="12">
<text x="20" y="20" font-weight="700">Coase: the noisy factory (quiet worth €1,000; insulation costs €700)</text>
<rect x="20" y="36" width="280" height="130" rx="8" class="bxi"/><text x="160" y="58" text-anchor="middle" font-weight="700">Right to make noise: factory</text><text x="160" y="84" text-anchor="middle" font-size="11">homeowner pays factory €700</text><text x="160" y="102" text-anchor="middle" font-size="11">→ factory insulates</text><text x="160" y="140" text-anchor="middle" class="acc" font-weight="700">insulation ✓</text>
<rect x="320" y="36" width="280" height="130" rx="8" class="bxg"/><text x="460" y="58" text-anchor="middle" font-weight="700">Right to quiet: homeowner</text><text x="460" y="84" text-anchor="middle" font-size="11">compensation €1,000 &gt; €700</text><text x="460" y="102" text-anchor="middle" font-size="11">→ factory insulates</text><text x="460" y="140" text-anchor="middle" class="acc" font-weight="700">insulation ✓</text>
<text x="20" y="195" class="mut" font-size="11">Same efficient outcome; only who pays whom differs. Only if transaction costs = 0.</text></g></svg>`,
cap:"Coase's claim from the lecture example.",
example:"Airbnb in Amsterdam: hosts form a small, concentrated, organised interest; neighbours are a large, diffuse group who free-ride, so regulation lags.",
quotes:["\"Property rights can be deliberately changed in order purposefully to influence land use.\" (Needham, p. 28)","\"Landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill.\" (Taylor, p. 272)"],
dims:{sa:85,rt:50,de:25,us:15,mp:15,norm:"Efficiency; public interest = aggregate of individual interests."},
exam:"Midterm sample Q2 answers: I = False (large groups fail to organise: free riding), II = True (Olson), III = True (lower transaction costs), IV = False (no objective public interest)."},

{id:"needham", wk:3, title:"Needham (2016) Interests and rights in property", cite:"Needham, B. (2016). Interests and rights in property, and their place in land-use planning: a theoretical investigation. In Planning by Law and Property Rights Reconsidered, pp. 23–36. Routledge", theory:"Rational choice / institutional economics of property", status:"slides",
statusNote:"Chapter NOT on file. Built from the lecture (quotes p. 24 via Needham 2012 and p. 28) plus my knowledge of Needham's work; check it against the text.",
one:"Land-use planning works through property rights: it only succeeds if it influences private owners' decisions. Rights are institutions that can be deliberately changed to steer land use.",
summary:["Property is a bundle of rights (use, exclude, transfer, derive income) held by various parties. People have interests in land (what they want) and rights (what they are entitled to do). Public land-use planning is the state restricting or redistributing these rights through public law.",
"The state plays a dual role (lecture slide): it defines and protects private property rights, AND it pursues public policies whose target groups are owners and whose end-beneficiaries are often non-owners. Because owners can simply not develop (a de facto veto), 'land-use planning will only succeed if it can influence private decisions'.",
"Since rights shape incentives, 'property rights can be deliberately changed in order purposefully to influence land use' (p. 28): a rational-choice/institutional view where institutions are external rules affecting cost-benefit calculations, and change is deliberate (transformation)."],
concepts:[["Bundle of rights","Property as separable rights: use, exclusion, transfer, income."],["Interests vs rights","What actors want vs what they are legally entitled to."],["Dual role of the state","Guarantor of private rights and actor pursuing public goals through them."],["Veto of landowners","Planning permits but can't force development."]],
fig:`<svg viewBox="0 0 560 200" role="img" aria-label="Dual role of the state matrix"><g font-size="12">
<rect x="120" y="30" width="200" height="70" class="bxi"/><rect x="320" y="30" width="200" height="70" class="bx"/><rect x="120" y="100" width="200" height="70" class="bxg"/><rect x="320" y="100" width="200" height="70" class="bxa"/>
<text x="220" y="20" text-anchor="middle" font-weight="700">Owners</text><text x="420" y="20" text-anchor="middle" font-weight="700">Non-owners</text><text x="110" y="70" text-anchor="end" font-weight="700">Private</text><text x="110" y="140" text-anchor="end" font-weight="700">Public</text>
<text x="220" y="70" text-anchor="middle">property rights</text><text x="420" y="70" text-anchor="middle" class="mut">—</text><text x="220" y="134" text-anchor="middle">target groups</text><text x="220" y="150" text-anchor="middle" class="mut" font-size="11">(of policy)</text><text x="420" y="134" text-anchor="middle">end-beneficiaries</text><text x="420" y="150" text-anchor="middle" class="mut" font-size="11">(of policy)</text>
<text x="20" y="192" class="mut" font-size="11">The state protects owners' rights and uses policy on owners to benefit others (lecture slide).</text></g></svg>`,
cap:"State property rights vs state policies.",
example:"Dutch 'kostenverhaal' and pre-emption rights (Wvg) redefine what landowners can do so the municipality can steer development.",
quotes:["\"Property rights can be deliberately changed in order purposefully to influence land use.\" (p. 28)"],
dims:{sa:75,rt:65,de:20,us:15,mp:15,norm:"Efficient, effective land use; balancing public goals with private rights."},
exam:"Needham shows that rational choice can explain transformation (deliberate change of rights), while Taylor shows reproduction by insiders."},

{id:"olson", wk:3, title:"Hindmoor (2006) Mancur Olson and The Logic of Collective Action", cite:"Hindmoor, A. (2006). Rational Choice, ch. 5. Basingstoke: Palgrave", theory:"Rational choice (public choice)", status:"slides",
statusNote:"Chapter NOT on file. Built from the lecture's Olson slides plus my knowledge of Olson/Hindmoor; please upload it.",
one:"Rational individuals won't contribute to a collective good they get anyway, so large, diffuse groups fail to organise while small, concentrated groups succeed, unless selective incentives or coercion exist.",
summary:["Olson overturned pluralist group theory, which assumed that people with a shared interest would organise to pursue it. If a collective good benefits all group members whether or not they contribute, the rational individual free-rides. The larger the group, the smaller each member's share and the less noticeable each contribution, so large ('latent') groups are under-organised.",
"Small ('privileged') groups, in which at least one member gains enough to provide the good alone, or where contributions are noticeable, organise more easily. Hence the 'exploitation of the great by the small' and the outsized influence of concentrated interests (landowners, developers, platform hosts) versus diffuse ones (tenants, neighbours, taxpayers).",
"Large groups can organise through selective incentives (private benefits only for members, the 'by-product theory', e.g. insurance via a union) or coercion (compulsory membership). Hindmoor discusses the critiques: people do participate for moral or expressive reasons, and political entrepreneurs can lower costs."],
concepts:[["Collective (public) good","Non-excludable benefit for all group members."],["Free-riding","Enjoying the good without contributing."],["Latent vs privileged group","Large diffuse group that won't organise vs small group that will."],["Selective incentives","Private rewards/sanctions that make contribution individually rational."],["Exploitation of the great by the small","Small groups carry the cost and gain, large groups get the policy they didn't fight for (or lose)."]],
fig:`<svg viewBox="0 0 560 200" role="img" aria-label="Group size versus likelihood of organising"><g font-size="11">
<line x1="60" y1="160" x2="520" y2="160" class="ln" stroke-width="1.5"/><line x1="60" y1="160" x2="60" y2="20" class="ln" stroke-width="1.5"/>
<path d="M60 35 C 200 45, 280 120, 510 150" class="accs" fill="none" stroke-width="3"/>
<text x="290" y="185" text-anchor="middle">group size / diffuseness →</text><text x="20" y="90" transform="rotate(-90 20 90)" text-anchor="middle">likelihood of organising</text>
<circle cx="90" cy="38" r="6" class="fg"/><text x="102" y="42">5 landowners</text><circle cx="470" cy="147" r="6" class="fw"/><text x="462" y="135" text-anchor="end">20,000 tenants</text></g></svg>`,
cap:"Illustrative curve: the logic of collective action.",
example:"Five landowners at the urban fringe finance a lobbyist; thousands of renters who would gain from lower land prices never organise.",
quotes:[],
dims:{sa:85,rt:25,de:30,us:15,mp:15,norm:"Efficiency; exposes why the 'public interest' is captured by organised minorities."},
exam:"Directly tested in sample Q2 (statements I and II)."},

{id:"taylor", wk:3, title:"Taylor (2016) Urban growth boundaries and betterment: rent-seeking in Melbourne", cite:"Taylor, E.J. (2016). Growth and Change, 47(2), 259–275. doi:10.1111/grow.12110", theory:"Rational choice (rent-seeking)", status:"slides",
statusNote:"Article NOT on file. Built from the lecture slides (p. 272 quote) plus my knowledge of the case; please upload it.",
one:"When Melbourne expanded its urban growth boundary and introduced a betterment levy (GAIC), landowners behaved as rational rent-seekers: those inside tried to keep restrictions and scarcity, those outside lobbied to be included and to weaken the levy, and they succeeded in modifying the bill.",
summary:["An urban growth boundary (UGB) creates a sharp land-value jump at the line: zoning land urban creates windfall betterment for owners. Victoria expanded the UGB (2010s) and introduced the Growth Areas Infrastructure Contribution (GAIC) to capture part of that uplift for infrastructure.",
"Taylor analyses the 'rational behaviour' of existing owners: (1) those who aim to preserve restrictions on growth (keeping scarcity rents), and (2) those who try to avoid controls limiting future development or to get their land included. Both are rational from a rent-seeking perspective.",
"'Landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill' (p. 272): concentrated interests shaping value-capture rules, a clear case of reproduction of owners' advantages."],
concepts:[["Urban growth boundary","Line separating land where urban development is allowed from where it isn't."],["Betterment","Land-value increase caused by public action (rezoning, infrastructure)."],["GAIC","Victoria's betterment levy on land brought inside the UGB."],["Rent-seeking","Using political influence to capture unearned land rents."]],
fig:`<svg viewBox="0 0 560 190" role="img" aria-label="Land value jump at the urban growth boundary"><g font-size="11">
<line x1="50" y1="150" x2="520" y2="150" class="ln"/><line x1="50" y1="150" x2="50" y2="20" class="ln"/>
<path d="M50 40 L260 70 L260 135 L520 140" class="accs" fill="none" stroke-width="3"/>
<line x1="260" y1="20" x2="260" y2="150" class="ln" stroke-dasharray="4 4"/><text x="260" y="170" text-anchor="middle" font-weight="700">UGB</text>
<text x="150" y="60">urban-zoned: high value</text><text x="390" y="128">rural: agricultural value</text>
<text x="270" y="100" class="acc">betterment gap</text><text x="30" y="90" transform="rotate(-90 30 90)" text-anchor="middle">land value</text></g></svg>`,
cap:"Illustrative: the gap at the line is the rent landowners fight over.",
example:"Rijnenburg (Utrecht): developer-owned land was framed as 'low-hanging fruit' for housing, lobbying against the energy-landscape vision.",
quotes:["\"Landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill.\" (p. 272)"],
dims:{sa:85,rt:25,de:30,us:15,mp:15,norm:"Implicit: capture betterment for the public, and expose rent-seeking."},
exam:"Links to Sorensen: both study land value capture, Taylor through actor incentives (RC), Sorensen through institutional history (HI)."},

/* ================= WEEK 4 ================= */
{id:"ni", wk:4, title:"Neo-institutionalism: the map", cite:"Hall & Taylor (1996) typology as adapted by Dembski & Salet (2010), Table 1 · lecture 29 Sept (Bouwmeester), slides not yet uploaded", theory:"New institutionalism", status:"partial",
statusNote:"Built from Dembski & Salet's Table 1 (on file). Tomorrow's lecture slides (29 Sept) aren't uploaded yet; add them and I'll update this card.",
one:"Institutions = patterns of social rules ('rules of the game'). Schools differ on whether institutions are external constraints or internalised, and whether they exist prior to action or are validated in action.",
summary:["The 'new institutionalism' (March & Olsen 1989; Powell & DiMaggio 1991) is not unified. Institutions are 'patterns of social rules' that enable collective action in a world of individual choices (Dembski & Salet), 'the rules of the game… humanly devised constraints' (North 1990), or for planning 'collectively enforced rules and expectations with respect to the creation, management, and use of urban space and property' (Sorensen 2015).",
"Four quadrants: rational choice institutionalism (external, prior to action: transaction costs, collective action dilemmas, homo economicus; North, Williamson, Buchanan & Tullock); historical institutionalism (internal, prior to action: path dependency, critical junctures; Pierson, Thelen, Mahoney); actor-centred/political institutionalism (external, in action: Ostrom, Scharpf, Mayntz; policy learning); sociological institutionalism (internal, in action: culture, legitimacy, logic of appropriateness; Berger & Luckmann, Bourdieu, March & Olsen, Scott).",
"Institutions ≠ organisations: institutions are the rules of the game, organisations the players (North; Moroni). Moroni adds an evolutionary (Hayekian) view: most institutions are the unintended result of human action, not human design."],
concepts:[["Institution","Pattern of social rules; formal (laws) or informal (norms, conventions)."],["Organisation","Purposeful arrangement of resources to achieve goals: the players, not the rules."],["Path dependency","Earlier choices constrain later ones; reversing course gets costlier (positive feedback)."],["Critical juncture","Short period with heightened probability that agents' choices shape lasting outcomes."],["Logic of appropriateness","Acting because it is normal/legitimate, not because it maximises utility (March & Olsen)."],["Transaction costs","Costs of exchange that institutions reduce (Williamson, North)."]],
fig:`<svg viewBox="0 0 600 270" role="img" aria-label="Two by two typology of institutionalisms"><g font-size="12">
<text x="250" y="20" text-anchor="middle" font-weight="700">Externalised</text><text x="470" y="20" text-anchor="middle" font-weight="700">Internalised</text>
<text x="110" y="95" text-anchor="end" font-weight="700">Prior to</text><text x="110" y="111" text-anchor="end" font-weight="700">action</text><text x="110" y="205" text-anchor="end" font-weight="700">In action</text>
<rect x="140" y="32" width="220" height="110" class="bxi"/><text x="250" y="60" text-anchor="middle" font-weight="700">Rational choice inst.</text><text x="250" y="80" text-anchor="middle" class="mut" font-size="11">North, Williamson</text><text x="250" y="100" text-anchor="middle" font-size="11">transaction costs,</text><text x="250" y="116" text-anchor="middle" font-size="11">collective action dilemmas</text>
<rect x="360" y="32" width="220" height="110" class="bxw"/><text x="470" y="60" text-anchor="middle" font-weight="700">Historical inst.</text><text x="470" y="80" text-anchor="middle" class="mut" font-size="11">Pierson, Thelen · Sorensen</text><text x="470" y="100" text-anchor="middle" font-size="11">path dependency,</text><text x="470" y="116" text-anchor="middle" font-size="11">critical junctures</text>
<rect x="140" y="142" width="220" height="110" class="bx"/><text x="250" y="170" text-anchor="middle" font-weight="700">Actor-centred inst.</text><text x="250" y="190" text-anchor="middle" class="mut" font-size="11">Ostrom, Scharpf</text><text x="250" y="210" text-anchor="middle" font-size="11">policy learning,</text><text x="250" y="226" text-anchor="middle" font-size="11">actors' strategies</text>
<rect x="360" y="142" width="220" height="110" class="bxg"/><text x="470" y="170" text-anchor="middle" font-weight="700">Sociological inst.</text><text x="470" y="190" text-anchor="middle" class="mut" font-size="11">Berger &amp; Luckmann, Bourdieu</text><text x="470" y="210" text-anchor="middle" font-size="11">culture, legitimacy,</text><text x="470" y="226" text-anchor="middle" font-size="11">Dembski &amp; Salet sit here</text></g></svg>`,
cap:"Dembski & Salet (2010) Table 1. Moroni's evolutionary view cuts across it (emergent, Hayekian).",
example:"The Dutch 'actieve grondpolitiek' tradition, municipalities buying land, is path-dependent (HI); its erosion after 2008 is a possible critical juncture.",
quotes:[],
dims:null,
exam:"Sample Q1: Alexander's deliberate institutional design critiqued by a sociological institutionalist → institutions embedded in cultural norms and cognitive scripts that shape planners' own perceptions (B). C = historical institutionalist, D = evolutionary (Moroni), A = actor-centred/RC."},

{id:"dembski", wk:4, title:"Dembski & Salet (2010) The transformative potential of institutions", cite:"Dembski, S. & Salet, W. (2010). Environment and Planning A, 42(3), 611–625. doi:10.1068/a42184", theory:"Sociological institutionalism", status:"full",
statusNote:"Full article on file.",
one:"Whether symbolic markers (metaphors, landmarks, events) can give new meaning to changing city-regions depends not on the symbol's design but on its institutional embedding: symbols work only if their meaning is inculcated in the audience's mental maps.",
summary:["Changing city-regions (Zwischenstadt, edge cities, métapolis) lack a crystallised identity, so planners use symbolic markers (Flemish Diamond, Pearl River Delta, Guggenheim Bilbao, IBA Emscher Park) to frame change and mobilise actors. Most fail. Central question: why does symbolisation of new urban spaces strengthen social meaning in some cases, while elsewhere symbols remain powerless or even backfire? Communicative/interpretive planning studies the symbol itself; the authors look for the answer in institutions.",
"They reject the view that institutions are 'rusty old fixtures' that only explain preservation, and position themselves with two choices (Table 1): institutions as internalised in actors' mindsets (not external constraints) and as validated in action (not fixed prior to action), which places them in sociological institutionalism. Institutions are the 'chance' of validating rules (Weber) and must be confirmed again and again in everyday practice: 'Institutions are not carved in stone.'",
"Theory: Berger & Luckmann (habitualisation, reciprocity of expectations), Bourdieu (habitus: practice informed by structure, the card-game metaphor; 'instituting'; rites of institution consecrate arbitrary boundaries and produce discontinuity out of continuity: 'Become what you are'), Geertz (symbols 'saying something of something'; the Balinese cockfight), Paasi (regional identity has an internal and an external side), Billig (banal nationalism). Symbolic markers cannot be used in a voluntaristic way: 'institutional transformation is deliberate change', yet it needs a sound notion of existing norms. The art of planning is finding under-institutionalised niches or institutional voids (Hajer).",
"Methodology (Box 1): 8 steps: (1) symbolic markers; (2) encoded message; (3) subjective context (who symbolises, legitimacy); (4) objective context (social structure, habitus: are symbols genuine?); (5) audience; (6) process of articulation over time; (7) internalisation of symbolic meaning; (8) sanctions for misrecognition."],
concepts:[["Symbolic marker","Metaphor, landmark, event or design used to frame and mobilise change."],["Institutional embedding","Symbols' meaning anchored in internalised social norms; the condition for their efficacy."],["Internalised vs external institutions","In people's mental maps/habitus vs outside constraints on choice."],["Validated in action","Institutions must be reaffirmed in each practice; meaning is never fixed."],["Habitus (Bourdieu)","Durable dispositions: structure internalised, informing but not determining practice."],["Rites of institution","Consecrating an arbitrary boundary so that representation changes reality ('social magic')."],["Inculcation","The audience absorbing and guaranteeing a symbol's meaning."],["Institutional void","Under-institutionalised space where new practices can take root (Hajer)."]],
fig:`<svg viewBox="0 0 620 230" role="img" aria-label="Why symbolic markers succeed or fail"><g font-size="12">
<rect x="20" y="30" width="150" height="54" rx="8" class="bxa"/><text x="95" y="54" text-anchor="middle" font-weight="700">Symbolic marker</text><text x="95" y="72" text-anchor="middle" class="mut" font-size="11">'Flemish Diamond'</text>
<path d="M170 57 L240 57" class="ln" stroke-width="2"/>
<rect x="240" y="20" width="160" height="74" rx="8" class="bxg"/><text x="320" y="44" text-anchor="middle" font-weight="700">Institutionally</text><text x="320" y="60" text-anchor="middle" font-weight="700">embedded?</text><text x="320" y="80" text-anchor="middle" class="mut" font-size="11">inculcated by audience</text>
<path d="M400 45 L460 30" class="ln" stroke-width="2"/><path d="M400 70 L460 110" class="ln" stroke-width="2"/>
<rect x="460" y="12" width="150" height="40" rx="8" class="bxg"/><text x="535" y="37" text-anchor="middle">yes → new meaning</text>
<rect x="460" y="92" width="150" height="40" rx="8" class="bx"/><text x="535" y="117" text-anchor="middle">no → powerless</text>
<text x="20" y="160" font-weight="700">Not decisive: the design quality, rhetoric or 'pearls of rhetoric' of the symbol itself.</text>
<text x="20" y="182" class="mut" font-size="11">Decisive: are the transmitters legitimate 'knowers'? does it fit existing norms? does the audience believe it (inside AND outside)?</text>
<text x="20" y="204" class="mut" font-size="11">Bilbao still isn't a cultural city; Green Heart works, but it aims at preservation, not transformation.</text></g></svg>`,
cap:"The paper's core causal claim.",
table:{head:["Step","Question"],rows:[["1 Symbolic markers","Which linguistic/material markers?"],["2 Encoded message","What social patterns do they symbolise (past, transformation, past bent to the future)?"],["3 Subjective context","Who symbolises, and are they legitimate?"],["4 Objective context","What social structure is reproduced; are symbols genuine?"],["5 Audience","Who is addressed?"],["6 Articulation","How do meanings change over time; who contests?"],["7 Internalisation","How is meaning inculcated, habituated, consecrated?"],["8 Sanctions","What happens on misrecognition, and who sanctions?"]]},
example:"'Brainport Eindhoven' as a marker works because it rests on embedded Philips/ASML industrial practices and identity; a 'Silicon Polder' label on a random business park would not.",
quotes:["\"It is in the institutional embedding in the mental maps of humankind that the success or failure of symbolic communication lies.\"","\"Institutions are not carved in stone.\"","\"Symbolic markers cannot be used in a voluntaristic manner. Institutional transformation is deliberate change.\""],
dims:{sa:45,rt:85,de:40,us:80,mp:70,norm:"Meaningful, legitimate transformation of city-regions; social mobilisation."},
exam:"Key identifiers: 'internalised', 'validated in action', 'habitus', 'logic of appropriateness', 'symbols', 'meaning' → sociological institutionalism. Emphasis on transformation, not path dependency."},

{id:"moroni", wk:4, title:"Moroni (2010) An evolutionary theory of institutions and a dynamic approach to reform", cite:"Moroni, S. (2010). Planning Theory, 9(4), 275–297. doi:10.1177/1473095210368778", theory:"Evolutionary institutionalism (Hayekian / liberal)", status:"full",
statusNote:"Full article on file.",
one:"Planning's institutional turn is right, but many planners treat institutions 'engineeristically', as objects to design. Institutions mostly evolve unintentionally and embody dispersed knowledge, so reform should be kosmos-oriented: modest, gradual, open, general rules.",
summary:["Taxis-oriented approach = the engineer's method applied to society (complete problem, one goal, all knowledge). It fails because social problems are 'incomplete' and involve practical, tacit knowledge (Oakeshott). A first-order taxis approach plans activities (end-state land-use plans). A second-order one redesigns institutions themselves for specific goals, and it lurks in the planning literature's institutional turn (e.g. Alexander's 'institutional design', Bolan).",
"Institutions ≠ organisations: institutions are basic rules of conduct acknowledged by a community and enforced by sanctions (rules of the game); organisations are systematic arrangements of resources for explicit shared goals (players) (North 1990). Institutions do two jobs: pattern-coordination of individual actions, and a fund of knowledge accumulated over generations.",
"Descriptive side: Scottish Enlightenment (Hume, Ferguson, Smith): institutions are 'the result of human action, but not the execution of any human design' (Ferguson). Evolution = variation → selection → propagation; open-ended, contingent, sub-optimal, no inevitable stages. Invisible-hand explanations (Jacobs on safe streets, Schelling on segregation). Three kinds of phenomena: natural; artificial by design (organisations); artificial but unintended (most institutions).",
"Prescriptive side: rename 'institutional design' → 'organisational design' vs 'institutional intervention'. Kosmos-oriented approach with 10 principles: peculiarity, knowability, sense-making, motivational realism, non-tabula-rasa, modesty, robustness, gradualism, adaptive efficiency (North), openness. Rather 'learn' than 'educate', 'recognize' than 'invent', 'improve' than 'reconstruct', indirect over direct intervention. 'Planning strictu senso cannot be applied to institutions.'"],
concepts:[["Taxis vs kosmos","Made, designed order vs grown, spontaneous order (Hayek)."],["First- vs second-order taxis","Designing activities (end-state plans) vs designing the institutional rules themselves."],["Institutions vs organisations","Rules of the game vs players (North)."],["Invisible-hand explanation","Order explained as the unintended outcome of dispersed actions, with an element of surprise."],["Three kinds of phenomena","Natural; artificial by design; artificial but not designed (most institutions)."],["Adaptive vs allocative efficiency","Rules that foster learning and discovery over time vs optimal allocation of known resources."],["Radical ignorance","Ignorance is ineradicable in a complex world, not just bounded rationality."],["Kosmos principles","Peculiarity, knowability, sense-making, motivational realism, non-tabula rasa, modesty, robustness, gradualism, adaptive efficiency, openness."]],
fig:`<svg viewBox="0 0 620 210" role="img" aria-label="Moroni's three kinds of phenomena"><g font-size="12">
${[[20,"Natural","no human action","weather, rivers","bx"],[220,"Artificial: designed","deliberate human design","organisations, a plan","bxi"],[420,"Artificial: undesigned","human action, not design","most institutions: property, contract, language","bxg"]].map(([x,t,s,e,c])=>`<rect x="${x}" y="30" width="180" height="120" rx="10" class="${c}"/><text x="${x+90}" y="56" text-anchor="middle" font-weight="700">${t}</text><text x="${x+90}" y="80" text-anchor="middle" class="mut" font-size="11">${s}</text><foreignObject x="${x+10}" y="92" width="160" height="54"><div xmlns="http://www.w3.org/1999/xhtml" style="font:11px/1.3 Public Sans,sans-serif;text-align:center;color:var(--ink)">${e}</div></foreignObject>`).join('')}
<text x="220" y="180" class="acc" font-weight="700">organisational design ✓</text><text x="420" y="180" class="acc" font-weight="700">only 'institutional intervention'</text><text x="420" y="198" class="mut" font-size="11">modest, gradual, general rules</text></g></svg>`,
cap:"The Greek physei / thesei / nomō distinction, made threefold after Hume, Ferguson and Smith.",
example:"Instead of a detailed zoning plan per site (taxis), a city sets simple, stable, general rules (plot coverage, nuisance rules) and lets development emerge (Oosterwold, Cozzolino).",
quotes:["\"the result of human action, but not the execution of any human design\" (Ferguson, quoted p. 278)","\"the question is not to apply planning also at the level of institutions … but to understand that planning strictu senso cannot be applied to institutions\"","\"institutions are sets of basic rules of conduct, acknowledged by a community, and usually enforced through some form of sanction; while organizations are systematic arrangements of resources for achieving explicit, shared goals\""],
dims:{sa:60,rt:30,de:90,us:65,mp:70,norm:"Liberty, peaceful coexistence, adaptive efficiency; anti-engineering humility."},
exam:"Sample Q1 option D ('emerge historically through evolutionary, trial-and-error processes that escape deliberate control') is Moroni's position, not the sociological one. Don't mix them up."},

{id:"sorensen", wk:4, title:"Sorensen (2024) Urban intensification and land value capture in Toronto", cite:"Sorensen, A. (2024). Environment and Planning A: Economy and Space, 56(6), 1803–1819. doi:10.1177/0308518X231216535", theory:"Historical institutionalism (+ conjunctural analysis)", status:"full",
statusNote:"Full article on file.",
one:"Land value capture (LVC) redistributes the costs and benefits of development; its Toronto history is a historical-institutionalist sequence of critical junctures (1946, 1989, 2019–22) followed by reactive sequences of contestation within a developmental pathway. HI adds analytical clarity to conjunctural analysis.",
summary:["Three contributions: (1) LVC is a purposeful attempt to alter the public/private distribution of development costs and benefits and should be a key metric of social equity ('growth should pay for growth'); (2) historical institutionalism (HI) complements conjunctural analysis (Gramsci → Stuart Hall → Peck; Inch & Shepherd; Leitner & Sheppard), which reads how political, economic and ideological forces 'con-join', but says little about specific institutional change; (3) the Toronto case reveals institutional change, path dependence mechanisms and how global hegemonic ideologies are translated locally.",
"Critical juncture: 'relatively short periods of time during which there is a substantially heightened probability that agents' choices will affect the outcome of interest' (Capoccia & Kelemen 2007). Sequence (Fig. 1): antecedent conditions → crisis creates permissive conditions (Soifer) → critical juncture, where productive conditions (actors, legal structures, ideology, timing) shape the choice → reactive sequence of contestation → relative stability. Both permissive and productive conditions are needed. Urban institutions are prone to CJs because of multilevel governance, disasters and constant new challenges. The planning system forms a Strategic Action Field (Fligstein & McAdam).",
"Toronto: CJ1 = the 1946 Planning Act (postwar housing crisis; subdivision agreements → lot levies spread); CJ2 = the Development Charges Act 1989 (1980s real-estate bubble) plus Section 37 density bonusing; recent CJ = Bill 108 (2019) and Bill 23 (2022, More Homes Built Faster) which cut LVC (S37 capped ~4% of uplift). 2009–18: C$490m S37 and C$2.29bn in DCs. Housing crises gave permissive conditions each time, but different productive conditions gave different outcomes (the first two enhanced LVC, the last reduced it).",
"Path dependence is usually not 'lock-in': contestation and incremental change are constant, but within a developmental pathway of bounded contestation that the critical juncture set up. Vancouver captures ~70% of uplift, Toronto negotiated 10–15%: variation comes from contingent institutional histories."],
concepts:[["Land value capture (LVC)","Public recovery of land-value uplift created by public action (DCs, density bonuses, levies, land readjustment)."],["Historical institutionalism","Institutions as historically produced, unequally distributive, contested, path-dependent."],["Conjunctural analysis","Reading the moment where multiple forces and contradictions 'con-join' (Gramsci, Stuart Hall, Peck)."],["Critical juncture","Short window of heightened agency whose choices set a lasting path."],["Permissive vs productive conditions","What opens the window (crisis) vs what shapes the outcome (actors, rules, ideology, timing)."],["Reactive sequence","Chain of contestation and refinement after a critical juncture."],["Developmental pathway","Bounded range of options within which contestation continues (path dependence without lock-in)."],["Strategic action field","Meso-level order where actors interact under shared rules and understandings."],["Section 37 / Development charges","Toronto density-bonus contributions / impact fees for growth infrastructure."]],
fig:`<svg viewBox="0 0 660 230" role="img" aria-label="Critical juncture sequence and Toronto timeline"><g font-size="11">
${[["antecedent conditions",20,"bx"],["permissive conditions (crisis)",150,"bxw"],["CRITICAL JUNCTURE + productive conditions",280,"bxa"],["reactive sequence",430,"bxi"],["relative stability",550,"bxg"]].map(([t,x,c],i)=>`<rect x="${x}" y="20" width="${i==2?140:112}" height="54" rx="8" class="${c}"/><foreignObject x="${x+4}" y="26" width="${i==2?132:104}" height="44"><div xmlns="http://www.w3.org/1999/xhtml" style="font:600 11px/1.25 Public Sans,sans-serif;text-align:center;color:var(--ink)">${t}</div></foreignObject>`).join('')}
<line x1="20" y1="150" x2="640" y2="150" class="ln" stroke-width="2"/>
${[[60,"1946","Planning Act","postwar housing crisis"],[300,"1989","DC Act + S37","80s property bubble"],[540,"2019–22","Bill 108 / 23","affordability crisis: LVC cut"]].map(([x,y,t,s])=>`<circle cx="${x}" cy="150" r="8" class="acc"/><text x="${x}" y="135" text-anchor="middle" font-family="IBM Plex Mono">${y}</text><text x="${x}" y="175" text-anchor="middle" font-weight="700">${t}</text><text x="${x}" y="191" text-anchor="middle" class="mut">${s}</text>`).join('')}
<text x="20" y="220" class="mut">Between junctures: incremental contestation (courts, OMB tribunal, legislature) within one developmental pathway.</text></g></svg>`,
cap:"Top: Sorensen's Fig. 1 logic. Bottom: the three Toronto junctures.",
example:"The Dutch 2008 crisis ended many municipalities' active land policy: a permissive condition. Whether it became a critical juncture depended on productive conditions such as the Omgevingswet and the kostenverhaal rules.",
quotes:["\"relatively short periods of time during which there is a substantially heightened probability that agents' choices will affect the outcome of interest\" (Capoccia & Kelemen, quoted)","\"In most cases path dependence is not a matter of 'lock-in' … but within a developmental pathway representing a relatively constrained range of options.\""],
dims:{sa:35,rt:45,de:45,us:40,mp:30,norm:"Social equity: fair distribution of costs and benefits of urban development."},
exam:"Identifiers of HI: path dependence, critical junctures, sequences, contestation, power-distributive institutions. Compare with the sample open question (Old Fadama): 'once actors have ventured far down a particular path… difficult to reverse course' = path dependence → (historical) institutionalism."},

/* extra */
{id:"mm", wk:2, title:"Madden & Marcuse (2016) In Defense of Housing, ch. 1", cite:"Madden, D. & Marcuse, P. (2016). In Defense of Housing, ch. 1 'The residential is political'. Verso", theory:"Marxist / critical political economy", status:"slides",
statusNote:"Scan on file (I OCR'd it) but not in the syllabus; used as an illustration in the 17 Sept lecture. This card follows the lecture quotes.",
one:"Housing problems are not market failures but 'how the market works': commodification of housing structurally produces inequality, so we need decommodified housing.",
summary:["The residential is political: the housing crisis results from the structural logic of the housing system, not from greed or dishonesty. Economic demand ≠ social need: many poor and working-class households need more housing than they can afford, and that need does not register with profit-oriented developers. Cities need more construction, but of decommodified dwellings (public, cooperative)."],
concepts:[["Commodification","Housing produced and traded for exchange value rather than use value."],["Decommodification","Removing housing from market logic (public, cooperative, non-profit)."],["Demand vs need","Effective market demand vs actual social need."]],
fig:"",cap:"",
example:"Vienna's Gemeindebau and cooperative sector as a decommodified model.",
quotes:["\"These are not market failures—they are how the market works.\""],
dims:{sa:15,rt:80,de:30,us:40,mp:40,norm:"Material equality; housing as a right."},
exam:"The progressive (Marxist) planner of the HC4 lecture, set against Glaeser & Gyourko's liberal planner."}
];
