const UPDATES = [
{id:"fw", status:"full", title:"Course framework + Rydin (2021) Introduction: Theory and planning research",
statusNote:"Full text on file: Rydin (2021) ch. 1 plus the 8 Sept lecture slides.",
one:"Theory is not optional: every definition of 'planning' already frames the object. A theory (ontology + epistemology + values) tells you what to focus on, links your case to a broader story, and lets research build theory. The course compares theories on four dimensions.",
summary:[
"Rydin (2021) writes about theory OF planning (analytic: how planning works), not normative planning theory FOR planning (how it should be done), while admitting the two are entangled: 'all research—including analytic research—is imbued with value judgements'. Even defining planning is theoretical: planning as goal-directed decision-making (instrumental, public administration, e.g. Næss & Saglie 2000) → as state action to order the environment in the collective interest → as intervention affecting diverse interests and system features. Each small shift implies a different view of the process.",
"Knowledge is more than information: it is about understanding the dynamics that produced a situation, 'a claim to know the cause of things' (rerum cognoscere causas). Research combines general understanding with a specific case. Theory can be seen as law-like (natural-science model; rejected by Flyvbjerg et al. 2012 because of complexity and Giddens' double hermeneutic) or, Rydin's view, as 'a heuristic aid to understand a situation, a way to try to know what is essentially unknowable in its completeness' (p. 9): 'a set of ideas that fit together coherently and make general statements about the world or a part of it'. Theories carry ontological, normative and epistemological positions, so the terrain of theory is contested and choosing one is a value choice.",
"Is theory necessary? Empiricism ('let the facts speak', Latour's 'modernist settlement') fails: data selection and interpretation involve value judgements, and pure empiricism gives a disparate, unconnected field. Flyvbjerg's phronesis (practical wisdom; four questions: where are we going, who gains/loses by which mechanisms of power, is it desirable, what should we do?) still relies on unacknowledged theory (double hermeneutic, praxis). Three advantages of theory: (1) it focuses attention under time/money limits; (2) it links partial findings to a broader, persuasive narrative, enabling generalisation; (3) empirical research can build and revise theory.",
"The course then compares theories on four dimensions: (1) sources of planning outcomes (structure ↔ agency); (2) reproduction and change (reproduction ↔ transformation; deliberate ↔ emergent); (3) knowledge (universal ↔ situated; monist ↔ pluralist; + realism ↔ relativism); (4) normative commitments. Theories make explanatory, evaluative and prescriptive claims. Rydin's book runs from the linear rational model (ch. 2), through actor-centred approaches (rational choice, institutions, governance, urban politics; chs 3–6) and structural political economy (ch. 7), to relational perspectives (Foucault, assemblage; chs 8–9)."],
concepts:[["Theory (Rydin 2021)","A heuristic aid; a coherent set of ideas making general statements about (part of) the world; a narrative account, never complete."],["Theory of vs theory for planning","Analytic (how planning works) vs normative (how it should be done) (Faludi's distinction)."],["Empiricism","'Let the facts speak for themselves': rejected because data choice and interpretation are value-laden and findings stay disconnected."],["Phronesis","Flyvbjerg's practical-wisdom research: situated, value-deliberative, attentive to power. Rydin: it still hides theoretical choices."],["Double hermeneutic","Social scientists interpret how people interpret the world (Giddens), so social science ≠ natural science."],["Three advantages of theory","Focus; link to a broader narrative (generalisation); build/revise theory."],["Structure / agency","Patterned arrangements limiting choice / capacity to act independently."],["Explanatory / evaluative / prescriptive claims","How it works / whether it is good / what to do."],["Normative commitment","Assumption about what ought to be valued, pursued, protected."]],
quotes:["\"a heuristic aid to understand a situation, a way to try to know what is essentially unknowable in its completeness\" (Rydin 2021, p. 9)","\"Theory is, therefore, best seen as a set of ideas that fit together coherently and make general statements about the world or a part of it.\"","\"all research—including analytic research—is imbued with value judgements\""],
exam:"Expect MCQs asking which role theory plays (focus, generalise, build theory) or that give a quote or case and ask where it sits on a dimension. Remember: defining 'planning' is itself a theoretical choice."},

{id:"buit", status:"full", statusNote:"Full article on file (Planning Theory 25(4), 351–370).",
one:"'The Just City' is a concept everyone supports, but its conceptions differ: the Happy, Equal, Supportive and Free City. Each has different materials of justice and policies, and they are not à la carte: some are internally or externally incongruent. Planners need 'justice literacy'.",
summary:["Concept vs conception (Moroni 2020, after Rawls): nobody opposes the concept of a just city, but conceptions differ. Three problems in debates: justice kept vague to avoid controversy (superficial consensus); justice defined narrowly as if only one conception exists (e.g. Fainstein's anti-neoliberal framing); and inconsistency when incompatible conceptions are pursued at once (you can't condemn segregation and gentrification AND support free settlement). Aim: improve 'justice literacy', i.e. the vocabulary (conceptions) and grammar (how they connect).",
"Premises: strictly, a city cannot be just; only institutions (formal and informal rules) can (Moroni). 'City' = the target territory where goods, duties or rights are allocated. Each conception decomposes into five materials of justice (Dawkins 2021): value (what is distributed), principle (how), scope (to whom/where), ground (why), basis (goal-based vs rights/duty-based).",
"Happy City (utilitarianism): value = utility/preference satisfaction; principle = maximum collective utility; goal-based. Policies: CBA, agglomeration economies (often labelled 'neoliberal'). Critique: ignores distribution and individual rights. Equal City (egalitarianism): value = equality of outcomes/opportunities; 'the more equal, the better'; inequality instrumentally problematic (neighbourhood effects) and intrinsically wrong. Policies: redistribution, social mixing. Supportive City (sufficientarianism, + prioritarianism, limitarianism): everyone ENOUGH (absolute, not relative poverty); access to primary goods/capabilities, e.g. affordable housing (≤30% of income), commuting limits; setting the threshold is key; rights/duty-based. Free City (liberalism; Hayek, Nozick): equal rights and freedom; 'assigning rights rather than distributing outcomes'; the city as spontaneous order; Nozick's entitlement theory (justice in acquisition and transfer); refrain from growth controls, inclusionary zoning, rent control; Oosterwold. A positive-freedom variant: the capability approach (Sen, Nussbaum).",
"Congruence: internal = do the materials within one conception fit (e.g. utility + individual rights don't)? External = do conceptions fit each other? Free + Supportive can combine (primary goods can be rights; capabilities fit sufficiency). The Free City is incompatible with the goal-based Happy and Equal Cities: formal equality clashes with material equality, and 'liberty upsets patterns' (Nozick), e.g. free settlement produces clustering. 'Justice is not à la carte.'"],
concepts:[["Concept vs conception","The general idea of justice vs a specific version of it."],["Justice literacy","Knowing the vocabulary (conceptions) and grammar (connections) of justice."],["Materials of justice","Value, principle, scope, ground, basis (Dawkins 2021)."],["Goal-based vs rights-based","Aims at an end-state for the collective (Happy, Equal) vs secures rights/duties (Supportive, Free)."],["Happy City","Utilitarian; maximum collective utility; CBA, agglomeration."],["Equal City","Egalitarian; everyone the same (relative); social mixing, redistribution."],["Supportive City","Sufficientarian; everyone enough (absolute); spatial primary goods such as affordable housing."],["Free City","Liberal; equal rights and freedom; refrain from intervening; Oosterwold; capabilities (positive freedom)."],["Internal / external (in)congruence","Fit between materials within one conception / between conceptions."],["Entitlement theory (Nozick)","A distribution is just if it came about through just acquisition and transfer."]],
table:{head:["","Happy","Equal","Supportive","Free"],rows:[["Philosophy","Utilitarianism","Egalitarianism","Sufficientarianism (+ prioritarianism, limitarianism)","Liberalism (negative + positive freedom)"],["Value","Utility, welfare, happiness","(Equality of) outcomes or opportunities","Access to primary goods, capabilities","(Equal) rights and freedom"],["Principle","Maximum collective utility","Everyone the same (relative)","Everyone enough (absolute)","Assign rights equally to all"],["Ground","Majority rule","Inequality instrumentally and intrinsically wrong","Absolute poverty relevant; inequality irrelevant","Importance of the individual"],["Basis","Goal-based","Goal-based","Rights/duty-based","Rights/duty-based"],["Policy","Agglomeration economies, CBA","Social mixing, redistribution","Spatial primary goods (affordable housing)","Refrain from intervening; create opportunities"]]},
example:"Amsterdam's rule that new developments include a fixed share of social housing combines the Equal City (mixing) and the Supportive City (enough affordable homes). A Free City critic would call it a restriction of property rights; a Happy City analyst would run a CBA.",
quotes:["\"justice is not a la carte\"","\"The principle is assigning rights rather than distributing outcomes.\" (on the Free City)","\"liberty upsets designed patterns\" (after Nozick 1974)"],
exam:"Know the Table 1 materials and which conceptions clash: Free vs Happy/Equal (external incongruence); Free + Supportive can combine."},

{id:"know", status:"full", statusNote:"Full article on file (author's version) + lecture 15 Sept + exit-ticket answers.",
one:"Modernist planning reified knowledge as an object; postmodern planning celebrates many knowledges but has no institutional arrangements to handle them. Rydin argues for treating knowledge as claims about causal relations, distinguishing them from other (ethical, aesthetic) claims, and creating arenas where planners open up to and test (close down) them.",
summary:["Starting point: the breakdown of the modernist consensus (Latour): knowledge is not a mirror of nature produced by neutral experts, but socially constructed and embedded in social relations and networks (epistemic communities, communities of practice). Modernist planning rested on planners' command of knowledge for progress. Knowledge differs from information and data because it specifies a causal relationship: planners need to know how impacts follow from actions.",
"The 'new orthodoxy' in planning theory (consensus building: Innes; collaborative: Healey; radical: Sandercock's 'epistemology of multiplicity') places knowledge outside planning organisations. But deliberation has limits: general ones (vague practice, planner skills, capture by powerful interests, unresolved conflict) and knowledge-specific ones: knowledges are not additive (Evans & Marvin); Innes's consensus building works when information is fully shared or 'uncertainty is rampant', whereas most planning lies in between. 'Engaging different knowledges is fundamentally different to engaging different voices.'",
"Knowledge claims must be distinguished from ethical, pragmatic, efficiency or aesthetic claims, since stakeholder rights ≠ expertise rights (Collins & Evans). Habermas's validity claims support this: truth (constatives), normative legitimacy (regulatives), truthfulness (expressives). Labelling all community claims 'knowledge' is politically understandable but wrong: experience 'is not of itself a sufficient condition for it to be knowledge' (p. 9 of MS / p. 56). Planners are co-producers of knowledge (Mode 2): they give voice (opening up) AND test and recognise claims (closing down), aiming at 'socially robust knowledge'. This is a realist constructivism: knowledge is socially constructed yet engages material reality.",
"Typology (Figure 1): planning seeks to turn State A into B1; without planning A becomes B; the actual result is B2. Seven knowledge types: (1) empirical State A, (2) predictive State B, (3) process A→B, (4) process A→B1 (how planning works), (5) empirical B2 (outcomes), (6) process A→B2, (7) normative B1 (desired future, normative yet grounded in possible paths). Collapsed into four: empirical, process, predictive, normative (Table 2). None is value-free and each carries a causal story. Each type needs different arenas and planner roles: empirical = lay + expert, planner as client, analyst or facilitator; process = theory-framed research, even action research; predictive = mostly expert-led, planner as client; normative = public-sphere debate, planners keep possible futures on the table (an ethical voice)."],
concepts:[["Knowledge (Rydin 2007)","A claim specifying causal relationships, not just data or information."],["Modernist consensus","Knowledge as an objective mirror of nature produced by experts; its breakdown = knowledge as socially constructed."],["New orthodoxy","Communicative/collaborative planning: many stakeholders, many knowledges, consensus."],["Knowledge vs other claims","Knowledge claims differ from ethical, pragmatic, efficiency and aesthetic claims (Habermas's validity claims; Collins & Evans)."],["Opening up & closing down","Give voice to claims; test and recognise which count as knowledge."],["Co-production","Planners help generate knowledge by testing and recognising claims."],["Seven → four knowledge types","Empirical, predictive, process (×3), normative → empirical, process, predictive, normative."],["Universal ↔ situated","Does validity depend on who produced the claim and from where?"],["Monist ↔ pluralist","How many independent sources can confer the status of knowledge?"],["Realism ↔ relativism","Can claims be judged against each other? Rydin: soft relativism, but claims can be tested."],["Multi- vs transdisciplinary","Several disciplines (can still be monist) vs non-academics as knowledge producers (pluralist)."]],
cap:"Rydin (2007) Figure 1 as redrawn in the lecture. Processual claims cover A→B, A→B1 and A→B2. Practice: 'Car ownership in Utrecht fell 12% 2015–2023' = empirical; 'Rijnenburg demand will exceed supply by 2030' = predictive; 'densification near stations reduces car use because it changes relative costs' = process; 'Rijnenburg should prioritise affordability' = normative.",
table:{head:["Knowledge type (Table 2)","Who generates it","Planner's role","How it is tested"],rows:[["Empirical","Lay and expert (experiential)","Client (consultancy), analyst, facilitator of community input","Forums: expert–expert, lay–lay, lay–expert; procedures to resolve claims"],["Process","Theory-framed research, action research","Object of research and co-researcher","Engaging rival causal models; evaluations"],["Predictive","Mostly expert-led","Client of researcher, alert to lay input","Challenging causal models + prediction methods"],["Normative","Public-sphere debate; academia's scenarios","Manage informed debate; keep possible futures open","Is the future scenario warranted as possible?"]]},
quotes:["\"engaging different knowledges is fundamentally different to engaging different voices\"","\"The experience of local stakeholders may be an important basis for claiming local or experiential knowledge but … such experience is not of itself a sufficient condition for it to be knowledge\"","\"Contemporary planning theory has tended to be better at discussing opening-up than closing-down.\""],
exam:"Traps: (1) a survey of 1,000 people isn't pluralism; (2) a positivist treats bias as error; (3) situated ≠ anything goes. New from the article: knowledge claims ≠ ethical claims, seven knowledge types → four, and Innes's two conditions for consensus."},

{id:"davoudi", status:"full", statusNote:"Full article on file (disP 165, 2/2006). Correction: the Hoch 'planners as lawyers' image is from Davoudi (2012), quoted in the exit ticket, not this 2006 article.",
one:"The UK enthusiasm for evidence-based policy rests on an instrumental, linear, utilitarian view of research, the same naive assumptions as 1960s–70s positivist planning. In the real world evidence competes with ideology, interests, institutions and prior information, so Davoudi argues for an enlightenment model: evidence-informed policy.",
summary:["Context: New Labour's Modernising Government White Paper (1999): 'what matters is what works'. Two models of the policy–research interface. The instrumental model (linear, direct) has two variants: 'expert on top' (research leads, evidence-driven policy) and 'expert on tap' (research follows policy concerns; speed, usable evidence on demand). The enlightenment model: indirect, long-term; research 'illuminates the landscape' and informs public debate, i.e. evidence-INFORMED rather than evidence-BASED policy.",
"The instrumental view rests on three misconceptions: policy-making is a rational process; evidence can only be generated by positive science; experts are apolitical and value-free, 'and they know best'. These echo planning history: Geddes' survey-analysis-plan (linear, but intuitive visionary planners); then 1960s–70s systems and rational planning (cybernetics, McLoughlin, Chadwick, location theory, Popper's falsifiability) which conceived planning as a science solving well-defined problems, 'the paradox of policy analysis'.",
"Real world: policy is bricolage (Ball); more information can confuse (Keynes); research sits on shelves ('problem of little effect', Weiss). Evidence competes with Weiss's four I's: ideology (e.g. urban containment/Green Belt sustained by values despite Hall's 1973 evidence), interests (DEFRA: evidence 'to turn strategic priorities into something concrete' → the political/tactical model, cherry-picking; think tanks under Thatcher; the Barker review), institutional norms and practices (quick fixes, unread reports), and prior information (facts only become evidence when used to support a proposition; evidence includes expert and experiential, formal and tacit knowledge; what counts is what is available; validity of relations matters). 'Power is knowledge' (Flyvbjerg): power determines what counts as knowledge.",
"The 2004 planning reform's 'soundness' test (PPS12: a 'robust and credible evidence base') became a largely procedural, tick-box exercise. Conclusion: the evidence-based enthusiasm and positivist planning share 'ambitious and naïve assumptions that the complex political and socio-economic processes could be technicized, commanded and controlled'. Keep a broad enlightenment view and two-way interaction between policy and research, and aim at an 'evidence-informed society'."],
concepts:[["Instrumental model","Linear, direct research→policy (expert on top) or policy→research (expert on tap)."],["Enlightenment model","Research indirectly illuminates the context and informs debate: evidence-informed policy."],["Expert on top / on tap","Research leads policy / research serves policy demands."],["Three misconceptions","Policy-making is rational; evidence only from positive science; experts are value-free and know best."],["Weiss's four I's","Ideology, interests, institutional norms/practices, prior information: competitors of evidence."],["Political/tactical model","Evidence gathered or cherry-picked to justify decisions already made."],["Evidence (OED, per Davoudi)","Facts become evidence only when used to (dis)prove a proposition; includes experiential and tacit knowledge."],["Soundness test","UK 2004 plan test on a 'robust and credible evidence base'; in practice procedural, tick-box."]],
fig:`<svg viewBox="0 0 620 220" role="img" aria-label="Instrumental versus enlightenment model of evidence use"><g font-size="12">
<text x="20" y="20" font-weight="700">Instrumental model (linear)</text>
<rect x="20" y="32" width="160" height="40" rx="6" class="bxa"/><text x="100" y="56" text-anchor="middle">policy domain</text>
<rect x="420" y="32" width="180" height="40" rx="6" class="bxi"/><text x="510" y="56" text-anchor="middle">research domain</text>
<path d="M420 44 L180 44" class="ln" stroke-width="2"/><text x="300" y="40" text-anchor="middle" font-size="11">expert on top → evidence-based policy</text>
<path d="M180 64 L420 64" class="ln" stroke-width="2" stroke-dasharray="4 3"/><text x="300" y="82" text-anchor="middle" font-size="11">expert on tap → policy-related research</text>
<text x="20" y="120" font-weight="700">Enlightenment model (indirect)</text>
<rect x="20" y="132" width="580" height="60" rx="8" class="bxg"/><text x="310" y="156" text-anchor="middle">research illuminates the landscape · informs public debate over time</text><text x="310" y="176" text-anchor="middle" class="mut" font-size="11">competes with ideology · interests · institutions · prior information (Weiss)</text>
<text x="20" y="212" class="mut" font-size="11">Davoudi: from evidence-based policy to an evidence-informed society.</text></g></svg>`,
cap:"Davoudi's Figure 1 (instrumental view) set against the enlightenment model.",
example:"The Dutch MKBA/'onderbouwing' culture resembles the instrumental model; the fact that Green Heart and urban containment persist on values more than evidence illustrates Weiss's 'ideology'.",
quotes:["\"What matters is what works\" (UK government, criticised)","\"power determines what counts as knowledge\" (Flyvbjerg, quoted)","\"ambitious and naïve assumptions that the complex political and socio-economic processes could be technicized, commanded and controlled through a scientific process\""],
dims:{sa:null,rt:null,de:null,us:70,mp:70,norm:"Evidence-informed, democratic debate; realism about power and values in policy."},
exam:"Davoudi links today's evidence-based rhetoric to 1960s–70s positivist/rational planning. Know the two models, the three misconceptions and the four I's."},

{id:"cozz", status:"full", cite:"Cozzolino, S. (2020). Environment and Planning B: Urban Analytics and City Science, 47(2), 203–219. doi:10.1177/2399808319857451",
statusNote:"Full article on file.",
one:"Cities as a whole are complex adaptive systems, but many 20th-century neighbourhoods built all at once are anti-adaptive. The cause lies in neglected factors: action (the source of change), ownership (which distributes design control) and time. Planners should create room for incremental, self-organised adaptation instead of more central plans.",
summary:["AANs = large residential neighbourhoods built all-at-once and from scratch in the 20th century (e.g. 'La Clementina', Bergamo, vs historic 'Borgo Santa Caterina'). They answered housing pressures and gave affordable ownership, but they are 'in a lock-in situation': they can't self-regenerate, so they call for top-down, 'paternalistic' regeneration. Aims: characterise the causes of AAN formation and perpetuation, and give policy/design implications. Adaptability matters for persistence, identity and innovation (use of dispersed local knowledge, Hayek, Jacobs).",
"Traditional cities grew from private ownership, incremental development and organic adjustment among households, governed by legal codes that protected neighbours. Modern planning shifted from proscriptive rules ('thou shalt not', only preventing externalities) to prescriptive rules that predefine spatial configurations. Complexity is emergent (spontaneous action); simplicity is designed: 'the more one neighbourhood is designed from the top, the less space there is for complexity to evolve'.",
"Planning's direct responsibility: pushing large-scale developments, demanding large public open spaces, and rules that freeze adaptation. Implications: include time (after construction, leave room for unpredictable adaptation); use 'locality knowledge' while preventing negative externalities; welcome multiple independent ownerships and distributed design control ('everything depends on the pattern of ownership', Moudon). Regeneration: abandon paternalism. New areas: top-down design only for certain common structures; Oosterwold as an experiment. Final point: the problem isn't too few central plans but 'the lack of flexible space for incremental adaptation and the evolution of self-organized orders'. Not nostalgic: the focus is 'the institutional framework that shaped [the traditional city's] evolutionary process', and a distance from New Urbanism."],
concepts:[["Anti-adaptive neighbourhood (AAN)","Built all-at-once from scratch, reluctant to incremental change, 'lock-in'."],["Action · ownership · time","The three under-estimated factors behind adaptability."],["Proscriptive vs prescriptive rules","Prohibitions preventing externalities vs rules predefining spatial outcomes."],["Complexity vs simplicity","Emergent order from spontaneous action vs designed artificial order: a trade-off."],["Distribution of design control","Ownership as the legal title that spreads design control among many actors."],["Locality knowledge","Jacobs: people's situated knowledge of their own needs and place."],["Paternalistic circle","AANs can't self-regenerate, so top-down interventions follow, which reproduce dependence."]],
quotes:["\"action (as the main source of urban change), ownership (as the legal title that effectively distributes 'design control' in the built environment), and time (as the essential condition in incremental processes of adaptation)\" (p. 4)","\"the more one neighbourhood is designed from the top, the less space there is for complexity to evolve\"","\"the main problem with AANs is not so much … the need for further centrally coordinated plans … but rather the lack of flexible space for incremental adaptation and the evolution of self-organized orders\""],
exam:"Agency-leaning, emergent, Free City; draws on Hayek, Jacobs and Moroni. Tutorial critiques: unequal actors (tenants), markets as power structures, a romanticised traditional city."},

{id:"taylor", status:"full", cite:"Taylor, E.J. (2016). Urban Growth Boundaries and Betterment: Rent-seeking by Landowners on Melbourne's Expanding Urban Fringe. Growth and Change, 47(2), 259–275. doi:10.1111/grow.12110",
statusNote:"Full article on file.",
one:"Analysing 264 public submissions on Melbourne's 2010 UGB expansion and the Growth Areas Infrastructure Contribution (a betterment tax), Taylor shows that landowners as 'insiders' rent-sought successfully: they discredited expected windfalls and got the GAIC shifted to purchasers, so costs are passed on to homebuyers ('outsiders').",
summary:["Melbourne's UGB (2002) expanded substantially in 2010; land inside rose 89% per hectare relative to comparable land outside, creating 'instant millionaires'. The GAIC was a hypothecated per-hectare tax on the expected betterment, to fund infrastructure.",
"Landowners have multiple interests: premium-seeking owners (often broadacre farmers, vacant land) want inclusion and to unlock development value, and containment creates speculation through 'dual predictability' (Nelson). Others, affluent rural-residential 'lifestyle' owners and hobby farmers, want to preserve restrictions for amenity and value stability ('homevoters', Fischel). Among submissions: 33 included owners were happy, 11 wanted to stay rural; 52 excluded owners wanted inclusion; grassland-zone owners called protection 'conning landowners from their rights'.",
"Landowners framed the GAIC as 'unbelievable, unethical, outright robbery', disputed that betterment would occur (a 'Taxed Out!' campaign), and argued it should be paid by developers/buyers. 'Landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill' (p. 272): exemptions for small parcels (0.41–5 ha, ~56% of liable parcels), liability shifted to purchasers (30% at purchase, rest at development), and in 2011 fully deferred to development, which protected hobby farmers.",
"Conclusion: the outcome legitimised landowners' misinterpretation of development gain; representations of self-interest were taken 'at face value as more equitable'. Policies 'are decided in large part on the basis of whether or not they survive conflict with groups with an existing economic stake'. Containment creates land premiums that are redistributed through the lobbying of 'insiders', with costs passed to housing consumers ('outsiders'). Rent-seeking by existing owners can decide whether and how strategic planning is implemented."],
concepts:[["Urban growth boundary (UGB)","Legislated line separating urban from non-urban land."],["Betterment","Land-value increase caused by public action; here the windfall from the UGB shift."],["GAIC","Growth Areas Infrastructure Contribution: hypothecated betterment tax, later made 'purchaser pays'."],["Rent-seeking","Lobbying to capture or keep unearned rents."],["Premium-seeking vs homevoter","Owners wanting development value vs owners protecting amenity and property value through restrictions."],["Dual predictability","Containment makes clear which land can be developed AND that it is scarce, fuelling speculation."],["Insiders vs outsiders","Existing property owners who capture gains vs future homebuyers who pay."]],
quotes:["\"Landowner-led pressure on policy makers ultimately led to a set of modifications to the GAIC bill.\" (p. 272)","\"policies with broader implications are decided in large part on the basis of whether or not they survive conflict with groups with an existing economic stake in the outcomes\""],
exam:"Rational choice/rent-seeking + Olson: a concentrated insider group beats diffuse future buyers. Shows reproduction of owners' advantages. Links to Sorensen (land value capture, analysed with historical institutionalism instead)."},

{id:"ni", status:"full", cite:"Lecture 29 Sept (Bouwmeester): Neo-institutionalism & planning · + Dembski & Salet (2010) Table 1",
statusNote:"Lecture slides on file.",
one:"Institutions are the formal and informal rules of the game, not organisations. They are 'ontologically both the context and object of planning' (Savini 2019). New institutionalism comes as rational choice, sociological, historical and evolutionary strands, which disagree on what institutions are, what they do and how they change, and so on how much planners can deliberately design them.",
summary:["Institutions = systems of established rules and norms that guide, constrain and regulate behaviour; organisations = concrete entities with a purpose (Eurovision: EBU = organisation; statutes and informal norms = institutions). Double life: they constrain actors but are also outcomes of action (context AND object of planning). Alexander (2005): if planning aims to transform society, 'institutional transformation must be a critical aspect of planning'. Some even say 'planning is institutional design' (Innes 1995): planners → design institutions → shape behaviour → reshape society/space.",
"Origins (Part A): Hardin's tragedy of the commons (1968): rational self-interest depletes shared resources. Ostrom (1990) shows how self-interested people self-organise rules to overcome the 'problem of commitment'. Her IAD framework has seven rule types: position, boundary, choice, aggregation, information, payoff, scope (applied to informal real estate by Bouwmeester & Hartmann 2021). New institutionalism explains how institutions shape behaviour and how they arise and change, and reconciles structure and agency (Giddens). Example: institutional arrangements shape residential morphology in NL, Flanders and NRW (Tennekes et al. 2015).",
"Strands (Part B, after Sorensen 2017 and Salet 2018). (1) Rational choice institutionalism: 'formal and informal rules of the game … humanly devised constraints' (North 1990); they coordinate and give certainty, information and credible commitment; they change when self-interested actors create rules to enhance cooperation. (2) Sociological: institutions 'establish the very criteria by which people discover their preferences'; goodness-of-fit with legitimate templates (DiMaggio & Powell); symbol systems, cognitive scripts, moral templates (Hall & Taylor); internalised; hegemonic norms. Example: Amsterdam-Noord's symbols linking the shipyard past to a creative future (Savini & Dembski 2016). (3) Historical: procedures, routines and norms embedded in the polity; path dependency, critical junctures, structural emphasis. Example: why participation in Norwegian land-use planning stayed weak (Holsen 2021). (4) Evolutionary (Moroni): institutions as unintended outcomes of evolution.",
"The key debate is institutional change and the limits of design. Dembski & Salet: symbols can't be used voluntaristically; find under-institutionalised niches. Sorensen: critical junctures, then bounded developmental pathways. Moroni: emergent institutions can't be designed like organisations, so a kosmos approach. 'How we conceptualize institutions shapes how we conceptualize planning agency.'"],
concepts:[["Institution vs organisation","Rules and norms (formal/informal) vs a concrete purposive entity."],["Context and object","Institutions constrain planning AND are what planning produces (Savini 2019)."],["Tragedy of the commons","Hardin: rational individuals overuse shared resources."],["Ostrom's IAD rules","Position, boundary, choice, aggregation, information, payoff, scope."],["Rational choice institutionalism","Rules of the game; certainty and credible commitment; changed by self-interested actors."],["Sociological institutionalism","Institutions shape preferences; legitimacy, goodness-of-fit, cognitive scripts; internalised."],["Historical institutionalism","Embedded routines; path dependency; critical junctures; structural."],["Evolutionary institutionalism","Institutions as unintended results of evolution (Moroni)."],["Planning as institutional design","Innes/Alexander: planners deliberately change institutions."]],
table:{head:["","Rational choice","Sociological","Historical","Evolutionary"],rows:[["What are institutions?","Rules of the game, constraints (North)","Symbols, cognitive scripts, moral templates","Procedures, routines, norms embedded in the polity","Unintended outcomes of long evolution"],["What do they do?","Coordinate; give certainty, information, commitment","Define appropriateness; shape preferences","Constrain; channel development along paths","Coordinate; store dispersed knowledge"],["Change","Deliberate redesign by self-interested actors","Deliberate but must be embedded (symbols, habitus)","Critical junctures, then bounded pathways","Emergent trial and error; only modest intervention"],["Planners","Rule designers (e.g. Ostrom, Coase)","Meaning-makers in niches","Actors exploiting junctures","Humble rule-keepers (kosmos)"],["Course author","Needham, Taylor (RC)","Dembski & Salet; Savini & Dembski","Sorensen; Holsen","Moroni"]]},
example:"Lecture homework: 'Housing is becoming unaffordable'. HI: the problem is path-dependent rules (e.g. mortgage-interest deduction); look for a crisis as a critical juncture. SI: norms of homeownership as 'normal'; change the meanings. Evolutionary: rules that block adaptation; simplify and open general rules gradually.",
quotes:["\"Institutions are ontologically both the context and object of planning practices from a relational perspective\" (Savini 2019)","\"Institutions do not just constrain options: they establish the very criteria by which people discover their preferences.\"","\"How we conceptualize institutions shapes how we conceptualize planning agency.\""],
exam:"Sample Q1: a sociological institutionalist says institutions are embedded in cultural norms and cognitive scripts that shape planners' own perceptions (B). C = historical, D = evolutionary (Moroni), A = rational choice/actor-centred."}
];
for(const u of UPDATES){const r=READINGS.find(x=>x.id===u.id);if(r)Object.assign(r,u);}

FC.push(
["fw","Rydin 2021: theory OF planning vs normative planning theory","Her book is analytic (how planning works) rather than normative (how it should be done), though the two are entangled and all research carries value judgements."],
["fw","Why is empiricism rejected (Rydin 2021)?","Choosing and interpreting data involves value judgements, and pure empiricism gives a disparate field that can't connect findings."],
["fw","Three advantages of using theory (Rydin 2021)","Focus attention (practical limits); link findings to a broader persuasive narrative (generalise); build/revise theory from empirical research."],
["fw","Phronesis and Rydin's critique","Flyvbjerg's practical-wisdom research (who gains/loses by which power mechanisms?). Rydin: it still relies on unacknowledged theory (double hermeneutic, praxis)."],
["fw","Double hermeneutic","Social scientists interpret how people interpret the world (Giddens), so social science shouldn't copy natural-science laws."],
["fw","How does defining 'planning' show theory is unavoidable?","Decision-making to reach goals (instrumental) vs state ordering the environment for the collective interest vs intervention affecting diverse interests: each framing implies a different theory."],
["buit","Concept vs conception of justice","Concept = the general idea everyone supports; conception = a specific version (Happy, Equal, Supportive, Free)."],
["buit","Buitelaar's five materials of justice","Value, principle, scope, ground, basis (Dawkins 2021)."],
["buit","Goal-based vs rights-based conceptions","Goal-based: Happy, Equal (end-states for the collective). Rights/duty-based: Supportive, Free."],
["buit","Why is the Free City incompatible with the Equal and Happy Cities?","Formal equality (equal rights) clashes with material equality, and liberty upsets designed patterns (Nozick)."],
["buit","Which two conceptions can be combined?","Free and Supportive: primary goods can include rights, and capabilities fit the sufficiency principle."],
["buit","Happy City policy instrument","Cost-benefit analysis; policies promoting agglomeration economies."],
["buit","Why can a city not be 'just' strictly speaking?","Only institutions (the formal and informal rules within which the city develops) can be just or unjust (after Moroni)."],
["buit","Justice literacy","Knowing the vocabulary (conceptions) and grammar (how they connect and conflict) of justice."],
["know","Rydin 2007: difference between knowledge and information/data","Knowledge specifies a causal relationship between action and impact."],
["know","Rydin's seven knowledge types","Empirical A; predictive B; process A→B; process A→B1; empirical B2; process A→B2; normative B1 (grouped into empirical, process, predictive, normative)."],
["know","Knowledge claims vs other claims (Rydin 2007)","Knowledge claims differ from ethical, pragmatic, efficiency and aesthetic claims (Habermas: truth vs normative legitimacy vs truthfulness)."],
["know","Innes's two conditions where consensus building works (per Rydin)","Fully shared information, or rampant uncertainty; most planning lies in between."],
["know","Which Rydin knowledge type is mostly expert-led?","Predictive knowledge: lay knowledge is rooted in past and present experience."],
["know","Rydin's diagnosis of modernist vs postmodern planning theory","Modernist reifies knowledge as an object; postmodern celebrates many knowledges but lacks institutional arrangements to test them."],
["davoudi","Davoudi's two models of the policy–research interface","Instrumental (linear: expert on top / expert on tap) and enlightenment (indirect, informs debate: evidence-informed)."],
["davoudi","Davoudi's three misconceptions behind evidence-based policy","Policy-making is rational; evidence only comes from positive science; experts are apolitical, value-free and know best."],
["davoudi","Weiss's four I's (in Davoudi)","Ideology, interests, institutional norms and practices, prior information: competitors of evidence."],
["davoudi","Political/tactical model of evidence use","Research agenda politically driven to justify decided policy, by cherry-picking evidence."],
["davoudi","What parallel does Davoudi draw?","Today's instrumental evidence-based policy repeats the assumptions of 1960s–70s positivist rational/systems planning."],
["cozz","Cozzolino's three under-estimated factors","Action (source of change), ownership (distributes design control), time (condition for incremental adaptation)."],
["cozz","Proscriptive vs prescriptive rules","Old codes forbade harm to others ('thou shalt not'); modern plans prescribe spatial outcomes."],
["cozz","Planning's direct responsibility for AANs (Cozzolino)","Pushing large-scale developments, demanding large public open spaces, rules that freeze adaptation."],
["taylor","What was the GAIC and what happened to it?","A hypothecated betterment tax on land brought into Melbourne's UGB; after landowner lobbying: small-parcel exemptions, purchaser pays, fully deferred to development (2011)."],
["taylor","Homevoters (Fischel) in Taylor","Owner-occupiers (e.g. lifestyle landowners) who support restrictions to protect amenity and property values."],
["taylor","Insiders vs outsiders (Taylor)","Existing landowners capture and redistribute land premiums through lobbying; costs pass to future homebuyers."],
["ni","Savini (2019) on institutions and planning","Institutions are ontologically both the context and the object of planning practices."],
["ni","Ostrom's seven rule types (IAD)","Position, boundary, choice, aggregation, information, payoff, scope."],
["ni","Hardin vs Ostrom","Hardin: rational users deplete commons (tragedy). Ostrom: users can self-organise institutions to prevent it."],
["ni","Sociological institutionalism: goodness-of-fit","Institutional arrangements reproduce because they fit established, legitimate templates (DiMaggio & Powell)."],
["ni","Amsterdam-Noord example (Savini & Dembski 2016)","Symbols linking the shipyard past to a creative-economy future mobilised consensus: sociological institutionalism."],
["ni","Holsen (2021) example","Path-dependent explanation of weak public participation in Norwegian land-use planning: historical institutionalism."],
["ni","'Planning is institutional design'","Innes (1995), via Alexander (2005): planners design institutions → shape behaviour → reshape society/space."]
);

MCQ.push(
{t:"fw",q:"According to Rydin (2021), which is NOT an advantage of using theory in planning research?",o:["It helps decide what to focus on","It links partial findings to a broader narrative","It lets researchers avoid value judgements","It allows empirical research to build or revise theory"],a:2,e:"Rydin stresses that all research is value-laden; theory makes value judgements explicit."},
{t:"fw",q:"Rydin (2021) criticises Flyvbjerg's phronesis mainly because…",o:["it ignores power","it presents research as a-theoretical while relying on unacknowledged theoretical choices","it is too quantitative","it rejects practice"],a:1,e:"E.g. the double hermeneutic and praxis are theoretical choices."},
{t:"fw",q:"'Let the facts speak for themselves' describes…",o:["phronesis","empiricism, which Rydin rejects","the heuristic view of theory","critical realism"],a:1,e:"Latour's 'modernist settlement'."},
{t:"buit",q:"In Buitelaar's framework, 'goal-based' conceptions are…",o:["Supportive and Free","Happy and Equal","Equal and Free","Happy and Supportive"],a:1,e:"They aim at an end-state for the collective; Supportive and Free are rights/duty-based."},
{t:"buit",q:"Why is the Free City externally incongruent with the Equal City?",o:["Both aim at maximum utility","Equal rights inevitably lead to unequal material outcomes, and correcting them requires limiting some people's rights","The Equal City ignores segregation","The Free City requires social mixing"],a:1,e:"Formal vs material equality; 'liberty upsets patterns'."},
{t:"buit",q:"Which pair of conceptions does Buitelaar say CAN be combined?",o:["Happy + Free","Equal + Free","Free + Supportive","Happy + Supportive via preference satisfaction"],a:2,e:"Primary goods can include rights; capabilities fit sufficiency."},
{t:"buit",q:"Which is one of Buitelaar's 'materials of justice'?",o:["Scale","Basis","Density","Tenure"],a:1,e:"Value, principle, scope, ground, basis."},
{t:"know",q:"Rydin (2007) argues that deliberative/collaborative approaches are insufficient for handling knowledge because…",o:["they give too little voice to residents","engaging different knowledges differs from engaging different voices; claims must be tested","consensus always produces the best knowledge","planners should decide alone"],a:1,e:"Knowledges are not additive."},
{t:"know",q:"A resident argues a heritage building should be kept because 'it is part of who we are'. In Rydin's terms this is primarily…",o:["an empirical knowledge claim","a predictive knowledge claim","an ethical/emotional claim distinct from a knowledge claim","a process knowledge claim"],a:2,e:"Rydin separates knowledge claims from ethical, aesthetic and emotional claims."},
{t:"know",q:"How many knowledge types does Rydin's Figure 1 generate, and how are they grouped?",o:["Four, into two","Seven, collapsed into four (empirical, process, predictive, normative)","Three, into universal and situated","Six, all empirical"],a:1,e:"Two empirical, one predictive, three process, one normative."},
{t:"davoudi",q:"In Davoudi's 'expert on tap' model…",o:["research leads policy","research follows policy concerns: the expert is on tap, not on top","research enlightens public debate","experts are excluded"],a:1,e:"Both variants are instrumental and linear."},
{t:"davoudi",q:"Which is one of Weiss's four I's that compete with evidence?",o:["Innovation","Ideology","Integration","Implementation"],a:1,e:"Ideology, interests, institutional norms and practices, prior information."},
{t:"davoudi",q:"Davoudi's main parallel is between today's evidence-based policy and…",o:["communicative planning","1960s–70s positivist rational/systems planning","Marxist planning","Geddes' visionary planning only"],a:1,e:"Both assume planning/policy can be technicised and controlled."},
{t:"cozz",q:"Which factor does Cozzolino see as the legal title that distributes design control?",o:["Time","Ownership","Action","Density"],a:1,e:"Action = source of change; time = condition for incremental adaptation."},
{t:"cozz",q:"Old building codes in traditional cities were mostly…",o:["prescriptive, fixing spatial outcomes","proscriptive, prohibiting harm to neighbours without predefining form","absent","set by one developer"],a:1,e:"The shift to prescriptive rules helped create AANs."},
{t:"taylor",q:"What was the outcome of landowner lobbying against Melbourne's GAIC?",o:["The GAIC was abolished","The GAIC was kept but modified: small-parcel exemptions, purchaser pays, payment deferred to development","The UGB expansion was cancelled","Landowners paid more"],a:1,e:"Costs shifted to developers and ultimately homebuyers ('outsiders')."},
{t:"taylor",q:"Lifestyle landowners who want to keep rural restrictions around their property are, in Taylor's terms…",o:["premium-seekers","homevoters","developers","outsiders"],a:1,e:"Fischel's homevoters protect amenity and property values."},
{t:"ni",q:"Ostrom's work showed that…",o:["commons are always depleted","self-interested users can self-organise institutions to manage commons","only the state can manage commons","privatisation is the only solution"],a:1,e:"A reply to Hardin's tragedy of the commons."},
{t:"ni",q:"'Institutions do not just constrain options: they establish the very criteria by which people discover their preferences.' Which strand?",o:["Rational choice institutionalism","Sociological institutionalism","Historical institutionalism","Evolutionary institutionalism"],a:1,e:"Internalised, preference-shaping institutions."},
{t:"ni",q:"Holsen (2021) explains weak public participation in Norwegian planning despite decades of legislation. This is an example of…",o:["rational choice institutionalism","sociological institutionalism","historical institutionalism (path dependence)","communicative planning"],a:2,e:"Lecture 29 Sept example."},
{t:"ni",q:"In the Eurovision example, the European Broadcasting Union is…",o:["an institution","an organisation","an informal rule","a critical juncture"],a:1,e:"Its statutes and informal norms are the institutions."},
{t:"ni",q:"Which is NOT one of Ostrom's IAD rule types?",o:["Boundary rules","Payoff rules","Symbol rules","Scope rules"],a:2,e:"Position, boundary, choice, aggregation, information, payoff, scope."}
);

OPEN.push(
{t:"ni",pts:12,q:"'Housing is becoming unaffordable.' Define the problem and a likely solution from (a) a historical institutionalist, (b) a sociological institutionalist and (c) an evolutionary institutionalist perspective. (Lecture 29 Sept homework)",
model:"(a) HI: unaffordability results from path-dependent institutions (e.g. mortgage-interest deduction, land and tenure rules) reproduced by positive feedback and the interests they create; change needs a critical juncture (a crisis as permissive condition) plus productive conditions: coalitions ready with an alternative (Sorensen). (b) SI: the problem is embedded norms and meanings, homeownership as 'normal' and the legitimate template; change requires new meanings to be inculcated, through symbolic markers and new practices in under-institutionalised niches (e.g. cooperatives), not voluntaristic top-down design (Dembski & Salet). (c) Evolutionary: over-detailed, frequently changed, prescriptive rules block adaptation and supply; solution: modest, gradual, general and stable rules that allow discovery and incremental development (Moroni; Cozzolino).",
rubric:["HI: path dependency + critical juncture logic","SI: norms/meanings + embedding/symbols","Evolutionary: emergent institutions + modest general rules","Uses at least one author per perspective"]},
{t:"davoudi",pts:10,q:"Explain Davoudi's (2006) distinction between the instrumental and enlightenment models of evidence use and why she argues the instrumental view resembles 1960s–70s planning.",
model:"Instrumental: linear, direct research–policy link, either 'expert on top' (research leads) or 'expert on tap' (research serves policy demands), underpinned by three misconceptions (rational policy-making, only positive science counts, value-free experts who know best). Enlightenment: research indirectly informs understanding and debate, so evidence-informed rather than evidence-based. The resemblance: like systems/rational planning, it assumes planning is a science solving well-defined problems with value-free techniques and that complex political processes can be 'technicized, commanded and controlled'. In reality evidence competes with ideology, interests, institutions and prior information (Weiss).",
rubric:["Instrumental model incl. on top/on tap","Enlightenment model = evidence-informed","Three misconceptions or the four I's","Link to positivist/rational planning"]}
);

(function fixes(){
 const h=FC.findIndex(c=>c[1].startsWith("Hoch's lawyer image"));if(h>=0)FC[h]=["know","Hoch's lawyer image (Davoudi 2012, exit ticket)","Planners don't uncover facts like geologists; like lawyers they organise facts as evidence within arguments (post-positivist)."];
 const p=FC.findIndex(c=>c[1]==="Policy-based evidence");if(p>=0)FC.splice(p,1);
 const e=FC.findIndex(c=>c[1].startsWith("Evidence-based vs evidence-informed"));if(e>=0)FC[e]=["davoudi","Evidence-based vs evidence-informed (Davoudi 2006)","Evidence-based: instrumental, linear hope that research determines policy. Evidence-informed: enlightenment model, where research clarifies context and informs debate."];
 const q=MCQ.find(x=>x.q.startsWith("'Planners do not uncover facts like geologists"));if(q){q.t="know";q.e="Exit ticket: Hoch, as used by Davoudi (2012), a post-positivist position.";}
 const q2=MCQ.find(x=>x.q.startsWith("Davoudi (2006) argues that 'evidence-based planning'"));if(q2){q2.o[1]="is largely rhetoric resting on an instrumental, linear view; in reality evidence competes with ideology, interests and institutions, so 'evidence-informed' is more realistic";}
})();
