/* p9a_mid.js : full-text rebuild of midterm readings hayek, needham, olson (replaces slide-based versions) */
const NEW_A=[
{id:"hayek", wk:2, title:"Hayek (1944) Planning and democracy", cite:"Hayek, F.A. (1944). Planning and democracy. The Road to Serfdom, ch. 5, pp. 42–53. London: Routledge. Reprinted in Hillier, J. & Healey, P. (eds) (2008) Critical Essays in Planning Theory, Vol. 1: Foundations of the Planning Enterprise, pp. 275–286. Aldershot: Ashgate", theory:"Liberalism / Austrian economics", status:"full",
statusNote:"Built from the full chapter (OCR of the Hillier & Healey reprint). The scan shows both paginations: original Road to Serfdom pp. 42–53 (used for all page references below) and reprint pp. 275–286 (reprint p. = original p. + 233). Lecture HC4 (17 Sept, Marx vs Hayek) used for what the slides emphasise. Several Hayek ideas on the slides (spontaneous order, dispersed knowledge, complex phenomena, indeterminism) are NOT in this chapter: see the table.",
one:"Central economic planning directs all of society towards a single goal, which presupposes a 'complete ethical code' that nobody has. Because democratic assemblies can agree that there should be a plan but not on its ends, planning shifts decisions to experts and discretion, and ultimately to dictatorship. Democracy only works when collective action is limited to fields where true agreement exists and power is bound by general rules.",
summary:["Starting point (pp. 42–44): all collectivism (communism, fascism) is 'the deliberate organisation of the labours of society for a definite social goal'. Goals such as the 'common good' or 'general welfare' are too vague to decide any concrete action; a single plan would need every need of every person ranked in one order of values, i.e. a 'complete ethical code'. No such code exists: as civilisation grew, moral rules became fewer and more general, merely marking out a sphere of individual freedom. Nobody can survey more than a limited field of needs, so only partial, mutually inconsistent scales of values exist, in individual minds. That, not egoism, is the basis of individualism: the individual is 'the ultimate judge of his ends'.",
"Limits of common action (pp. 44–45): social ends are just the identical ends of many individuals, so common action must be limited to fields where people agree; agreement is likeliest on means that serve many purposes, and its probability falls as the scope of state action widens. Once the state controls a large enough share of resources (Germany 1928: 53% of national income), it indirectly controls almost everything, and the 'social scale of values' must cover nearly all individual ends.",
"The democratic mechanism (pp. 45–51): people may agree on planning without agreeing on its ends, like a group committing to a journey without agreeing where to go. Parliaments then fail and are seen as 'talking shops'; planning is 'taken out of politics' and delegated to experts (Hayek quotes the Webbs, Laski and the Donoughmore Committee). Majority voting suits choices between limited alternatives, but a plan needs 'a unitary conception' and cannot be voted clause by clause. Unlike a general with one goal, the planner must choose between competing ends, so experts impose their own scale of preferences. Delegation of general rule-making (even to local authorities) is acceptable; delegation of discretion in particular cases ('judging the case on its merits') creates arbitrary power. Separate sectoral plans do not add up, the cry for an 'economic dictator' follows, and parliament ends up choosing persons with near-absolute power: 'plebiscitarian dictatorship'. Germany before 1933 is the example: Hitler exploited a democracy that had already decayed.",
"Conclusion (pp. 51–53): 'It is the price of democracy' that conscious control is limited to fields of true agreement and some things are left to chance. The liberal creed reduced the range of subjects needing agreement; only within a competitive system based on free disposal over private property is democracy possible. Democracy is not an end but 'a utilitarian device' for peace and freedom; a homogeneous majority can be oppressive. Planning leads to dictatorship because dictatorship is the most effective instrument of coercion. What prevents arbitrary power is 'not the source but the limitation of power'.",
"Slides vs chapter: the lecture presents Hayek through spontaneous order, indeterminism, 'the theory of complex phenomena' (cited as Hayek 1989) and equality of rights vs Marx's material equality. None of these terms appears in this chapter. Dispersed local knowledge comes from Hayek (1945) 'The use of knowledge in society' (cited by Cozzolino); spontaneous order (kosmos vs taxis) from Law, Legislation and Liberty (1973; Moroni cites the 1982 edition). The chapter itself argues from value pluralism, the limits of any one mind's view of needs and ends, and the political mechanics of majority rule and delegation. The slide headings 'The philosophy of individualism' and 'Planning in democracy' are the parts actually drawn from this chapter."],
concepts:[["Collectivism","'The deliberate organisation of the labours of society for a definite social goal' (p. 42); denies autonomous spheres where individual ends are supreme."],["Complete ethical code","A ranking of all human values complete enough to decide every choice a central plan requires; Hayek says it does not exist (pp. 43–44)."],["Individualism (Hayek)","Not egoism: because no mind can survey more than a sector of society's needs, the individual should be the ultimate judge of his own ends within defined limits (p. 44)."],["Limits of agreement","Common action is legitimate where individual views coincide; agreement falls as the scope of state action grows (p. 45)."],["Delegation to experts","When assemblies cannot agree on a plan, it is handed to experts, who then impose their own scale of preferences (pp. 46–48)."],["General rules vs discretion","Delegating general rule-making is acceptable; delegating decisions on particular cases 'on their merits' produces arbitrary power (p. 49)."],["Plebiscitarian dictatorship","End state of democratic planning: parliament only confirms a leader who holds practically absolute power (p. 51)."],["Price of democracy","Conscious control restricted to fields of true agreement; 'in some fields things must be left to chance' (p. 51)."],["Democracy as means","'A utilitarian device for safeguarding internal peace and individual freedom' (p. 52), not the highest end."]],
fig:`<svg viewBox="0 0 620 270" role="img" aria-label="Hayek's causal chain from democratic planning to dictatorship, with the liberal alternative"><defs><marker id="hyk9a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<text x="310" y="20" text-anchor="middle" font-weight="700" font-size="12">Democratic planning slides into dictatorship (pp. 45–51)</text>
<rect x="5" y="35" width="110" height="72" rx="8" class="bxi"/><text x="60" y="61" text-anchor="middle">Democracy agrees</text><text x="60" y="76" text-anchor="middle">'there must be</text><text x="60" y="91" text-anchor="middle">a plan'</text>
<rect x="127" y="35" width="110" height="72" rx="8" class="bxw"/><text x="182" y="61" text-anchor="middle">No agreement on</text><text x="182" y="76" text-anchor="middle">ends: no complete</text><text x="182" y="91" text-anchor="middle">ethical code</text>
<rect x="249" y="35" width="110" height="72" rx="8" class="bxw"/><text x="304" y="61" text-anchor="middle">Parliament fails:</text><text x="304" y="76" text-anchor="middle">'talking shop',</text><text x="304" y="91" text-anchor="middle">no majority plan</text>
<rect x="371" y="35" width="110" height="72" rx="8" class="bxw"/><text x="426" y="61" text-anchor="middle">Delegation to</text><text x="426" y="76" text-anchor="middle">experts: discretion</text><text x="426" y="91" text-anchor="middle">not general rules</text>
<rect x="493" y="35" width="112" height="72" rx="8" class="bxa"/><text x="549" y="61" text-anchor="middle">Cry for economic</text><text x="549" y="76" text-anchor="middle">dictator: plebis-</text><text x="549" y="91" text-anchor="middle">citarian dictatorship</text>
<line x1="115" y1="71" x2="125" y2="71" class="ln" stroke-width="1.5" marker-end="url(#hyk9a)"/><line x1="237" y1="71" x2="247" y2="71" class="ln" stroke-width="1.5" marker-end="url(#hyk9a)"/><line x1="359" y1="71" x2="369" y2="71" class="ln" stroke-width="1.5" marker-end="url(#hyk9a)"/><line x1="481" y1="71" x2="491" y2="71" class="ln" stroke-width="1.5" marker-end="url(#hyk9a)"/>
<text x="310" y="150" text-anchor="middle" font-weight="700" font-size="12">Liberal alternative (pp. 49–53)</text>
<rect x="10" y="165" width="190" height="66" rx="8" class="bxg"/><text x="105" y="189" text-anchor="middle">Limit common action</text><text x="105" y="204" text-anchor="middle">to fields where true</text><text x="105" y="219" text-anchor="middle">agreement exists</text>
<rect x="215" y="165" width="190" height="66" rx="8" class="bxg"/><text x="310" y="189" text-anchor="middle">General rules, not</text><text x="310" y="204" text-anchor="middle">discretion on cases</text><text x="310" y="219" text-anchor="middle">'on their merits'</text>
<rect x="420" y="165" width="190" height="66" rx="8" class="bxg"/><text x="515" y="189" text-anchor="middle">Not the source but</text><text x="515" y="204" text-anchor="middle">the limitation of</text><text x="515" y="219" text-anchor="middle">power stops arbitrariness</text>
<text x="310" y="258" text-anchor="middle" class="mut">Cause of the slide: task too big for agreement, not bad politicians (p. 47)</text></g></svg>`,
cap:"The chapter's mechanism: agreement on planning without agreement on ends pushes power to experts and then to a dictator; the liberal answer is limited, rule-bound collective action.",
table:{head:["Idea attributed to Hayek","In this chapter?","Where it actually comes from"],rows:[
["No complete ethical code; no single scale of values","Yes (pp. 42–44)","Planning and democracy"],
["Limits of one mind: nobody can survey all needs","Yes (p. 44), about needs and values (ends)","Planning and democracy"],
["Delegation to experts; general rules vs discretion","Yes (pp. 46–50)","Planning and democracy"],
["Plebiscitarian dictatorship; limitation (not source) of power","Yes (pp. 51–53)","Planning and democracy"],
["Dispersed, local knowledge of particular circumstances","No","Hayek (1945) The use of knowledge in society (cited by Cozzolino)"],
["Spontaneous order (kosmos vs taxis)","No, term absent","Hayek's later work, e.g. Law, Legislation and Liberty (1973); used by Moroni (2010)"],
["Complex phenomena; indeterminism vs Marx's determinism","No","Separate Hayek essay cited in HC4; lecture framing"],
["Equality of rights vs material equality","Not in these terms","HC4 comparison of Marx and Hayek"]]},
example:"The chapter's own cases: Germany, where by 1928 public authorities controlled 53% of national income and democracy had in effect broken down before 1933, so 'Hitler did not have to destroy democracy' (p. 50); and Britain, where Laski proposed governing by delegated legislation and Order in Council (pp. 46–47). Planning illustration (not in the text): a permit system that decides each project 'on its merits' is what Hayek calls discretion; a zoning code of general rules is the acceptable form.",
quotes:["\"It presupposes, in short, the existence of a complete ethical code in which all the different human values are allotted their due place.\" (p. 43)","\"It is the price of democracy that the possibilities of conscious control are restricted to the fields where true agreement exists, and that in some fields things must be left to chance.\" (p. 51)","\"Democracy is essentially a means, a utilitarian device for safeguarding internal peace and individual freedom.\" (p. 52)","\"it is not the source but the limitation of power which prevents it from being arbitrary.\" (p. 53)"],
dims:{sa:80,rt:40,de:75,us:40,mp:85,norm:"Individual freedom (liberty) first; democracy valued as a means; rule of general rules over discretion; limited government."},
exam:"MCQ traps: (1) Hayek's individualism is explicitly NOT an assumption of selfishness (p. 44). (2) He does not oppose delegation as such, only delegation of discretion. (3) He does not say democracy is the highest end, nor that dictatorship must always destroy freedom. (4) 'Spontaneous order' and 'dispersed knowledge' are lecture/other-work ideas, not this chapter. Framework: agency (individual ends), pluralist about values, change towards serfdom is an unintended but causal slide; liberal order leaves things 'to chance' (emergent). Commentary use: Hayek grounds critiques of discretionary, comprehensive planning; critique him from Marxism (formal freedom ignores material inequality and property power), communicative planning (agreement can be built through deliberation rather than only found), or rational-comprehensive planning (experts can rank goals)."},

{id:"needham", wk:3, title:"Needham (2012) Interests and rights in property", cite:"Needham, B. (2012). Interests and rights in property, and their place in land-use planning: a theoretical investigation. In T. Hartmann & B. Needham (eds), Planning By Law and Property Rights Reconsidered (ch. 1, pp. 23–36). Taylor & Francis Group, 2012 (the syllabus lists it as Routledge 2016; same pagination)", theory:"Institutional economics of property rights (law and economics; rational choice lens in the course)", status:"full",
statusNote:"Built from the full chapter (ProQuest ebook, copyright 'Taylor & Francis Group 2012'; pp. 23–35 text, 35–36 references). The syllabus lists it as 2016 (Routledge); pagination 23–36 matches. Lecture HC6 (24 Sept) used for how the course frames it. The 'dual role of the state' matrix and the landowner 'veto' are lecture framings, not terms in the chapter.",
one:"Land-use planning is not the public interest against the market: it is one of two ways the state protects identifiable private interests in land, the other being property rights enforced by their holders in court. Which interests get which protection is a political and technical choice that can be revised, so some planning goals could be reached by creating markets in property rights; Needham finds this feasible only under limited circumstances.",
summary:["Reframing (pp. 23–26): planning is usually justified by 'the public interest', which Needham rejects: it is hard to substantiate, economic 'distortion' arguments no longer convince, and it depersonalises: 'But we too are the public!' People have interests in how land is used, their own and their neighbours' (a deep hole, a pink door, traffic, shops, open landscape, clean air). The authority upholds 'the identifiable interests of many identifiable private persons'. Planning is also not 'command and control': owners' decisions remain voluntary, and 'Land-use planning will succeed only if it can influence the private decisions' (p. 24), via permits, subsidies/levies, persuasion or infrastructure; only taking ownership removes the decision.",
"Rights (pp. 26–28): ownership is never absolute; owners may not seriously harm others (though many countries allow harm if the benefit exceeds it, Coase), and owners can grant partial rights (a lease). A property right is a way of using land 'recognized by, and protected by, the courts', so rights are created by the state, not natural (against Locke): 'It is the fact that something is protected that makes it a right' (Bromley). The state protects interests in two ways: private law (the interest becomes a property right the holder enforces in court) and public law (a public authority such as a municipality restricts how others use their rights, e.g. via building permits). Which route applies is partly political (the door colour is not protected at all) and partly technical (right of support: clear cause and few parties; clean air: diffuse effects, hundreds of victims who cannot organise a lawsuit, so public law).",
"Rights as policy variable (pp. 28–29): because the split is a decision, it can be revised; property rights can 'be deliberately changed in order purposefully to influence land use', although rights carry high ideological content and the ECHR limits change. Example: vesting future generations' interests as rights held by trustees. A market exists when there is a wanted good, voluntary exchange with free choice of partner, and regular exchange (Hodgson). As markets cannot be excluded (Lindblom), 'planning or the market?' is the wrong question; it is about the mix (Buitelaar), and moving protection from public to private law means creating markets in property rights.",
"Method and cases (pp. 30–34): Coase's reciprocity ('Should A be allowed to harm B or should B be allowed to harm A?'), Ellickson's alternatives to zoning and Webster & Lai's club goods. Needham distinguishes this from libertarian attacks on planning, keeps the planning goals, and compares instruments by effectiveness ('remediability', Williamson), not by assumed efficiency. Four cases: housing-estate amenity via covenants and a residents' association (US, England; not binding in the Netherlands); industrial estates maintained by one investor-landlord (not possible in NL: no compulsory association, leases not tradable, so estates decay and need public money; fix: make unexpired leases saleable); privately owned public spaces under permit conditions; and regional coherence, where effects are too dispersed for a market, though US conservation agreements buy development rights.",
"Conclusions (pp. 34–35): creating markets in property rights is feasible 'only under certain limited circumstances', and feasibility is not desirability. Advantages: less inflexible, no public compensation for 'takings'; risks: exclusive developments such as gated communities and urban fragmentation. Politically neither left nor right: with Blomley, Needham argues poorer people can be empowered by giving them rights in property. Course framing (HC6): rational choice can explain transformation through deliberate redesign of rights, while Taylor shows reproduction by insiders."],
concepts:[["Interest in land","What a person wants regarding how any land is used (own or others'); only some interests are protected, as rights or by planning (pp. 25–28)."],["Property right","'A way of using land (and buildings), where that way is recognized by, and protected by, the courts' (p. 27); created by the state, never absolute."],["Private-law protection","The state makes an interest a property right; the holder takes the violator to court on her own initiative (p. 27)."],["Public-law protection","A public authority uses powers (permits, prohibitions) to protect those who cannot protect their interests otherwise: land-use planning (pp. 27–28)."],["Political vs technical allocation","Whether an interest is protected at all is political; whether as right or by regulation depends on clarity of cause–effect and number of parties (p. 28)."],["Property rights as policy variable","Since rights are created, they can be deliberately changed to steer land use, like land tenure reform (pp. 28–29)."],["Market (Hodgson)","Something wanted; voluntary exchange with free choice of partner; regular exchange among more people (p. 29)."],["Coasean reciprocity","Restricting A to protect B harms A; the question is who may harm whom (p. 30)."],["Remediability","Williamson's approach: compare how effectively alternative instruments reach the same policy goal, not maximum efficiency (p. 30)."],["Creating markets in property rights","Shifting protection from public law to private law, creating exchange structures in which people realise planning goals themselves (pp. 29–31)."]],
fig:`<svg viewBox="0 0 620 310" role="img" aria-label="How the state allocates interests in land to property rights, public-law planning, or no protection"><defs><marker id="ndh9a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="210" y="8" width="200" height="48" rx="8" class="bxi"/><text x="310" y="28" text-anchor="middle" font-weight="700">People's interests</text><text x="310" y="44" text-anchor="middle">in how land is used</text>
<rect x="210" y="84" width="200" height="48" rx="8" class="bx"/><text x="310" y="104" text-anchor="middle" font-weight="700">State decides</text><text x="310" y="120" text-anchor="middle">political + technical</text>
<line x1="310" y1="56" x2="310" y2="82" class="ln" stroke-width="1.5" marker-end="url(#ndh9a)"/>
<line x1="290" y1="132" x2="110" y2="170" class="ln" stroke-width="1.5" marker-end="url(#ndh9a)"/><line x1="310" y1="132" x2="310" y2="170" class="ln" stroke-width="1.5" marker-end="url(#ndh9a)"/><line x1="330" y1="132" x2="510" y2="170" class="ln" stroke-width="1.5" marker-end="url(#ndh9a)"/>
<rect x="15" y="172" width="180" height="92" rx="8" class="bxg"/><text x="105" y="193" text-anchor="middle" font-weight="700">Property right</text><text x="105" y="210" text-anchor="middle">private law: holder</text><text x="105" y="225" text-anchor="middle">sues in court</text><text x="105" y="245" text-anchor="middle" class="mut">right of support</text>
<rect x="220" y="172" width="180" height="92" rx="8" class="bxw"/><text x="310" y="193" text-anchor="middle" font-weight="700">Public-law protection</text><text x="310" y="210" text-anchor="middle">authority: permits,</text><text x="310" y="225" text-anchor="middle">prohibitions</text><text x="310" y="245" text-anchor="middle" class="mut">clean air (diffuse)</text>
<rect x="425" y="172" width="180" height="92" rx="8" class="bx"/><text x="515" y="193" text-anchor="middle" font-weight="700">Not protected</text><text x="515" y="210" text-anchor="middle">interest judged</text><text x="515" y="225" text-anchor="middle">less important</text><text x="515" y="245" text-anchor="middle" class="mut">neighbour's door colour</text>
<path d="M300,266 Q205,292 115,268" class="accs" fill="none" stroke-width="1.5" marker-end="url(#ndh9a)"/>
<text x="310" y="304" text-anchor="middle">Shift public law to property right = create a market in property rights (p. 29)</text></g></svg>`,
cap:"Two state routes for protecting interests in land (p. 27); the allocation is revisable, which is Needham's opening for 'markets in property rights'.",
table:{head:["Situation (pp. 31–34)","Usual public-law route","Property-rights route","Verdict in the chapter"],rows:[
["Amenity in housing estates","Plan conditions, permits, monitoring","Covenants enforced by a residents' association (US 'private community associations', English 'scheme of development')","Feasible; not legally binding in NL (membership cannot be compulsory)"],
["Well-maintained industrial estates","Building/planning plus environmental permits (poor at maintenance)","One investor-landlord owns and leases the estate, maintaining its value","Works in England/US; in NL estates decay; fix: make unexpired leases tradable"],
["Urban public spaces","Municipality provides and maintains","Privately owned, publicly accessible spaces (malls, resident-owned spaces) under permit conditions","Rights deliberately created for a type of urban environment"],
["Coherent regional development","Land-use plans and infrastructure","Market in rights hardly realistic: effects too dispersed","Only public bodies/trusts using private law, e.g. US conservation agreements buying development rights"]]},
example:"Dutch industrial estates (p. 32): firms that own their buildings cannot be obliged to join an association that maintains shared spaces, and tenants avoid long leases because an unexpired lease cannot be sold on. So nobody holds the rights needed to protect the shared interest in quality, estates deteriorate quickly, and only large amounts of public money improve them. In England/US one investor-landlord holds the rights and maintains the estate to protect his investment.",
quotes:["\"Land-use planning will succeed only if it can influence the private decisions.\" (p. 24)","\"The authority is acting not so much to uphold some general public interest, as to uphold the identifiable interests of many identifiable private persons.\" (p. 26)","\"It is the fact that something is protected that makes it a right, rather than that something is protected because it is a right\" (Bromley 1998, quoted p. 27)","\"creating markets in property rights is a feasible alternative only under certain limited circumstances\" (p. 34)"],
dims:{sa:60,rt:75,de:15,us:45,mp:65,norm:"Protecting the legitimate interests of identifiable citizens; effectiveness (remediability) rather than efficiency; freedom and responsibility of rights holders; empowering the poor through rights; wary of exclusion and fragmentation."},
exam:"Know the two routes (private vs public law), the political vs technical allocation (door colour, right of support, clean air), rights as state-created and changeable, and the modest conclusion (feasible only in limited circumstances; feasibility is not desirability). Traps: Needham does NOT reject planning's goals or legitimacy, does NOT argue for replacing planning with markets, does NOT assume efficiency is the goal, and says the approach is neither left nor right. The lecture's 'veto of landowners' and 'dual role of the state' matrix are course framings. Link to Olson: the clean-air case is a collective action problem (many diffuse victims cannot organise). Critique angles: Marxism/political economy (rights reflect and reproduce class power; Needham himself concedes gated communities and fragmentation), communicative planning (interests are formed in deliberation, not given), historical institutionalism (path dependence makes rights hard to change: 'high ideological content')."},

{id:"olson", wk:3, title:"Hindmoor (2006) Mancur Olson and the logic of collective action", cite:"Hindmoor, A. (2006). Mancur Olson and the logic of collective action. In Rational Choice (ch. 5, pp. 102–128). Basingstoke: Palgrave Macmillan", theory:"Rational choice (collective action / public choice)", status:"full",
statusNote:"Built from the full chapter (OCR of scanned pages 102–128). Pages 124–125 (Box 5.5 on norms and part of the Marwell & Ames discussion) are badly garbled in the OCR; only clearly legible content from them is used. Lecture HC6 (Airbnb as a collective action problem) used for the course application. Note: 'exploitation of the great by the small', 'by-product theory' and a lobby of 'concentrated vs diffuse interests' do NOT appear in this chapter.",
one:"Collective goods are non-excludable, so each rational, self-interested member may free-ride and the good goes under-provided: a collective action problem, best modelled as an (N-person) prisoners' dilemma. Olson does not claim collective action is impossible; groups overcome the problem through coercion, privileged members, selective incentives, process benefits, or conditional cooperation. The self-interest assumption and the lack of a full theory of group formation limit the account.",
summary:["The problem (pp. 102–105): Olson (1965) challenged the assumption that people with common interests will act on them: 'unless the number of individuals is quite small, or there is coercion or some other special device', self-interested individuals will not act for their group interest. Goods are classed by excludability and rivalness (Box 5.1): public goods (defence), common-pool goods (fisheries), toll goods, private goods. Olson defines public goods only by non-excludability, so the problem covers common goods too. Examples: union dues, Marxist revolution (why risk the barricades?), pluralists such as Truman and Bentley (latent groups like migrant workers may never form), CO2 emissions, the security dilemma.",
"Game theory (pp. 105–112; Olson himself used none): the prisoners' dilemma (Jake and Keith) has a dominant strategy of defection and a Pareto-inferior equilibrium; the N-person version (join a protest or stay home) shows free-riding. Not every collective action problem is a PD: in the assurance game (the dam needs both farmers) there is no dominant strategy and cooperation should be easy; in chicken (either farmer can fix the dam) each tries to make the other do it, and 'anything can happen'.",
"Solutions (pp. 113–121): Olson 'does not suggest that groups will always fail'. (1) Coercion by the state (taxes; Hardin's leviathan for the tragedy of the commons, against which free-market economists propose property rights and tradeable permits based on Coase) or by gangs (Gambetta's Mafia enforcing exchange). (2) Privileged groups: at least one member values the good enough to pay the whole cost (flatmate who cleans; hegemonic stability); several such members can turn it into chicken. (3) Selective incentives: positive (union legal aid) or negative (ostracism); they raise a second-order collective action problem, possibly solved by entrepreneurs. (4) Process benefits: participation itself is rewarding (Chong on civil rights; kibbutz gossip). (5) Conditional cooperation in intermediate groups, where members notice who contributes: tit-for-tat won Axelrod's tournaments; Ostrom shows communities manage commons without leviathan or market when interaction is long-term, exit is costly, monitoring is cheap and groups are tightly integrated.",
"Group size (p. 121): large groups are more likely to be latent, because contributions are easier to see in small groups, but the link is 'at most, an empirical tendency' (a mining community vs strangers in a bed-sit). Limits (pp. 122–128): people also contribute because norms say they ought to; Olson concedes his theory cannot explain 'non-economic' groups like Greenpeace or Amnesty. Experiments (Marwell & Ames) find substantial group contributions that fall, but stay positive, when stakes rise; a few unconditional cooperators may be needed to pass the threshold at which cooperation becomes stable. Assessment: Olson was the first to give a general analysis and inspired many case studies, but he offers no comprehensive theory of how interests and group identities form, how platforms are agreed, how collective action changes policy, or why groups collapse; social psychology and insider-group research are needed too.",
"Course application (HC6, not in the chapter): Airbnb regulation lags because hosts/investors organise while neighbours free-ride. Hindmoor's chapter supports the free-riding part, but warns that size is only a tendency and that small groups organise when one member gains enough (privileged) or when members can monitor each other (intermediate). The link with Needham: diffuse harms such as air pollution cannot be protected by individual property rights because victims cannot organise to sue."],
concepts:[["Collective action problem","All members gain if they act together, but no individual gains from contributing to the collective good: free-riding (p. 102)."],["Public / common-pool / toll / private goods","Classified by excludability and rivalness (Box 5.1); Olson's definition uses non-excludability only, so common-pool goods face the problem too."],["Prisoners' dilemma","Game where defection is the dominant strategy and the equilibrium is Pareto-inferior to mutual cooperation (pp. 105–110)."],["Assurance and chicken","Collective action games without a dominant strategy: assurance (both needed, cooperation easy); chicken (one suffices, each waits for the other) (pp. 110–112)."],["Latent / privileged / intermediate group","Latent: nobody bears their share; privileged: at least one member will pay the full cost (Olson 1965: 48–50); intermediate: members notice whether others contribute (Olson 1965: 50)."],["Selective incentives","Excludable rewards for contributors (e.g. free legal representation) or punishments for non-contributors (e.g. ostracism) (Olson 1965: 133–5)."],["Second-order collective action problem","Applying selective incentives (e.g. punishing free-riders) is itself a collective good, risking an infinite regress (pp. 116–117)."],["Process benefits","Instrumental or expressive rewards from participating itself; tied to the collective good, so the problem 'simply dissolves' (pp. 117–118)."],["Conditional cooperation / tit-for-tat","Cooperate as long as others do; in iterated games tit-for-tat wins on average via simplicity, generosity, responsiveness (pp. 118–120)."],["Ostrom's self-governed commons","Communities build rules of allocation, monitoring and sanctioning for common-pool resources without a leviathan or the market (p. 120)."]],
fig:`<svg viewBox="0 0 620 262" role="img" aria-label="The collective action problem and five ways groups overcome it"><defs><marker id="ols9a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="195" y="8" width="230" height="64" rx="8" class="bxa"/><text x="310" y="28" text-anchor="middle" font-weight="700">Collective action problem</text><text x="310" y="44" text-anchor="middle">free-riding on a non-</text><text x="310" y="59" text-anchor="middle">excludable good (N-person PD)</text>
<line x1="270" y1="72" x2="62" y2="126" class="ln" stroke-width="1.5" marker-end="url(#ols9a)"/><line x1="290" y1="72" x2="183" y2="126" class="ln" stroke-width="1.5" marker-end="url(#ols9a)"/><line x1="310" y1="72" x2="304" y2="126" class="ln" stroke-width="1.5" marker-end="url(#ols9a)"/><line x1="330" y1="72" x2="425" y2="126" class="ln" stroke-width="1.5" marker-end="url(#ols9a)"/><line x1="350" y1="72" x2="546" y2="126" class="ln" stroke-width="1.5" marker-end="url(#ols9a)"/>
<rect x="6" y="128" width="112" height="96" rx="8" class="bxi"/><text x="62" y="150" text-anchor="middle" font-weight="700">Coercion</text><text x="62" y="168" text-anchor="middle">state taxes;</text><text x="62" y="183" text-anchor="middle">Hardin's leviathan;</text><text x="62" y="198" text-anchor="middle">Mafia</text>
<rect x="127" y="128" width="112" height="96" rx="8" class="bxg"/><text x="183" y="150" text-anchor="middle" font-weight="700">Privileged</text><text x="183" y="168" text-anchor="middle">one member pays</text><text x="183" y="183" text-anchor="middle">the whole cost</text><text x="183" y="198" text-anchor="middle">(hegemon)</text>
<rect x="248" y="128" width="112" height="96" rx="8" class="bxg"/><text x="304" y="150" text-anchor="middle" font-weight="700">Selective</text><text x="304" y="165" text-anchor="middle" font-weight="700">incentives</text><text x="304" y="183" text-anchor="middle">+ legal aid</text><text x="304" y="198" text-anchor="middle">- ostracism</text>
<rect x="369" y="128" width="112" height="96" rx="8" class="bxg"/><text x="425" y="150" text-anchor="middle" font-weight="700">Process</text><text x="425" y="165" text-anchor="middle" font-weight="700">benefits</text><text x="425" y="183" text-anchor="middle">taking part is</text><text x="425" y="198" text-anchor="middle">itself rewarding</text>
<rect x="490" y="128" width="112" height="96" rx="8" class="bxg"/><text x="546" y="150" text-anchor="middle" font-weight="700">Conditional</text><text x="546" y="165" text-anchor="middle" font-weight="700">cooperation</text><text x="546" y="183" text-anchor="middle">intermediate groups;</text><text x="546" y="198" text-anchor="middle">tit-for-tat, Ostrom</text>
<text x="310" y="250" text-anchor="middle" class="mut">Olson: groups face the problem but may overcome it (p. 113); limits: norms, identity (pp. 122–128)</text></g></svg>`,
cap:"Hindmoor's structure: one problem, five routes out; the chapter stresses that Olson never said collective action is impossible.",
table:{head:["Game","Story in the chapter","Dominant strategy?","Outcome"],rows:[
["Prisoners' dilemma","Jake and Keith: confess or stay quiet","Yes: defect (confess)","Both confess (3, 3) although both prefer (2, 2)"],
["N-person prisoners' dilemma","Join a street protest or stay home","Yes: stay home","Everyone defects; cooperation Pareto-superior but individually irrational"],
["Assurance","Dam survives only if both farmers work","No","Cooperation should be easily achieved if rationality is common knowledge"],
["Chicken","One day of work by either farmer saves the dam","No","Each tries to pre-commit to defect; in a single play 'anything can happen'"]]},
example:"Ostrom's Valencia irrigation system (p. 121): it is designed so that the person whose turn is next has a built-in incentive to check that the current user does not take more than their share, lowering monitoring costs so conditional cooperation can last without state coercion or privatisation. Course application (HC6): short-term rental hosts organise while neighbours free-ride, so regulation lags.",
quotes:["\"Olson argues that groups face a collective action problem but recognizes that they may be able to overcome it.\" (p. 102)","\"Though all of the members of a group therefore have a common interest in obtaining this collective benefit, they have no common interest in paying the cost of providing that collective good.\" (Olson 1965: 21, quoted p. 104)","\"Yet the relationship between size and 'latency' is, at most, an empirical tendency.\" (p. 121)","\"Successful collective action will not usually depend upon everyone in a group eschewing their self-interest. In its early stages it may however require that a few are prepared to do so.\" (p. 127)"],
dims:{sa:85,rt:40,de:50,us:20,mp:20,norm:"Explanatory rather than normative; implicitly, collective goods are under-provided without coercion, incentives or institutions; Hindmoor stresses the limits of the self-interest assumption."},
exam:"Definitions are MCQ material: privileged (one member bears full cost) vs intermediate (members can notice others' contribution) vs latent; positive vs negative selective incentives; PD vs assurance vs chicken (which have a dominant strategy?). Big trap: 'Olson shows collective action is impossible/irrational': the chapter says this reading is wrong. Second trap: small group size is not the definition of a privileged group, and size predicts latency only as a tendency. Framework: methodological individualism (agency), universal rationality assumptions (monist, universal), change deliberate (incentive design, coercion) or emergent (tit-for-tat norms, Ostrom). Critique angles: sociological institutionalism and norms (people contribute because they ought to), communicative planning (identity and interests formed in interaction), Marxism/power (who can organise reflects structural resources, not only group size)."}
];

const FC_A=[
["hayek","How does Hayek define what all collectivist systems share?","'The deliberate organisation of the labours of society for a definite social goal' (p. 42). Communism and fascism differ only in the goal; all refuse autonomous spheres where individual ends are supreme."],
["hayek","Why is 'the common good' or 'general welfare' no basis for a single plan (Hayek)?","The terms are too vague to decide any action; welfare cannot be measured on one scale. A single plan presupposes a 'complete ethical code' ranking every need, which does not exist (pp. 42–43)."],
["hayek","Does Hayek's individualism assume people are selfish?","No, explicitly not (p. 44). It starts from the limits of imagination: nobody can include more than a sector of society's needs in his scale of values, so only partial, inconsistent scales exist, and the individual should judge his own ends."],
["hayek","Hayek: why does state control spread once the public sector is large?","Agreement falls as the scope of common action grows; once the state controls a large share of resources (Germany 1928: 53% of national income) it indirectly controls almost the whole economy (p. 45)."],
["hayek","Hayek's journey metaphor","Agreeing on central planning without agreeing on ends is like committing to a journey together without agreeing where to go: most end up on a journey they do not want (p. 46)."],
["hayek","Why can a parliament not adopt an economic plan by majority vote (Hayek)?","Majorities form between limited alternatives; it is a 'superstition' that there is a majority on everything. A plan needs a unitary conception, so voting clause by clause 'makes nonsense' and the task is delegated to experts (pp. 47–48)."],
["hayek","Hayek's military-campaign analogy","Like a campaign, a plan gets delegated to experts; but a general has one supreme goal, while an economic planner must choose between competing ends of different people, so experts impose their own scale of preferences (p. 48)."],
["hayek","When is delegation objectionable for Hayek?","Not delegation as such: delegating general rule-making, even to local authorities, can be fine. It is objectionable when it delegates discretion over particular cases ('judging the case on its merits'), which amounts to arbitrary power (p. 49)."],
["hayek","Hayek on the value of democracy","A means, 'a utilitarian device for safeguarding internal peace and individual freedom' (p. 52), not the highest end; a homogeneous majority can be oppressive. What prevents arbitrary power is 'not the source but the limitation of power' (p. 53)."],
["hayek","Which lecture ideas about Hayek are NOT in 'Planning and democracy'?","Spontaneous order/kosmos vs taxis (later work, e.g. Law, Legislation and Liberty), dispersed local knowledge (Hayek 1945, via Cozzolino), complex phenomena/indeterminism, and 'equality of rights' as a label. The chapter argues from value pluralism and the mechanics of majority rule and delegation."],
["needham","Why does Needham reject 'the public interest' as the justification for planning?","It is hard to substantiate, economic 'distortion' arguments no longer convince, and it depersonalises those affected: 'But we too are the public!' (p. 25). Planning upholds 'the identifiable interests of many identifiable private persons' (p. 26)."],
["needham","Is land-use planning 'command and control' for Needham?","No. Owners' decisions stay voluntary; the authority cannot decide unless it owns the land. It influences via permits, subsidies/levies, persuasion and infrastructure; only (compulsory) purchase takes the decision away (pp. 24–25)."],
["needham","Needham's two ways the state protects interests in land","Private law: the interest becomes a property right that the holder enforces in court. Public law: a public authority (e.g. a municipality) restricts how others use their rights, via permits and prohibitions, for those who cannot protect themselves (p. 27)."],
["needham","Why is there a right of support but no property right to clean air (Needham)?","Technical reasons: foundation damage has a clear cause and few parties, so private enforcement works. Air pollution is diffuse and affects hundreds who would struggle to cooperate in a lawsuit, so it is protected by public law (p. 28)."],
["needham","Needham's example of an interest protected neither way, and why","The colour of the neighbour's front door: it was decided politically that my interest in it matters less than hers (p. 28)."],
["needham","What makes something a property right, according to Needham (quoting Bromley)?","Court protection: 'It is the fact that something is protected that makes it a right, rather than that something is protected because it is a right' (p. 27). Rights are state-created, not natural (contra Locke), so they differ between countries and can be a 'policy variable'."],
["needham","Why is 'planning or the market?' the wrong question for Needham?","Voluntary exchange cannot be excluded from land-use processes (Lindblom), so the real question is the mix of planning and market (Buitelaar). Shifting protection from public to private law creates markets in property rights (p. 29)."],
["needham","What is Williamson's 'remediability' approach as Needham uses it?","Not assuming economic efficiency is the goal of policy, but comparing how effectively different instruments achieve the same politically chosen goals (p. 30)."],
["needham","Why do US-style residents' covenants not exist in the Netherlands (Needham)?","Dutch property law does not allow owners to be obliged to join a residents' association (Van Velten 2003), so the market route to residential amenity is blocked; the law could be changed (p. 31)."],
["needham","Needham's overall conclusion on markets in property rights","Feasible 'only under certain limited circumstances' (p. 34), and feasibility is not desirability. Pros: less inflexible, no public compensation for 'takings'; cons: exclusivity (gated communities), fragmentation. Politically neither left nor right (pp. 34–35)."],
["olson","Hindmoor: is Olson arguing that collective action is impossible or irrational?","No. 'This is simply not the case' (p. 102): Olson says groups face a collective action problem but may overcome it, and much of The Logic analyses how (p. 113)."],
["olson","How does Olson define a public good, and why does it matter (Box 5.1)?","Solely by non-excludability: those who do not pay cannot be kept from consuming it (Olson 1965: 12). So the collective action problem affects common-pool goods (rival but non-excludable, e.g. fisheries) as well as pure public goods."],
["olson","Privileged vs intermediate group","Privileged: at least one member values the good so much they will bear the entire cost and tolerate free-riding (Olson 1965: 48–50). Intermediate: members can notice whether others contribute, enabling conditional cooperation (Olson 1965: 50)."],
["olson","What is the second-order collective action problem?","Selective incentives such as ostracising free-riders are themselves a collective good: why would anyone bear the cost of punishing? This threatens an infinite regress; entrepreneurs or process benefits may solve it (pp. 116–118)."],
["olson","Process benefits (Hindmoor)","Participation itself yields instrumental or expressive benefit (civil rights activists' 'adrenaline rush'; enjoyable kibbutz gossip), so the problem dissolves. Unlike legal aid, the benefit is tied to, even constitutive of, the collective good (pp. 117–118)."],
["olson","Why did tit-for-tat win Axelrod's tournaments?","It cooperates first, then copies the other's last move. It wins on average (not every game) through simplicity, generosity (rewards cooperation) and responsiveness (punishes defection) (pp. 119–120)."],
["olson","Ostrom's conditions for conditional cooperation (Hindmoor)","Long-term interaction (reputation), costly exit, cheap monitoring (e.g. Valencia irrigation turns), and tightly integrated groups. Then communities manage commons without a leviathan or the market (pp. 120–121)."],
["olson","Is group size the key to latency, according to Hindmoor?","Olson suggests large groups are more likely latent because contributions are harder to see, but the link is 'at most, an empirical tendency' (p. 121): a large mining community can know its free-riders; bed-sit neighbours may not know each other."],
["olson","Two limits of Olson's account (Hindmoor's assessment)","(1) The self-interest assumption: norms make people contribute, and Olson concedes he cannot explain 'non-economic' groups like Greenpeace or Amnesty. (2) No comprehensive theory of how group interests and identities form, platforms are agreed, policy changes or groups collapse (pp. 122–128)."],
["olson","Hardin's tragedy of the commons: coercive vs free-market solution (Box 5.3)","Hardin: a 'leviathan' must control access to common-pool resources. Free-market economists: define property rights (Demsetz) and use tradeable permits based on the Coase theorem (pp. 113–114). Links to Needham's markets in property rights."]
];

const MCQ_A=[
{t:"hayek",q:"In 'Planning and democracy', Hayek bases the 'philosophy of individualism' on…",o:["the assumption that people are egoistic and should be","the fact that no mind can include more than a sector of society's needs in its scale of values","the natural right to property","the proven efficiency of spontaneous market order"],a:1,e:"Hayek explicitly denies the egoism reading (p. 44); individualism rests on the limits of imagination and the partial nature of all value scales."},
{t:"hayek",q:"Which statement is consistent with Hayek's chapter?",o:["Democracy is the highest political end","Delegation of law-making power is objectionable in itself","It is the price of democracy that in some fields things must be left to chance","Dictatorship must inevitably extirpate freedom"],a:2,e:"p. 51. He calls democracy a means (p. 52), accepts delegation of general rule-making (p. 49), and says his point is not that dictatorship must destroy freedom (p. 52)."},
{t:"hayek",q:"Mannheim argued that sovereignty can be boundlessly strengthened without renouncing democratic control. Hayek replies that…",o:["parliament can control only where it has agreed on the aim; otherwise it ends up choosing persons with practically absolute power","Mannheim is right as long as parliament keeps the right to vote","experts are always democratically accountable","planning is compatible with democracy if done locally"],a:0,e:"p. 51: without agreement on ends, parliament can only accept or reject the whole plan; the system tends towards plebiscitarian dictatorship."},
{t:"hayek",q:"Which concept on the HC4 slides does NOT appear in 'Planning and democracy'?",o:["A complete ethical code","Delegation to experts","Plebiscitarian dictatorship","Spontaneous order"],a:3,e:"Spontaneous order comes from Hayek's later work (kosmos/taxis, via Moroni); the other three are central to ch. 5."},
{t:"hayek",q:"How does Hayek explain Hitler's rise to power in this chapter?",o:["Hitler destroyed a functioning democracy by force","Democracy had already decayed under demands for planning; Hitler seemed the only man strong enough to get things done","The working class organised a revolution","Laissez-faire capitalism produced a crisis that required a dictator"],a:1,e:"'Hitler did not have to destroy democracy; he merely took advantage of the decay of democracy' (p. 50)."},
{t:"needham",q:"According to Needham, why is a person's interest in clean air protected by public law rather than by a property right?",o:["Clean air has no economic value","Effects are diffuse, cause and effect are unclear, and hundreds of victims could hardly cooperate to sue","The ECHR forbids property rights in air","It has been decided that clean air matters less than the factory's interest"],a:1,e:"p. 28: the 'technical' reason. The door-colour example is the 'political' reason (option D)."},
{t:"needham",q:"What does Needham conclude about creating markets in property rights?",o:["They should replace land-use planning","They are infeasible in all cases","They are a feasible alternative only under certain limited circumstances, and feasibility is not desirability","They are always more efficient than regulation"],a:2,e:"p. 34. He explicitly does not recommend replacing planning (p. 23) and does not compare desirability."},
{t:"needham",q:"In Needham's terms, which is an example of the 'private law' way of protecting interests in land?",o:["A municipality refusing a building permit","Emission limits for factories","A homeowner taking her neighbour to court for undermining her foundations (right of support)","A zoning plan for a region"],a:2,e:"Private law: the holder of the right enforces it herself in court (pp. 27–28). The others are public-law measures."},
{t:"needham",q:"Why, according to Needham, do Dutch industrial estates tend to deteriorate?",o:["Municipalities refuse environmental permits","Firms cannot be obliged to join a maintenance association and leases are not tradable, so nobody holds the rights needed to maintain the estate","Property investors own too many estates","Dutch planning is too market-led"],a:1,e:"p. 32: the fix he suggests is making it possible to sell unexpired leases, i.e. changing a property right."},
{t:"needham",q:"How does Needham position his investigation relative to libertarian critics of planning (e.g. Sorensen)?",o:["He agrees that there are no external effects of land use","He accepts planning's goals and the legitimacy of the state influencing land use, and only questions the instruments","He argues that public authorities cannot protect anyone's interests","He argues that property rights are natural and absolute"],a:1,e:"p. 30: libertarians deny externalities or the state's capacity; Needham asks only whether goals can be reached by changing rights."},
{t:"olson",q:"Hindmoor argues that the common reading of Olson as showing that collective action is impossible or irrational is…",o:["correct: Olson proves groups cannot organise","wrong: Olson argues groups face a collective action problem but may overcome it","correct only for small groups","irrelevant, because Olson used game theory to prove the opposite"],a:1,e:"pp. 102, 113 and 127. Olson did not use game theory himself (Box 5.2)."},
{t:"olson",q:"Two farmers' crops depend on a dam that is maintained only if BOTH work on it. Which game is this and what follows?",o:["Prisoners' dilemma: both defect","Chicken: each waits for the other","Assurance game: no dominant strategy, and cooperation should be easily achieved","Tragedy of the commons: a leviathan is needed"],a:2,e:"pp. 110–111. If one day's work by EITHER farmer suffices, it becomes chicken."},
{t:"olson",q:"The 'second-order collective action problem' refers to…",o:["the fact that punishing or rewarding contributors (selective incentives) is itself a collective good that someone must provide","a collective action problem that occurs twice in a row","conflict between two different groups","the failure of the state to coerce"],a:0,e:"pp. 116–117: why would anyone ostracise the one who failed to ostracise? Entrepreneurs or process benefits can break the regress."},
{t:"olson",q:"What does Hindmoor conclude about the relationship between group size and latency?",o:["Large groups can never organise","Small groups are by definition privileged","It is at most an empirical tendency: what matters is whether members can see who cooperates","Group size has no relationship at all with latency"],a:2,e:"p. 121: a large mining community may know its free-riders; bed-sit residents may not."},
{t:"olson",q:"Ostrom's work on common-pool resources, as presented by Hindmoor, shows that…",o:["only privatisation saves the commons","only a coercive leviathan saves the commons","communities can devise their own rules of allocation, monitoring and sanctioning, sustaining cooperation without a leviathan or the market","commons always end in tragedy"],a:2,e:"p. 120: conditional (tit-for-tat) cooperation, most likely with long-term interaction, costly exit, cheap monitoring and integrated groups."},
{t:"olson",q:"Which is a NEGATIVE selective incentive in Olson's sense?",o:["Free legal representation for union members","Workers who do not join the union being ostracised ('sent to Coventry')","A pay rise for all workers","The adrenaline rush of protesting"],a:1,e:"p. 116. A is a positive selective incentive, C is the collective good itself, D is a process benefit."}
];

const OPEN_A=[
{t:"hayek",pts:12,q:"A Dutch municipality wants to meet its housing target by deciding every large development 'on its merits' through negotiated, discretionary deals, with the council approving the overall programme only as a package. (a) Explain how Hayek (1944, 'Planning and democracy') would criticise this approach, using at least three concepts from the chapter. (b) Contrast this with how a Marxist-inspired planner (as presented in HC4) would evaluate the same approach.",
model:"(a) Hayek would see a small-scale version of the mechanism in ch. 5. A housing programme serves many competing ends (affordability, density, green space, profit), and there is no 'complete ethical code' ranking them; the council can agree that there must be a plan but not on its content. Presenting it as a package leaves parliament (here the council) only to accept or reject the whole, so criticism 'cannot direct' (p. 51). Deciding cases 'on their merits' is exactly the delegation of discretion Hayek calls arbitrary power (p. 49); general rules, even local ones, would be acceptable. The officials negotiating deals must choose between ends and therefore impose their own scale of preferences (p. 48). What prevents arbitrariness is 'not the source but the limitation of power' (p. 53): democratic approval of the package does not make the discretion legitimate. Hayek's alternative is to restrict collective action to where true agreement exists and to use general rules. (b) A Marxist planner (Madden & Marcuse in HC4) would judge the approach on outcomes: markets turn housing into a commodity and produce material inequality, so the problem is not too much discretion but that deals with developers reproduce the structural logic of profit. They would support stronger, deliberate intervention (decommodified public or cooperative housing) and treat Hayek's formal equality of rights as blind to property power. Contrast: liberty and limited, rule-bound power vs material equality and structural transformation.",
rubric:["Uses at least three chapter concepts correctly (complete ethical code, delegation/discretion vs general rules, plebiscitarian/take-it-or-leave-it plan, limitation of power)","Applies them to the case rather than reciting","Marxist evaluation: structure, commodification, material equality, deliberate transformation","Explicit contrast of normative commitments (liberty/equality of rights vs material equality)"]},
{t:"needham",pts:12,q:"(a) Explain Needham's (2012) distinction between the private-law and public-law ways in which the state protects interests in land, and why the choice between them is partly political and partly technical. (b) Use Olson's logic of collective action (Hindmoor 2006) to explain the 'technical' part. (c) What does this imply for Needham's proposal to reach planning goals by creating markets in property rights?",
model:"(a) People have interests in how land is used, their own and others' (neighbours, traffic, clean air). The state protects some by making them property rights: the holder enforces them in court (private law). It protects others by empowering a public authority to restrict how owners exercise their rights, through permits or prohibitions (public law = land-use planning). Some interests are not protected. Whether an interest is protected is political (my interest in my neighbour's door colour is judged less important than hers). Which route is used is partly technical: a right of support works because cause and effect are clear and few people are involved; for air pollution affecting hundreds, a property right would be ineffective (p. 28). (b) The clean-air case is a collective action problem: winning a lawsuit against the factory is a non-excludable good for all residents, so each has an incentive to free-ride on others' legal action. It is a latent group with diffuse, small individual stakes, while the factory is a single concentrated actor. Unless there are selective incentives, a privileged member or low monitoring costs, nobody sues, so the state provides the good through public law (coercion). (c) Markets in property rights work only where interests can be organised: small estates with covenants and a residents' association (an intermediate group with monitoring), or one landlord who internalises the shared interest (a privileged actor). At regional scale, effects are too dispersed, which explains Needham's conclusion: feasible 'only under certain limited circumstances' (p. 34).",
rubric:["Correct private vs public law distinction with examples","Political (door colour) vs technical (right of support vs clean air) allocation","Correct Olson concepts (non-excludability, free-riding, latent group, possible solutions) applied to the case","Links back to Needham's limited-feasibility conclusion (e.g. residents' association / landlord vs regional scale)"]},
{t:"olson",pts:10,q:"In HC6, the slow regulation of short-term rentals (Airbnb) was explained as a collective action problem. (a) Explain, using Hindmoor's (2006) account of Olson, why neighbours affected by short-term rentals may fail to act collectively. (b) Discuss two mechanisms from the chapter through which they might still organise. (c) Give one limitation of the Olsonian explanation that Hindmoor himself identifies.",
model:"(a) Stricter regulation is a collective good for all neighbours: non-excludable, because every resident benefits from less noise and more housing supply whether or not they campaigned. Campaigning costs time and effort, and each individual's contribution makes little difference, so each prefers to free-ride. This is an N-person prisoners' dilemma: staying home is the dominant strategy, even though everyone campaigning is Pareto-superior. Many dispersed neighbours who hardly know each other form a latent group, while hosts or investors have concentrated stakes (lecture). Hindmoor notes that size is only 'an empirical tendency'; what matters is whether members can see who contributes. (b) Selective incentives: a residents' association (VvE) could offer members-only benefits such as legal advice (positive) or social pressure on non-participants (negative), though this raises a second-order problem that an entrepreneur (an active neighbour or local politician) may solve. Conditional cooperation in intermediate groups: in one building or street, long-term neighbours can monitor each other and cooperate tit-for-tat style, as Ostrom shows for commons. Process benefits (the satisfaction of protecting 'our' neighbourhood) or a privileged member who pays the whole cost are also valid. (c) Olson assumes self-interest: people also act because norms say they ought to, and the theory cannot explain how residents come to identify with a group or how collective action changes policy (pp. 122–128).",
rubric:["Collective good, non-excludability and free-riding correctly applied","Two mechanisms from the chapter, explained and applied (selective incentives, conditional cooperation, process benefits, privileged group, coercion)","Nuance: size only an empirical tendency / Olson does not say it is impossible","One limitation taken from Hindmoor (self-interest and norms; no theory of identity or group formation)"]}
];
