const NEW_B=[
{id:"harvey", wk:6, title:"Harvey (1989) From managerialism to entrepreneurialism", cite:"Harvey, D. (1989). From managerialism to entrepreneurialism: the transformation in urban governance in late capitalism. Geografiska Annaler: Series B, Human Geography 71(1), 3–17. DOI 10.1080/04353684.1989.11879583", theory:"Marxist political economy (historical-geographical materialism)", status:"partial",
 statusNote:"The 1989 article itself is NOT on file. The only file is an encyclopedia entry ABOUT Harvey (Woodward & Jones, 'Harvey, D.', International Encyclopedia of Human Geography, Elsevier 2009, pp. 24–27), which covers his wider framework (historical-geographical materialism, spatial fix, circuits of capital, flexible accumulation, accumulation by dispossession) but not the 1989 argument. The summary of the 1989 article below is built from general knowledge of that text and must be checked against the article itself; no quotes from the 1989 article are given. All quotes are from the encyclopedia entry and labelled as such. Upload the actual article (DOI 10.1080/04353684.1989.11879583) to verify page numbers and add verbatim quotes.",
 one:"Since the early 1970s urban governance in advanced capitalist countries has shifted from managerialism (local provision of services and welfare to residents) to entrepreneurialism (cities competing to attract mobile capital, consumers and state funds). This shift is not a free local choice but is driven by deindustrialisation, fiscal austerity and heightened capital mobility, and it disciplines cities through inter-urban competition, deepening uneven development while shifting risk to the public sector.",
 summary:[
  "Context and claim (general knowledge; verify): In the 1960s urban governments were mainly managerial: they provided services, facilities and benefits to their populations, largely backed by national welfare-state redistribution. From the 1970s, with deindustrialisation, rising unemployment, fiscal austerity, neoliberal ideology and more mobile (flexible) capital, cities across political colours and national systems converged on an entrepreneurial stance: proactively fostering local growth and competing for investment. Harvey stresses that 'urban governance' is broader than urban government: it is a coalition of forces (local state, business, chambers of commerce, developers, financiers, unions, media) in which the formal government is only one part. He also warns against reifying 'the city' as an actor: cities do not act, class alliances and coalitions do.",
  "Three features of urban entrepreneurialism (general knowledge; verify): (1) public-private partnership: traditional local boosterism is combined with the powers of local government to attract external funding, investment and jobs; (2) the partnership is speculative in design and execution, and the public sector typically absorbs the risk while the private sector takes much of the benefit, unlike rational, coordinated development planning; (3) the focus is on the political economy of place (flagship projects: waterfronts, convention centres, stadiums, shopping malls) rather than territory (improving living and working conditions across a jurisdiction), so benefits are indirect and may be narrower or wider than the jurisdiction. Baltimore's Inner Harbor/Harborplace is his signature example.",
  "Four competitive strategies (general knowledge; verify): cities can compete (a) in the international division of labour, creating competitive advantage for production through infrastructure, subsidies, labour and location; (b) in the spatial division of consumption: tourism, spectacle, culture, gentrification, consumer attractions, urban image; (c) for command and control functions in finance, government, information and media; (d) for the redistribution of surplus via central government (e.g. defence spending, higher education, state programmes). Because inter-urban competition works as an external coercive force, successful innovations are rapidly copied: serial reproduction (science parks, festival markets, waterfronts) erodes any temporary advantage, so competition tends towards a zero-sum game and a regressive redistribution towards capital and middle/upper classes.",
  "Consequences and politics (general knowledge; verify): entrepreneurialism fosters ephemeral projects, spectacle and 'bread and circuses', masks growing polarisation and pushes the public sector to underwrite private risk. It is functional to the wider transition from Fordism to flexible accumulation that Harvey theorised in The Condition of Postmodernity (1989). Yet he leaves an opening: the shift is not wholly determined, and a progressive urban corporatism based on alliances between cities rather than competition, and on a clear sense of how capital accumulation works geographically, could in principle turn entrepreneurial capacity to progressive ends. The article became a founding text for literatures on neoliberal urbanism, growth coalitions and inter-urban competition.",
  "Wider framework (from the encyclopedia entry): Harvey's project is a historical-geographical materialism that spatialises Marx: The Limits to Capital (1982) introduces the 'spatial fix' (capitalism resolves crises of overaccumulation by remaking space) and the role of finance; The Urbanization of Capital (1985) shows the city as the key site of accumulation and describes 'capitalist switches' among primary, secondary (built environment) and tertiary circuits (p. 26). The encyclopedia notes that the chapters on urban politics and planning in Urbanization 'presage later work on urban entrepreneurialism' (p. 26). Later work (The New Imperialism 2003; A Brief History of Neoliberalism 2005) theorises 'accumulation by dispossession' through privatisation of social spaces and services (p. 27). Hyötyläinen & Haila and Savini & Aalbers both build on this Harveyan toolkit."
 ],
 concepts:[
  ["Urban managerialism","Governance oriented to the local provision of services, facilities and welfare benefits to residents, backed by national redistribution (typical of the 1960s)."],
  ["Urban entrepreneurialism","Governance oriented to promoting local growth and competing for mobile capital, consumers and state funds; speculative, partnership-based, focused on place rather than territory."],
  ["Public-private partnership","Core institutional form of entrepreneurialism: local state powers combined with private boosterism; public sector tends to absorb risk, private sector captures gains."],
  ["Place vs territory","Entrepreneurialism targets specific places/projects (flagships) rather than improving conditions across the whole territory of a jurisdiction."],
  ["Inter-urban competition","Acts as an external coercive force that disciplines cities into capitalist growth logics; leads to serial reproduction and zero-sum outcomes."],
  ["Serial reproduction","Rapid copying of successful urban strategies (waterfronts, science parks, convention centres) that erodes the competitive advantage each was meant to create."],
  ["Spatial fix (encyclopedia)","'The tendency of capitalism to remake spaces … so as to resolve contradictions and crises generated in production and overaccumulation' (Woodward & Jones 2009, p. 24)."],
  ["Circuits of capital / capital switching","Capital moves from the primary (production) circuit into the secondary circuit (built environment) and tertiary circuit (science, social spending) when overaccumulation threatens (encyclopedia p. 26)."],
  ["Accumulation by dispossession (encyclopedia)","Creating new spaces for capital by dispossessing people of spaces and services to which they have certain rights, e.g. privatisation of state services (p. 27)."],
  ["Flexible accumulation","Post-Fordist regime of more contingent labour and spatially nimble, disintegrated firms (encyclopedia glossary); the macro-context of entrepreneurialism."]
 ],
 fig:`<svg viewBox="0 0 620 260" role="img" aria-label="Shift from managerialism to entrepreneurialism, drivers and four strategies"><defs><marker id="hvA" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="20" width="160" height="70" rx="8" class="bxi"/><text x="90" y="44" text-anchor="middle" font-weight="bold">Managerialism</text><text x="90" y="62" text-anchor="middle">1960s: services,</text><text x="90" y="78" text-anchor="middle">welfare for residents</text>
<rect x="230" y="10" width="160" height="90" rx="8" class="bxw"/><text x="310" y="30" text-anchor="middle" font-weight="bold">Drivers (1970s+)</text><text x="310" y="48" text-anchor="middle">deindustrialisation</text><text x="310" y="64" text-anchor="middle">fiscal austerity</text><text x="310" y="80" text-anchor="middle">mobile capital</text><text x="310" y="95" text-anchor="middle" class="mut" font-size="11">flexible accumulation</text>
<rect x="450" y="20" width="160" height="70" rx="8" class="bxa"/><text x="530" y="44" text-anchor="middle" font-weight="bold">Entrepreneurialism</text><text x="530" y="62" text-anchor="middle">PPP, speculative,</text><text x="530" y="78" text-anchor="middle">place not territory</text>
<line x1="170" y1="55" x2="228" y2="55" class="ln" marker-end="url(#hvA)"/><line x1="390" y1="55" x2="448" y2="55" class="ln" marker-end="url(#hvA)"/>
<line x1="530" y1="90" x2="530" y2="120" class="ln" marker-end="url(#hvA)"/>
<text x="310" y="135" text-anchor="middle" class="mut">four ways to compete (inter-urban competition as coercive force)</text>
<rect x="10" y="148" width="140" height="56" rx="8" class="bx"/><text x="80" y="170" text-anchor="middle">1 Production</text><text x="80" y="188" text-anchor="middle" class="mut">division of labour</text>
<rect x="165" y="148" width="140" height="56" rx="8" class="bx"/><text x="235" y="170" text-anchor="middle">2 Consumption</text><text x="235" y="188" text-anchor="middle" class="mut">spectacle, tourism</text>
<rect x="320" y="148" width="140" height="56" rx="8" class="bx"/><text x="390" y="170" text-anchor="middle">3 Command</text><text x="390" y="188" text-anchor="middle" class="mut">finance, info, gov</text>
<rect x="475" y="148" width="140" height="56" rx="8" class="bx"/><text x="545" y="170" text-anchor="middle">4 Redistribution</text><text x="545" y="188" text-anchor="middle" class="mut">via central state</text>
<rect x="110" y="218" width="400" height="34" rx="8" class="bxa"/><text x="310" y="240" text-anchor="middle">Serial reproduction, zero-sum, uneven development</text>
</g></svg>`,
 cap:"Harvey's argument as a causal chain (built from general knowledge of the 1989 article; verify against the text).",
 table:{head:["","Managerialism","Entrepreneurialism"],rows:[
  ["Period","1960s","From early 1970s"],
  ["Main task","Provide services, facilities, welfare to residents","Foster local growth; attract capital, consumers, funds"],
  ["Institutional form","Local government, national redistribution","Public-private partnership, growth coalition"],
  ["Risk","Low; planned, coordinated","Speculative; public sector absorbs risk"],
  ["Object","Territory (whole jurisdiction)","Place (flagship projects, image)"],
  ["Outcome","Redistribution towards residents","Regressive redistribution, uneven development"]
 ]},
 example:"Baltimore's Inner Harbor redevelopment (Harborplace and related projects) is Harvey's signature example of place-focused, spectacle-driven, public-risk entrepreneurialism (general knowledge; verify). Course link: Hyötyläinen & Haila explicitly use Harvey's (1989) managerial/entrepreneurial pair for Helsinki's sale of Eiranranta to attract 'good taxpayers' and a 'global city' image.",
 quotes:[
  "Encyclopedia entry (Woodward & Jones 2009), not the 1989 article: \"Spatial Fix The tendency of capitalism to remake spaces – either in new places or in the transformation of existing ones – so as to resolve contradictions and crises generated in production and overaccumulation.\" (p. 24)",
  "Encyclopedia entry, quoting Harvey's Urbanization of Capital: \"Capitalist development has therefore to negotiate a knife-edge path between preserving the exchange values of past capital investments in the built environment and destroying the value of these investments in order to open up fresh room for accumulation\" (p. 25)",
  "Encyclopedia entry: \"Chapters on urban politics and planning close out Urbanization. They presage later work on urban entrepreneurialism that was to become one leg of his next major book, The Condition of Postmodernity.\" (p. 26)",
  "Encyclopedia entry on accumulation by dispossession: \"a process of creating new spaces for capitalism by dispossessing people of spaces and services to which they have certain rights.\" (p. 27)"
 ],
 dims:{sa:25, rt:40, de:60, us:30, mp:20, norm:"Social justice and anti-capitalist critique; exposing regressive redistribution and uneven development; hope for a progressive, cooperative (inter-urban alliance) alternative to competition."},
 exam:"Commentary angle: the argument is grounded in Marxist political economy / historical-geographical materialism: structural forces (capital mobility, overaccumulation, fiscal crisis) explain the shift; agency is located in class coalitions, and competition is a coercive structural law. Best critiques: (1) neo-institutionalism (historical/sociological): Harvey's convergence thesis underplays path dependence and national/local institutional variation (e.g. Nordic land ownership in Helsinki; Italian PII regime in Milan); (2) regime theory / urban politics: governing coalitions have real agency and outcomes vary by regime type; (3) governmentality/discourse: entrepreneurialism is also a constructed rationality ('necessity to save', city image), not merely an economic imperative; (4) Hayek/public choice (Tiebout-style): inter-jurisdictional competition can be efficient and disciplines wasteful governments, so Harvey's normative verdict is contestable. Also note monism (class/capital as master variable) and the functionalist risk of explaining every policy by its utility for capital. MCQ traps: entrepreneurialism is not only a right-wing project (Harvey says it spans parties); 'place' vs 'territory' reversed; the four strategies (production, consumption, command, redistribution via central government); Harvey rejects reifying 'the city' as actor."},

{id:"fog", wk:6, title:"Foglesong (1986/2003) Planning the capitalist city", cite:"Foglesong, R.E. (2003). Planning the capitalist city. In S. Campbell & S.S. Fainstein (eds), Readings in Planning Theory (2nd ed.), pp. 102–107. Oxford: Blackwell. Excerpt from Foglesong, R.E. (1986), Planning the Capitalist City: The Colonial Era to the 1920s. Princeton: Princeton University Press.", theory:"Marxist theory of the state / political economy", status:"missing",
 statusNote:"NOT on file. Everything on this page is built from general knowledge of Foglesong's argument, not from the assigned excerpt, and must be checked against the text on Brightspace (Campbell & Fainstein, pp. 102–107). No quotes and no page numbers are given. Treat specific formulations as provisional.",
 one:"Planning in capitalist cities is best explained as a response to contradictions of capitalist urbanisation: above all the property contradiction between the social character of urban land and its private ownership and control, and the capitalism–democracy contradiction. Planning is needed to socialise some control over land for capital's collective interest, yet it is constrained because it must not undermine private property or hand control to democratic majorities.",
 summary:[
  "Problem (general knowledge; verify): mainstream planning theory treats planning as a neutral, technical pursuit of the public interest, or explains it by market failure, without asking why planning exists in capitalist societies and why it takes the limited form it does. Foglesong proposes a Marxist political-economy account that links planning to the structural needs and contradictions of capitalist urbanisation, while rejecting crude functionalism.",
  "Property contradiction (general knowledge; verify): urban land and the built environment are social in character: their value and use depend on collective investment (infrastructure, neighbouring uses) and they serve the reproduction of labour and capital as a whole. Yet land is privately owned and controlled, and individual owners pursue their own returns, producing congestion, incompatible uses, housing crises and threats to property values. Capital collectively needs some socialisation of control over land use (via planning, zoning, public works), but individual capitalists and property owners resist it. Planning is thus both necessary for capital and restricted by it.",
  "Capitalism–democracy contradiction (general knowledge; verify): socialising control over land means transferring decisions to the state, which in a democracy is exposed to popular pressure. The danger for capital is that democratic control over land could go further than capital wants (e.g. redistribution, public housing, limits on property rights). Planning institutions therefore tend to be insulated from democratic control (expert commissions, technical procedures, independent boards), so that planning helps capital while containing popular demands.",
  "Theory of the state (general knowledge; verify): Foglesong positions himself within Marxist debates. Instrumentalist accounts see the state (and planning) as a tool directly controlled by capitalists; structuralist accounts stress that the state has relative autonomy and serves the long-term, collective interests of capital even against individual capitalists. Foglesong leans to a structural, contradiction-based view while leaving room for class struggle and contingency: planning outcomes are shaped by conflicts between capital fractions, property owners and working-class movements. In the 1986 book he applies this to US planning history from the colonial era to the 1920s (housing reform, City Beautiful, zoning)."
 ],
 concepts:[
  ["Property contradiction","Tension between the social character of urban land (collectively produced, collectively needed) and its private ownership and control (general knowledge; verify)."],
  ["Capitalism–democracy contradiction","Socialising land-use control via the state risks democratic control going further than capital accepts; hence planning is insulated from popular pressure (general knowledge; verify)."],
  ["Social character of land","Land value and use depend on collective investments and surrounding uses, not only on the owner's actions."],
  ["Instrumentalist theory of the state","The state (planning) is a tool directly controlled by the capitalist class."],
  ["Structuralist theory / relative autonomy","The state serves capital's long-term collective interests because of structural constraints, even against individual capitalists; it has relative autonomy from specific capitalists."],
  ["Planning as contradictory response","Planning both serves capital (coordination, legitimation) and is constrained by it (property rights, fear of democratic control)."],
  ["Legitimation","Planning also helps legitimise capitalist urban development by presenting it as the public interest."]
 ],
 fig:`<svg viewBox="0 0 620 230" role="img" aria-label="Foglesong's two contradictions leading to constrained planning"><defs><marker id="fgA" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="20" width="190" height="80" rx="8" class="bxa"/><text x="105" y="42" text-anchor="middle" font-weight="bold">Property contradiction</text><text x="105" y="62" text-anchor="middle">social character of land</text><text x="105" y="78" text-anchor="middle">vs private ownership</text><text x="105" y="94" text-anchor="middle" class="mut">and control</text>
<rect x="10" y="130" width="190" height="80" rx="8" class="bxw"/><text x="105" y="152" text-anchor="middle" font-weight="bold">Capitalism–democracy</text><text x="105" y="172" text-anchor="middle">socialised control via</text><text x="105" y="188" text-anchor="middle">state risks popular</text><text x="105" y="204" text-anchor="middle">control of property</text>
<rect x="250" y="75" width="140" height="80" rx="8" class="bxi"/><text x="320" y="100" text-anchor="middle" font-weight="bold">Planning</text><text x="320" y="120" text-anchor="middle">response to</text><text x="320" y="136" text-anchor="middle">contradictions</text>
<line x1="200" y1="60" x2="248" y2="100" class="ln" marker-end="url(#fgA)"/><line x1="200" y1="170" x2="248" y2="130" class="ln" marker-end="url(#fgA)"/>
<rect x="440" y="20" width="170" height="80" rx="8" class="bxg"/><text x="525" y="44" text-anchor="middle">Serves capital:</text><text x="525" y="62" text-anchor="middle">coordination,</text><text x="525" y="78" text-anchor="middle">legitimation</text>
<rect x="440" y="130" width="170" height="80" rx="8" class="bx"/><text x="525" y="154" text-anchor="middle">Constrained:</text><text x="525" y="172" text-anchor="middle">property rights,</text><text x="525" y="188" text-anchor="middle">insulated from</text><text x="525" y="204" text-anchor="middle">democracy</text>
<line x1="390" y1="100" x2="438" y2="65" class="ln" marker-end="url(#fgA)"/><line x1="390" y1="130" x2="438" y2="165" class="ln" marker-end="url(#fgA)"/>
</g></svg>`,
 cap:"Foglesong: planning as a contradictory response to two contradictions of capitalist urbanisation (general knowledge; verify).",
 table:{head:["","Liberal/pluralist view","Instrumentalist Marxism","Structuralist / Foglesong"],rows:[
  ["Why planning exists","Public interest; market failure","Capitalists use the state as a tool","Contradictions of capitalist urbanisation"],
  ["Role of the state","Neutral arbiter among groups","Controlled by capitalist class","Relatively autonomous; serves capital's collective interest"],
  ["Limits of planning","Technical/knowledge limits","Whatever capitalists want","Property rights; fear of democratic control"],
  ["Room for agency","High (groups compete)","Low for non-capitalists","Some: class struggle shapes outcomes"]
 ]},
 example:"Illustration (not from the text): US zoning in the 1910s–20s restricted individual owners' freedom to protect aggregate property values, yet was run by expert commissions rather than popular bodies; both contradictions at work. Course link: in Eiranranta (Hyötyläinen & Haila) and Falck (Savini & Aalbers) the social character of land (public development rights, value capture) collides with private and financial ownership.",
 quotes:[],
 dims:{sa:20, rt:25, de:40, us:30, mp:15, norm:"Critique of planning's claim to neutrality; exposing whose interests planning serves; implicit sympathy for democratic and working-class control over land."},
 exam:"Commentary angle: grounded in Marxist political economy and a structuralist theory of the capitalist state (relative autonomy), with planning explained by contradictions rather than by the public interest. Best critiques: (1) liberal pluralism / communicative planning: planning outcomes reflect many competing groups and deliberation, not just capital; Foglesong risks functionalism (explaining planning by its usefulness to capital); (2) Hayek/liberal: the 'social character' of land does not justify central control; prices and property rights coordinate dispersed knowledge better; (3) public choice: planners and politicians pursue their own interests (bureau-maximising), not capital's; (4) neo-institutionalism: planning systems differ nationally (e.g. Dutch/Nordic public landownership) in ways a general theory of capitalism cannot explain. MCQ traps: the property contradiction is NOT between capital and labour but between social character of land and private ownership/control; the capitalism–democracy contradiction concerns the risk of democratic control of property; instrumentalist vs structuralist definitions swapped."},

{id:"hh", wk:6, title:"Hyötyläinen & Haila (2018) Entrepreneurial public real estate policy: Eiranranta, Helsinki", cite:"Hyötyläinen, M. & Haila, A. (2018). Entrepreneurial public real estate policy: The case of Eiranranta, Helsinki. Geoforum 89, 137–144. DOI 10.1016/j.geoforum.2017.04.001", theory:"Political economy of urban land / neoliberal urbanism (Harvey, Brenner & Theodore)", status:"full",
 statusNote:"Built from the full text of the published article (Geoforum 89, pp. 137–144). Page numbers refer to the journal pagination.",
 one:"Finnish cities and the Finnish state, which own much land, have shifted from administrative allocation and leasing to an 'entrepreneurial public real estate policy': selling land or charging market rent to maximise revenue. The Eiranranta case in Helsinki shows unintended harmful effects: the City ceded planning power, dropped its social housing requirement, reinforced exclusion via record prices, and allowed a fenced enclave for the wealthy that is new in a Nordic welfare city.",
 summary:[
  "Concept and method: entrepreneurial public real estate policy is a rent-maximising land and real estate policy carried out not by private landlords, developers or REITs but by municipalities and the state; it takes two forms, selling public land or charging market rent when leasing, and can be called neoliberal in the sense of introducing a market logic to public land (p. 137). Helsinki owns 60% of its land area (p. 138, fn 3). Leasing had kept planning power with town planners and helped produce a heterogeneous urban fabric without glaring inequalities (p. 138). Data: agendas and minutes of the City Council and Real Estate Committee (REC), interviews with 5 of the 9 REC members who decided the 2005 sale, and field observations/photographs (pp. 137–138). Contribution: political economy of urban land and neoliberal urban policies.",
  "Enabling conditions (pp. 138–139): after the early-1990s recession the state closed the National Board of Public Building (1995) and created state real estate companies (Kapiteeli, Senaatti, Sponda); Helsinki began selling land in 1993, calculated 'shadow rents', and in 2005 set up the Premises Centre charging market rent. Three changes 'scaled down' land-use decisions: (1) a new state urban policy making cities compete for state subsidies via 'urban programmes' and public-private partnerships; (2) a redistribution shift under the ideology of 'the necessity to save', turning the welfare state into welfare cities; (3) the Land Use and Building Act (MRL, 1999), which removed state ratification of local plans and legalised 'development areas' and development contracts. The state, now a real estate player itself, lost its impartial mediating role.",
  "Justification (pp. 139–140): four arguments: put public assets to work (Sipilä); make land use efficient; increase transparency; create diversity. The 'necessity to save' became a Bourdieuian 'strong discourse' that made market rule appear natural; the media and some urban scholars (celebrating diversity of 'luxury' and 'rough' areas) supported it. In Eiranranta (former industrial/depot shore next to prestigious Eira, rezoned residential 2001) the REC decided to sell in March 2004; the highest bid would win. Deputy Mayor Pekka Korpinen, an economist, promoted selling shoreline land to maximise revenue and even renamed the area for marketing. REC members cited the budget's sales targets, inter-city competition with Espoo and Kauniainen for 'good taxpayers', and a 'global city' image vis-à-vis Copenhagen, Stockholm and Tallinn: in Harvey's (1989) terms, managerial strategies were replaced with entrepreneurial ones (p. 140).",
  "The deal and outcomes (pp. 141–142): bids hit a Finnish record of €2621/m², €54 million in total; the newcomer investment company Apollo outbid household developers (SRV, NCC, Tarkala) by €3 million; the Real Estate Department preferred Skanska despite its lower bid. The authors suggest established developers were used to undervaluing land and capturing the value created by public development rights; only one councillor opposed the sale. Apartments sold at €10,000–16,000/m². Eiranranta has no social housing, contradicting the metropolitan social-mix policy; REC members saw concentrations of social housing (Kontula, Jakomäki) as the problem, not concentrations of wealth. The master plan required 1.2 m fences and gated entrances; ads stressed that 'no common laundries are needed'.",
  "Conclusion (pp. 142–144): the authors do not call Eiranranta a gated community, since residents pay city taxes, use public services and the fences allow right of passage, but it manifests Harvey's 'neoliberal turn'. Unlike the UK state, the Finnish state itself became a land-rent maximiser, treating land as a financial asset 'according to the rent it yields' (Harvey 1982), and lost the impartiality needed to manage the contradictions of marketisation. Privatising land can mean privatising development rights. Selling to investors like Apollo may break developers' monopoly but risks 'creating liquidity out of spatial fixity' (Gotham 2009). Eiranranta is an experiment at the upper end of the market that contradicts Helsinki's welfare instruments (social housing, tenure mix)."
 ],
 concepts:[
  ["Entrepreneurial public real estate policy","Rent-maximising land policy by municipalities and the state: selling public land or charging market rent (p. 137; concept from Haila 2016)."],
  ["Planning monopoly / development rights","In Finland cities have the sole right to assign development rights, so the value increase due to development belongs to them (p. 138)."],
  ["'Necessity to save'","Post-recession ideology that justified spending cuts and market-based use of public assets; a 'strong discourse' (Bourdieu) naturalising market rule (pp. 139–140)."],
  ["Four justifications","Put public assets to work; efficient land use; transparency; diversity (p. 139)."],
  ["MRL (Land Use and Building Act 1999)","Ended state ratification of local plans and legalised development areas/contracts (PPP), enabling disconnected enclaves (p. 139)."],
  ["Welfare state to welfare cities","Shift of responsibility for social services from state to municipalities, creating pressure to save (p. 139)."],
  ["Inter-city competition for 'good taxpayers'","Helsinki sold Eiranranta to attract high-income residents from Espoo and Kauniainen (income tax is municipalities' main revenue) (p. 140)."],
  ["State as real estate player","By corporatising its real estate, the Finnish state lost impartiality and its capacity to mediate conflicts (pp. 139, 143)."],
  ["Gated community vs exclusive enclave","Eiranranta is fenced and exclusive but not a full gated community: residents pay city taxes, use public services, and passage is allowed (p. 143)."]
 ],
 fig:`<svg viewBox="0 0 620 250" role="img" aria-label="Causal chain from recession to Eiranranta outcomes"><defs><marker id="hhA" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="20" width="140" height="60" rx="8" class="bxw"/><text x="80" y="44" text-anchor="middle">Early-1990s</text><text x="80" y="62" text-anchor="middle">recession</text>
<rect x="175" y="10" width="170" height="100" rx="8" class="bx"/><text x="260" y="30" text-anchor="middle" font-weight="bold">State shifts</text><text x="260" y="50" text-anchor="middle">urban programmes</text><text x="260" y="66" text-anchor="middle">'necessity to save'</text><text x="260" y="82" text-anchor="middle">MRL 1999</text><text x="260" y="98" text-anchor="middle">state RE companies</text>
<rect x="370" y="20" width="240" height="70" rx="8" class="bxa"/><text x="490" y="42" text-anchor="middle" font-weight="bold">Entrepreneurial public</text><text x="490" y="60" text-anchor="middle" font-weight="bold">real estate policy</text><text x="490" y="78" text-anchor="middle" class="mut">sell land / market rent</text>
<line x1="150" y1="50" x2="173" y2="50" class="ln" marker-end="url(#hhA)"/><line x1="345" y1="55" x2="368" y2="55" class="ln" marker-end="url(#hhA)"/>
<rect x="370" y="115" width="240" height="46" rx="8" class="bxi"/><text x="490" y="135" text-anchor="middle">Eiranranta sold 2005 to</text><text x="490" y="151" text-anchor="middle">highest bidders, €54M</text>
<line x1="490" y1="90" x2="490" y2="113" class="ln" marker-end="url(#hhA)"/>
<text x="180" y="140" text-anchor="middle" class="mut">motives: revenue, 'good taxpayers',</text><text x="180" y="156" text-anchor="middle" class="mut">'global city' image</text>
<rect x="10" y="185" width="190" height="56" rx="8" class="bxa"/><text x="105" y="208" text-anchor="middle">Planning power ceded;</text><text x="105" y="224" text-anchor="middle">no social housing</text>
<rect x="215" y="185" width="190" height="56" rx="8" class="bxa"/><text x="310" y="208" text-anchor="middle">Record prices exclude</text><text x="310" y="224" text-anchor="middle">non-market buyers</text>
<rect x="420" y="185" width="190" height="56" rx="8" class="bxa"/><text x="515" y="208" text-anchor="middle">Fenced enclave for</text><text x="515" y="224" text-anchor="middle">the wealthy</text>
<line x1="450" y1="161" x2="120" y2="183" class="ln" marker-end="url(#hhA)"/><line x1="480" y1="161" x2="320" y2="183" class="ln" marker-end="url(#hhA)"/><line x1="510" y1="161" x2="515" y2="183" class="ln" marker-end="url(#hhA)"/>
</g></svg>`,
 cap:"From national restructuring to entrepreneurial land policy to three unintended outcomes in Eiranranta (pp. 137–143).",
 table:{head:["Justification claimed","What Eiranranta showed"],rows:[
  ["Put public assets to work / saves money","€54M one-off revenue, but developers sold at €10,000–16,000/m² and likely captured value from public development rights"],
  ["Efficiency (highest bidder)","'Efficiency' = highest-paying use; planning power and social-housing requirement ceded"],
  ["Transparency","Bid prices published, but key issue (developer cartel, land rent capture) sidelined in debate"],
  ["Diversity","A homogeneous enclave for high net-worth residents; contradicts social-mix policy"]
 ]},
 example:"Eiranranta, Helsinki: a former industrial shore and city depot next to prestigious Eira, rezoned residential in 2001; four sites sold in 2005 at a record €2621/m² (€54M); no social housing; blocks bordered by 1.2 m fences with gated entrances; apartments marketed with wine cabinets and home theatres and 'no common laundries'.",
 quotes:[
  "\"by selling the land to private developers who developed the area for homeowners, the City ceded its planning power with no demands that the area should include social housing.\" (p. 137)",
  "\"A wish to represent Helsinki as a ‘global city’ was, at that time, one of the key drivers for replacing managerial strategies with entrepreneurial ones (to borrow Harvey’s (1989) terms for these two types of urban governance).\" (p. 140)",
  "REC member: \"Those are the rules of the game today. If you wish to succeed, then city real estate policy must live with the programme. And this isn’t a politically divisive question.\" (p. 141)",
  "\"by establishing real estate companies and turning into just one player in the real estate market, the state lost its impartiality and therefore possibilities to intervene\" (p. 143)"
 ],
 dims:{sa:55, rt:70, de:45, us:80, mp:35, norm:"Nordic welfare-city ideals: public land ownership and leasing, social mix, social housing, public capture of land value, equality; critique of neoliberal marketisation."},
 exam:"Commentary angle: grounded in the political economy of urban land (Harvey's land as financial asset, Haila's land rent theory) and neoliberal urbanism (Brenner & Theodore, Peck); Harvey's (1989) managerialism/entrepreneurialism is used explicitly (p. 140). Note it also has a discursive element (Bourdieu's 'strong discourse', Weber's 'discursive practice') and an institutional one (MRL, state urban policy). Best critiques: (1) rational/public choice and Hayek: the 'apologists' argue market prices reveal opportunity costs of land and make subsidies transparent (Pursiainen & Saarimaa); the authors dismiss this without testing welfare effects or counterfactuals (would Eiranranta with leasing have produced social housing?); (2) neo-institutionalism: the story is path-dependent institutional change (MRL, state reform) more than a structural capitalist logic, and Finland's land regime mediates neoliberalism; (3) communicative planning: the REC was a representative forum but there was no real debate and excluded groups had no say, so the problem is also democratic deliberation. Methodological: single case, 5 of 9 interviews, 'unintended' effects partly inferred. MCQ traps: the authors do NOT call Eiranranta a gated community; the Real Estate Department preferred Skanska, not Apollo; it was the state (not only cities) that pioneered entrepreneurial real estate policy."},

{id:"savini", wk:6, title:"Savini & Aalbers (2016) De-contextualisation of land use planning through financialisation: Milan", cite:"Savini, F. & Aalbers, M.B. (2016). The de-contextualisation of land use planning through financialisation: Urban redevelopment in Milan. European Urban and Regional Studies 23(4), 878–894. DOI 10.1177/0969776415585887", theory:"Political economy of financialisation (Harvey's capital switching, land as fictitious capital), with an institutional reading of local government capacity", status:"full",
 statusNote:"Built from the full text of the authors' accepted manuscript ('forthcoming in EURS, OnlineFirst 2015'). Page numbers refer to the manuscript pagination (pp. 1–15), NOT the journal pagination (878–894). Tutorial 4 seminar article.",
 one:"Financialisation turns land into a liquid financial asset whose valuation and investment decisions are made by layered investors far from the site; this de-contextualises land capital from local socio-political contexts and makes planning instrumental to unlocking capital. In the Falck site in Sesto San Giovanni, successive owners and SPVs inflated the programme and land price, while a weak, yield-dependent municipality ended up in gridlocked negotiations.",
 summary:[
  "Argument and trends (pp. 1–4): finance increasingly penetrates land planning and development, but fine-grained case studies of the mechanisms are rare. Building on Harvey's 'capital switching' and land as financial asset, the authors identify three features of contemporary urban development: (a) investment relocation towards riskier peripheral, out-of-prime locations (brownfields in urban belts) expected to yield more in the long run; (b) clustering and enlargement of projects into bigger packages that dissolve demand variations and outplay smaller investors, with standardisation and starchitecture to increase liquidity; (c) instrumental land use planning geared to attracting finance, especially where fiscal stress makes municipalities dependent on incoming capital. They are more sceptical than Weber (2010) that municipalities can use financial markets for their own agenda (p. 2).",
  "De-contextualised land capital (pp. 4–7): as land becomes liquid and part of global portfolios, decisions on its exchange and use are disconnected from the local values, norms and needs where they land; valuations rest on simplified yield projections. Decisions on land-use programmes (local needs) separate from decisions on investment (shareholder profit expectations), with many layers of intermediaries. Land is also used as collateral to create credit for investments elsewhere. Special-purpose vehicles (SPVs) are the key tool: they isolate project risk from the holding, can be bought and sold, and link project gains to shareholders; they are 'both separators and connectors'. Local governments try value capture via regulation, betterment levies, public land development or TIF, but detachment of investment from land-use decisions weakens their understanding and bargaining power.",
  "The Falck case (pp. 7–13): a 150 ha polluted former steelworks in Sesto San Giovanni (80,000+ inhabitants; about a quarter of its area vacant industrial land), negotiated under the PII regime; 15 years without agreement; land sold four times. Periodisation (Table 1): 1990s: Falck Corporation and a public-private agency (PSTA, later ASNM; municipality 80%, province 5%, Falck 15%) pursuing reindustrialisation. 2000: sold (€180M in the text; €140M land cost in Table 1) to local investor Gruppo Pasini, SPV Immobiliare Cascina Rubina with a Banca Intesa loan; modest plan, 9% expected return; not approved. 2005: ICR sold to Risanamento (Gruppo Zunino), clustered with Santa Giulia etc.; Renzo Piano masterplan, ~double floor area, 50% high-end housing, 15% expected gain on ~€5bn. 2009: credit crunch, bankruptcy procedure. 2010: Sesto Immobiliare (Bizzi & Partners; Korean and other investors) buys for €405M, largely via land transfer to creditor banks, conditional on approval of ≥962,000 m² within two years; programme grows to ~1.2M m²; 12% expected return. 2011: council approves; region commits €323M for a health campus.",
  "Explanation and conclusion (pp. 13–15): the outcome results from two concurrent trends: growing institutional distance between developer and investors/creditors, and the municipality's increasing dependence on the project's yields, which weakened its negotiating position. Each transfer bound the project more tightly to financial returns and promises of future yields, and the programme was intensified to cover rising costs and debts; planning became 'functional to the urgent need to unlock capital' rather than a response to local needs. Main features of de-contextualisation: separation of ownership and planning responsibility; SPVs insulating risk; complexified, nested property structures. Theoretically, financialisation goes 'one step further than Harvey foresaw in 1982': land is not only a spatial fix but collateral to create credit elsewhere. The outcome is not inevitable: the complexity of financial constructions and the regulatory position of public authorities differentiate outcomes; governing property-led development requires strong regulation combined with proactive intervention capacity."
 ],
 concepts:[
  ["Financialisation of land","Land treated as a financial asset valued by expected yields and traded in portfolios; increasingly used as collateral to create credit (pp. 2, 5–6, 14–15)."],
  ["De-contextualisation","The detachment of land investment decisions from the socio-economic and political contexts where their effects are felt (pp. 4–5, 14)."],
  ["Three trends","Investment relocation (riskier peripheries), clustering/enlargement of projects, instrumental land use planning (pp. 3–4)."],
  ["Special-purpose vehicle (SPV)","Project company that isolates risk from its generator/holding, can be traded, and channels gains to shareholders; 'both separators and connectors' between planning and investment (p. 6)."],
  ["Capital switching","Harvey's notion of capital moving into the built environment; finance invents new strategies to reconnect global strategies with local production of space (p. 1)."],
  ["Land as fictitious capital","What is bought and sold is title to future ground rent; land becomes an interest-bearing investment (Harvey 1982, quoted p. 14)."],
  ["Value capture","Public capture of land value increments for public benefits; harder when investment decisions are detached from land-use processes (pp. 6–7)."],
  ["Yield dependence of local government","A fiscally weak municipality depends on project returns for public gains, weakening its bargaining capacity (pp. 13–14)."],
  ["PII (Programmi Integrati d'Intervento)","Italian regulatory framework requiring close negotiation between municipal executives and the developer (p. 7)."]
 ],
 fig:`<svg viewBox="0 0 620 280" role="img" aria-label="Layered structure of de-contextualised land capital with the SPV as interface, and Falck timeline"><defs><marker id="saA" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="10" width="250" height="50" rx="8" class="bxw"/><text x="135" y="31" text-anchor="middle">Investors, banks, holdings</text><text x="135" y="48" text-anchor="middle" class="mut">global portfolios, yield targets</text>
<rect x="10" y="85" width="250" height="50" rx="8" class="bxa"/><text x="135" y="106" text-anchor="middle" font-weight="bold">SPV</text><text x="135" y="123" text-anchor="middle">separator and connector</text>
<rect x="10" y="160" width="250" height="50" rx="8" class="bxi"/><text x="135" y="181" text-anchor="middle">Municipality / local planning</text><text x="135" y="198" text-anchor="middle" class="mut">local needs, value capture</text>
<line x1="135" y1="60" x2="135" y2="83" class="ln" marker-end="url(#saA)"/><line x1="135" y1="135" x2="135" y2="158" class="ln" marker-end="url(#saA)"/>
<text x="135" y="232" text-anchor="middle" class="mut">distance grows: decisions de-contextualised</text>
<text x="135" y="250" text-anchor="middle" class="mut">yield dependence weakens bargaining</text>
<text x="450" y="22" text-anchor="middle" font-weight="bold">Falck site, Sesto San Giovanni</text>
<line x1="300" y1="45" x2="300" y2="260" class="ln"/>
<circle cx="300" cy="55" r="4" class="acc"/><text x="312" y="59">1990s Falck + public agency</text>
<circle cx="300" cy="100" r="4" class="acc"/><text x="312" y="96">2000 Pasini / SPV ICR</text><text x="312" y="112" class="mut">~734,000 m², 9% return</text>
<circle cx="300" cy="150" r="4" class="acc"/><text x="312" y="146">2005 Risanamento (Zunino)</text><text x="312" y="162" class="mut">1.1M m², 15%, land €298M</text>
<circle cx="300" cy="200" r="4" class="acc"/><text x="312" y="196">2010 Sesto Immobiliare</text><text x="312" y="212" class="mut">≥962,000 m², 12%, land €405M</text>
<circle cx="300" cy="245" r="4" class="acc"/><text x="312" y="249">2011 plan approved; gridlock</text>
</g></svg>`,
 cap:"Left: the SPV as interface between de-contextualised finance and local planning; right: the Falck site's successive owners (Table 1, p. 9).",
 table:{head:["Period","Owner","Financial model","Programme / expected gain","Land cost"],rows:[
  ["1990–2000","Falck Corporation","Joint-stock public-private agency (PSTA)","High-end industry, small manufacturing; gain not defined","Undefined"],
  ["2000–2005","Gruppo Pasini (local)","SPV ICR; €250M debt with Banca Intesa","~734,000 m²; 9%","€140M (Table 1; text: sold for €180M)"],
  ["2005–2010","Gruppo Zunino / Risanamento","ICR SPVs; 25% equity","1.1M m², 50% high-end housing; 15%","€298M (€88M down payment)"],
  ["2010–","Bizzi & Partners / Sesto Immobiliare","New SPV; 5% equity; land deeds with creditor banks","Min. 962,000 m² (later ~1.2M m²); 12%","€405M"]
 ]},
 example:"Falck, Sesto San Giovanni (Milan): 150 ha polluted steelworks; land sold four times with steadily rising prices while no brick was laid; the 2010 purchase was conditional on municipal approval of at least 962,000 m² within two years, putting the municipality under pressure to approve a larger programme.",
 quotes:[
  "\"In becoming liquid, land is decontextualised from the local and this has important consequences for the organisation and outcomes of the planning process.\" (pp. 4–5, manuscript)",
  "\"SPVs are therefore both separators and connectors between the land use planning process and investment strategies.\" (p. 6, manuscript)",
  "\"credit is not only used to invest in land resulting in spatial fix, land itself is used as leverage to create credit that can then be invested elsewhere\" (p. 15, manuscript)",
  "\"the Falck case demonstrates how a local government is being shaped and constrained by finance without being able to give shape to financial markets.\" (p. 15, manuscript)"
 ],
 dims:{sa:30, rt:60, de:65, us:60, mp:40, norm:"Socio-spatial equity and local democratic control over land use; planning should respond to local needs, not investor yields; calls for strong regulation plus proactive public intervention."},
 exam:"Commentary angle (likely model for the 5 Nov exam): grounded in Marxist political economy of financialisation (Harvey 1982/1985: capital switching, land as financial/fictitious capital, spatial fix), extended by the claim that land now also serves as collateral. But it is not purely structural: the authors deny the outcome is inevitable and name institutional variables (complexity of financial constructions; regulatory versus proactive role of public authorities), which invites a neo-institutionalist reading. Best critiques: (1) neo-institutionalism: the gridlock may stem from Italian institutions (PII negotiation regime, corruption: the 2000s events are under bribery investigation, fn 3, weak municipal capacity) rather than financialisation per se; single extreme case limits generalisation; (2) Weber / agency and regime theory: other cities (Chicago) use finance for their own agenda; local coalitions matter; (3) rational choice / game theory: value capture is a bargaining game (the paper cites Samsura & van der Krabben); a rational choice analysis would explain outcomes by pay-offs and credible commitments; (4) Hayek/liberal: long vacancy could be read as over-regulation blocking market adjustment, which the authors themselves partly admit ('Overregulation might disengage investors', p. 7). MCQ traps: the three trends (relocation, clustering, instrumental planning); SPVs are separators AND connectors; the paper says financialisation goes further than Harvey foresaw (land as collateral), not that Harvey was wrong; the municipality took a regulative, not proactive, role in later phases."}
];

const FC_B=[
["harvey","What distinguishes urban managerialism from entrepreneurialism (Harvey 1989)?","Managerialism (1960s) focuses on providing services, facilities and welfare to residents; entrepreneurialism (from the 1970s) focuses on fostering local growth and competing for capital, consumers and funds (general knowledge; verify)."],
["harvey","Name the three features of urban entrepreneurialism.","(1) Public-private partnership; (2) speculative execution and design, with the public sector absorbing risk; (3) focus on the political economy of place (projects) rather than territory (general knowledge; verify)."],
["harvey","What are Harvey's four strategies of inter-urban competition?","Competition for (a) production (international division of labour), (b) consumption (spectacle, tourism), (c) command and control functions (finance, government, information), (d) redistribution of surplus via central government (general knowledge; verify)."],
["harvey","Why does serial reproduction make entrepreneurialism a zero-sum game?","Successful strategies are rapidly copied by other cities, eroding any temporary competitive advantage; competition then mainly redistributes resources towards capital (general knowledge; verify)."],
["harvey","Why does Harvey warn against reifying 'the city'?","Cities do not act; coalitions and class alliances within urban governance do. Treating 'the city' as an actor hides whose interests entrepreneurial policies serve (general knowledge; verify)."],
["harvey","What is the 'spatial fix' (encyclopedia entry)?","The tendency of capitalism to remake spaces, in new places or by transforming existing ones, to resolve crises of production and overaccumulation (Woodward & Jones 2009, p. 24)."],
["harvey","What is accumulation by dispossession?","Creating new spaces for capital by dispossessing people of spaces and services to which they have rights, e.g. privatisation of state services (encyclopedia p. 27)."],
["harvey","Which theoretical perspective grounds Harvey (1989), and which course perspective best critiques its convergence thesis?","Marxist political economy (historical-geographical materialism). Neo-institutionalism (path dependence, national variation) or regime theory (local coalition agency) critique the claim that all cities converge on entrepreneurialism."],
["fog","What is Foglesong's property contradiction?","The tension between the social character of urban land (collectively produced and needed) and its private ownership and control (general knowledge; verify against text)."],
["fog","What is the capitalism–democracy contradiction?","Capital needs some socialised control over land via the state, but democratic control could go further than capital wants; planning is therefore insulated from popular pressure (general knowledge; verify)."],
["fog","Instrumentalist vs structuralist theory of the state?","Instrumentalist: the state is a tool directly controlled by capitalists. Structuralist: the state has relative autonomy and serves capital's long-term collective interest, even against individual capitalists."],
["fog","Why is planning both enabled and constrained under capitalism (Foglesong)?","It is needed to coordinate land use and legitimise development for capital as a whole, but it must not undermine private property or hand control to democratic majorities (general knowledge; verify)."],
["fog","Foglesong meets Week 6 cases: where do you see the property contradiction?","In Helsinki (public development rights and land value captured by developers after sale) and in Falck (land's social uses subordinated to financial owners' yields): the social character of land versus private/financial control."],
["fog","Why does Foglesong ask 'why does planning exist' at all?","Because mainstream theory assumes planning pursues the public interest (or corrects market failure) without explaining why it arises in capitalist cities or why it takes its limited form (general knowledge; verify)."],
["fog","What is the functionalism critique of Foglesong?","Explaining planning by its usefulness to capital's collective interest risks assuming what must be shown; it underplays actors' intentions, pluralist conflict and contingent institutional design."],
["fog","Which perspective grounds Foglesong, and which would critique it best in a commentary?","Marxist political economy / structuralist theory of the state. Liberal pluralism or communicative planning (planning as the outcome of many groups and deliberation), Hayek (market coordination), or neo-institutionalism (national variation) are strong critiques."],
["hh","Define entrepreneurial public real estate policy.","A rent-maximising land and real estate policy carried out by municipalities and the state: selling public land or charging market rent when leasing (p. 137)."],
["hh","What four justifications were given for this policy?","Put public assets to work; make land use efficient; increase transparency; create diversity (p. 139)."],
["hh","Which three changes 'scaled down' land-use decisions in Finland?","A new state urban policy making cities compete for subsidies; a redistribution shift under 'the necessity to save'; and the 1999 Land Use and Building Act (MRL) (pp. 138–139)."],
["hh","What three harmful effects did the Eiranranta sale have?","The City ceded planning power and dropped social housing; record prices reinforced exclusion of those who cannot pay market prices; a fenced enclave for the wealthy, new to Helsinki (p. 137)."],
["hh","Why do the authors not call Eiranranta a gated community?","Residents still pay city taxes, use public services, and the fences allow right of passage (p. 143)."],
["hh","What was unique about the Finnish state's role?","By creating state real estate companies it became one player in the market, lost its impartiality and thus its ability to mediate and manage the contradictions of marketisation (p. 143)."],
["hh","How does Eiranranta illustrate Harvey's (1989) shift to entrepreneurialism?","Helsinki sold public land to attract 'good taxpayers' from Espoo/Kauniainen and a 'global city' image vs Copenhagen, Stockholm and Tallinn; the authors explicitly call this replacing managerial with entrepreneurial strategies (p. 140). Public revenue, private enclave: place over territory."],
["hh","Why might Apollo have bid €3 million more than established developers?","Established developers were likely used to undervaluing land and capturing land rent and value from public development rights; Apollo may have bid the market value (pp. 141, 143)."],
["savini","What does 'de-contextualisation' mean in Savini & Aalbers?","The detachment of investment decisions about land from the local socio-economic and political contexts where their effects are felt, as land becomes liquid and part of global portfolios (pp. 4–5)."],
["savini","Name the three trends of contemporary urban development.","Relocation of investment to riskier peripheral locations; clustering/enlargement of projects; instrumental land use planning (pp. 3–4)."],
["savini","What role do SPVs play?","They isolate project risk from the holding, can be traded, and channel gains to shareholders; they are 'both separators and connectors' between planning and investment (p. 6)."],
["savini","Which two concurrent trends explain the Falck gridlock?","Growing detachment between land planning and financial dynamics, and the municipality's growing dependence on the project's yields, which weakened its negotiating capacity (p. 13)."],
["savini","How do the authors go 'one step further than Harvey'?","Land is not only a spatial fix absorbing overaccumulated capital; it is used as collateral to create credit invested elsewhere (pp. 14–15)."],
["savini","Is the Falck outcome inevitable under financial capitalism, according to the authors?","No: the complexity of financial constructions and the regulatory position of public authorities differentiate outcomes; they call for strong regulation plus proactive intervention (p. 15)."],
["savini","Why is local government's value capture harder under financialisation?","When investment decisions are detached from land-use processes, cities poorly understand the economic calculations and cannot define a viable programme; excessive demands risk jeopardising the project (pp. 7, 15)."],
["savini","Helsinki vs Milan: how does the public sector's position differ?","In Helsinki the public sector is the landowner that chose to act as a rent-maximising seller (entrepreneurial public real estate policy); in Sesto the municipality is a regulator without land, dependent on financial owners' yields. Both show planning power drained by market/financial logics."]
];

const MCQ_B=[
{t:"harvey",q:"According to Harvey (1989), which is NOT one of the characteristic features of urban entrepreneurialism?",o:["Public-private partnership","Speculative development in which the public sector absorbs much of the risk","A focus on improving living conditions across the whole territory","A focus on the political economy of place"],a:2,e:"Entrepreneurialism focuses on place (projects) rather than territory; improving conditions across the territory is closer to managerialism (general knowledge; verify)."},
{t:"harvey",q:"Which of the following is one of Harvey's four entrepreneurial strategies?",o:["Competition for redistribution of surplus via central government","Competition for planning permissions from higher tiers","Deliberative consensus-building among stakeholders","Tiebout-style sorting of residents by tax preference"],a:0,e:"Harvey lists production, consumption, command functions and redistribution of surplus via central government (general knowledge; verify)."},
{t:"harvey",q:"In Harvey's framework, what drives cities to adopt similar entrepreneurial strategies?",o:["Communicative learning between planners","Inter-urban competition acting as an external coercive force","National planning legislation mandating growth","Consumer sovereignty expressed in local elections"],a:1,e:"Competition disciplines cities and leads to serial reproduction of strategies (general knowledge; verify)."},
{t:"harvey",q:"The encyclopedia entry defines the 'spatial fix' as:",o:["The fixing of land-use patterns by zoning","Capitalism remaking spaces to resolve crises of production and overaccumulation","A planning technique to stabilise property values","Fixed capital in factories"],a:1,e:"Woodward & Jones (2009, p. 24) define it as capitalism remaking spaces to resolve contradictions and crises of production and overaccumulation."},
{t:"harvey",q:"Which course perspective most directly challenges Harvey's claim that cities converge on entrepreneurialism?",o:["Rational-comprehensive planning","Historical neo-institutionalism","Instrumentalist Marxism","Growth machine theory"],a:1,e:"Historical neo-institutionalism stresses path dependence and institutional variation between countries and cities, questioning convergence."},
{t:"fog",q:"Foglesong's 'property contradiction' refers to the tension between:",o:["Capital and labour in the workplace","Use value and exchange value of housing","The social character of land and its private ownership and control","Central and local government"],a:2,e:"The property contradiction is between land's social character and private ownership/control (general knowledge; verify against the text)."},
{t:"fog",q:"The capitalism–democracy contradiction implies that planning tends to be:",o:["Fully controlled by popular assemblies","Insulated from democratic control while socialising some control over land","Abolished during economic crises","Delegated to individual property owners"],a:1,e:"Capital needs state control of land but fears democratic majorities; planning is therefore insulated (e.g. expert commissions) (general knowledge; verify)."},
{t:"fog",q:"A structuralist (relative autonomy) theory of the state holds that:",o:["The state is a tool directly controlled by capitalists","The state is a neutral arbiter between interest groups","The state serves capital's long-term collective interest, sometimes against individual capitalists","The state maximises the budget of its bureaucrats"],a:2,e:"Option A is instrumentalist, B pluralist, D public choice (Niskanen-type)."},
{t:"fog",q:"Which critique of Foglesong would a Hayekian liberal most likely make?",o:["Planning ignores class struggle","The social character of land does not justify state control; prices and property rights coordinate dispersed knowledge better","Planning is insufficiently deliberative","Planning is a discourse producing subjects"],a:1,e:"Hayek emphasises dispersed knowledge and market coordination; the other options are Marxist, communicative and Foucauldian critiques."},
{t:"fog",q:"Which Week 6 case best illustrates Foglesong's property contradiction?",o:["Harvey's Baltimore festival market as spectacle","Falck: land's social uses (housing, public facilities) subordinated to successive financial owners' yield requirements","Helsinki's corporate tax redistribution","A communicative visioning workshop"],a:1,e:"The social character of land collides with private/financial control over it; Falck (and Eiranranta) show this directly."},
{t:"hh",q:"Which was NOT one of the four justifications for entrepreneurial public real estate policy identified by Hyötyläinen & Haila?",o:["Put public assets to work","Increase transparency","Create diversity","Promote social mixing through social housing"],a:3,e:"The four were: put public assets to work, efficient land use, transparency, diversity (p. 139); social housing was precisely what Eiranranta lacked."},
{t:"hh",q:"Why did REC members say Helsinki sold the Eiranranta sites?",o:["To fund social housing elsewhere","Budget sales targets, competition with Espoo and Kauniainen for 'good taxpayers', and a 'global city' image","EU state-aid rules required it","The state ordered the sale"],a:1,e:"Pp. 140–141: sales goals in the budget, attracting high-income taxpayers, and international city image."},
{t:"hh",q:"Which statement about the Eiranranta deal is correct?",o:["The Real Estate Department preferred Apollo","The winning bid was the lowest","The Real Estate Department proposed selling to Skanska despite its lower bid","The City Council rejected the deal"],a:2,e:"P. 141: the Department preferred Skanska; Korpinen and the Council favoured Apollo; only one councillor opposed the sale."},
{t:"hh",q:"What do the authors conclude about Eiranranta as a 'gated community'?",o:["It is a classic US-style gated community","It is not a gated community, as residents pay city taxes, use public services and passage is allowed","It is social housing with fences","The question is not discussed"],a:1,e:"P. 143: exclusive and fenced but not a gated community."},
{t:"hh",q:"Hyötyläinen & Haila use Harvey (1989) to characterise Helsinki's shift as one from:",o:["Planning to deregulation","Managerial to entrepreneurial strategies","Territory to network","Fordism to Keynesianism"],a:1,e:"P. 140: 'replacing managerial strategies with entrepreneurial ones (to borrow Harvey's (1989) terms …)'."},
{t:"hh",q:"Which pairing of Week 6 readings with the public sector's role is correct?",o:["Helsinki: municipality as landowner selling to maximise rent; Sesto San Giovanni: municipality as regulator dependent on financial owners' yields","Helsinki: regulator without land; Sesto: landowner","Both: municipalities as proactive co-investors","Both: the national state as developer"],a:0,e:"Helsinki owns 60% of its land and sold Eiranranta; in Falck, private/financial owners held the land and Sesto regulated, growing dependent on yields."},
{t:"savini",q:"Which three trends do Savini & Aalbers identify in contemporary urban development?",o:["Gentrification, displacement, touristification","Relocation of investment, clustering of projects, instrumental land use planning","Densification, sustainability, participation","Privatisation, deregulation, decentralisation"],a:1,e:"Pp. 3–4."},
{t:"savini",q:"SPVs in Savini & Aalbers are best described as:",o:["Public agencies for value capture","Both separators and connectors between land use planning and investment strategies","Community land trusts","Regulatory instruments of the PII"],a:1,e:"P. 6: SPVs isolate risk and can be traded, while linking the project to the holding and shareholders."},
{t:"savini",q:"How do the authors claim to go beyond Harvey (1982)?",o:["They reject the concept of fictitious capital","They show land is also used as collateral to create credit invested elsewhere, not only as a spatial fix","They argue finance has no effect on planning","They replace Marxism with rational choice theory"],a:1,e:"Pp. 14–15: financialisation goes 'one step further than Harvey foresaw'."},
{t:"savini",q:"According to Savini & Aalbers, which two trends together explain the Falck gridlock?",o:["Public opposition and heritage protection","Detachment of land planning from financial dynamics, and the municipality's dependence on project yields","EU regulation and national austerity","Architectural disputes and soil pollution"],a:1,e:"P. 13: two concurrent trends; the municipality's regulative role weakened as the project grew."},
{t:"savini",q:"Which Week 6 connection is most accurate?",o:["Savini & Aalbers show Harvey's entrepreneurialism fully replaced by communicative planning","Hyötyläinen & Haila warn that selling to investment companies may 'create liquidity out of spatial fixity', the same financialisation dynamic Savini & Aalbers trace in Milan","Foglesong argues financialisation began in the 1920s","Harvey (1989) analyses SPVs"],a:1,e:"H&H (pp. 143–144) cite Gotham on liquidity from spatial fixity; Savini & Aalbers analyse that liquidity mechanism in detail."}
];

const OPEN_B=[
{t:"harvey",pts:20,q:"Write a short theoretical commentary on Harvey (1989), 'From managerialism to entrepreneurialism'. (a) Identify the theoretical perspective that grounds the argument and show how it shapes Harvey's explanation of the shift. (b) Critique the argument from one alternative perspective covered in the course.",model:"(a) Harvey argues that since the 1970s urban governance shifted from managerialism (service and welfare provision) to entrepreneurialism: public-private partnerships, speculative projects with public risk, and a focus on place rather than territory. The grounding perspective is Marxist political economy (historical-geographical materialism). The explanation is structural: deindustrialisation, fiscal crisis and mobile, flexible capital make inter-urban competition a coercive force; cities compete for production, consumption, command functions and central-state redistribution. This perspective also shapes the normative verdict: competition is largely zero-sum through serial reproduction and redistributes towards capital, deepening uneven development. Agency exists in class coalitions (and Harvey refuses to reify 'the city'), but it is heavily constrained. (b) From historical neo-institutionalism the convergence thesis is too strong. Institutions filter global pressures: path dependence, national land regimes and fiscal systems produce different varieties of entrepreneurialism. Helsinki's public landownership meant entrepreneurialism took the form of a municipal land sale mediated by the MRL and state urban policy (Hyötyläinen & Haila), while Sesto's weak position under the PII regime produced gridlock (Savini & Aalbers). Harvey's monist, capital-centred explanation risks functionalism (every policy explained by its utility for capital) and cannot account for such variation or for institutional reform as a lever of change. A strong answer notes that Harvey does leave room for a progressive alternative, which sits uneasily with his structural determinism.",rubric:["Correctly summarises managerialism vs entrepreneurialism and its key features/strategies","Identifies Marxist political economy and links it to the structural, competition-driven explanation","Critique from a clearly named alternative perspective with its own assumptions (e.g. neo-institutionalism, regime theory, governmentality, Hayek/public choice)","Uses examples or course readings to support the critique and weighs strengths/limits (structure vs agency, monism)"]},
{t:"fog",pts:20,q:"Write a short theoretical commentary on Foglesong's 'Planning the capitalist city'. (a) Which theoretical perspective grounds his explanation of why planning exists? (b) Critique it from a liberal (Hayek) or communicative perspective. (Note: check your answer against the text on Brightspace.)",model:"(a) Foglesong grounds his account in Marxist political economy and a structuralist theory of the capitalist state. He rejects the view that planning is a neutral pursuit of the public interest and explains it by contradictions of capitalist urbanisation. The property contradiction sets the social character of land (collectively produced, collectively needed) against its private ownership and control; capital as a whole needs some socialised control of land use, while individual owners resist it. The capitalism–democracy contradiction arises because socialising control via a democratic state risks popular control going further than capital wants; planning is therefore insulated from democracy. Against instrumentalist Marxism, the state has relative autonomy and serves capital's collective interest, with class struggle shaping outcomes. (b) A Hayekian critique rejects the premise that land's social character calls for state coordination. Knowledge about land use is dispersed and tacit; prices and secure property rights coordinate it better than planners can. Where Foglesong sees planning as capital's collective interest, Hayek sees a risk of arbitrary state power, and would read cases such as Eiranranta as a rational revealing of land's opportunity cost rather than as capture. Hayek also questions whether 'capital's collective interest' can be known or served by the state at all. The Hayekian critique exposes Foglesong's functionalism, but it ignores the distributive consequences of market allocation that Foglesong puts centre stage.",rubric:["Explains the property contradiction and capitalism–democracy contradiction accurately","Identifies the Marxist/structuralist theory of the state and distinguishes it from instrumentalism","Critique from a named alternative perspective, with its assumptions made explicit","Balanced evaluation (e.g. functionalism risk vs distributive blind spots of the alternative)"]},
{t:"hh",pts:20,q:"Write a theoretical commentary on Hyötyläinen & Haila (2018), 'Entrepreneurial public real estate policy: the case of Eiranranta, Helsinki'. (a) Identify the theoretical perspective(s) that ground the argument. (b) Critique the argument from an alternative perspective covered in the course.",model:"(a) The authors argue that Finnish cities and the state shifted from administrative land allocation and leasing to an entrepreneurial public real estate policy: selling land or charging market rent. In Eiranranta, Helsinki sold shoreline land to the highest bidders (record €2621/m²), ceding planning power, dropping social housing and enabling a fenced enclave for the wealthy. The grounding perspective is the political economy of urban land (Harvey's land as financial asset, Haila's rent theory), combined with neoliberal urbanism (Brenner & Theodore; Harvey's 1989 managerial-to-entrepreneurial shift, invoked explicitly on p. 140). Structural pressures (the 1990s recession, the 'necessity to save', state urban policy making cities compete) explain the policy, and a Bourdieuian 'strong discourse' naturalises market rule. Normatively the authors defend Nordic welfare-city values: public land, social mix, public capture of land value. (b) From a public choice / Hayekian perspective, the 'apologists' have a point the authors do not test. Selling at market prices reveals the opportunity cost of public land and ends hidden subsidies to developers, who (as the authors admit) captured land rent under discount pricing. The study offers no counterfactual or welfare analysis: would leasing have produced social housing on this site? It relies on 5 of 9 REC interviews and one case. A neo-institutionalist could add that the change is best explained by institutional reform (MRL 1999, corporatised state real estate), which is contingent and reversible, rather than by an inevitable neoliberal logic. The paper remains convincing on distributive outcomes, but its causal claim is weaker than its normative one.",rubric:["Accurate summary of the policy, the Eiranranta case and its three outcomes","Identifies political economy of land / neoliberal urbanism (and the explicit Harvey 1989 link)","Critique from a named alternative perspective (public choice/Hayek, neo-institutionalism, communicative), with assumptions made explicit","Uses evidence from the text (justifications, Apollo/Skanska, MRL, method) and weighs strengths and limits"]},
{t:"savini",pts:20,q:"Write a theoretical commentary on Savini & Aalbers (2016), 'The de-contextualisation of land use planning through financialisation'. (a) Which theoretical perspective grounds the argument, and how does it shape the explanation of the Falck case? (b) Critique the argument from an alternative perspective (e.g. neo-institutionalism or rational choice).",model:"(a) The authors argue that financialisation turns land into a liquid asset whose investment decisions are made by layered, distant investors, de-contextualising land capital from local needs. Three trends (relocation to risky peripheries, clustering, instrumental planning) and SPVs as 'separators and connectors' produce this. In the Falck case the site was sold four times; each owner inflated the programme (≈734,000 to ≈1.2M m²) and land price (up to €405M) to cover debt and expected returns, and the yield-dependent municipality of Sesto San Giovanni lost bargaining power, ending in gridlock. The grounding is Marxist political economy of financialisation: Harvey's capital switching and land as fictitious capital, extended by the claim that land now also serves as collateral to create credit elsewhere. Structure dominates: planning becomes functional to unlocking capital. Yet they add an institutional variable: outcomes vary with the complexity of financial constructions and the regulatory versus proactive role of public authorities. (b) A neo-institutionalist critique: the explanatory weight given to financialisation is hard to separate from Italian institutions: the PII negotiation regime, a small fiscally weak municipality, and alleged bribery (fn 3). An extreme single case cannot show that financialisation, rather than these institutions, caused gridlock; comparison with Weber's Chicago suggests institutional capacity is decisive. A rational-choice reading would model value capture as a bargaining game with commitment problems (SPVs can exit by resale), which explains the municipality's dilemma without a macro theory of capitalism. The authors' own conclusion (strong regulation plus proactive intervention) implicitly concedes that institutions, not finance alone, differentiate outcomes.",rubric:["Explains de-contextualisation, the three trends, SPVs and the Falck periodisation accurately","Identifies Marxist/Harveyan political economy of financialisation and the 'one step further than Harvey' claim; notes the institutional nuance","Critique from a named alternative perspective with explicit assumptions (neo-institutionalism, rational choice, Hayek, regime theory)","Evaluates methodology (single extreme case) and structure vs agency, reaching a reasoned judgement"]}
];
