const NEW_C=[
{id:"rydin6", wk:7, title:"Rydin (2021) Urban politics: conflict, power and justice", cite:"Rydin, Y. (2021). Urban politics: conflict, power and justice. In Theory in Planning Research (Ch. 6, pp. 105–125). Singapore: Palgrave Macmillan. https://doi.org/10.1007/978-981-33-6568-1_6", theory:"Urban politics / social movements (framework chapter: growth coalitions, regime theory, urban social movements, agonism, justice)", status:"full",
statusNote:"Built from the full text of Chapter 6 (extracted from the whole book); page numbers are the book's running headers (pp. 105–125). Note what the chapter does NOT contain: no discussion of Lukes' three dimensions of power, and Lefebvre appears only in a reference title (Butler 2012); 'Right to the City' gets one paragraph. The only power distinction it makes is Stone's 'power to' vs 'power over'.",
one:"Where the governance frame assumes conflict can be handled towards agreement, the urban politics frame sees conflict as unavoidable, power at play within planning and inequality in its outcomes; so planners cannot be neutral and must ask how to plan justly. Rydin organises the field into three dynamics (growth coalitions/urban regimes, urban social movements, agonism) with a running concern for justice, and shows how each is used in planning research.",
summary:["Framing (pp. 105–107). Urban politics starts from the insight that conflict is part of the fibre of planning. Unlike governance theory (ch. 5), it does not assume conflicts can be handled to reach effective or agreed outcomes; it looks at power in processes and inequality in outcomes. Planners 'cannot be neutral' and should act more like advocates; the research task is how to plan justly. The perspective studies both elite and non-elite actors, and rejects pluralism (Dahl), in which group activism simply follows demand: pluralism came to be seen as 'naïve' because power and resources are unequal, some issues never get on the agenda, and it legitimated a focus on middle-class pressure groups. Urban politics instead attends to the disempowered and treats non-violent occupations and even violence against property as legitimate protest.",
"Justice (pp. 106–107). Agyeman distinguishes four aspects: recognition of groups as self-determined (more than giving voice), fair process (e.g. visioning), just exercise of procedures (regulation, implementation) and fair outcomes. This frame is widely used for environmental justice (US origins in toxic sites near communities of colour; Love Canal). A second theme is the Right to the City movement (Butler 2012), e.g. Occupy after 2008. Because conflicts are linked to wider power and inequality (links to structuralism, ch. 7), planning alone can achieve little: justice requires wider political change. The research focus is not the sociology of conflict itself but how planners, planning organisations and systems respond to it (p. 107).",
"Coalitions and regimes (pp. 108–109). Molotch's growth coalitions: actors with most to gain from land and property development coalesce, with links to local government, to secure property-led growth; a response to technocratic views, emphasising class and local elites. Critiques: too agent-based (from political economy) and too simple (coalitions are fragmented, unstable, not only local, not always growth-led). Hence Stone's urban regime (Atlanta, 1989): an 'informal yet relatively stable group' that assembles the capacity to act because local government cannot implement its agenda alone; 'power to' rather than 'power over'; based on resource interdependence, cooperation has to be achieved. Four regime types (maintenance/caretaker, development, middle-class progressive, lower-class opportunity expansion); Dowding et al.'s eight criteria. Critiques: bias to corporate interests (Pierre: leaders must cater to business to access its 'systemic power'), US-specific (property taxes, local autonomy), limited transferability (Holman's four reasons).",
"Urban social movements and agonism (pp. 109–112). Left theorists disheartened by political economy's crisis-and-revolution message turned to politics with some autonomy from capitalist structures (Gramsci: the oppressed can perceive their own interests without a vanguard). Movements express a social cleavage, not a single issue. Castells linked urban social movements to conflicts over the means of collective consumption (public services needed to reproduce labour), resisting middle-class appropriation and capitalist limitation of services. Later work links USMs to identity, difference and place (Nicholls; Gualini and Bianchi); Mayer's four phases run from industrial crisis via collective consumption and gentrification to globalisation/financialisation. Critiques: gender blindness, North Atlantic bias. The USM's distinctive feature is its physical base in a place. Agonism (Mouffe) rejects governance's promise of consensus: conflict is inevitable and productive; the aim is to turn enemies into adversaries who 'agree to disagree'; critics ask whether it accepts existing power inequalities (Yamamoto).",
"Research in practice (pp. 112–123). Regimes revisited: Turin (Ravazzi and Belligni: incubation, naming/blaming/claiming, shift from pro-welfare to market-centred regime) and Guangzhou's Three Old Redevelopment (Li and Liu: regime concept supplemented with 'fragmented authoritarianism' and 'strategic selectivity'). Racism: Sulukule, Istanbul (Uysal: a Roma USM that failed to stop demolition because of unclear property rights, speculation, lack of public support, marginalisation, fragmentation and counter-pressure) and Native American fishing rights after the 1974 Boldt decision (environmental justice as decolonisation). Managing conflict: Trapenberg Frick's Tea Party/progressive tactical coalitions (ephemeral, emergent, established), REDWatch in Sydney as monitory democracy, and Fougère and Bond's Denniston Plateau coal mine (antagonism can create space for agonism; expert knowledge depoliticises). Conclusion: qualitative, normative, often action research, from the emic perspective of the marginalised."],
concepts:[["Urban politics perspective","Frame that sees conflict as unavoidable in planning, power at play within its processes and inequality in outcomes; planners cannot be neutral technocrats (p. 105)."],
["Pluralism (Dahl) and its critique","Groups form when there is demand (supply follows demand). Rejected as naïve: unequal resources, non-issues, and a legitimation of middle-class pressure groups (p. 106)."],
["Justice (Agyeman)","Four aspects: recognition of self-determined groups, fair process, just exercise of procedures, fair outcomes; widely used in environmental justice (pp. 106–107)."],
["Right to the City","Movement and claim against limited access to the city and inequitable use of its assets (Butler 2012; Occupy after 2008). Only briefly treated; Lefebvre himself is not discussed (p. 107)."],
["Growth coalition (Molotch)","Coalition of actors with most to gain from land and property development, linked to local government, pursuing property-led growth; criticised as too agent-based and too simple (p. 108)."],
["Urban regime (Stone)","'An informal yet relatively stable group with access to institutional resources' that assembles the capacity to govern through resource interdependence; four types; criteria by Dowding et al. (pp. 108–109)."],
["'Power to' vs 'power over'","Regime power is the capacity to achieve goals by combining resources ('power to'), not domination of one actor by another ('power over'); often less visible, alongside formal politics (p. 108)."],
["Systemic power / transferability","Pierre: to reach business's 'systemic power' leaders must cater to corporate interests; regime theory reflects US local government (property taxes, autonomy), so its transfer abroad needs amendment (Holman's four factors) (p. 109)."],
["Gramsci","Politics has relative autonomy from socio-economic structure; the oppressed can recognise their own interests and achieve change short of revolution, without a vanguard (p. 110)."],
["Urban social movement / collective consumption (Castells)","Movements expressing a social cleavage, mobilising over collective means (public services) for reproducing labour; Castells' USM combines collective consumption demands, community culture and political self-management (pp. 110, 116)."],
["Mayer's four phases","Industrial crisis 1960–80; collective consumption and welfare erosion 1980–90; gentrification and regeneration 1990–2000; globalisation and financialisation since 2000 (p. 111)."],
["Agonism (Mouffe)","Conflict is inevitable and productive; turn enemies into adversaries who can 'agree to disagree'; rejects deliberative consensus as a false promise; critics: may accept existing power inequalities (p. 112)."],
["Post-political","Planning that annuls dissent and silences overt conflict, e.g. by recourse to expert knowledge (Raco; Fougère and Bond) (pp. 112, 121–122)."],
["Place attachment vs NIMBY","Place-based identity used to resist the pejorative NIMBY label (Devine-Wright) (p. 112)."],
["Emic perspective / action research","Urban politics research takes the perspective of the marginalised and often supports the groups studied (p. 123)."]],
fig:`<svg viewBox="0 0 620 300" role="img" aria-label="Rydin's urban politics framework: critique of governance, three dynamics, justice running through all"><defs><marker id="mk_rydin6" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="20" y="10" width="230" height="52" rx="8" class="bx"/><text x="135" y="32" text-anchor="middle">Governance (ch. 5)</text><text x="135" y="50" text-anchor="middle" class="mut">conflict → agreement</text>
<rect x="370" y="10" width="230" height="52" rx="8" class="bxa"/><text x="485" y="32" text-anchor="middle">Urban politics (ch. 6)</text><text x="485" y="50" text-anchor="middle">power and inequality</text>
<line x1="252" y1="36" x2="366" y2="36" class="ln" stroke-width="1.5" marker-end="url(#mk_rydin6)"/><text x="309" y="28" text-anchor="middle" class="mut" font-size="11">critique</text>
<line x1="485" y1="62" x2="110" y2="98" class="ln" stroke-width="1.2" marker-end="url(#mk_rydin6)"/><line x1="485" y1="62" x2="310" y2="98" class="ln" stroke-width="1.2" marker-end="url(#mk_rydin6)"/><line x1="485" y1="62" x2="510" y2="98" class="ln" stroke-width="1.2" marker-end="url(#mk_rydin6)"/>
<rect x="20" y="100" width="180" height="100" rx="8" class="bxi"/><text x="110" y="122" text-anchor="middle">Coalitions + regimes</text><text x="110" y="142" text-anchor="middle" class="mut">Molotch: growth</text><text x="110" y="158" text-anchor="middle" class="mut">coalition →</text><text x="110" y="174" text-anchor="middle" class="mut">Stone: urban regime</text><text x="110" y="190" text-anchor="middle" class="mut">'power to'</text>
<rect x="220" y="100" width="180" height="100" rx="8" class="bxg"/><text x="310" y="122" text-anchor="middle">Urban social movements</text><text x="310" y="142" text-anchor="middle" class="mut">Gramsci → Castells:</text><text x="310" y="158" text-anchor="middle" class="mut">collective consumption</text><text x="310" y="174" text-anchor="middle" class="mut">→ identity, place</text><text x="310" y="190" text-anchor="middle" class="mut">physical base</text>
<rect x="420" y="100" width="180" height="100" rx="8" class="bxw"/><text x="510" y="122" text-anchor="middle">Agonism (Mouffe)</text><text x="510" y="142" text-anchor="middle" class="mut">enemies → adversaries</text><text x="510" y="158" text-anchor="middle" class="mut">agree to disagree</text><text x="510" y="174" text-anchor="middle" class="mut">vs post-political</text><text x="510" y="190" text-anchor="middle" class="mut">consensus</text>
<text x="310" y="228" text-anchor="middle">Running through all three: justice (Agyeman)</text>
<rect x="20" y="242" width="135" height="44" rx="8" class="bx"/><text x="87" y="268" text-anchor="middle">Recognition</text>
<rect x="168" y="242" width="135" height="44" rx="8" class="bx"/><text x="235" y="268" text-anchor="middle">Fair process</text>
<rect x="316" y="242" width="135" height="44" rx="8" class="bx"/><text x="383" y="268" text-anchor="middle">Just procedures</text>
<rect x="465" y="242" width="135" height="44" rx="8" class="bx"/><text x="532" y="268" text-anchor="middle">Fair outcomes</text>
</g></svg>`,
cap:"Urban politics as a critique of the governance frame: three analytical dynamics, with justice as the common normative thread.",
table:{head:["Dynamic","Key authors","View of power / conflict","Research example in the chapter"],rows:[
["Growth coalition","Molotch","Local elites with land/property stakes steer planning towards growth","(Critiqued; replaced by regime concept)"],
["Urban regime","Stone; Dowding et al.; Pierre; Holman","'Power to': capacity assembled from interdependent resources; bias to business","Turin (Ravazzi and Belligni); Guangzhou TOR (Li and Liu)"],
["Urban social movement","Gramsci; Castells; Mayer; Nicholls","Social cleavage; collective consumption; identity and place","Sulukule, Istanbul (Uysal); Native American fishing rights (Miller Cantzler and Huynh)"],
["Agonism","Mouffe; Raco; Yamamoto","Conflict inevitable and productive; enemies → adversaries","Tea Party coalitions (Trapenberg Frick); REDWatch (Rogers); Denniston Plateau (Fougère and Bond)"]]},
example:"Sulukule, Istanbul (Uysal 2012, pp. 115–117): the 2006 state-led regeneration of a largely Roma area for tourism and heritage displaced most residents to the outskirts. The Sulukule Platform (NGOs, a Roma association, outside activists and academics with an alternative STOP plan) is framed as a Castellsian USM. It won national and international attention but failed to stop demolition: unclear property rights, land speculation, lack of wider public support (reluctance to align with the Roma), a resource-poor marginalised community, internal fragmentation and counter-pressure from the council and developers.",
quotes:["\"Planners cannot be neutral in this conceptual context.\" (p. 105)",
"\"Regime analysis views power as fragmented and regimes as the collaborative arrangements through which local government and private actors assemble the capacity to govern\" (Mossberger and Stoker 2016: 812, quoted p. 108)",
"\"Urban politics is seen as the realm of social movements, which are socially more significant than individual pressure groups.\" (p. 110)",
"\"In essence, agonism involves a willingness to agree to disagree.\" (p. 112)"],
dims:{sa:60, rt:70, de:50, us:65, mp:70, norm:"Explicitly normative: equity, equality and justice (recognition, process, procedure, outcomes); planners as advocates rather than neutral technocrats; research from the emic perspective of disempowered groups, often as action research; conflict accepted (agonism) rather than wished away."},
exam:"Rydin is the framework text: use it to NAME the perspective in a commentary. Grounding: urban politics sits between agency-centred coalition/regime analysis and structural political economy (ch. 7); USMs keep capitalist conflict in view but give politics relative autonomy (Gramsci). Best critiques: (1) Marxist political economy: regime and coalition analysis is too agent-based and ignores structural drivers of accumulation; incremental movements cannot change structures. (2) Rational choice/Olson: why would large, poor, diffuse groups mobilise at all? The free-rider problem predicts under-organisation, which is also why pluralism fails (Olson and urban politics agree pluralism is wrong, for different reasons). (3) Neo-institutionalism: regimes are informal institutions; historical institutionalism explains why regime theory does not travel (US property tax, autonomy). (4) Governmentality: agonism and participation can be technologies that channel conflict; the 'post-political' critique. (5) Hayek: planners as advocates politicise planning and undermine the rule of law. Critical points: normative bias of researchers; US/North-Atlantic origins; agonism may accept existing inequalities. MCQ traps: regime power is 'power to' not 'power over'; Stone not Molotch coined urban regime; collective consumption = public services for reproducing labour (not consumer goods); no Lukes in this chapter; urban politics critiques pluralism."},

{id:"bossuyt", wk:7, title:"Bossuyt & D'Ottaviano (2025) Patterns of protection for housing commons", cite:"Bossuyt, D. & D'Ottaviano, C. (2025). The patterns of protection for housing commons: building occupations in São Paulo. International Journal of Urban and Regional Research, 2025 issue 5, 1021–1039. https://doi.org/10.1111/1468-2427.13335", theory:"Urban commons (neo-Marxian commons theory combined with Ostrom-style institutionalism); urban social movements", status:"full",
statusNote:"Built from the full published open-access text (IJURR 2025, issue 5, pp. 1021–1039 per the Wiley download header; volume number not shown in the file); page numbers are the journal's. Daniël Bossuyt (UU) is the course coordinator: expect this to be one of the commentary articles or at least a reference point.",
one:"Occupying vacant (public) buildings in central São Paulo turns them into housing commons, but reclaiming is not enough: commons must be protected against enclosure over time. Two self-managed cases (Dandara, Marisa Letícia) show five patterns of protection at three levels (regularization, restoration, integration, ideation, federation), yet protection is partial because regularization converts collective use claims into individual private titles that open new routes to enclosure.",
summary:["Problem and theory (pp. 1021–1024). The global housing crisis shows the failure of markets; the commons has emerged as a paradigm for reclaiming housing. Research on common-pool resources studies stability (Ostrom), but urban-commons work neglects reproduction: how commons endure against enclosure by capital and state. Housing commons have three dimensions: use value over exchange value (decommodification), self-governance (collective-choice and operational rules), and solidarity through cohabitation. Enclosure takes three forms: commodification (selling for profit), marginalization (exclusivity towards outsiders) and cooptation (state undermining self-governance). Theorists split on property: Dardot and Laval (commons cannot be property), Harvey ('some degree of closure' needed), de Angelis and Stavrides (porosity and proliferation). The authors use de Angelis' tripartite commons (common good, community, commoning practices) and a relational view of property.",
"Context and method (pp. 1024–1028). Qualitative participatory action research (2016–2021, via the Brazilian extensão model: one team member was architect of Dandara's retrofit) plus 19 interviews (10 residents, 3 movement leaders, 3 policymakers, 2 social workers, 1 architect). São Paulo has about 590,000 vacant properties and 29,500 homeless families (2022 census). The 1988 Constitution and 2001 City Statute enshrine the right to housing and the social function of property; occupations exploit the contradiction between this principle and the right to private property, legitimising themselves by targeting vacant, tax-defaulting or public buildings. The ULC (founded 1991), part of the UMM umbrella (1987), is less confrontational and frames occupation through citizenship and social rights.",
"The cases (pp. 1028–1033). Dandara (former state court in Sé, occupied 2009, renovated 2014–2018) and Marisa Letícia (INSS warehouse site in Brás, completed 2019) are the only two occupations in central São Paulo completed as permanent self-managed housing. Stages: appropriation (forced entry, care, rules of access, legitimacy vs 'invasion'); regularization via autogestão and structural coupling with the state (SPU Ordinance 179; MCMV-Entidades, which gave movements direct access to federal funds but at a cap requiring municipal and state top-ups); renovation through mutirão, committees and an effort-based points system that allocated units and prevented free-riding; moving in, with gates, doormen, condominium courses by social workers. Property regimes diverge: Marisa Letícia became an individual condominium; Dandara a use-right concession.",
"Patterns of protection (pp. 1033–1035). Level of the common good: regularization (legal recognition, tenure security) and material restoration (habitability, night vigils, barriers). Level between housing development and movement: integration (embedding residents in the movement's political struggle; points system cultivates solidarity) and ideation (commons ideas stored in movements and materialising later, e.g. Uruguayan cooperative know-how). Interface movement–state: federation (floor committees → resident committees → entidades → movements → federations), which inserted autogestão into state policy (MCMV-E).",
"Partial protection and contribution (pp. 1035–1037). Regularization converts collectively claimed public property into individual private titles plus mortgages, making households 'indebted subjects' and eroding collective action; movements ban sale and subletting but cannot enforce it, and a unit appeared on a subletting platform. Institutionalist approaches are 'only of partial use' because they ignore the political dimension; commoning is a pragmatic practice with contradictions. Contributions: combining institutionalist and neo-Marxian understandings of the commons, and showing private law's progressive potential; they call for legal reform enabling collective property and for an 'archipelago of the commons'."],
concepts:[["Commons / commoning","Commons: resources collectively produced, shared and used for use value; commoning: the active practices of sharing and managing them. Housing is not a commons in itself but becomes one through practices and rules (p. 1022)."],
["Three dimensions of housing commons","Use value over exchange value (decommodification); self-governance (residents set collective-choice and operational rules); solidarity and participation through cohabitation (p. 1022)."],
["Enclosure (three forms)","Commodification (individual sale for profit), marginalization (exclusivity towards outsiders), cooptation (state undermining self-governance) (p. 1023)."],
["Tripartite commons (de Angelis)","A social system of common good (object, incl. relational property), community (subject) and commoning practices, within a socio-political context (pp. 1023–1024)."],
["Social function of property","Brazilian constitutional principle that private property must benefit the collective; basis for legitimising occupation of vacant property against the right to private property (p. 1027)."],
["Autogestão / mutirão","Collective self-management and collective labour: residents' organisations (entidades) run procurement, labour and construction; also a political principle of horizontal governance (pp. 1029–1031)."],
["Structural coupling","De Angelis: commons strategically align with state systems (legal frameworks, funding) to stabilise their claims and safeguard autonomy (p. 1030)."],
["MCMV-Entidades","Federal programme (2009) channelling funds to movement-led self-managed housing (3% of the MCMV budget); first direct federal access for movements; per-unit cap insufficient for central retrofits (p. 1030)."],
["Effort-based points system","Allocation of units by participation (meetings, occupations, marches) to incentivise contribution and prevent free-riding: a self-regulatory boundary (p. 1031)."],
["Five patterns of protection","Regularization and restoration (housing development); integration and ideation (development ↔ movement); federation (movement ↔ state) (pp. 1033–1035)."],
["Ideation","Varvarousis: commons 'ideated' during a liminal occupation materialise later elsewhere; know-how stored in movements awaits an opportune political moment (pp. 1034–1035)."],
["Partial protection / new enclosure","Regularization protects against eviction but creates individual titles and debt that enable commodification (subletting, sale) (p. 1035)."]],
fig:`<svg viewBox="0 0 620 300" role="img" aria-label="Commoning cycle from appropriation to moving in, five patterns of protection at three levels, and new enclosure through private titles"><defs><marker id="mk_bossuyt" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="20" y="10" width="130" height="48" rx="8" class="bx"/><text x="85" y="30" text-anchor="middle">Appropriation</text><text x="85" y="47" text-anchor="middle" class="mut" font-size="11">occupy vacant bldg</text>
<rect x="175" y="10" width="130" height="48" rx="8" class="bx"/><text x="240" y="30" text-anchor="middle">Regularization</text><text x="240" y="47" text-anchor="middle" class="mut" font-size="11">coupling with state</text>
<rect x="330" y="10" width="130" height="48" rx="8" class="bx"/><text x="395" y="30" text-anchor="middle">Renovation</text><text x="395" y="47" text-anchor="middle" class="mut" font-size="11">mutirão, autogestão</text>
<rect x="485" y="10" width="115" height="48" rx="8" class="bx"/><text x="542" y="30" text-anchor="middle">Moving in</text><text x="542" y="47" text-anchor="middle" class="mut" font-size="11">condominium</text>
<line x1="150" y1="34" x2="172" y2="34" class="ln" stroke-width="1.5" marker-end="url(#mk_bossuyt)"/><line x1="305" y1="34" x2="327" y2="34" class="ln" stroke-width="1.5" marker-end="url(#mk_bossuyt)"/><line x1="460" y1="34" x2="482" y2="34" class="ln" stroke-width="1.5" marker-end="url(#mk_bossuyt)"/>
<text x="310" y="88" text-anchor="middle">Five patterns of protection at three levels</text>
<rect x="20" y="100" width="180" height="92" rx="8" class="bxg"/><text x="110" y="122" text-anchor="middle">1 Housing development</text><text x="110" y="148" text-anchor="middle" class="mut">regularization</text><text x="110" y="166" text-anchor="middle" class="mut">restoration</text>
<rect x="220" y="100" width="180" height="92" rx="8" class="bxi"/><text x="310" y="122" text-anchor="middle">2 Development ↔</text><text x="310" y="138" text-anchor="middle">movement</text><text x="310" y="160" text-anchor="middle" class="mut">integration</text><text x="310" y="178" text-anchor="middle" class="mut">ideation</text>
<rect x="420" y="100" width="180" height="92" rx="8" class="bxw"/><text x="510" y="122" text-anchor="middle">3 Movement ↔ state</text><text x="510" y="154" text-anchor="middle" class="mut">federation</text>
<line x1="110" y1="192" x2="220" y2="236" class="ln" stroke-width="1.5" marker-end="url(#mk_bossuyt)"/>
<rect x="220" y="236" width="220" height="56" rx="8" class="bxa"/><text x="330" y="256" text-anchor="middle">Partial: new enclosure</text><text x="330" y="274" text-anchor="middle" font-size="11">private titles, debt,</text><text x="330" y="287" text-anchor="middle" font-size="11">subletting online</text>
<text x="520" y="262" text-anchor="middle" class="mut" font-size="11">use value vs</text><text x="520" y="277" text-anchor="middle" class="mut" font-size="11">exchange value</text>
</g></svg>`,
cap:"Commoning cycle (top), the five patterns of protection by level (middle) and the contradiction that regularization reopens enclosure (bottom).",
table:{head:["Pattern","Level","What it protects","Case evidence"],rows:[
["Regularization","Housing development (common good)","Tenure security against eviction via legal recognition","SPU Ordinance 179 (Dandara, use-right concession); MCMV-E (Marisa Letícia, condominium)"],
["Restoration","Housing development","Habitability, safety, collective use rights","Mutirão renovation; night vigils; gates, doorman"],
["Integration","Development ↔ movement","Political engagement, solidarity; prevents marginalization","Entidades as entry point; effort-based points system"],
["Ideation","Development ↔ movement","Know-how that outlives hostile politics","Uruguayan cooperative federation's influence (1980s)"],
["Federation","Movement ↔ state","Resources and policy change","ULC within UMM; autogestão institutionalised in MCMV-E"]]},
example:"Dandara: a vacant former state court on Avenida Ipiranga (Sé) occupied by the ULC in 2009 after negotiations with the federal patrimony secretariat stalled. SPU Ordinance 179 designated it a public-interest asset; MCMV-Entidades funded a self-managed retrofit (federal cap of BRL 76,000 per unit, topped up by state and municipal funds). Families earned points for participation, sat on committees and slept on the mezzanine for over a year to guard the site; they moved in from December 2017 under a use-right concession. Residents may not sell or sublet, but the movement cannot enforce this.",
quotes:["\"Housing, like any other good, does not constitute a commons in and of itself; rather, it becomes one through an open-ended interaction between practices and rules (Dardot and Laval, 2019).\" (p. 1022)",
"\"Housing units were allocated by entidades using an effort-based points system designed to incentivize participation and prevent free-riding.\" (p. 1031)",
"\"Collective use claims are thus essentially transformed into individual property titles, illustrating how regularization—purely out of necessity—may reproduce a hegemonic property regime in the absence of legal options for collective ownership.\" (p. 1034)",
"\"In trying to understand the stability of housing commons, prevailing institutionalist approaches are only of partial use because they overlook the political dimension integral to such projects.\" (p. 1036)"],
dims:{sa:65, rt:55, de:55, us:80, mp:65, norm:"Decommodification of housing (use value over exchange value), right to housing and to live in the centre, social function of property, self-management and solidarity; engaged research (participatory action research with the movements); calls for legal reform enabling collective property."},
exam:"Grounding perspective: urban commons theory in a neo-Marxian register (de Angelis, Harvey, Dardot and Laval: enclosure, use vs exchange value, capitalist urbanization) combined with Ostrom-style institutionalism (collective-choice rules, boundaries, points system against free-riding); movements are USMs in Castells' sense (collective consumption, the right to the city). The authors themselves claim to bridge institutionalist and neo-Marxian views. Best critiques: (1) Neo-institutionalism / Pruijt: regularization, MCMV-E and 'structural coupling' look like institutionalization or even cooptation (movements become housing producers for a countercyclical state programme); historical institutionalism explains why only a condominium regime was available (path dependence of Brazil's ownership culture). (2) Marxist political economy (harder line): the state crafts private property and debt from collective claims; commons as a fix that lets the state off the hook; only two successes out of many occupations. (3) Rational choice/Olson: the points system IS a selective incentive; residents' homeownership aspirations and subletting show individual interest eroding the collective good once the selective incentive ends. (4) Hayek: secure private titles are what give residents security and freedom; occupations violate the rule of law and property. (5) Governmentality: condominium courses and mortgages produce responsible, indebted subjects. Critical points: two successful cases (selection on the dependent variable), researchers are involved actors (PAR), normative commitment to commons shapes interpretation, 'protection' partly means exclusion. MCQ traps: five patterns (not three), levels, 'structural coupling' is de Angelis', enclosure forms."},

{id:"pruijt", wk:7, title:"Pruijt (2003) Is the institutionalization of urban movements inevitable?", cite:"Pruijt, H. (2003). Is the institutionalization of urban movements inevitable? A comparison of the opportunities for sustained squatting in New York City and Amsterdam. International Journal of Urban and Regional Research, 27(1), 133–157. https://doi.org/10.1111/1468-2427.00436", theory:"Urban social movements / political opportunity structure, testing post-Fordist theory and Castells' life-cycle view of institutionalization", status:"full",
statusNote:"Built from the full text of the author's PREPRINT (header: 'Preprint. Published in IJURR, 2003, Vol. 27, nr. 1, March, 133-157'). Page numbers given here are the preprint's own (pp. 1–29), NOT the journal pagination 133–157; wording may differ slightly from the published version.",
one:"Institutionalization of urban movements is not inevitable: Amsterdam's squatters combined legalization with continued disruption (flexible institutionalization), whereas in New York the market-oriented regime co-opted housing-movement squatting into service provision. A squatters' movement proper, for which squatting is an end and not only a means, is immune to cooptation; paradoxically, a redistributive regime offers more opportunities for squatting than a market-oriented one.",
summary:["Question and theory (pp. 1–6). Squatting, like any movement, operates within an opportunity structure. Castells (1977) observed that states respond to radical urban movements with both repression and integration; Castells (1983) held that institutionalization, with its attendant identity loss, is inevitable, and protest-wave theory places it at the end of a cycle. Pruijt distinguishes two forms of integration. Institutionalization: a movement channelled into a stable pattern based on formalized rules; terminal (convention replaces disruption) or flexible (conventional tactics complement disruptive ones). Cooptation (after Selznick): the co-opting organization embraces some movement ideas while redefining problems so that solving them does not threaten its stability. Post-Fordist theory predicts that a market-oriented regime, cutting welfare, pushes the 'privatization of poverty' and co-opts movement groups as service providers, while city competition increases repression.",
"Cases (pp. 6–11). Both cities had a housing shortage and many vacant buildings but different regimes: the US a liberal welfare regime, the Netherlands social-democratic traits (Esping-Andersen). Amsterdam housed about 9,000 squatters (1981) with a rich infrastructure; New York's movement peaked at 500 squatters in 20 buildings. In Amsterdam the municipality bought about 200 squats and handed them to housing associations; squatters took part in planning, yet kept defending buildings and rioting (e.g. the 1980 coronation): flexible institutionalization, with hardly any cooptation. In New York, 1970s squatting by housing groups died out as organizers moved into city programmes (Tenant Interim Lease, official homesteading with 'sweat equity'), ACORN got 58 buildings only after promising to stop squatting, and Banana Kelly became a service provider: cooptation as post-Fordist theory predicts.",
"The anomaly and its explanation (pp. 11–14). After 1983 a squatters' movement proper emerged on the Lower East Side that was neither co-opted nor repressed out of existence; the city refused to negotiate, and 11 squats were legalized only in 2002 via UHAB once no squattable buildings were left: terminal institutionalization. The city did try cooptation elsewhere (ICP, Bronx, 1992), so the explanation lies in the movement. For a housing movement, squatting is a means to house the poor; officials can claim to share the goal and offer support if squatters switch to approved means. For a squatters' movement, squatting is itself institutionalized (Berger and Luckmann) as means and goal, so officials cannot claim shared goals. European activists carried this identity to New York: a pre-existing oppositional identity can partly override the opportunity structure.",
"Other opportunity-structure differences (pp. 14–18). Property protection: the 1971 Dutch Supreme Court extended 'house right' to squatters, whereas in the US squatting is criminal trespass, pushing squatters to covert action and city-owned buildings, which leaves speculators alone. Technical condition: New York's abandoned, disinvested tenements were far worse than Amsterdam's. Gentrification: squatters can be precursors but squatting is not gentrification; its effect on the Lower East Side is contested (it may have slowed it).",
"Competition with low-income housing providers and conclusion (pp. 19–24). In New York squatters clashed frequently with non-profit developers in an opaque public–private 'poverty industry'; in Amsterdam a broad consensus (affordability, profit/non-profit demarcation, reliability, democratic planning, recognition of squatters' needs) meant squatters left for renewal voluntarily. The market regime leaves one leeway: radicals can act as watchdogs against the 'Weber-Michels' scenario of co-opted groups, but conflict stays local, leaving big real estate, banking and politics unaffected. Post-Fordist theory sees only cooptation; movements that keep an oppositional identity have other options."],
concepts:[["Opportunity structure","The context that determines whether and how a movement can develop and how effective it can be; here urban regime, property law, access to officials, building condition (p. 1)."],
["Institutionalization","A movement 'channeled into a stable pattern based on formalized rules and laws'; for Castells it implies identity loss; for Kriesi et al. a shift from disruption to convention (pp. 2–3)."],
["Terminal vs flexible institutionalization","Terminal: convention replaces disruption (end of movement, e.g. New York 2002). Flexible: conventional tactics complement disruption (Amsterdam) (p. 4)."],
["Cooptation","The co-opting organization embraces some movement ideas while redefining problems so their solution does not threaten its stability; gives activists a role (Selznick; Warren et al.) (p. 4)."],
["Privatization of poverty","Post-Fordist logic: a retreating welfare state encourages self-help and uses movement groups as 'plugs for holes'; self-help becomes a cheaper substitute and absorbs activists' energy (pp. 5, 9)."],
["Market-oriented vs redistributive urban regime","Pruijt's 'urban regime' means a city's policy orientation (market forces vs state intervention/redistribution), grounded in welfare-state regimes (Esping-Andersen), not Stone's coalition concept (pp. 1, 7)."],
["Housing movement vs squatters' movement","For a housing movement squatting is one possible means to house the poor (co-optable); for a squatters' movement squatting is means and end, with its own identity (immune to cooptation) (pp. 12–13)."],
["House right (1971)","Dutch Supreme Court ruling extending protection of the home to squatters, which made long-lived squats possible; its erosion after 1986 coincided with decline (pp. 14–15)."],
["Covert squatting","Without legal rights, New York squatters hid and chose city-owned buildings, which isolated them and left speculators in peace (p. 15)."],
["Poverty industry / Weber-Michels scenario","Opaque third-sector low-income housing sector; co-opted groups may drift from movement to managerial self-interest, and radicals can act as watchdogs (pp. 22–23)."]],
fig:`<svg viewBox="0 0 620 300" role="img" aria-label="Pruijt's typology: state responses of repression and integration; integration as flexible or terminal institutionalization or cooptation, with case outcomes"><defs><marker id="mk_pruijt" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="210" y="8" width="200" height="40" rx="8" class="bx"/><text x="310" y="33" text-anchor="middle">State response</text>
<rect x="40" y="70" width="160" height="38" rx="8" class="bxa"/><text x="120" y="94" text-anchor="middle">Repression</text>
<rect x="380" y="70" width="160" height="38" rx="8" class="bxi"/><text x="460" y="94" text-anchor="middle">Integration</text>
<line x1="280" y1="48" x2="160" y2="68" class="ln" stroke-width="1.5" marker-end="url(#mk_pruijt)"/><line x1="340" y1="48" x2="440" y2="68" class="ln" stroke-width="1.5" marker-end="url(#mk_pruijt)"/>
<line x1="460" y1="108" x2="115" y2="146" class="ln" stroke-width="1.2" marker-end="url(#mk_pruijt)"/><line x1="460" y1="108" x2="310" y2="146" class="ln" stroke-width="1.2" marker-end="url(#mk_pruijt)"/><line x1="460" y1="108" x2="505" y2="146" class="ln" stroke-width="1.2" marker-end="url(#mk_pruijt)"/>
<rect x="20" y="148" width="185" height="64" rx="8" class="bxg"/><text x="112" y="170" text-anchor="middle">Flexible institut.</text><text x="112" y="188" text-anchor="middle" class="mut" font-size="11">convention added,</text><text x="112" y="203" text-anchor="middle" class="mut" font-size="11">disruption kept</text>
<rect x="218" y="148" width="185" height="64" rx="8" class="bxw"/><text x="310" y="170" text-anchor="middle">Terminal institut.</text><text x="310" y="188" text-anchor="middle" class="mut" font-size="11">convention replaces</text><text x="310" y="203" text-anchor="middle" class="mut" font-size="11">disruption</text>
<rect x="416" y="148" width="185" height="64" rx="8" class="bxa"/><text x="508" y="170" text-anchor="middle">Cooptation</text><text x="508" y="188" text-anchor="middle" font-size="11">movement groups →</text><text x="508" y="203" text-anchor="middle" font-size="11">service providers</text>
<text x="112" y="234" text-anchor="middle" font-size="11">Amsterdam squatters'</text><text x="112" y="249" text-anchor="middle" font-size="11">movement 1965–2002</text>
<text x="310" y="234" text-anchor="middle" font-size="11">NY Lower East Side:</text><text x="310" y="249" text-anchor="middle" font-size="11">11 squats legal 2002</text>
<text x="508" y="234" text-anchor="middle" font-size="11">NY housing movement:</text><text x="508" y="249" text-anchor="middle" font-size="11">TIL, ACORN, Banana Kelly</text>
<text x="310" y="284" text-anchor="middle" class="acc">Squatting as end (not only means) → immune to cooptation</text>
</g></svg>`,
cap:"Pruijt's three forms of integration and where each case ends up; cooptation is favoured by a market-oriented regime.",
table:{head:["","New York City","Amsterdam"],rows:[
["Urban regime","Market-oriented (liberal welfare regime)","Regulation/redistribution (social-democratic traits)"],
["Squatting as housing-movement tactic","1970–72; co-opted (plus repression), visible squatting disappears","Not present"],
["Squatters' movement proper","1983–2002; not co-opted; terminal institutionalization (2002)","1965–2002; not co-opted; flexible institutionalization"],
["Protection of owners against squatters","Strict (trespass)","Qualified (1971 house right)"],
["Squatters' access to officials","Direct access impossible","Easy"],
["Technical state / ownership of squats","Poor; public buildings only","Poor to outstanding; public and private"],
["Conflict with non-profit low-income developers","Frequent (opaque 'poverty industry')","Rare (broad consensus on renewal)"],
["Scope of conflict","Neighbourhood, low-income housing arena","Municipal and national politics, real estate, banks"]]},
example:"ACORN in Brooklyn (p. 10): in 1985 it organized the squatting of 25 city-owned buildings that were due to be auctioned. The city changed policy and turned 58 buildings over to ACORN/Mutual Housing Association of New York, with rehabilitation funds, but only after ACORN promised to abandon squatting: a textbook case of cooptation, where officials accept the goal (homes for the poor) and trade support for giving up the oppositional means.",
quotes:["\"Institutionalization means that a movement is channeled into a stable pattern based on formalized rules and laws.\" (preprint p. 2)",
"\"Terminal institutionalization implies that, in the repertoire of action, convention replaces disruption; in flexible institutionalization, conventional tactics complement disruptive ones.\" (preprint p. 4)",
"\"Thus the absence of rights gives rise to covert action which diminishes the likelihood of cooperation and self-organization.\" (preprint p. 15)",
"\"A squatters' movement such as the one in Amsterdam is immune to cooptation because it involves squatting not only as a means but also as an end.\" (preprint p. 23)"],
dims:{sa:50, rt:55, de:55, us:70, mp:55, norm:"Implicitly sympathetic to squatting: 'effective squatting' means viable squatting models for all empty buildings and a lively, low-income-people-friendly city; favours redistributive planning and the Amsterdam consensus model; critical of self-help as a cheap substitute for welfare (privatization of poverty)."},
exam:"Grounding perspective: social-movement theory (political opportunity structure, repertoires of action) used to test post-Fordist (neo-Marxian regulation) theory and Castells' claim that institutionalization is inevitable; structure (regime, law, building stock) vs agency (movement identity) is the central tension. Best critiques: (1) Neo-institutionalism: Pruijt's own key term. Sociological institutionalism explains why the squatters' identity became taken for granted (Berger and Luckmann, which he cites) and why co-opted groups converge on service-provider forms (isomorphism); historical institutionalism: the 1971 ruling as a critical juncture creating path dependence. (2) Rational choice/Olson: squatting is a rare movement where the collective good comes with a private, excludable benefit (a home), i.e. a selective incentive, which explains mobilisation; but it also explains why housing-movement squatters accept legalization (economic vs political aims, Cherki) and why homesteaders turned against squatters once they became owners. (3) Hayek: squatting violates property rights and the rule of law; the Amsterdam model depends on heavy state planning. (4) Governmentality: cooptation and the 'privatization of poverty' as governing through community and self-help ('state-organized norm of organization and control'). (5) Marxist: squatters as unwitting gentrification pioneers; conflict contained locally leaves capital untouched (Pruijt concedes this). Weaknesses: two cases, author involved in the Amsterdam scene/research (1980–84), functionalist reasoning, dated. MCQ traps: 'urban regime' here = market vs redistributive orientation, not Stone; flexible (Amsterdam) vs terminal (NY 2002); cooptation ≠ institutionalization; market regime offers FEWER opportunities for squatting except in low-income rehabilitation."}
];

const FC_C=[
["rydin6","How does the urban politics perspective differ from the governance frame (ch. 5)?","Governance assumes conflicts can be handled towards effective and even agreed outcomes; urban politics sees conflict as unavoidable, power at play within planning processes and inequality in outcomes (p. 105)."],
["rydin6","Why does urban politics reject pluralism (Dahl)?","Pluralism assumes groups form when demand exists; but power and resources are unequal, some issues never become the focus of activism, and pluralism legitimated a focus on middle-class pressure groups: it was seen as naïve (p. 106)."],
["rydin6","Agyeman's four aspects of justice?","Recognition of groups as self-determined; fair process; just exercise of procedures (regulation, implementation); fair outcomes (pp. 106–107)."],
["rydin6","Growth coalition (Molotch) and its two critiques?","Actors with most to gain from land and development coalesce with local government to secure property-led growth. Critiques: too agent-based (political economy) and too simple (fragmented, unstable, not only local or growth-led), leading to regime theory (p. 108)."],
["rydin6","Stone's definition of an urban regime and its kind of power?","'An informal yet relatively stable group with access to institutional resources that enable it to have a sustained role in making governing decisions'; it generates 'power to' (capacity to act), not 'power over' (p. 108)."],
["rydin6","Stone's four regime types?","Maintenance/caretaker; development; middle-class progressive; lower-class opportunity expansion (p. 109)."],
["rydin6","Why does regime theory travel badly (Pierre, Holman)?","It reflects US local government (reliance on property taxes, autonomy) and a bias to corporate 'systemic power'; Holman: actor diversity, differences in local autonomy, business incentives, and globalisation (p. 109)."],
["rydin6","What is 'collective consumption' in Castells?","The collective (usually public) means needed to reproduce labour, such as public services; USMs resist their appropriation by the middle class and their limitation to capitalist needs (p. 110)."],
["rydin6","What did Gramsci add for urban politics theorists?","Politics has relative autonomy from socio-economic structure: the working class and disempowered can perceive their own interests and achieve change short of revolution, without a vanguard (p. 110)."],
["rydin6","Agonism in one line, and its main critique?","Conflict is inevitable and productive; aim to turn enemies into adversaries who 'agree to disagree' (Mouffe). Critique: may accept existing power dynamics and inequalities (Yamamoto) (p. 112)."],
["rydin6","Fougère and Bond's Denniston Plateau finding?","Antagonism (protests, hearings) created conditions for agonistic spaces (e.g. the Bioblitz), but institutionalised expert knowledge depoliticised the process so antagonistic pro/anti-mine conflict dominated (pp. 121–122)."],
["bossuyt","Three dimensions of housing commons?","Use value over exchange value (decommodification); self-governance (collective-choice and operational rules); solidarity and participation through cohabitation (p. 1022)."],
["bossuyt","Three forms of enclosure of housing commons?","Commodification (selling for profit), marginalization (exclusivity towards outsiders), cooptation (state undermining self-governance) (p. 1023)."],
["bossuyt","Name the five patterns of protection and their levels.","Regularization and restoration (housing development); integration and ideation (between development and movement); federation (movement and state) (pp. 1033–1035)."],
["bossuyt","What is 'structural coupling'?","De Angelis' term: commons strategically align with state systems (law, funding) to stabilise claims and safeguard autonomy; e.g. SPU Ordinance 179 and MCMV-Entidades (p. 1030)."],
["bossuyt","How do occupations legitimise themselves legally?","By the constitutional social function of property and right to housing: vacant (often tax-defaulting or public) buildings fail their social function, so housing rights should prevail (p. 1027)."],
["bossuyt","Why is protection 'inherently partial'?","Regularization turns collectively claimed public property into individual private titles plus mortgages: indebted subjects, eroded collective action, and possible sale or subletting that movements cannot enforce against (pp. 1035–1036)."],
["bossuyt","Methods and cases?","Participatory action research 2016–2021 (extensão; one member was Dandara's architect) plus 19 interviews; Dandara (former state court, Sé, use-right concession) and Marisa Letícia (INSS warehouse site, Brás, condominium) (pp. 1024, 1028, 1032)."],
["bossuyt","Two claimed contributions?","Bringing together institutionalist and neo-Marxian understandings of the commons; showing private law's progressive potential (vs a focus on public law like the City Statute) (p. 1036)."],
["pruijt","Pruijt's definition of cooptation?","The co-opting organization embraces some movement ideas while redefining problems so that solving them does not threaten its own stability, giving co-opted activists a role (p. 4)."],
["pruijt","Terminal vs flexible institutionalization, with cases?","Terminal: convention replaces disruption (New York Lower East Side, 11 squats legalized 2002 when no squattable buildings were left). Flexible: convention complements disruption (Amsterdam) (pp. 4, 8, 11)."],
["pruijt","What does post-Fordist theory predict and was it confirmed?","A market-oriented regime 'privatizes poverty' and co-opts movement groups as service providers (plus more repression). Confirmed for New York housing-movement squatting (TIL, ACORN, Banana Kelly), not for Amsterdam or the post-1983 Lower East Side (pp. 5–11)."],
["pruijt","Why is a squatters' movement immune to cooptation?","Squatting is means and end; officials cannot claim to share the goal and offer support in exchange for dropping squatting, as they can with a housing movement (pp. 12–13, 23)."],
["pruijt","Why was squatting harder in New York? (three opportunity-structure factors)","Strict property protection (trespass → covert squatting, only city buildings), no access to officials, and poor technical condition of disinvested buildings (pp. 14–16, 23)."],
["pruijt","The paradoxical main conclusion?","A market-oriented regime with little redistributive commitment offers fewer opportunities for squatting than a redistributive, planning-based regime (pp. 22–23)."],
["pruijt","Why did Amsterdam squatters rarely fight low-income housing developers?","Broad consensus on renewal: affordability ('building for the neighbourhood'), clear profit/non-profit demarcation, reliability, democratic planning, recognition of squatters' needs (pp. 20–22)."],
["pruijt","Which text is this and what page numbers?","The author's preprint; pages cited are preprint pp. 1–29, not IJURR 27(1) pp. 133–157."],
["pruijt","Link: Pruijt's institutionalization vs Bossuyt's patterns of protection?","Pruijt treats integration with the state as a threat (identity loss, cooptation) unless flexible; Bossuyt treats state coupling (regularization, federation) as protection of commons, while admitting it opens new enclosure. São Paulo's ULC is a housing movement using occupation as a means, i.e. Pruijt's co-optable type."],
["bossuyt","Link: how do Bossuyt's cases answer Olson's free-rider problem?","Through selective incentives and rules (Ostrom-style): an effort-based points system rewarding participation with a housing unit, plus committee duties and a one-year minimum for Dandara. Once titles are individual, the incentive ends and individual interest (subletting) re-emerges."],
["rydin6","Link: how do Olson and urban politics both reject pluralism, but differently?","Olson: rational individuals free-ride, so large diffuse groups fail to organise. Urban politics: power and resources are unequal and some issues are kept off the agenda. Both conclude organised groups are not a fair sample of interests; urban politics then asks how the disempowered DO mobilise (movements, identity, place)."]
];

const MCQ_C=[
{t:"rydin6",q:"According to Rydin, what distinguishes the urban politics perspective from the governance perspective?",o:["It assumes conflicts can be resolved through well-designed networks","It sees power at play within planning processes and inequality in outcomes, so planners cannot be neutral","It focuses on the efficiency of markets in land allocation","It treats planning as a technical, value-free activity"],a:1,e:"Rydin: urban politics rejects governance's assumption of agreed outcomes and sees power and inequality; planners must behave more like advocates (p. 105)."},
{t:"rydin6",q:"In urban regime theory (Stone), regime power is best described as:",o:["'Power over': domination of local government by business","'Power to': capacity to act assembled by combining interdependent resources","Structural power of capital determining all outcomes","Formal legal authority of elected councils"],a:1,e:"Regimes generate 'power to' achieve goals, not 'power over' other actors (p. 108)."},
{t:"rydin6",q:"For Castells, 'collective consumption' refers to:",o:["Mass consumption of consumer goods in cities","The collective (usually public) means, such as services, needed to reproduce labour","Shared ownership of housing cooperatives","Tourism and leisure consumption in regenerated areas"],a:1,e:"Labour cannot be reproduced by private means alone; public services are at issue in urban social movements (p. 110)."},
{t:"rydin6",q:"Which critique of the growth coalition concept came from the political economy perspective?",o:["It is too structuralist","It is too agent-based","It ignores the role of land ownership","It overstates the role of planners"],a:1,e:"Political economists favoured a more structuralist approach and saw the coalition approach as too agent-based (p. 108)."},
{t:"rydin6",q:"Which statement about agonism (Mouffe) as presented by Rydin is correct?",o:["It aims at consensus through ideal speech","It treats conflict as a sign of planning failure","It sees conflict as inevitable and productive, aiming to turn opponents into adversaries","It is Rydin's term for violent protest"],a:2,e:"Agonism dismisses governance's move to consensus; conflict is inevitable and productive; 'agree to disagree' (p. 112)."},
{t:"rydin6",q:"Which of the following does Rydin's chapter NOT discuss?",o:["Stone's four types of urban regime","Agyeman's aspects of justice","Lukes' three dimensions of power","Mayer's four phases of urban social movements"],a:2,e:"The chapter distinguishes only 'power to' vs 'power over'; Lukes is not discussed."},
{t:"bossuyt",q:"Which is NOT one of Bossuyt and D'Ottaviano's five patterns of protection?",o:["Ideation","Federation","Gentrification","Restoration"],a:2,e:"The five are regularization, restoration, integration, ideation and federation (pp. 1033–1035)."},
{t:"bossuyt",q:"At which level does 'federation' operate?",o:["Within the housing development","Between the housing development and the social movement","At the interface between social movements and the state","Between individual residents"],a:2,e:"Regularization/restoration: development; integration/ideation: development–movement; federation: movement–state (pp. 1033–1034)."},
{t:"bossuyt",q:"Why do the authors call protection of housing commons 'inherently partial'?",o:["Because the state evicted both occupations","Because regularization turns collective use claims into individual private titles and debt, opening new enclosure","Because the movements refused state funding","Because residents rejected self-management"],a:1,e:"Private titles and mortgages make households indebted subjects; sale/subletting cannot be prevented (pp. 1035–1036)."},
{t:"bossuyt",q:"'Structural coupling' (de Angelis) in the article means:",o:["The physical linking of buildings into one complex","Commons strategically aligning with state systems to stabilise claims and safeguard autonomy","The cooptation of movements by political parties","The coupling of rents to incomes"],a:1,e:"Regularization relies on structural coupling with the state's legal frameworks and resources (p. 1030)."},
{t:"bossuyt",q:"Which legal principle do São Paulo's housing movements invoke to legitimise occupations?",o:["Adverse possession","The social function of property","The house right (huisrecht)","Eminent domain"],a:1,e:"The constitutional social function of property and the right to housing (p. 1027). Adverse possession and house right come from Pruijt's US/Dutch discussion."},
{t:"bossuyt",q:"What do the authors claim as their theoretical contribution?",o:["Rejecting Ostrom's institutionalism entirely","Bringing together institutionalist and neo-Marxian understandings of the commons","Proving that commons cannot coexist with property","Showing that public law (City Statute) is sufficient to sustain commons"],a:1,e:"First contribution: combining institutionalist and neo-Marxian views; second: private law's progressive potential (p. 1036)."},
{t:"pruijt",q:"In Pruijt's terms, Amsterdam's squatters' movement experienced:",o:["Terminal institutionalization","Cooptation into service providers","Flexible institutionalization","Pure repression"],a:2,e:"Legalization and participation coexisted with continued disruption: conventional tactics complemented disruptive ones (pp. 7–8)."},
{t:"pruijt",q:"What does 'urban regime' mean in Pruijt's comparison?",o:["Stone's informal governing coalition","A city's orientation towards market forces vs state intervention and redistribution","The legal regime of squatting","The squatters' internal organisation"],a:1,e:"He compares a market-oriented (NY) with a regulation/redistribution (Amsterdam) regime, rooted in welfare-state types; not Stone's concept."},
{t:"pruijt",q:"Why, according to Pruijt, is a squatters' movement proper immune to cooptation?",o:["Its members are wealthier","It has formal leaders who refuse negotiation","Squatting is both means and end, so officials cannot claim to share its goal","US law forbids negotiation with squatters"],a:2,e:"Cooptation requires officials to accept the movement's goal and offer support for switching means; impossible when squatting is itself the goal (pp. 12–13, 23)."},
{t:"pruijt",q:"Which outcome did Pruijt find paradoxical?",o:["Repression increased squatting","A market-oriented regime offered fewer opportunities for squatting than a redistributive one","Legalization ended squatting in Amsterdam","New York squatters targeted private speculators"],a:1,e:"One might expect market neglect to leave space for squatting, yet the redistributive, planning-based regime offered more (pp. 22–23)."},
{t:"pruijt",q:"The 2002 legalization of eleven Lower East Side squats is classified as:",o:["Flexible institutionalization","Terminal institutionalization","Cooptation","Repression"],a:1,e:"It came when no squattable buildings were left and required no contact with officials: terminal (p. 11)."},
{t:"pruijt",q:"Which is a consequence of the absence of legal protection for squatters in New York?",o:["Squatters mainly occupied private speculative buildings","Covert squatting, isolation and a focus on city-owned buildings","Easy access to municipal officials","Rapid legalization"],a:1,e:"Covert action reduces cooperation and self-organization; city-owned buildings carry less eviction risk (p. 15)."},
{t:"bossuyt",q:"Seen through Pruijt's framework, the São Paulo ULC occupations are closest to:",o:["A squatters' movement proper, immune to cooptation","A housing movement using occupation as a means, and thus susceptible to cooptation/institutionalization","A post-political agonistic coalition","A growth coalition"],a:1,e:"ULC uses occupation as a tactic to obtain housing and seeks validation through citizenship and social rights; Pruijt predicts such movements can be integrated once officials accept the goal (via MCMV-E)."},
{t:"bossuyt",q:"From an Olsonian rational-choice perspective, the effort-based points system in Dandara and Marisa Letícia is best described as:",o:["Coercion by the state","A selective incentive that makes contributing to the collective good individually rational","A pure public good","An example of agonism"],a:1,e:"Units (private, excludable benefits) are allocated by participation to prevent free-riding: Olson's selective incentive, operationalised as Ostrom-style rules."}
];

const OPEN_C=[
{t:"rydin6",pts:20,q:"Rydin argues that from an urban politics perspective 'planners cannot be neutral'. Identify the theoretical perspective(s) on which her account of urban politics rests, explain how growth coalitions, urban regimes and urban social movements each conceptualise power, and critically evaluate this perspective from ONE alternative perspective discussed in the course.",
model:"Rydin's urban politics frame is a critique of governance theory: conflict is unavoidable, power operates within planning and outcomes are unequal, so the planner must plan justly and act as advocate (p. 105). It rejects pluralism (Dahl) as naïve. Its three dynamics differ in how they see power. Growth coalitions (Molotch): elites with land and property stakes steer local government towards growth, i.e. power over the agenda rooted in class and land. Urban regimes (Stone): an informal but stable coalition assembles 'power to' govern by pooling interdependent resources; business's 'systemic power' biases regimes (Pierre). Urban social movements (Castells, via Gramsci): the disempowered mobilise around social cleavages, first over collective consumption, later identity and place; politics has relative autonomy from capitalist structures. Justice (Agyeman: recognition, process, procedure, outcomes) runs through all. Critique from rational choice (Olson): urban politics assumes that the disempowered mobilise, but collective action is costly; large diffuse groups free-ride, so movements should be rare and short-lived unless selective incentives exist. This explains why some issues never become activism better than 'power' alone, and warns planners that organised voices are unrepresentative. Olson in turn underplays identity, solidarity and moral motives that USM theory highlights, and ignores unequal structural power. A second angle (political economy) would call regime theory too agent-based. Conclusion: urban politics is strong on normativity and conflict, weaker on explaining when mobilisation happens.",
rubric:["Identifies urban politics as a critique of governance/pluralism, with links to structuralism (Gramsci, Castells) and normative commitment to justice","Correctly distinguishes growth coalition, regime ('power to', Stone) and USM (collective consumption) views of power","Develops a coherent critique from one named alternative perspective (e.g. Olson, political economy, neo-institutionalism, governmentality, Hayek)","Evaluates: strengths and limits on both sides, uses chapter evidence and page references"]},
{t:"bossuyt",pts:20,q:"Write a theoretical commentary on Bossuyt and D'Ottaviano (2025). Which theoretical perspective grounds their argument about the 'patterns of protection' of housing commons? Critique their argument from an alternative perspective of your choice (for example neo-institutionalism, rational choice or Hayekian liberalism).",
model:"The article is grounded in urban commons theory in a neo-Marxian register: housing is reclaimed from enclosure by capital and state, prioritising use over exchange value (de Angelis, Harvey, Dardot and Laval), and occupations are movement-led claims based on the social function of property and the right to the city. The authors add Ostrom-style institutionalism (collective-choice rules, boundaries) and claim to bridge both (p. 1036). Argument: protection happens through five patterns at three levels (regularization and restoration; integration and ideation; federation), but is partial because regularization reproduces a hegemonic private property regime (p. 1034). Critique from neo-institutionalism, sharpened by Pruijt: what the authors call 'structural coupling' and 'federation' can equally be read as institutionalization and cooptation. MCMV-Entidades embraced the movements' goal (housing the poor) while redefining the problem so it fitted a countercyclical construction programme and homeownership; movements became producers and managers, and the end state is individual condominium titles and mortgages. Historical institutionalism explains why: Brazil's path dependence on ownership (military-era lending, cultural ideal) left no collective tenure form. So the 'protection' patterns may be the mechanism of enclosure rather than a shield against it. The authors partly concede this, but their normative commitment to commons and their role as participatory researchers, and the selection of the only two successes, bias the reading towards protection. A rational-choice angle adds that the points system is a selective incentive that disappears after allocation, explaining subletting. Evaluation: strong on contradictions and empirical richness; weaker on generalisability.",
rubric:["Identifies commons theory (neo-Marxian enclosure/use value) plus Ostrom institutionalism as grounding, with key concepts (five patterns, levels, structural coupling, enclosure)","Accurately reports the argument, including partial protection via private titles and debt","Critiques convincingly from a named alternative perspective (e.g. institutionalization/cooptation, path dependence, Olson's selective incentives, Hayek on property)","Evaluates methodology and normativity (two successful cases, participatory action research, authors' commitment)"]},
{t:"pruijt",pts:20,q:"Write a theoretical commentary on Pruijt (2003). Which theoretical perspective grounds his argument that institutionalization of urban movements is not inevitable? Critique it from an alternative perspective discussed in the course.",
model:"Pruijt's argument rests on social-movement theory (political opportunity structure, repertoires of action) used to test two structural claims: Castells' view that institutionalization, with identity loss, is inevitable, and post-Fordist theory that market-oriented regimes 'privatize poverty' and co-opt movements as service providers. Comparing Amsterdam and New York, he distinguishes terminal and flexible institutionalization and cooptation. New York's housing-movement squatting was co-opted (TIL, ACORN, Banana Kelly), confirming post-Fordism; Amsterdam's squatters were legalised yet kept disrupting (flexible). A squatters' movement proper, for which squatting is means and end, resists cooptation; opportunity structure (property law, access, building condition) still shapes outcomes, so a redistributive regime paradoxically offers more room for squatting. Critique from rational choice (Olson): squatting is unusual because the collective good comes bundled with a private, excludable benefit, a home: a selective incentive. This explains mobilisation without needing identity, and also cooptation: once legalization secures individual housing, the incentive to keep protesting falls (Cherki's economic vs political aims; homesteaders turning against squatters). Pruijt's identity explanation for the Lower East Side is thus under-theorised; rational choice would ask about costs (covert squatting, trespass law) and benefits. Olson, however, struggles with Amsterdam's continued riots after legalization, where expressive and identity motives matter. A neo-institutionalist would add that the 1971 ruling was a critical juncture. Weaknesses: two cases, author embedded in the Amsterdam scene, functionalist reasoning and a preprint-era dataset. Conclusion: a persuasive challenge to determinism, but with a thin micro-foundation.",
rubric:["Identifies social-movement/opportunity-structure theory and the tested theories (Castells, post-Fordism); correct use of terminal/flexible institutionalization and cooptation","Reports key comparative findings and the means/end mechanism accurately","Critiques from a named alternative perspective with a clear argument (e.g. Olson's selective incentives, neo-institutionalism, governmentality, Hayek, Marxist gentrification critique)","Evaluates design and bias (two cases, functionalism, author involvement, generalisability)"]}
];
