const NEW_D=[
{id:"raco", wk:7, title:"Raco & Imrie (2000) Governmentality and rights and responsibilities in urban policy", cite:"Raco, M. & Imrie, R. (2000). Governmentality and rights and responsibilities in urban policy. Environment and Planning A, 32(12), 2187–2204. doi:10.1068/a3365", theory:"Foucault / governmentality (advanced liberalism, after Rose, Miller and Dean)", status:"full",
 statusNote:"Full article on file (pp. 2187–2204); page numbers are the journal pagination. No lecture slides yet for the 22 Oct session. Links to Rydin ch. 8, Taylor (2016), NPM/rational choice and Marxism are my own connections, marked as such.",
 one:"New Labour's 'rights and responsibilities' agenda, studied through the Single Regeneration Budget (SRB), is not a devolution of power to communities but a shift in the art of government: the state governs 'at a distance' by constructing active, self-responsible communities and binding them with audit, targets and competitive bidding. In return for a little extra freedom, subjects come under greater monitoring, scrutiny and surveillance.",
 summary:["Framework (pp. 2188–2191). Following Foucault, Rose, Miller and Dean, governmentality is the 'conduct of conduct': government works through political rationalities (ways of thinking about which problems authorities should address, with moral justifications and a picture of who is to be governed), programmes (white papers, guidance, inquiries that try to reorganise practice) and technologies (audit, benchmarking, devolved budgets, performance criteria that create 'calculable spaces'). Power is not reducible to the state; the state is 'no more than a specific form of government' (p. 2190). 'Advanced liberalism' governs through the self-governing capacities of free subjects; welfare retrenchment means less state intervention but 'not necessarily ... any less government' (p. 2191).",
 "Rationality and programme: government through community (pp. 2192–2196). SRB (April 1994) replaced many 1980s schemes with one competitive fund for local public–private partnerships that must 'involve the community fully at all stages'. Ten per cent of project funding goes to community 'capacity building'. Territory of government is rescaled from society to community: the local gets 'ontological status' as the site of effective government. The authors read this as directed self-government producing Rose's 'communities of obligation': more rights to define agendas, but conditional on wider responsibilities, and bids must 'work within the grain' of national frameworks. Behind the inclusion rhetoric lie 'discourses of public and private sector abandonment' (p. 2195): deprived areas must provide for themselves.",
 "Technologies: subjectivity and expertise (pp. 2196–2201). Partnerships must file quantitative progress reports every three months against a priori targets; accountability is vertical, not horizontal; underperformance can lead to intensive monitoring or withdrawal of funding. Best Value and Best Practice discipline local authorities and bidders, partly through peer comparison ('disciplinary government at a distance'). Expertise is redrawn: local knowledge is given privileged status rhetorically, yet community representatives are trained by professionals to handle bureaucratic procedures, baselines and monitoring, making community aspirations 'calculable'. Professionals too become subordinated to performance mechanisms.",
 "Conclusion (pp. 2201–2202). The Foucauldian approach links the mentalities and conduct of the population to the objectives and techniques of government. SRB 'identifies and institutionalises communities of action', gives them a minimum of competitively allocated resources, and binds them into 'rigid and closely monitored managerial frameworks'. Because the art of government is politically constructed, it can also be reconstructed: the analysis may feed 'resistance, contestation, and challenge', e.g. subpolitics of identity and a rebuilt 'social'.",
 "Method and status of the claim. The evidence is a critical reading of official documents (DETR bidding guidance, ministerial speeches, CSJ report) plus secondary evaluation evidence (mainly Foley et al. 1998); there is no primary fieldwork (p. 2192). SRB is used as a 'heuristic vehicle' to comment on governmentalisation. This matters for a commentary: the article shows how policy texts construct subjects, not how people on the ground actually experienced or resisted them."],
 concepts:[["Governmentality","Foucault's term for the ensemble of institutions, procedures, calculations and tactics through which the conduct of a population is shaped; government as 'the conduct of conduct', not reducible to the state."],["Political rationality","A way of thinking about which problems can and should be governed, with moral justifications and a description of the subjects to be governed (Rose & Miller)."],["Technologies of government","Practical techniques (audit, targets, benchmarking, devolved budgets, bidding rules) that make programmes operable and create 'calculable spaces of action'."],["Advanced liberalism","Rose's term for rule through the regulated choices of autonomous actors: marketised welfare, audit, fragmentation of collective provision, reinvented community."],["Government at a distance","Central government steers local actors through rules, funding conditions and monitoring instead of direct provision; the governed police themselves."],["Government through community","Community is made both the object and the instrument of policy; pre-existing bonds are transformed, affiliated to expertise and given duties."],["Communities of obligation","Rose: communities gain rights to shape agendas only on condition of accepting wider responsibilities for delivery."],["Responsibilisation / active citizen","Transformation of subjectivity from passive recipient to self-governing agent who takes responsibility for welfare and regeneration."],["Empowerment as technology","After Cruikshank: 'empowerment' is a technique for transforming subjectivity, producing a qualitative change in subjects, not a quantitative gain in power."],["Calculable spaces","Domains made governable through quantification (baselines, outputs, milestones) that experts can monitor from above."]],
 fig:`<svg viewBox="0 0 620 260" role="img" aria-label="Governmentality chain in the SRB: rationality, programme, technologies, subjectivity, and the paradox of freedom versus surveillance"><defs><marker id="arR7" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="15" width="135" height="115" rx="8" class="bxi"/><text x="77" y="36" text-anchor="middle" font-weight="bold">Rationality</text><text x="77" y="56" text-anchor="middle">advanced liberalism:</text><text x="77" y="72" text-anchor="middle">rights and</text><text x="77" y="88" text-anchor="middle">responsibilities</text><text x="77" y="110" text-anchor="middle" class="mut" font-size="11">Blair, CSJ, Mulgan</text>
<rect x="165" y="15" width="135" height="115" rx="8" class="bx"/><text x="232" y="36" text-anchor="middle" font-weight="bold">Programme</text><text x="232" y="56" text-anchor="middle">SRB (1994): bid</text><text x="232" y="72" text-anchor="middle">competitively via</text><text x="232" y="88" text-anchor="middle">local partnerships</text><text x="232" y="110" text-anchor="middle" class="mut" font-size="11">'involve community'</text>
<rect x="320" y="15" width="135" height="115" rx="8" class="bxw"/><text x="387" y="36" text-anchor="middle" font-weight="bold">Technologies</text><text x="387" y="56" text-anchor="middle">10% capacity building</text><text x="387" y="72" text-anchor="middle">quarterly targets</text><text x="387" y="88" text-anchor="middle">audit, Best Value</text><text x="387" y="104" text-anchor="middle">peer review</text>
<rect x="475" y="15" width="135" height="115" rx="8" class="bxg"/><text x="542" y="36" text-anchor="middle" font-weight="bold">Subjectivity</text><text x="542" y="56" text-anchor="middle">active citizens,</text><text x="542" y="72" text-anchor="middle">communities of</text><text x="542" y="88" text-anchor="middle">obligation that</text><text x="542" y="104" text-anchor="middle">police themselves</text>
<line x1="145" y1="72" x2="163" y2="72" class="ln" marker-end="url(#arR7)"/><line x1="300" y1="72" x2="318" y2="72" class="ln" marker-end="url(#arR7)"/><line x1="455" y1="72" x2="473" y2="72" class="ln" marker-end="url(#arR7)"/>
<rect x="60" y="175" width="210" height="70" rx="8" class="bx"/><text x="165" y="198" text-anchor="middle" font-weight="bold">Official discourse</text><text x="165" y="216" text-anchor="middle">empowerment, inclusion,</text><text x="165" y="232" text-anchor="middle">bottom-up</text>
<rect x="350" y="175" width="210" height="70" rx="8" class="bxa"/><text x="455" y="198" text-anchor="middle" font-weight="bold">Foucauldian reading</text><text x="455" y="216" text-anchor="middle">little extra freedom,</text><text x="455" y="232" text-anchor="middle">more surveillance</text>
<line x1="270" y1="210" x2="348" y2="210" class="ln" marker-end="url(#arR7)"/><text x="309" y="202" text-anchor="middle" class="mut" font-size="11">unmasked as</text>
<line x1="542" y1="130" x2="490" y2="173" class="ln" marker-end="url(#arR7)"/><text x="310" y="158" text-anchor="middle" class="mut" font-size="11">government at a distance: DETR, RDAs, partnerships, communities</text>
</g></svg>`,
 cap:"Rationality, programme and technologies produce responsible subjects; 'empowerment' turns out to be a qualitative change in subjectivity under closer control (pp. 2195, 2201).",
 table:{head:["SRB element","Official rationale","Raco & Imrie's reading"],rows:[["Community involvement 'at all stages'","Schemes better focused on local needs; ownership","'not optimal but a necessary requirement (for funders)' (p. 2194)"],["10% capacity building","Community makes a 'full and equal contribution'","Training produces representatives who make aspirations calculable"],["Self-help: credit unions, social enterprises","Active citizenship, local quality of life","Arms-length governance; 'public and private sector abandonment'"],["Quarterly quantitative reporting","Transparency, accountability","Vertical accountability; 'inspection mentality' (Foley et al.)"],["Best Value / Best Practice","'Nonideological' tools of empowerment","Disciplinary power; peer review as government at a distance"],["RDAs as regional bodies","Regional devolution","Sub-contractors of central government (fn. 3)"]]},
 example:"SRB bidding guidance (DETR 1999b): bids must 'involve the community fully at all stages', devote 10% of funding to capacity building, set their own baselines, milestones and outcomes, and file quantitative progress reports every three months; if a scheme 'falls short on its performance, the RDA may take measures varying from the intensive monitoring and review to the reduction or withdrawal of funding' (p. 2198).",
 quotes:["\"the retraction of the welfare state which, while meaning less state intervention, does not necessarily mean any less government\" (p. 2191)","\"It creates forms of 'empowerment' that do not lead to quantitative increases in power for communities but a qualitative transformation of forms of subjectivity to make government work\" (p. 2195)","\"Far from propagating agendas of social 'inclusion', SRB is underpinned by discourses of public and private sector abandonment\" (p. 2195)","\"in return for a little extra freedom of action, subjects come under greater monitoring, scrutiny, and surveillance by the state\" (p. 2201)"],
 dims:{sa:30, rt:45, de:40, us:70, mp:65, norm:"Critical: exposes control behind empowerment rhetoric; values unconditional rights, local democratic (horizontal) accountability and the possibility of resistance/reconstruction of the 'social'."},
 exam:"Grounding perspective: Foucault/governmentality (Rose, Miller, Dean): rationalities, programmes, technologies; power as productive and dispersed, the state as one site among many; subjects constituted by discourse. Structure-leaning but not structuralist (my link: Rydin ch. 8 places Foucauldian work between actor-centred and political-economy approaches). Best critiques: (1) Rational choice / principal-agent (my link: Rydin ch. 8, p. 156, notes NPM is often justified as incentive alignment): the same evidence (managers use monitoring only to check targets; involvement is 'a necessary requirement (for funders)') suggests strategic compliance with funding incentives rather than internalised subjectivity, so governmentality may over-read the texts. (2) Marxist political economy: Raco and Imrie deliberately refuse a unified state and class analysis, yet their own sources point to cost-cutting and 'abandonment'; a Marxist reading would ground SRB in fiscal crisis and the reproduction of uneven development rather than in 'mentalities'. (3) Communicative planning / Healey (quoted in the opening): capacity building could be genuine institution-building; the article offers no way to tell empowerment from control. (4) Method: documents plus secondary evaluation only; little evidence on actual subjects or resistance, which the conclusion itself calls for. MCQ traps: governmentality is not 'less government' but different government; 'empowerment' = qualitative change in subjectivity, not quantitative gain; accountability is vertical, not horizontal; communities of obligation = rights conditional on duties; the paper is about New Labour but says it continues Thatcherite active-citizen ideas."},

{id:"gurran", wk:7, title:"Gurran & Ruming (2016) Less planning, more development? Housing and urban reform discourses in Australia", cite:"Gurran, N. & Ruming, K. (2016). Less planning, more development? Housing and urban reform discourses in Australia. Journal of Economic Policy Reform, 19(3), 262–280. doi:10.1080/17487870.2015.1065184", theory:"Discourse analysis (broadly Foucauldian: regimes of truth) within a critique of neoliberal planning reform", status:"full",
 statusNote:"Full text on file, but it is the online-first version (published online 22 Sep 2015), paginated 1–16, not the issue pagination 262–280. All page numbers here refer to the online-first pages. Figures 1–3 are charts only partly legible in the text file; the numbers used are those stated in the prose. Links to Taylor (2016), Hayek/Glaeser, Marxism and neo-institutionalism are my own connections.",
 one:"In the 2011–2014 New South Wales planning reform, the development industry's framing of planning as 'red tape' that blocks housing supply, growth and affordability became a 'regime of truth' that the government's White Paper and draft Planning Bill largely adopted, while community, environmental and affordable-housing concerns were sidelined. Housing affordability served as a 'semantic justification' for a wider deregulatory agenda; the Bill nevertheless stalled under community backlash, and approvals boomed while prices kept rising.",
 summary:["Context (pp. 1–7). Planning systems have resisted deregulation and elsewhere (UK section 106, US inclusionary zoning) are used to secure affordable housing, but their legitimacy is now questioned for slowing supply (Glaeser and Ward, Ball) and for exclusionary use by owners. Australia has one of the world's most expensive housing markets; ownership fell from about 71% (mid-1980s) to 68% (2012). A long-running national microeconomic reform agenda (COAG) prioritises deregulation of planning and development assessment. Social housing approvals in NSW fell from around 15% of dwellings in 1983 to under 2% in July 2014; the NHSC's 85,000-dwelling shortfall would have been roughly offset (90,000 extra dwellings) had social housing production stayed at its 1996 level (p. 6).",
 "Approach (pp. 2–3, 7–9). A 'broadly Foucauldian analysis' treats language as producing reality: the power of a group rests on its capacity to sustain a version of reality as 'objective truth'; discourses harden into 'regimes of truth' that fix acceptable problems and solutions (Jacobs, Hastings, Clapham). Data: the July 2012 Green Paper (over 1,200 submissions, 72% from community individuals and organisations, 1% from the development industry), 13 selected submissions (industry: PCA, UDIA, Urban Taskforce, Australand, HIA, Master Builders; plus PIA, LGSA, WSROC, Shelter NSW, EDO, NCC/TEC, and the resident group FOKE), and the April 2013 White Paper and draft Planning Bill; close reading, coding and NVIVO keyword searches.",
 "Findings: framing and objectives (pp. 10–11). Industry frames planning as dysfunctional, bureaucratic and anti-growth, and residents as part of the problem; local government and residents frame the problem as distrust and 'undue influence of developers'. PCA: the system should deliver 'an economic dividend'. Local government and residents want ecologically sustainable development, social impact and heritage objectives kept. The White Paper makes promoting economic growth the 'main purpose' of planning; the Bill positions housing as 'economic activity' and relegates environment and society through 'while' and 'having regard to'.",
 "Findings: specific reforms (pp. 11–14). Easier spot rezoning with developer appeals: supported by industry, opposed by councils, adopted. Participation: promised as central, yet no new consultation rights and curtailed statutory consultation in development assessment; Australand wants an 'antidevelopment culture' to shift. Red tape: PCA's claim of 40% cost reduction comes with no evidence; the Bill bans 'onerous' controls affecting financial viability. Infrastructure: here government resists industry, which (against its free-market line) wants broad-based public funding; developers keep paying. Affordable housing: Shelter's inclusionary zoning ignored; existing affordable housing contribution provisions are wound back.",
 "Conclusion (pp. 14–16). Industry discourse aligned with neoliberal ideology dominated the formal process, but ideology and interests are not the only drivers: the Bill stalled by the end of 2013 in parliament, where the government lacked a majority, after a backlash by the Better Planning Network (more than 300 resident groups; the 'Hazzard tape' protest), whose influence worked outside the formal process. Ironically, approvals reached a 20-year high and almost doubled (Dec 2011 to 2014) under the unreformed system, while Sydney's median house price rose from $535,000 (March 2011) to $735,000 (December 2014): more supply did not ease affordability. The authors ask whether reform discourse distracts from the real pressures on low-income renters and aspiring owners."],
 concepts:[["Discourse (Foucauldian)","Language as producing reality and knowledge, not a neutral medium; meaning is contested and tied to power."],["Regime of truth","A dominant, relatively static representation of reality that fixes which problems and solutions count as acceptable (Foucault 1980, via Jacobs)."],["Supply-side / 'red tape' discourse","The industry narrative that planning regulation constrains supply, raises costs and so causes unaffordability; deregulation is the cure."],["Semantic justification","Using housing affordability as a rhetorical warrant for deregulation whose real content is growth and development."],["Rhetorical relegation","Placing environmental and social goals in subordinate clauses ('while', 'having regard to') so that growth becomes the primary purpose."],["Neoliberal planning reform","Microeconomic reform aimed at deregulation and competition: simplified controls, faster decisions, standardised plans, user-pays infrastructure."],["Spot rezoning","Changing permissible land uses on a single site; can deliver large windfalls; the reform eased it and allowed developer appeals."],["Inclusionary zoning / value capture","Levying the value uplift from upzoning to fund affordable housing or infrastructure; proposed by Shelter and PIA, not adopted."],["Urban consolidation","Australian term for growth management: containing greenfield spread and densifying existing areas; opposed by both industry (land supply) and residents (density)."]],
 fig:`<svg viewBox="0 0 620 300" role="img" aria-label="Discourse flow in the NSW planning reform: industry frames adopted by government, community frames sidelined, backlash stalls the Bill"><defs><marker id="arG7" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="12" width="165" height="72" rx="8" class="bxa"/><text x="92" y="32" text-anchor="middle" font-weight="bold">Industry (1%)</text><text x="92" y="50" text-anchor="middle">planning = red tape,</text><text x="92" y="66" text-anchor="middle">blocks supply, growth</text>
<rect x="10" y="98" width="165" height="72" rx="8" class="bxg"/><text x="92" y="118" text-anchor="middle" font-weight="bold">Community, councils</text><text x="92" y="136" text-anchor="middle">distrust; keep ESD,</text><text x="92" y="152" text-anchor="middle">heritage, participation</text>
<rect x="10" y="184" width="165" height="56" rx="8" class="bxi"/><text x="92" y="204" text-anchor="middle" font-weight="bold">Shelter, PIA</text><text x="92" y="222" text-anchor="middle">value capture, IZ</text>
<rect x="225" y="20" width="165" height="100" rx="8" class="bxw"/><text x="307" y="40" text-anchor="middle" font-weight="bold">Rhetorical strategies</text><text x="307" y="58" text-anchor="middle">affordability as</text><text x="307" y="74" text-anchor="middle">semantic justification</text><text x="307" y="90" text-anchor="middle">'40%' without evidence</text><text x="307" y="106" text-anchor="middle">'while', 'having regard'</text>
<rect x="440" y="20" width="170" height="120" rx="8" class="bx"/><text x="525" y="40" text-anchor="middle" font-weight="bold">White Paper + Bill</text><text x="525" y="58" text-anchor="middle">growth = main purpose</text><text x="525" y="74" text-anchor="middle">easier rezoning</text><text x="525" y="90" text-anchor="middle">no 'onerous' controls</text><text x="525" y="106" text-anchor="middle">AH contributions cut</text><text x="525" y="122" text-anchor="middle">less DA consultation</text>
<line x1="175" y1="48" x2="223" y2="60" class="ln" marker-end="url(#arG7)"/><line x1="390" y1="70" x2="438" y2="70" class="ln" marker-end="url(#arG7)"/><text x="414" y="62" text-anchor="middle" class="mut" font-size="10">adopted</text>
<line x1="175" y1="134" x2="438" y2="128" class="ln" stroke-dasharray="4 4" marker-end="url(#arG7)"/><text x="307" y="146" text-anchor="middle" class="mut" font-size="10">little traction</text>
<line x1="175" y1="212" x2="438" y2="138" class="ln" stroke-dasharray="4 4" marker-end="url(#arG7)"/>
<rect x="225" y="236" width="180" height="56" rx="8" class="bxg"/><text x="315" y="256" text-anchor="middle" font-weight="bold">Better Planning Netw.</text><text x="315" y="274" text-anchor="middle">300+ groups: Bill stalls</text>
<rect x="420" y="236" width="190" height="56" rx="8" class="bxa"/><text x="515" y="256" text-anchor="middle" font-weight="bold">Outcome 2011–14</text><text x="515" y="274" text-anchor="middle">approvals up, price up</text>
<line x1="175" y1="160" x2="258" y2="234" class="ln" marker-end="url(#arG7)"/><text x="335" y="229" text-anchor="middle" class="mut" font-size="10">outside formal process</text>
<line x1="405" y1="264" x2="418" y2="264" class="ln" marker-end="url(#arG7)"/>
</g></svg>`,
 cap:"Industry frames pass through rhetorical strategies into the White Paper and Bill; community and advocate frames gain little traction in the formal process but stall the Bill from outside (pp. 10–16).",
 table:{head:["Reform area","Industry","Councils / community / advocates","Government response (White Paper, draft Bill)"],rows:[["Purpose of planning","'economic dividend' (PCA)","Keep ESD, social impact, heritage","Growth is the 'main purpose'"],["Spot rezoning","Support; developer appeals","Undermines strategic planning","Adopted: new rezoning tools"],["Community participation","Endorse limits; change 'antidevelopment culture'","Participation in plan making and DA","Charter promised; DA consultation curtailed"],["Red tape / speed","Cut costs 40% (no evidence)","Speed not at expense of assessment","Ban 'onerous' controls hurting viability"],["Infrastructure","Broad-based public funding","Value capture","Private participation; developers still pay"],["Affordable housing","Opposes planning requirements","Shelter: inclusionary levy on uplift","Existing contribution provisions wound back"]]},
 example:"The PCA claimed the new system should 'reduce costs by 40% by 2015' through red-tape reduction; the authors note 'no evidence of actual costs or savings is ever provided', yet the draft Bill (s3.3, Principle 10) bars local plans from 'overly complex or onerous controls that may adversely impact on the financial viability of proposed development' (p. 12).",
 quotes:["\"the power of an individual or group rests on their capacity to promote and sustain a particular version of reality as being the 'objective truth'\" (p. 3, online-first)","\"Environmental and social concerns are thus relegated to secondary or ancillary positions through terms such as 'while' and 'having regard to'.\" (p. 11, online-first)","\"housing affordability problems are used as a semantic justification for a wider deregulatory agenda\" (p. 14, online-first)","\"increased supply did not ease affordability pressures\" (p. 16, online-first)"],
 dims:{sa:50, rt:35, de:30, us:70, mp:60, norm:"Public interest beyond growth: environmental and social goals, genuine community participation, direct support for affordable housing for low-income renters and aspiring owners; sceptical of deregulation."},
 exam:"Grounding perspective: discourse analysis in a broadly Foucauldian sense (regimes of truth, language constructs problems and solutions) combined with a critique of neoliberalism; unlike Raco & Imrie it is actor-centred: identifiable interest groups mobilise discourse strategically (closer to Hajer-style discourse coalitions, my link via Rydin ch. 8). Best critiques: (1) Hayek / liberal economics (and Glaeser-style supply economics, cited on p. 1): the authors never test whether regulation raises prices; approvals rising with prices under the old system does not show supply is irrelevant (no counterfactual: demand, interest rates, investment incentives also moved), and industry's 'regime of truth' may simply be true. (2) Rational choice / public choice (my link: Taylor 2016 uses the same method, public submissions, to show landowner rent-seeking; Olson): influence follows concentrated interests and campaign funding, so 'discourse' may be an epiphenomenon of interest-group power; and the resident groups are also rent-seekers (NIMBY protection of property values, p. 9), which the authors bracket. (3) Marxist political economy: the analysis stays at the level of text; it does not explain why developer capital holds 'disproportionate' discursive power (land rent, accumulation, state dependence on growth). (4) Neo-institutionalism: the 1979 Act's survival and the stalled Bill suggest path dependence and veto points, not discourse, explain the outcome. (5) Method: 13 submissions out of 1,220; influence inferred from textual similarity, not from process tracing. MCQ traps: community submitted 72% but had least influence; government resisted industry on infrastructure; affordability was the rhetorical rationale but affordable housing provisions were cut; approvals rose without the reform; the Bill stalled because of backlash outside the formal process."}
];

const FC_D=[
["raco","What is 'governmentality' in Raco & Imrie?","Foucault's 'conduct of conduct': the ensemble of institutions, procedures, calculations and tactics that shape how people govern themselves and others; government is broader than the state."],
["raco","Name the three analytical layers Raco & Imrie use (after Rose & Miller).","Political rationalities (ways of thinking, moral justifications, who is to be governed), programmes (purposive attempts to reorganise practice, e.g. white papers, guidance) and technologies of government (audit, targets, budgets, calculable spaces)."],
["raco","What is the SRB and why is it their case?","The Single Regeneration Budget (April 1994): one competitive fund for locally defined public–private partnership projects. It is used as a 'heuristic vehicle' for the governmentalisation of UK urban policy under New Labour."],
["raco","What does 'advanced liberalism' mean here?","Rose's term for governing through the regulated choices of autonomous, active subjects: marketised welfare, audit and accounting, fragmented collective welfare, reinvented community, and discipline for deviant performance."],
["raco","Why is welfare retrenchment not 'less government' for Raco & Imrie?","Less state intervention does not mean less government: the state governs at a distance by shaping the conduct and subjectivity of communities and partnerships (p. 2191)."],
["raco","What are 'communities of obligation'?","Rose's term: communities are given more rights to define policy agendas, but only on condition of accepting wider responsibilities for implementing them."],
["raco","How is 'empowerment' reinterpreted?","As a technology of citizenship: not a quantitative increase in community power but a qualitative transformation of subjectivity 'to make government work' (p. 2195)."],
["raco","Which technologies of government does SRB use?","10% of funding for capacity building, competitive bids, baselines and milestones set by bidders, quarterly quantitative progress reports, RDA sanctions, Best Value, Best Practice and peer review, 'accountable bodies'."],
["raco","Vertical or horizontal accountability in SRB?","Vertical: monitoring leaves partnerships open to assessment and funding discipline from above, rather than letting communities judge projects from below (p. 2198)."],
["raco","How is expertise redrawn?","Local knowledge is given privileged status in rhetoric, but representatives are trained by professionals in bureaucratic and monitoring procedures, making community aspirations calculable; professionals are also subordinated to performance mechanisms."],
["raco","What is Foucault's 'paradoxical assertion' in the conclusion?","In return for a little extra freedom of action, subjects come under greater monitoring, scrutiny and surveillance by the state (p. 2201)."],
["raco","Where do the authors see room for resistance?","If the art of government is politically constructed, it can be reconstructed: the analysis can support contestation, subpolitics of identity and a rebuilt 'social' (p. 2202)."],
["gurran","What is Gurran & Ruming's central claim?","In the NSW planning reform (2011–2014), government responses heavily reflected development industry narratives that framed planning as a constraint on growth and supply; affordability was a semantic justification for deregulation."],
["gurran","What is a 'regime of truth' in their analysis?","A dominant representation of reality that determines acceptable formulations of problems and solutions; power rests on sustaining a version of reality as 'objective truth' (p. 3)."],
["gurran","What data do they analyse?","The 2012 Green Paper, 13 selected submissions (industry, planners, councils, residents, environmental and housing groups) out of 1,220, and the 2013 White Paper and draft Planning Bill; close reading, coding and NVIVO searches."],
["gurran","Who made most Green Paper submissions, and who was most influential?","Community individuals and organisations made 72% of submissions; the development industry only 1%, yet industry narratives were most reflected in government responses."],
["gurran","How does the Bill relegate environmental and social goals?","Through subordinating phrases: growth 'while protecting the environment', development 'having regard to environmental and social considerations' (p. 11)."],
["gurran","What was the PCA's '40%' claim and the authors' objection?","PCA wanted red-tape reduction to cut costs by 40% by 2015; no evidence of actual costs or savings was ever provided, yet it made deregulation appear obvious (p. 12)."],
["gurran","In which area did government resist industry?","Infrastructure funding: industry wanted broad-based public funding, but developers continued to finance the infrastructure their projects require (pp. 13–14)."],
["gurran","What happened to affordable housing provisions?","Despite affordability being the headline rationale, existing provisions for affordable housing contributions were wound back in the draft Bill; Shelter's inclusionary proposal was not taken up."],
["gurran","Why did the reform stall?","Community backlash outside the formal process: the Better Planning Network (300+ resident groups and councils, the 'Hazzard tape' protest); the Bill stalled by the end of 2013 where the government lacked a majority."],
["gurran","What is the 'irony' in the conclusion?","Housing approvals hit a 20-year high and almost doubled under the unreformed system, yet Sydney's median house price rose from $535,000 to $735,000 (2011–2014): more supply did not ease affordability."],
["gurran","Link: how do both readings use Foucault differently?","Raco & Imrie use governmentality: how government shapes subjects through rationalities and technologies. Gurran & Ruming use discourse analysis: how interest groups make a version of reality a 'regime of truth'. The first is about the conduct of conduct, the second about contests over meaning (my comparison)."],
["gurran","Link: how is 'less planning' made common sense in Gurran & Ruming, and what would a governmentality reading add?","Via repeated framing (planning = red tape; supply = affordability; growth = public benefit) that government adopts. A governmentality reading (my link, Raco & Imrie; Rydin ch. 8) would add how such discourse is built into technologies, e.g. viability tests and bans on 'onerous' controls, that make councils govern themselves by market criteria."],
["gurran","Link: Gurran & Ruming vs Taylor (2016)?","Both analyse public submissions in Australian growth debates. Taylor explains outcomes as rational-choice rent-seeking by landowners; Gurran & Ruming as discursive power producing a regime of truth (my comparison)."]
];

const MCQ_D=[
{t:"raco",q:"According to Raco & Imrie, the shift to a 'rights and responsibilities' agenda means:",o:["Less government, because the welfare state retracts","Less state intervention but not necessarily less government","A return to Keynesian collective provision","The end of central control over local policy"],a:1,e:"The retraction of the welfare state means less state intervention, 'not necessarily ... any less government' (p. 2191): government works at a distance."},
{t:"raco",q:"Which is NOT one of the three layers of governmentality in the article?",o:["Political rationalities","Programmes of government","Technologies of government","Modes of production"],a:3,e:"Rationalities, programmes and technologies come from Rose & Miller; modes of production is Marxist vocabulary, which the authors set aside."},
{t:"raco",q:"How do Raco & Imrie characterise 'empowerment' under SRB?",o:["A quantitative increase in community power","A qualitative transformation of subjectivity to make government work","A transfer of statutory powers to residents","A purely symbolic gesture with no effects"],a:1,e:"Empowerment does not lead to 'quantitative increases in power' but to 'a qualitative transformation of forms of subjectivity' (p. 2195)."},
{t:"raco",q:"SRB monitoring frameworks mainly produce which kind of accountability?",o:["Horizontal, to local communities","Electoral, to local councillors","Vertical, to funders and central government","Market accountability to consumers"],a:2,e:"They focus on vertical rather than horizontal accountability; communities cannot assess projects from below (p. 2198)."},
{t:"raco",q:"Rose's 'communities of obligation' means communities:",o:["are obliged to accept whatever central government decides","gain rights to shape agendas conditional on taking on wider responsibilities","are replaced by market actors","owe taxes to fund regeneration"],a:1,e:"Communities are ostensibly given more rights but must adopt more widely defined responsibilities (p. 2194)."},
{t:"raco",q:"Which critique of Raco & Imrie uses their own evidence most directly (my link)?",o:["Complexity theory: SRB was self-organising","Rational choice: managers treated monitoring as target-checking and involvement as a funding requirement, suggesting strategic compliance rather than internalised subjectivity","Communicative planning: SRB ignored local knowledge entirely","Hayek: SRB was central planning of the economy"],a:1,e:"The article cites managers using figures only to check targets and involvement as 'a necessary requirement (for funders)'; a principal-agent reading explains this without internalisation."},
{t:"gurran",q:"Gurran & Ruming's method is best described as:",o:["Econometric modelling of supply elasticities","Discourse analysis of submissions and government documents","Ethnography of planning officers","Survey of home buyers"],a:1,e:"They close-read and coded 13 Green Paper submissions and the White Paper and draft Bill, using NVIVO keyword searches."},
{t:"gurran",q:"Which group made the largest share of Green Paper submissions?",o:["The development industry","Local government","Community individuals and organisations","Peak bodies"],a:2,e:"Community individuals and organisations made 72% (739 + 136 of 1,220); the development industry only 1%."},
{t:"gurran",q:"In which reform area did the NSW government NOT follow the development industry?",o:["Objectives of the planning system","Spot rezoning","Red tape and 'onerous' controls","Infrastructure funding"],a:3,e:"On infrastructure the government implicitly defended regulation: developers still finance the infrastructure their projects require (pp. 13–14)."},
{t:"gurran",q:"What do the authors mean by affordability as a 'semantic justification'?",o:["Affordability was defined precisely in the Bill","Affordability was invoked to legitimise deregulation whose real content was growth, while affordable housing provisions were cut","Affordability was dropped from the debate","Affordability was measured with new indicators"],a:1,e:"'housing affordability problems are used as a semantic justification for a wider deregulatory agenda' (p. 14)."},
{t:"gurran",q:"Why did the draft NSW Planning Bill stall?",o:["The High Court struck it down","Industry withdrew support","Community backlash (Better Planning Network) outside the formal process, with the government lacking a majority","A recession ended the reform"],a:2,e:"More than 300 resident groups and councils mobilised; influence was exerted outside the formal policy process (p. 15)."},
{t:"gurran",q:"Which is the strongest liberal-economics (Hayek/Glaeser) objection to Gurran & Ruming?",o:["They ignore the role of discourse","They show rising approvals and prices under the old system but do not establish a counterfactual, so the supply-constraint claim is not tested","They overstate the role of community groups","They rely on econometrics"],a:1,e:"Discourse analysis shows how the supply claim is framed, not whether it is false; prices may have risen for demand-side reasons."},
{t:"gurran",q:"Link question: which statement best contrasts the two readings?",o:["Both treat the state as a unified actor imposing its will","Raco & Imrie analyse how government shapes self-governing subjects through technologies; Gurran & Ruming analyse how interest groups make one framing a 'regime of truth' that government adopts","Gurran & Ruming use governmentality; Raco & Imrie use rational choice","Both conclude that planning reform empowered communities"],a:1,e:"Governmentality (conduct of conduct, technologies) versus actor-centred discourse analysis (contest over meaning). Both are Foucault-inspired, neither treats the state as unified."}
];

const OPEN_D=[
{t:"raco",pts:20,q:"Theoretical commentary on Raco & Imrie (2000). (a) Identify the theoretical perspective that grounds their argument about the Single Regeneration Budget and explain the key concepts they use. (b) Critique the argument from an alternative perspective covered in the course.",model:"(a) The article is grounded in Foucault's governmentality as developed by Rose, Miller and Dean. Government is the 'conduct of conduct' and is not reducible to the state. The authors trace a political rationality (advanced liberalism: rights and responsibilities, active citizens), a programme (SRB: competitive bids by local partnerships that must involve the community) and technologies (10% capacity building, quarterly quantitative targets, audit, Best Value, peer review). The result is 'government at a distance' through 'communities of obligation'; empowerment is a qualitative transformation of subjectivity, not a gain in power (p. 2195), and subjects gain a little freedom in return for more surveillance (p. 2201). (b) From rational choice (principal-agent, NPM as incentive alignment), the same evidence reads differently: managers used monitoring only to check targets and community involvement was 'a necessary requirement (for funders)'. That is strategic compliance with funding conditions, not internalised subjectivity, so the governmentality reading over-interprets policy texts. Its method (documents plus one secondary evaluation) cannot show how subjects actually think. A Marxist reading would add that the authors' own findings (cost-cutting, 'abandonment') point to fiscal crisis and uneven development, which a focus on mentalities leaves unexplained. Still, governmentality explains well why decentralisation can increase central control.",rubric:["Correctly identifies Foucault/governmentality (Rose, Miller, Dean) as the grounding perspective","Explains rationality, programme and technology with SRB evidence (capacity building, targets, vertical accountability)","States the core claim: empowerment as transformation of subjectivity; freedom in return for surveillance","Develops a coherent critique from a named alternative (e.g. rational choice, Marxism, communicative planning) using evidence from the text","Evaluates: strengths and limits, including method (documents and secondary sources) and structure/agency"]},
{t:"gurran",pts:20,q:"Theoretical commentary on Gurran & Ruming (2016). (a) Which theoretical perspective grounds their analysis of the NSW planning reform, and how do they show that 'less planning' was made common sense? (b) Critique their argument from an alternative theoretical perspective.",model:"(a) The analysis is broadly Foucauldian discourse analysis set within a critique of neoliberal planning reform. Language constructs reality; power lies in sustaining one version of reality as 'objective truth', which hardens into a 'regime of truth' fixing acceptable problems and solutions (p. 3). Comparing 13 Green Paper submissions with the White Paper and draft Bill, they show industry framing planning as red tape that blocks supply, growth and affordability. Government adopted it: growth became the 'main purpose', environment and society were relegated by 'while' and 'having regard to', rezoning was eased, 'onerous' controls were banned and affordable housing contributions were cut. Affordability worked as a 'semantic justification' for deregulation (p. 14), even though communities made 72% of submissions. (b) From liberal economics (Hayek, Glaeser-style supply arguments), the paper shows how the supply claim was framed but never tests whether it is true. The fact that approvals and prices both rose under the old system is not a counterfactual. From rational choice (compare Taylor 2016 on rent-seeking), 'discourse' may simply reflect concentrated interests and campaign funding, and resident groups are rent-seekers too. Neo-institutionalism would stress veto points and path dependence, since the 1979 Act survived. The case is strong on framing and weak on causation.",rubric:["Identifies discourse analysis / Foucauldian regime of truth (and neoliberalism critique) as the grounding","Uses evidence: framing, relegation language, specific reforms adopted, affordability as semantic justification, 72% vs 1%","Notes the complications: infrastructure exception, Bill stalled by backlash, approvals up with prices up","Develops a critique from a named alternative (Hayek/liberal economics, rational choice, Marxism or neo-institutionalism) with specific points","Evaluates method (13 submissions, influence inferred from textual similarity) and gives a balanced judgement"]}
];
