const SL_4={
 ni:{figs:[
  {title:"Ostrom's IAD framework",svg:`<svg viewBox="0 0 620 270" role="img" aria-label="Institutional Analysis and Development framework"><defs><marker id="sl4iad" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<text x="105" y="26" text-anchor="middle" font-weight="700">Exogenous variables</text>
<rect x="20" y="36" width="170" height="174" rx="8" class="bx"/>
<rect x="32" y="48" width="146" height="40" rx="8" class="bxg"/><text x="105" y="65" text-anchor="middle">Biophysical/material</text><text x="105" y="80" text-anchor="middle">conditions</text>
<rect x="32" y="102" width="146" height="40" rx="8" class="bxi"/><text x="105" y="119" text-anchor="middle">Attributes of</text><text x="105" y="134" text-anchor="middle">community</text>
<rect x="32" y="156" width="146" height="40" rx="8" class="bxa"/><text x="105" y="181" text-anchor="middle">Rules</text>
<line x1="190" y1="123" x2="232" y2="123" class="ln" marker-end="url(#sl4iad)"/>
<text x="310" y="26" text-anchor="middle" font-weight="700">Action arena</text>
<rect x="235" y="36" width="150" height="174" rx="8" class="bx"/>
<rect x="250" y="52" width="120" height="40" rx="8" class="bxw"/><text x="310" y="69" text-anchor="middle">Action</text><text x="310" y="84" text-anchor="middle">situations</text>
<rect x="250" y="152" width="120" height="40" rx="8" class="bxw"/><text x="310" y="177" text-anchor="middle">Participants</text>
<line x1="295" y1="94" x2="295" y2="149" class="ln" marker-end="url(#sl4iad)"/><line x1="325" y1="150" x2="325" y2="95" class="ln" marker-end="url(#sl4iad)"/>
<line x1="385" y1="78" x2="417" y2="78" class="ln" marker-end="url(#sl4iad)"/>
<rect x="420" y="58" width="110" height="38" rx="8" class="bx"/><text x="475" y="82" text-anchor="middle">Interactions</text>
<rect x="420" y="168" width="110" height="38" rx="8" class="bx"/><text x="475" y="192" text-anchor="middle">Outcomes</text>
<line x1="475" y1="96" x2="475" y2="165" class="ln" marker-end="url(#sl4iad)"/>
<rect x="540" y="112" width="74" height="40" rx="8" class="bxi"/><text x="577" y="129" text-anchor="middle" font-size="11">Evaluative</text><text x="577" y="144" text-anchor="middle" font-size="11">criteria</text>
<line x1="560" y1="112" x2="533" y2="92" class="ln" marker-end="url(#sl4iad)"/><line x1="560" y1="152" x2="533" y2="178" class="ln" marker-end="url(#sl4iad)"/>
<path d="M475,206 L475,240 L105,240 L105,213" class="ln" stroke-dasharray="5 4" marker-end="url(#sl4iad)"/>
<path d="M310,240 L310,213" class="ln" stroke-dasharray="5 4" marker-end="url(#sl4iad)"/>
<text x="290" y="258" text-anchor="middle" class="mut" font-size="11">feedback: outcomes change the exogenous variables and the arena</text></g></svg>`,cap:"Ostrom's Institutional Analysis and Development framework: exogenous variables (incl. rules) shape the action arena, whose interactions produce outcomes judged by evaluative criteria; dashed lines are feedback. The seven rule types in the table below specify the 'Rules' box. After Ostrom, HC7.",slide:"HC7 slides 16–17"},
  {title:"The prisoners' dilemma",svg:`<svg viewBox="0 0 620 250" role="img" aria-label="Prisoners dilemma payoff matrix"><g font-size="12">
<text x="390" y="20" text-anchor="middle" font-weight="700">Prisoner B</text>
<rect x="180" y="30" width="205" height="36" rx="8" class="bxi"/><text x="282" y="53" text-anchor="middle">confesses</text>
<rect x="395" y="30" width="205" height="36" rx="8" class="bxi"/><text x="497" y="53" text-anchor="middle">remains silent</text>
<text x="30" y="160" font-weight="700" transform="rotate(-90 30 160)" text-anchor="middle">Prisoner A</text>
<rect x="50" y="76" width="120" height="72" rx="8" class="bxw"/><text x="110" y="117" text-anchor="middle">confesses</text>
<rect x="50" y="158" width="120" height="72" rx="8" class="bxw"/><text x="110" y="199" text-anchor="middle">remains silent</text>
<rect x="180" y="76" width="205" height="72" rx="8" class="bxa"/><text x="282" y="104" text-anchor="middle">A: 5 years</text><text x="282" y="121" text-anchor="middle">B: 5 years</text><text x="282" y="139" text-anchor="middle" class="mut" font-size="11">what rational actors choose</text>
<rect x="395" y="76" width="205" height="72" rx="8" class="bx"/><text x="497" y="108" text-anchor="middle">A: 0 years (goes free)</text><text x="497" y="125" text-anchor="middle">B: 20 years</text>
<rect x="180" y="158" width="205" height="72" rx="8" class="bx"/><text x="282" y="190" text-anchor="middle">A: 20 years</text><text x="282" y="207" text-anchor="middle">B: 0 years (goes free)</text>
<rect x="395" y="158" width="205" height="72" rx="8" class="bxg"/><text x="497" y="186" text-anchor="middle">A: 1 year</text><text x="497" y="203" text-anchor="middle">B: 1 year</text><text x="497" y="221" text-anchor="middle" class="mut" font-size="11">best joint outcome</text>
<text x="390" y="246" text-anchor="middle" class="mut" font-size="11">Confessing is better for each whatever the other does, so both end up with 5 years.</text></g></svg>`,cap:"The payoff matrix shown before Hardin's tragedy of the commons: individually rational choices produce a collectively worse outcome. Ostrom's question is how people create institutions that make cooperation credible (the 'problem of commitment'). Values from the slide (Encyclopaedia Britannica graphic).",slide:"HC7 slide 13"},
  {title:"Institutions between structure and agency",svg:`<svg viewBox="0 0 620 230" role="img" aria-label="Structure and agency overlap in choices"><defs><marker id="sl4venn" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<text x="215" y="24" text-anchor="middle" font-weight="700">STRUCTURE</text><text x="215" y="40" text-anchor="middle" class="mut">(rules)</text>
<text x="365" y="24" text-anchor="middle" font-weight="700">AGENCY</text><text x="365" y="40" text-anchor="middle" class="mut">(freedom)</text>
<circle cx="240" cy="118" r="68" class="bxi" fill-opacity="0.8"/><circle cx="340" cy="118" r="68" class="bx" fill-opacity="0.6"/>
<text x="290" y="122" text-anchor="middle" font-weight="700">choices</text>
<line x1="290" y1="222" x2="290" y2="136" class="ln" marker-end="url(#sl4venn)"/>
<text x="20" y="200" class="mut" font-size="11">Neo-institutionalism reconciles</text><text x="20" y="215" class="mut" font-size="11">structure and agency (Giddens)</text>
<text x="420" y="200" class="mut" font-size="11">actors choose, but within</text><text x="420" y="215" class="mut" font-size="11">rules that constrain and enable</text></g></svg>`,cap:"The slide's diagram: choices sit where structure (rules) and agency (freedom) overlap. Institutions are the way new institutionalism answers and reconciles the structure–agency relationship.",slide:"HC7 slide 19"},
  {title:"Rational choice institutionalism: how institutions shape action",svg:`<svg viewBox="0 0 620 250" role="img" aria-label="Interests, beliefs and information drive actions"><defs><marker id="sl4rci" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="250" y="20" width="120" height="38" rx="8" class="bxa"/><text x="310" y="44" text-anchor="middle" font-weight="700">Actions</text>
<rect x="40" y="104" width="130" height="38" rx="8" class="bxi"/><text x="105" y="128" text-anchor="middle">Interests</text>
<rect x="420" y="96" width="180" height="56" rx="8" class="bxw"/><text x="510" y="116" text-anchor="middle">Beliefs about possible</text><text x="510" y="131" text-anchor="middle">action opportunities</text><text x="510" y="146" text-anchor="middle">and their effects</text>
<rect x="250" y="190" width="120" height="38" rx="8" class="bxg"/><text x="310" y="214" text-anchor="middle">Information</text>
<line x1="150" y1="102" x2="247" y2="52" class="ln" marker-end="url(#sl4rci)"/>
<line x1="470" y1="94" x2="373" y2="52" class="ln" marker-end="url(#sl4rci)"/>
<line x1="250" y1="196" x2="150" y2="146" class="ln" marker-end="url(#sl4rci)"/>
<line x1="370" y1="196" x2="470" y2="155" class="ln" marker-end="url(#sl4rci)"/>
<text x="310" y="120" text-anchor="middle" class="mut" font-size="11">institutions supply</text><text x="310" y="135" text-anchor="middle" class="mut" font-size="11">certainty and information</text></g></svg>`,cap:"Diagram on the rational choice slide (after Sorensen 2017): information shapes actors' interests and their beliefs about possible actions and effects, which together drive action. Institutions work by providing certainty, information and credible commitment.",slide:"HC7 slide 25"},
  {title:"The double life of institutions",svg:`<svg viewBox="0 0 620 250" role="img" aria-label="Institutions as context and object of planning"><defs><marker id="sl4dbl" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="40" width="160" height="80" rx="8" class="bxi"/><text x="90" y="62" text-anchor="middle" font-weight="700">CONTEXT</text><text x="90" y="80" text-anchor="middle">framework within</text><text x="90" y="95" text-anchor="middle">which planning</text><text x="90" y="110" text-anchor="middle">decisions are made</text>
<rect x="240" y="55" width="140" height="50" rx="8" class="bx"/><text x="310" y="77" text-anchor="middle">Planning practice</text><text x="310" y="94" text-anchor="middle">(actors)</text>
<rect x="450" y="40" width="160" height="80" rx="8" class="bxg"/><text x="530" y="62" text-anchor="middle" font-weight="700">OBJECT</text><text x="530" y="80" text-anchor="middle">the outcome of</text><text x="530" y="95" text-anchor="middle">planning processes</text>
<line x1="170" y1="80" x2="237" y2="80" class="ln" marker-end="url(#sl4dbl)"/><text x="205" y="72" text-anchor="middle" class="mut" font-size="11">constrain</text>
<line x1="380" y1="80" x2="447" y2="80" class="ln" marker-end="url(#sl4dbl)"/><text x="414" y="72" text-anchor="middle" class="mut" font-size="11">produce</text>
<text x="90" y="138" text-anchor="middle" class="mut" font-size="11">e.g. land planning law</text><text x="530" y="138" text-anchor="middle" class="mut" font-size="11">e.g. a land-use plan</text>
<path d="M530,146 C530,196 90,196 90,148" class="ln" stroke-dasharray="5 4" marker-end="url(#sl4dbl)"/>
<text x="310" y="200" text-anchor="middle" class="mut" font-size="11">outcomes become the next context</text>
<text x="310" y="224" text-anchor="middle" font-size="11">"Institutions are ontologically both the context and object of</text><text x="310" y="239" text-anchor="middle" font-size="11">planning practices from a relational perspective" (Savini 2019)</text></g></svg>`,cap:"Institutions constrain actors but are also the outcome of human action. The slide illustrates context with a set of land planning law volumes and object with a conceptual land-use plan.",slide:"HC7 slides 9–10, 37"},
  {title:"Planning as institutional design, and its limits",svg:`<svg viewBox="0 0 620 230" role="img" aria-label="Chain from planners to society and the readings that qualify it"><defs><marker id="sl4des" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="30" width="120" height="44" rx="8" class="bxa"/><text x="70" y="57" text-anchor="middle">Planners</text>
<rect x="165" y="30" width="125" height="44" rx="8" class="bx"/><text x="227" y="49" text-anchor="middle">design</text><text x="227" y="65" text-anchor="middle">institutions</text>
<rect x="325" y="30" width="125" height="44" rx="8" class="bx"/><text x="387" y="49" text-anchor="middle">shape</text><text x="387" y="65" text-anchor="middle">behaviour</text>
<rect x="485" y="30" width="125" height="44" rx="8" class="bxg"/><text x="547" y="49" text-anchor="middle">reshape</text><text x="547" y="65" text-anchor="middle">society/space</text>
<line x1="130" y1="52" x2="162" y2="52" class="ln" marker-end="url(#sl4des)"/><line x1="290" y1="52" x2="322" y2="52" class="ln" marker-end="url(#sl4des)"/><line x1="450" y1="52" x2="482" y2="52" class="ln" marker-end="url(#sl4des)"/>
<text x="310" y="104" text-anchor="middle" class="mut" font-size="11">'planning is institutional design' (Innes 1995, via Alexander 2005) ... qualified by the three readings:</text>
<rect x="10" y="118" width="190" height="96" rx="8" class="bxi"/><text x="105" y="138" text-anchor="middle" font-weight="700">Dembski &amp; Salet</text><text x="105" y="157" text-anchor="middle" font-size="11">symbols can't be used</text><text x="105" y="172" text-anchor="middle" font-size="11">voluntaristically; find</text><text x="105" y="187" text-anchor="middle" font-size="11">under-institutionalised</text><text x="105" y="202" text-anchor="middle" font-size="11">niches</text>
<rect x="215" y="118" width="190" height="96" rx="8" class="bxw"/><text x="310" y="138" text-anchor="middle" font-weight="700">Sorensen</text><text x="310" y="157" text-anchor="middle" font-size="11">change at critical</text><text x="310" y="172" text-anchor="middle" font-size="11">junctures, then within a</text><text x="310" y="187" text-anchor="middle" font-size="11">constrained pathway</text>
<rect x="420" y="118" width="190" height="96" rx="8" class="bxg"/><text x="515" y="138" text-anchor="middle" font-weight="700">Moroni</text><text x="515" y="157" text-anchor="middle" font-size="11">institutions evolve</text><text x="515" y="172" text-anchor="middle" font-size="11">unintentionally; intervene,</text><text x="515" y="187" text-anchor="middle" font-size="11">but not taxis-style</text></g></svg>`,cap:"Top: the chain on the 'planning as institutional design' slide. Bottom: how the quotes the lecturer selected for each reading limit that chain.",slide:"HC7 slides 31, 34–36"},
  {title:"Path dependence in numbers: US mortgage interest deduction",svg:`<svg viewBox="0 0 620 260" role="img" aria-label="Rising cost of mortgage interest deductibility 2000 to 2014"><g font-size="11">
<line x1="70" y1="220" x2="590" y2="220" class="ln"/><line x1="70" y1="40" x2="70" y2="220" class="ln"/>
<text x="62" y="224" text-anchor="end" class="mut">$0</text><text x="62" y="179" text-anchor="end" class="mut">$40bn</text><text x="62" y="134" text-anchor="end" class="mut">$80bn</text><text x="62" y="89" text-anchor="end" class="mut">$120bn</text><text x="62" y="44" text-anchor="end" class="mut">$160bn</text>
<line x1="70" y1="175" x2="590" y2="175" class="ln" stroke-dasharray="2 4"/><line x1="70" y1="130" x2="590" y2="130" class="ln" stroke-dasharray="2 4"/><line x1="70" y1="85" x2="590" y2="85" class="ln" stroke-dasharray="2 4"/>
<text x="70" y="238" text-anchor="middle" class="mut">2000</text><text x="144" y="238" text-anchor="middle" class="mut">2002</text><text x="219" y="238" text-anchor="middle" class="mut">2004</text><text x="293" y="238" text-anchor="middle" class="mut">2006</text><text x="367" y="238" text-anchor="middle" class="mut">2008</text><text x="441" y="238" text-anchor="middle" class="mut">2010</text><text x="516" y="238" text-anchor="middle" class="mut">2012</text><text x="590" y="238" text-anchor="middle" class="mut">2014</text>
<polyline points="70,153 107,147 144,148 181,151 219,150 256,149 293,141 311,124 330,121 367,130 404,117 441,103 478,91 516,77 553,65 590,51" class="accs" fill="none" stroke-width="2.5"/>
<text x="80" y="30" font-size="12" font-weight="700">Treasury revenue loss from deducting mortgage interest (US)</text>
<text x="545" y="50" text-anchor="end" class="acc">≈ $150bn</text><text x="80" y="170" class="acc">≈ $60bn</text>
<text x="330" y="255" text-anchor="middle" class="mut">approximate values read from the slide's chart (Subsidyscope / Pew data)</text></g></svg>`,cap:"Chart on the historical institutionalism slide: the cost of deducting mortgage interest on owner-occupied homes grows from about $60bn to about $150bn a year (2000–2014). An established rule keeps reproducing itself; link this to the 'housing is becoming unaffordable' homework.",slide:"HC7 slide 28"}],
  tables:[
  {title:"Ostrom's seven types of rules (IAD)",head:["Rule type","What it does","Fishing example on the slide"],rows:[["1 Position","Defines the roles or positions available to participants","-"],["2 Boundary","Specifies how actors enter or leave a position","Membership rules for a fishing cooperative"],["3 Choice","Defines what an actor in a position is allowed, obliged or forbidden to do","Fishers may only use certain gear"],["4 Aggregation","Determines how individual actions combine into collective decisions","Majority voting in a village council"],["5 Information","Regulates what information must, may or must not be shared","Fishers must report catches to the cooperative"],["6 Payoff","Assigns rewards or sanctions to actions and outcomes","Fines for breaking quotas, bonuses for compliance"],["7 Scope","Defines the outcomes that are affected","Areas off-limits to fishing; protected species"]],slide:"HC7 slide 17"},
  {title:"Institutions visible in morphology (Tennekes, Harbers & Buitelaar 2015)",head:["Flanders (aerial photo, Fig. 3)","Netherlands (aerial photo, Fig. 2)"],rows:[["Development with cul-de-sacs","Identical houses"],["Vacant lot","Hierarchical road system"],["Open spaces in agricultural use","Clustered amenities"],["Ribbon development","Clear plan boundary"]],slide:"HC7 slide 20"},
  {title:"Exercise: the quotes the lecturer picked per reading",head:["Reading","Strand","Selected quotes (page)"],rows:[["1 Dembski & Salet (2010)","Sociological","Reality socially constructed, but symbolic markers 'cannot be used in a voluntaristic way' (621); new institutions emerge through new cultural practices that become institutionalised (622); institutionalisation = ongoing normalisation and habituation (618); 'the art of planning is to find niches of underinstitutionalised space' (622)"],["2 Sorensen (2024)","Historical","Critical junctures = short periods of heightened probability that agents' choices matter (1807); path dependence usually not 'lock-in' but a constrained developmental pathway (1814); actors use conjunctural crises to further particular changes (1805)"],["3 Moroni (2010)","Evolutionary","Most institutions are the unintentional outcome of slow evolution (279); emergent realities cannot be designed like organisations (282); this does not prevent intervening, but calls for an approach different from the taxis-oriented one (287)"]],slide:"HC7 slides 32–36"}],
  points:[
  {t:"Prisoners' dilemma as the starting puzzle",d:"Before Hardin, the lecture shows the prisoners' dilemma: each prisoner does best by confessing whatever the other does, so both get 5 years instead of the 1 year each they would get by staying silent. It is the logic behind the tragedy of the commons and the 'problem of commitment' that Ostrom's institutions solve.",slide:"HC7 slide 13"},
  {t:"Hardin: the lecturer's question",d:"After stating Hardin's (1968) argument (pasture, fish stock, atmosphere as examples of shared resources), the slide simply asks 'Solution?'. Ostrom's answer on the next slide is self-organised rules rather than only privatisation or the state.",slide:"HC7 slides 14–15"},
  {t:"Sources behind the definitions",d:"The 'institutionalisms may disagree on' slide cites Sorensen (2017), 'New institutionalism and planning theory', Routledge Handbook of Planning Theory pp. 250–263. The list of three paradigms cites Salet (2018), Public Norms and Aspirations: The Turn to Institutions in Action (Routledge).",slide:"HC7 slides 22, 24"},
  {t:"Eurovision rulebook",d:"The Eurovision slide shows the EBU logo (organisation) next to the booklet 'Rules of the 59th Eurovision Song Contest' (Copenhagen 2014) as a formal institution, and asks: 'Can you come up with any formal/informal rules of the Eurovision?'",slide:"HC7 slide 7"}]},

 dembski:{points:[
  {t:"Lecture exercise: Dembski & Salet as reading 1",d:"In HC7 students pick a reading and answer: how does it explain the limits of deliberate, top-down institutional design; which mechanisms of change does it emphasise; what role do planners have compared with planners as intentional designers? 'Use quotes to support your answers.' The lecturer's answer quotes for this paper are below.",slide:"HC7 slides 33–34"},
  {t:"Quote: limits of design (p. 621)",d:"\"The fact that reality is socially constructed does not by any means imply that planners and policy makers can create whatever social reality they desire. Symbolic markers cannot be used in a voluntaristic way.\"",slide:"HC7 slide 34"},
  {t:"Quote: mechanism of change (pp. 618, 622)",d:"\"New institutions emerge through new cultural practices that become institutionalised.\" (p. 622) and \"Institutionalisation is an ongoing process of normalisation and habituation.\" (p. 618)",slide:"HC7 slide 34"}]},

 moroni:{points:[
  {t:"Lecture exercise: Moroni as reading 3",d:"HC7 uses Moroni as the evolutionary answer to the exercise questions (limits of top-down design, mechanisms of change, role of planners). The lecturer's quotes: most institutions are 'the unintentional outcome of a slow and lengthy evolution over time' (p. 279), and acknowledging this 'does not prevent us from intervening upon them, but simply calls for an approach that is quite different from the taxis-oriented one' (p. 287).",slide:"HC7 slides 33, 36"},
  {t:"Quote: why design fails (p. 282)",d:"\"If institutions are complex and largely unintentional emergent realities, […] they cannot be designed in the same way as organizations.\"",slide:"HC7 slide 36"},
  {t:"Evolutionary strand in the lecture",d:"Evolutionary institutionalism has no definition slide of its own in HC7: it appears in the Part B agenda, through Moroni in the exercise, in the housing homework and in the take-home message listing 'rational-choice, sociological, historical institutionalism and evolutionary institutionalism'.",slide:"HC7 slides 2, 38–39"}]},

 sorensen:{points:[
  {t:"Lecture exercise: Sorensen as reading 2",d:"HC7 uses Sorensen as the historical-institutionalist answer to the exercise questions. The lecturer's three quotes: the critical juncture definition (p. 1807), path dependence as 'not a matter of lock-in' but a 'relatively constrained range of options' (p. 1814), and critical juncture analysis explaining how 'political actors take advantage of conjunctural crises to further particular institutional changes' (p. 1805).",slide:"HC7 slides 33, 35"},
  {t:"Two Sorensens in the lecture",d:"Besides this 2024 Toronto article, the lecture's framework slides cite Sorensen (2017), 'New institutionalism and planning theory' (Routledge Handbook of Planning Theory), for the questions institutionalisms disagree on and for the rational choice definition. Don't mix up the two in citations.",slide:"HC7 slides 22, 25"}]},

 p1:{figs:[
  {title:"1962–1972: the foundational decade",svg:`<svg viewBox="0 0 620 200" role="img" aria-label="Timeline of foundational sustainability books"><g font-size="12">
<rect x="40" y="92" width="480" height="16" rx="6" class="bxg"/><text x="180" y="126" text-anchor="middle" class="mut" font-size="11">foundational decade</text>
<line x1="20" y1="100" x2="600" y2="100" class="ln"/>
<circle cx="40" cy="100" r="5" class="acc"/><circle cx="328" cy="100" r="5" class="acc"/><circle cx="520" cy="100" r="5" class="acc"/><circle cx="568" cy="100" r="5" class="fm"/>
<line x1="40" y1="95" x2="40" y2="60" class="ln"/><text x="46" y="56" font-weight="700">1962</text><text x="46" y="72">Silent Spring (Carson)</text>
<line x1="328" y1="112" x2="328" y2="135" class="ln"/><text x="328" y="150" text-anchor="middle" font-weight="700">1968</text><text x="328" y="166" text-anchor="middle">The Population Bomb (Ehrlich)</text>
<line x1="520" y1="92" x2="520" y2="30" class="ln"/><text x="514" y="28" text-anchor="end" font-weight="700">1972</text><text x="514" y="50" text-anchor="end">Blueprint for Survival (The Ecologist)</text><text x="514" y="70" text-anchor="end">The Limits to Growth</text>
<line x1="568" y1="105" x2="568" y2="180" class="ln"/><text x="562" y="194" text-anchor="end">Small is Beautiful (Schumacher, 1973)</text></g></svg>`,cap:"The five book covers on the slide, placed on a timeline (publication years added). Together they set up the 'limits' framing that Brundtland (1987) later softened into limits of technology and social organisation.",slide:"PSC L1 slide 15"},
  {title:"Planetary boundaries: assessed vs crossed",svg:`<svg viewBox="0 0 620 230" role="img" aria-label="Number of planetary boundaries assessed and crossed per assessment year"><g font-size="12">
<line x1="60" y1="190" x2="600" y2="190" class="ln"/>
<rect x="95" y="55" width="44" height="135" rx="4" class="fm" fill-opacity="0.35"/><rect x="141" y="145" width="44" height="45" rx="4" class="acc"/><text x="117" y="80" text-anchor="middle">7</text><text x="163" y="139" text-anchor="middle" class="acc">3</text>
<rect x="225" y="55" width="44" height="135" rx="4" class="fm" fill-opacity="0.35"/><rect x="271" y="130" width="44" height="60" rx="4" class="acc"/><text x="247" y="80" text-anchor="middle">7</text><text x="293" y="124" text-anchor="middle" class="acc">4</text>
<rect x="355" y="55" width="44" height="135" rx="4" class="fm" fill-opacity="0.35"/><rect x="401" y="100" width="44" height="90" rx="4" class="acc"/><text x="377" y="50" text-anchor="middle">9</text><text x="423" y="94" text-anchor="middle" class="acc">6</text>
<rect x="485" y="55" width="44" height="135" rx="4" class="fm" fill-opacity="0.35"/><rect x="531" y="85" width="44" height="105" rx="4" class="acc"/><text x="507" y="50" text-anchor="middle">9</text><text x="553" y="79" text-anchor="middle" class="acc">7</text>
<text x="140" y="208" text-anchor="middle" font-weight="700">2009</text><text x="270" y="208" text-anchor="middle" font-weight="700">2015</text><text x="400" y="208" text-anchor="middle" font-weight="700">2023</text><text x="530" y="208" text-anchor="middle" font-weight="700">2025</text>
<rect x="60" y="14" width="14" height="12" class="fm" fill-opacity="0.35"/><text x="80" y="25">boundaries assessed (of 9)</text><rect x="270" y="14" width="14" height="12" class="acc"/><text x="290" y="25">boundaries crossed</text>
<text x="330" y="226" text-anchor="middle" class="mut" font-size="11">Rockström et al. 2009, Steffen et al. 2015, Richardson et al. 2023; Stockholm Resilience Centre 2025</text></g></svg>`,cap:"The slide's four planetary-boundary diagrams reduced to their message: more boundaries can be quantified over time, and more are crossed (3 → 4 → 6 → 7). Unlike Brundtland's relative limits, these are global biophysical limits.",slide:"PSC L1 slide 19"},
  {title:"Dutch consumption footprints vs GDP (2010 = 100)",svg:`<svg viewBox="0 0 620 260" role="img" aria-label="GDP rises while consumption footprints fall"><g font-size="11">
<line x1="70" y1="220" x2="500" y2="220" class="ln"/><line x1="70" y1="40" x2="70" y2="220" class="ln"/>
<text x="62" y="224" text-anchor="end" class="mut">50</text><text x="62" y="164" text-anchor="end" class="mut">75</text><text x="62" y="104" text-anchor="end" class="mut">100</text><text x="62" y="44" text-anchor="end" class="mut">125</text>
<line x1="70" y1="100" x2="500" y2="100" class="ln" stroke-dasharray="2 4"/>
<text x="70" y="238" text-anchor="middle" class="mut">2010</text><text x="142" y="238" text-anchor="middle" class="mut">2012</text><text x="213" y="238" text-anchor="middle" class="mut">2014</text><text x="285" y="238" text-anchor="middle" class="mut">2016</text><text x="357" y="238" text-anchor="middle" class="mut">2018</text><text x="428" y="238" text-anchor="middle" class="mut">2020</text><text x="500" y="238" text-anchor="middle" class="mut">2022</text>
<polyline points="70,100 142,99 213,95 285,86 357,74 392,71 428,76 464,62 500,46" class="accs" fill="none" stroke-width="2.5"/>
<polyline points="70,100 142,117 213,134 285,129 357,134 428,138 500,146" class="ln" stroke-width="2" stroke-dasharray="6 4"/>
<polyline points="70,100 142,120 213,136 285,131 357,134 428,148 464,146 500,136" class="ln" stroke-width="2.5"/>
<text x="506" y="50" class="acc">GDP</text><text x="506" y="152" class="mut">land use (dashed)</text><text x="506" y="134" class="mut">GHG, biodiversity</text>
<text x="80" y="30" font-size="12" font-weight="700">Consumption footprints of the Dutch economy (CBS 2025)</text>
<text x="285" y="256" text-anchor="middle" class="mut">shape and values approximate, read from the slide; 2022 provisional</text></g></svg>`,cap:"Relative decoupling: GDP grows (index about 120+ by 2022) while the greenhouse gas, land-use and biodiversity footprints fall to roughly 80–85, with GHG and biodiversity rising again after 2021. The absolute footprints stay far beyond the country's own land area (see point).",slide:"PSC L1 slide 5"},
  {title:"Deaths linked to air pollution in the EU, 2023 (top 7)",svg:`<svg viewBox="0 0 620 240" role="img" aria-label="Bar chart of air pollution deaths by country"><g font-size="12">
<text x="20" y="22" font-weight="700">Deaths attributable to long-term PM2.5 exposure, 2023 (EEA)</text>
<text x="120" y="51" text-anchor="end">#1 Italy</text><rect x="130" y="38" width="380" height="18" rx="3" class="fi"/><text x="516" y="51">43,083</text>
<text x="120" y="79" text-anchor="end">#2 Poland</text><rect x="130" y="66" width="223" height="18" rx="3" class="fi"/><text x="359" y="79">25,268</text>
<text x="120" y="107" text-anchor="end">#3 Germany</text><rect x="130" y="94" width="191" height="18" rx="3" class="fi"/><text x="327" y="107">21,640</text>
<text x="120" y="135" text-anchor="end">#4 France</text><rect x="130" y="122" width="130" height="18" rx="3" class="fi"/><text x="266" y="135">14,741</text>
<text x="120" y="163" text-anchor="end">#5 Romania</text><rect x="130" y="150" width="124" height="18" rx="3" class="fi"/><text x="260" y="163">14,065</text>
<text x="120" y="191" text-anchor="end">#6 Spain</text><rect x="130" y="178" width="117" height="18" rx="3" class="fi"/><text x="253" y="191">13,317</text>
<text x="120" y="219" text-anchor="end">#7 Greece</text><rect x="130" y="206" width="90" height="18" rx="3" class="fi"/><text x="226" y="219">10,249</text>
<text x="600" y="219" text-anchor="end" class="mut" font-size="11">… #27: 34</text></g></svg>`,cap:"Top of the slide's ranking of 27 EU countries (countries identified from the flags). The #11 bar, 3,847 deaths, carries a red-white-blue flag, apparently the Netherlands; the lowest is 34. Used in the intro as evidence that cities are not yet sustainable.",slide:"PSC L1 slide 6"},
  {title:"The efficiency paradox (rebound effect)",svg:`<svg viewBox="0 0 620 240" role="img" aria-label="Direct and indirect rebound effects of a fuel-efficient car"><defs><marker id="sl4reb" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="10" y="98" width="120" height="44" rx="8" class="bxg"/><text x="70" y="117" text-anchor="middle">Fuel-efficient</text><text x="70" y="133" text-anchor="middle">car</text>
<rect x="170" y="30" width="130" height="44" rx="8" class="bx"/><text x="235" y="49" text-anchor="middle">Lower petrol</text><text x="235" y="65" text-anchor="middle">bills</text>
<rect x="335" y="30" width="120" height="44" rx="8" class="bx"/><text x="395" y="49" text-anchor="middle">Holiday</text><text x="395" y="65" text-anchor="middle">in Fiji</text>
<rect x="170" y="166" width="130" height="44" rx="8" class="bx"/><text x="235" y="185" text-anchor="middle">Lower running</text><text x="235" y="201" text-anchor="middle">costs</text>
<rect x="335" y="166" width="120" height="44" rx="8" class="bx"/><text x="395" y="185" text-anchor="middle">Drive further,</text><text x="395" y="201" text-anchor="middle">more often</text>
<rect x="495" y="30" width="115" height="44" rx="8" class="bxa"/><text x="552" y="57" text-anchor="middle">More energy</text>
<rect x="495" y="166" width="115" height="44" rx="8" class="bxa"/><text x="552" y="193" text-anchor="middle">More energy</text>
<line x1="130" y1="110" x2="167" y2="68" class="ln" marker-end="url(#sl4reb)"/><line x1="130" y1="130" x2="167" y2="172" class="ln" marker-end="url(#sl4reb)"/>
<line x1="300" y1="52" x2="332" y2="52" class="ln" marker-end="url(#sl4reb)"/><line x1="455" y1="52" x2="492" y2="52" class="ln" marker-end="url(#sl4reb)"/>
<line x1="300" y1="188" x2="332" y2="188" class="ln" marker-end="url(#sl4reb)"/><line x1="455" y1="188" x2="492" y2="188" class="ln" marker-end="url(#sl4reb)"/>
<text x="400" y="114" text-anchor="middle" font-weight="700">The efficiency paradox</text>
<text x="400" y="131" text-anchor="middle" class="mut" font-size="11">top: indirect rebound · bottom: direct rebound</text></g></svg>`,cap:"Graphic by Ben Godden on the slide 'Direct and indirect impacts of the rebound effect': savings from efficiency are spent on more energy use, so efficiency alone may not cut total consumption, which is why sufficiency follows.",slide:"PSC L1 slide 29"},
  {title:"Sufficiency: the consumption corridor",svg:`<svg viewBox="0 0 620 220" role="img" aria-label="Consumption corridor between minimum and maximum standards"><defs><marker id="sl4cor" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<line x1="90" y1="200" x2="90" y2="22" class="ln" marker-end="url(#sl4cor)"/><text x="80" y="30" text-anchor="end" class="mut" font-size="11">Resource</text><text x="80" y="44" text-anchor="end" class="mut" font-size="11">consumption</text>
<rect x="105" y="70" width="270" height="90" rx="8" class="bxw"/><text x="240" y="112" text-anchor="middle" font-weight="700">Consumption corridor</text><text x="240" y="130" text-anchor="middle" class="mut" font-size="11">'seeking enough when more is possible'</text>
<line x1="105" y1="70" x2="390" y2="70" class="accs" stroke-dasharray="5 3"/><line x1="105" y1="160" x2="390" y2="160" class="accs" stroke-dasharray="5 3"/>
<text x="398" y="66" class="acc" font-weight="700">Maximum consumption standard</text><text x="398" y="82" class="mut" font-size="11">above: planetary boundaries exceeded</text>
<text x="398" y="156" class="acc" font-weight="700">Minimum consumption standard</text><text x="398" y="172" class="mut" font-size="11">below: protected needs not satisfied</text></g></svg>`,cap:"Diagram on the sufficiency slide (quote from Princen, The Logic of Sufficiency, 2005): a good life lies between a floor that satisfies everyone's needs and a ceiling set by planetary boundaries.",slide:"PSC L1 slide 30"}],
 tables:[
  {title:"Course structure: the learning arch",head:["Theme 1: Planning dilemmas","Theme 2: Spatialising planning for sustainability","Theme 3: Planning approaches for sustainable cities"],rows:[["Perspectives on sustainability","Dutch planning system (case study: Fight, flight or freeze? Governing the future of Moerdijk)","Urban sustainability transitions"],["Are cities sustainable?","Planning for sustainability in African cities","Urban experimentation and co-creation"],["Sustainability: a planning dilemma","Planning for sustainability in Chinese cities","Digital planning for sustainable urban futures"],["","","Artificial intelligence, planning and sustainability"],["","","Planning for post-growth cities"],["","","Planning with nature: history, principles and urban futures"]],slide:"PSC L1 slides 9–10"},
  {title:"What happened in the Brundtland Commission's 900 days (Oct 1984–Apr 1987)",head:["Event","Toll on the slide"],rows:[["Drought-triggered environment-development crisis in Africa","36 million people at risk; perhaps a million killed"],["Pesticides factory leak, Bhopal (India)","More than 2,000 killed; over 200,000 blinded and injured"],["Liquid gas tanks exploded, Mexico City","1,000 killed; thousands left homeless"],["Chernobyl nuclear reactor explosion","Fallout across Europe; higher risk of future cancers"],["Warehouse fire in Switzerland: agricultural chemicals, solvents and mercury into the Rhine","Millions of fish killed; drinking water threatened in West Germany and the Netherlands"],["Diarrhoeal diseases from unsafe drinking water and malnutrition","An estimated 60 million dead, most of them children"]],slide:"PSC L1 slide 18"},
  {title:"Efficiency, consistency, sufficiency by sector (Rudolf & Schmidt 2025)",head:["Sector","Efficiency (IAM: efficiency)","Consistency (IAM: technological substitution)","Sufficiency (IAM: lifestyle change)"],rows:[["Transport","Fuel-efficient vehicles","Electric vehicles","Public transport; tele-conferencing"],["Residential","Energy-efficient products","Micro-generation","Thermostat adjustment; tiny house"],["Food","Efficient food production","Local products","Sustainable, healthy diet"],["Consumer goods & services","Efficient supply chain","Purchase sustainable goods","Sustainable use of goods; sharing economy"]],slide:"PSC L1 slide 27"},
  {title:"Three kinds of social sustainability (Vallance et al. 2011)",head:["Type","Focus"],rows:[["Development sustainability","Addressing basic needs, justice and equity"],["Bridge sustainability","Change in social behaviour to achieve bio-physical (environmental) goals"],["Maintenance sustainability","Preservation of socio-cultural characteristics"]],slide:"PSC L1 slide 32"},
  {title:"Compact city characteristics (Neuman, 'The Compact City Fallacy', Table 2)",head:["#","Characteristic"],rows:[["1","High residential and employment densities"],["2","Mixture of land uses"],["3","Fine grain of land uses (proximity of varied uses and small relative size of land parcels)"],["4","Increased social and economic interactions"],["5","Contiguous development (some parcels or structures may be vacant or abandoned or surface parking)"],["6","Contained urban development, demarcated by legible limits"],["7","Urban infrastructure, especially sewerage and water mains"],["8","Multimodal transportation"],["9","High degrees of accessibility: local/regional"],["10","High degrees of street connectivity (internal/external), including sidewalks and bicycle lanes"],["11","High degree of impervious surface coverage"],["12","Low open-space ratio"],["13","Unitary control of planning of land development, or closely coordinated control"],["14","Sufficient government fiscal capacity to finance urban facilities and infrastructure"]],slide:"PSC L1 slide 36"}],
 points:[
  {t:"Income inequality across Dutch municipalities",d:"A CBS map of the Gini coefficient by municipality (2022, provisional) uses five classes from below 0.24 to 0.30 or more. The most unequal municipalities cluster in the western Randstad, while much of the north and east is in the lowest classes.",slide:"PSC L1 slide 3"},
  {t:"Income disparities within cities (PBL 2016)",d:"PBL's 'Cities in the Netherlands' maps income per person and the share of residents with a non-western background in Amsterdam, The Hague and Arnhem. Rich households occupy Amsterdam's historic centre and Oud-Zuid, The Hague's high sandy ground near the coast (the traditional 'sand and peat divide': Duinoord, Statenkwartier, Archipelbuurt) and Arnhem's northern edge near the Veluwe; the second set of maps shows roughly the reverse pattern.",slide:"PSC L1 slide 4"},
  {t:"The Dutch footprint in numbers (CBS 2025)",d:"Greenhouse gas footprint: 239 Mt CO₂-equivalent in 2022, or 13.5 thousand kg per person, smaller since 2010 but growing again from 2021. Land-use footprint: 13 million ha in 2022 (0.7 ha per person), three times the land area of the Netherlands. Biodiversity footprint: over 18 million ha in 2021, more than four times the country's size.",slide:"PSC L1 slide 5"},
  {t:"Opening quote (Yigitcanlar & Teriman 2015)",d:"\"The concept of sustainable urban development has been around over a considerably long time … however, to date such development has not been achieved in large scales anywhere around the globe\"",slide:"PSC L1 slide 7"},
  {t:"Why 'dilemma'",d:"The course frames sustainability as a dilemma, defined on the slide as 'a situation in which a difficult choice has to be made between two or more alternatives, especially ones that are equally undesirable.'",slide:"PSC L1 slide 8"},
  {t:"Teachers",d:"Shaun Smith (assistant professor, coordinator; urban energy transitions, African cities), Yanliu Lin (associate professor in spatial planning and digitalisation; digital planning/governance, collaborative planning, planning support science) and Niki Frantzeskaki (chair professor of regional and metropolitan governance and planning; urban transitions and transformations, climate adaptation, nature-based solutions).",slide:"PSC L1 slide 11"},
  {t:"Assessment",d:"(1) Portfolio of 4,700 words built up through the course, deadline 6 November. (2) One group presentation at the end of an allocated lecture, based on that session's mandatory reading. (3) Written exam on university laptops with two question types: comprehension and an essay.",slide:"PSC L1 slide 12"},
  {t:"Brundtland quote on limits",d:"\"The concept of sustainable development does imply limits - not absolute limits but limitations imposed by the present state of technology and social organization on environmental resources and by the ability of the biosphere to absorb the effects of human activities\" (WCED 1987)",slide:"PSC L1 slide 17"},
  {t:"Three ways to draw sustainability (Purvis et al. 2019)",d:"The 'conventional view' slide shows three depictions: three intersecting circles (social, environment, economic, 'sustainable' in the middle), literal pillars holding up 'sustainability', and concentric circles with the economy inside society inside the environment.",slide:"PSC L1 slide 20"},
  {t:"Weak sustainability: who and when",d:"Weak sustainability stems from neo-classical economics in the 1970s (the slide names Robert Solow and 'John Kawrick', i.e. John Hartwick) and presumes that social and natural capitals are (necessarily) interchangeable. The slide on weak vs strong is illustrated with the Antarctic ozone hole, an example of a biophysical limit.",slide:"PSC L1 slide 21"},
  {t:"Weak sustainability example: Norway",d:"Headlines 'Norway's growing $2 trillion oil empire' (the oil fund's market value since inception) next to 'Oslo Is Ranked One Of The Most Sustainable Cities In The World': a green capital financed by fossil-fuel wealth, i.e. natural capital converted into financial capital.",slide:"PSC L1 slide 22"},
  {t:"Daly: vague on purpose",d:"Daly (1996, Beyond Growth) argued sustainable development was left intentionally vague to build consensus, including among actors with diverse interests such as business leaders and environmental campaigners.",slide:"PSC L1 slide 23"},
  {t:"Volkswagen and the failure of CSR",d:"A Forbes article 'Volkswagen And The Failure Of Corporate Social Responsibility' (2015) illustrates how a vague, consensus-friendly sustainability concept can be claimed by firms whose practices contradict it.",slide:"PSC L1 slide 24"},
  {t:"Swyngedouw: which natures?",d:"Swyngedouw contests the dominant view of a 'dynamic equilibrium-based nature' that is doomed to catastrophe if we don't align to it. That view blocks political questions about which nature(s) are desirable: 'we may want to preserve natures, to make, or to eradicate'. Since it is impossible not to support sustainability (Næss 2000), the dominant discourse can be manipulated by incumbent interests who may be perpetuating unsustainability in the first place.",slide:"PSC L1 slide 25"},
  {t:"Swyngedouw quote",d:"\"The fantasy of 'sustainability' imagines the possibility of an originally fundamentally harmonious Nature, one that is now out-of-synch but, which, if 'properly' managed, we can and have to return to by means of a series of technological, managerial and organisational fixes.\" (Swyngedouw 2010)",slide:"PSC L1 slide 26"},
  {t:"Huber's triad: origin",d:"Efficiency, sufficiency and consistency were proposed by the German economist and sociologist Joseph Huber to solve the dilemma of conflicting sustainability goals. Efficiency can mean a relative or an absolute reduction in economic impact; consistency means technological leaps that mimic the natural resource cycle.",slide:"PSC L1 slide 27"},
  {t:"Efficiency examples",d:"A ranking of the most fuel-efficient cars (V3Cars 2026) and an IRPP (2023) figure showing that deep retrofits of a low-income single-family home and an affordable multi-unit building improve affordability, energy efficiency and climate resilience: efficient lighting and appliances, heating and cooling, windows, doors and insulation, water-efficient plumbing, flood- and fire-resilient construction, battery backup, vehicle charging and low-carbon materials.",slide:"PSC L1 slide 28"},
  {t:"Social sustainability: three problems",d:"General: social sustainability is neglected as a concept. Messy: there are many social conceptions (liveability, justice, basic social needs approaches) that are hard to align in one approach. And it raises arguably the most problematic questions, e.g. Global North vs South.",slide:"PSC L1 slide 32"},
  {t:"Vallance et al. quote",d:"\"need to rely less on 'objective data' and 'scientific evidence' to stimulate changed human perspectives on bio-physical environmental issues. This is not a call to abandon environmental science, but rather a suggestion that its practitioners work alongside social scientists in order to explore how residents interpret, and incorporate concerns about, the places in which they live and the world around them\" (Vallance et al. 2011)",slide:"PSC L1 slide 33"},
  {t:"Næss: relational approach",d:"Besides the points already on this page, the Næss slide lists a relational approach to planning research, and notes that his 2001 paper is often credited as the first to address sustainable development in the context of urban planning.",slide:"PSC L1 slide 34"},
  {t:"Neuman: process over form",d:"Neuman argues that \"sustainable urban development, runs counter to the principles of the compact city in one fundamental respect: the primacy of process over form\". Liveability is found in both compact and low-density cities. Yet a purely procedural view of planning neglects substantive content. Sustainability is a question about how to live: a long-term process, health, place specificity and interrelationships.",slide:"PSC L1 slide 35"},
  {t:"Post-growth planning (closing slide)",d:"From postgrowthplanning.com: a planning in which growth is neither a necessary starting point nor a goal. It works on change but does not set economic growth (GDP) or competition between public entities (for population or economic numbers) as its goal. It aims to enhance quality of life for a diversity of people, but not with more of the same growth solutions. It acts within available resources (including land) and planetary boundaries, so that critical post-growth planners take honest, just and democratic decisions.",slide:"PSC L1 slide 37"}]}
};
