const SL_5={
 p2:{figs:[
  {title:"Urban overtakes rural population",svg:`<svg viewBox="0 0 620 260" role="img" aria-label="Urban and rural world population 1950 to 2050"><g font-size="11">
<path d="M60 30 L60 220 L590 220" class="ln"/>
<text x="54" y="224" text-anchor="end" class="mut">0</text><text x="54" y="176" text-anchor="end" class="mut">2,000</text><text x="54" y="129" text-anchor="end" class="mut">4,000</text><text x="54" y="81" text-anchor="end" class="mut">6,000</text><text x="54" y="34" text-anchor="end" class="mut">8,000</text>
<path d="M60 172.5 L590 172.5 M60 125 L590 125 M60 77.5 L590 77.5" class="ln" stroke-dasharray="3 4" opacity="0.5"/>
<text x="60" y="238" text-anchor="middle" class="mut">1950</text><text x="325" y="238" text-anchor="middle" class="mut">2000</text><text x="590" y="238" text-anchor="middle" class="mut">2050</text>
<path d="M60 202 L166 188 L272 165 L362 140 L431 115 L484 98 L590 61" fill="none" class="accs" stroke-width="2.5"/>
<path d="M60 177 L166 164 L272 148 L362 140 L457 138 L537 142 L590 146" fill="none" class="ln" stroke-width="2.5"/>
<circle cx="362" cy="140" r="5" class="fw"/>
<text x="362" y="128" text-anchor="end" font-weight="700">crossover late 2000s</text>
<text x="585" y="54" text-anchor="end" class="acc" font-weight="700">Urban</text><text x="585" y="164" text-anchor="end" class="mut" font-weight="700">Rural</text>
<text x="20" y="20" class="mut">Population (millions)</text>
</g></svg>`,cap:"Urban and rural population of the world, 1950–2050; shape and approximate levels read from the slide's chart (urban ≈ 6.7 bn vs rural ≈ 3.1 bn by 2050).",slide:"L2 slide 3"},
  {title:"The 'great acceleration' behind urban growth",svg:`<svg viewBox="0 0 620 270" role="img" aria-label="Social, ecological and technological trends 1750 to 2010"><g font-size="11">
<rect x="6" y="20" width="76" height="72" rx="8" class="bxw"/><text x="44" y="60" text-anchor="middle" font-weight="700">SOCIAL</text>
<rect x="6" y="102" width="76" height="72" rx="8" class="bxg"/><text x="44" y="136" text-anchor="middle" font-weight="700">ECOLO-</text><text x="44" y="150" text-anchor="middle" font-weight="700">GICAL</text>
<rect x="6" y="184" width="76" height="72" rx="8" class="bxi"/><text x="44" y="218" text-anchor="middle" font-weight="700">TECHNO-</text><text x="44" y="232" text-anchor="middle" font-weight="700">LOGICAL</text>
<rect x="90" y="20" width="170" height="72" rx="8" class="bx"/><text x="175" y="36" text-anchor="middle">A. Urban population</text><path d="M100 84 Q200 82 250 46" fill="none" class="accs" stroke-width="2"/>
<rect x="268" y="20" width="170" height="72" rx="8" class="bx"/><text x="353" y="36" text-anchor="middle">B. Real GDP</text><path d="M278 84 Q390 84 428 44" fill="none" class="accs" stroke-width="2"/>
<rect x="446" y="20" width="170" height="72" rx="8" class="bx"/><text x="531" y="36" text-anchor="middle">C. Global water usage</text><path d="M456 84 Q560 82 606 46" fill="none" class="accs" stroke-width="2"/>
<rect x="90" y="102" width="170" height="72" rx="8" class="bx"/><text x="175" y="118" text-anchor="middle">D. Biosphere degradation</text><path d="M100 166 Q190 160 250 128" fill="none" class="accs" stroke-width="2"/>
<rect x="268" y="102" width="170" height="72" rx="8" class="bx"/><text x="353" y="118" text-anchor="middle">E. Surface temperature</text><path d="M278 162 L320 160 L350 156 L380 150 L400 154 L428 128" fill="none" class="accs" stroke-width="2"/>
<rect x="446" y="102" width="170" height="72" rx="8" class="bx"/><text x="531" y="118" text-anchor="middle">F. Carbon dioxide</text><path d="M456 166 Q560 164 606 128" fill="none" class="accs" stroke-width="2"/>
<rect x="90" y="184" width="170" height="72" rx="8" class="bx"/><text x="175" y="200" text-anchor="middle">G. Primary energy use</text><path d="M100 248 Q205 246 250 208" fill="none" class="accs" stroke-width="2"/>
<rect x="268" y="184" width="170" height="72" rx="8" class="bx"/><text x="353" y="200" text-anchor="middle">H. Crude steel</text><path d="M278 248 Q360 236 428 208" fill="none" class="accs" stroke-width="2"/>
<rect x="446" y="184" width="170" height="72" rx="8" class="bx"/><text x="531" y="200" text-anchor="middle">I. Cement production</text><path d="M456 248 Q550 244 606 208" fill="none" class="accs" stroke-width="2"/>
</g></svg>`,cap:"McPhearson et al. (2021): urban population, GDP, resource use and environmental pressures all curve sharply upwards together since about 1950 (schematic of the nine panels).",slide:"L2 slide 6"},
  {title:"CO₂ per capita vs urbanisation: weakening link",svg:`<svg viewBox="0 0 620 200" role="img" aria-label="Correlation between urbanisation and CO2 per capita over time"><g font-size="12">
<path d="M80 170 L560 170" class="ln"/>
<rect x="110" y="42" width="70" height="128" rx="6" class="bxa"/><text x="145" y="34" text-anchor="middle" font-weight="700">r = 0.6416</text><text x="145" y="188" text-anchor="middle">1990</text>
<rect x="230" y="45" width="70" height="125" rx="6" class="bxa"/><text x="265" y="37" text-anchor="middle" font-weight="700">r = 0.6252</text><text x="265" y="188" text-anchor="middle">2000</text>
<rect x="350" y="52" width="70" height="118" rx="6" class="bxa"/><text x="385" y="44" text-anchor="middle" font-weight="700">r = 0.5918</text><text x="385" y="188" text-anchor="middle">2010</text>
<rect x="470" y="61" width="70" height="109" rx="6" class="bxa"/><text x="505" y="53" text-anchor="middle" font-weight="700">r = 0.5465</text><text x="505" y="188" text-anchor="middle">2019</text>
<text x="20" y="20" class="mut" font-size="11">Correlation: urban share (%) × CO₂ per capita</text>
</g></svg>`,cap:"Countries with a higher urban share emit more CO₂ per capita, but the correlation weakens between 1990 and 2019 (scatterplots summarised by their r values).",slide:"L2 slide 10"},
  {title:"Vulnerability: urban vs rural",svg:`<svg viewBox="0 0 620 260" role="img" aria-label="Median vulnerability index score for urban, intermediate and rural areas"><g font-size="11">
<path d="M70 30 L70 230 L480 230" class="ln"/>
<text x="64" y="234" text-anchor="end" class="mut">2.0</text><text x="64" y="179" text-anchor="end" class="mut">3.0</text><text x="64" y="124" text-anchor="end" class="mut">4.0</text><text x="64" y="69" text-anchor="end" class="mut">5.0</text>
<text x="90" y="248" text-anchor="middle">Urban</text><text x="280" y="248" text-anchor="middle">Intermediate</text><text x="470" y="248" text-anchor="middle">Rural</text>
<path d="M90 113 L280 78 L470 56" fill="none" class="accs" stroke-width="2.5"/>
<path d="M90 57 L280 69 L470 76" fill="none" class="ln" stroke-width="2.5"/>
<path d="M90 126 L280 115 L470 101" fill="none" class="ln" stroke-width="1.5" stroke-dasharray="5 4"/>
<path d="M90 185 L280 164 L470 133" fill="none" class="accs" stroke-width="1.5" stroke-dasharray="2 3"/>
<path d="M90 175 L280 165 L470 133" fill="none" class="ln" stroke-width="1.5"/>
<text x="486" y="56">Economic ↑</text><text x="486" y="80">Environmental ↓</text><text x="486" y="104">Overall ↑</text><text x="486" y="137">Social, Political ↑</text>
<text x="20" y="20" class="mut">Median vulnerability index score (EEA 2026)</text>
</g></svg>`,cap:"EEA (2026): economic, social, political and overall vulnerability scores rise from urban to rural areas; only environmental vulnerability is highest in urban areas. Levels read approximately from the slide.",slide:"L2 slide 11"},
  {title:"Urban heat island: temperature profile",svg:`<svg viewBox="0 0 620 210" role="img" aria-label="Urban heat island temperature profile across land uses"><g font-size="11">
<path d="M40 170 L590 170" class="ln"/>
<path d="M60 150 C110 148 130 130 170 122 C210 112 230 40 270 40 C310 40 320 95 350 100 C380 104 390 140 410 138 C430 136 450 110 480 112 C520 114 540 150 580 152" fill="none" class="accs" stroke-width="3"/>
<text x="60" y="188" text-anchor="middle">Rural</text><text x="130" y="188" text-anchor="middle">Suburban</text><text x="200" y="188" text-anchor="middle">Commercial</text><text x="270" y="188" text-anchor="middle" font-weight="700">Downtown</text><text x="345" y="188" text-anchor="middle">Urban res.</text><text x="410" y="188" text-anchor="middle">Park</text><text x="480" y="188" text-anchor="middle">Suburban</text><text x="570" y="188" text-anchor="middle">Farmland</text>
<text x="270" y="30" text-anchor="middle" class="acc" font-weight="700">peak</text><text x="410" y="128" text-anchor="middle" class="fg" font-weight="700">dip</text>
<text x="20" y="20" class="mut">Late-afternoon temperature (≈85–92 °F)</text>
</g></svg>`,cap:"Urban Heat Island Effect (adapted from US EPA, via GIZ 2019): temperatures peak downtown and dip over parks. The Antwerp map (slide 15) shows the densest centre on average 2 °C warmer than the peri-urban surroundings.",slide:"L2 slides 14–15"},
  {title:"Vicious cycle of urban heat islands",svg:`<svg viewBox="0 0 620 270" role="img" aria-label="Vicious cycle of urban heat islands"><defs><marker id="sl5uhi" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="30" y="20" width="170" height="36" rx="8" class="bxa"/><text x="115" y="42" text-anchor="middle">Higher local temperatures</text>
<rect x="420" y="20" width="170" height="36" rx="8" class="bxw"/><text x="505" y="42" text-anchor="middle">More air conditioning</text>
<rect x="420" y="120" width="170" height="36" rx="8" class="bxw"/><text x="505" y="142" text-anchor="middle">Greater energy demand</text>
<rect x="420" y="220" width="170" height="36" rx="8" class="bxw"/><text x="505" y="242" text-anchor="middle">More GHG release</text>
<rect x="30" y="220" width="170" height="36" rx="8" class="bxa"/><text x="115" y="242" text-anchor="middle">More global warming</text>
<rect x="225" y="120" width="170" height="36" rx="8" class="bx"/><text x="310" y="142" text-anchor="middle">Lower air quality</text>
<rect x="30" y="120" width="170" height="36" rx="8" class="bx"/><text x="115" y="136" text-anchor="middle">Intensified urban</text><text x="115" y="150" text-anchor="middle">heat island effect</text>
<path d="M200 38 L416 38" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M505 56 L505 116" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M505 156 L505 216" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M420 238 L204 238" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M30 238 L14 238 L14 38 L26 38" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M420 138 L399 138" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M225 138 L204 138" class="ln" marker-end="url(#sl5uhi)"/>
<path d="M115 120 L115 60" class="ln" marker-end="url(#sl5uhi)"/>
</g></svg>`,cap:"'Vicious cycle of business as usual' (GIZ 2019), simplified: heat drives cooling demand and emissions, which feed back into higher temperatures.",slide:"L2 slide 14"},
  {title:"Two Anthropocene pathways",svg:`<svg viewBox="0 0 620 250" role="img" aria-label="Status quo to good or dystopian Anthropocene"><defs><marker id="sl5anth" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="20" y="105" width="110" height="44" rx="8" class="bx"/><text x="75" y="124" text-anchor="middle" font-weight="700">Status quo</text><text x="75" y="140" text-anchor="middle" class="mut">2020</text>
<path d="M130 120 C230 110 300 50 430 45" class="ln" stroke-width="2" marker-end="url(#sl5anth)"/>
<path d="M130 134 C230 144 300 200 430 205" class="ln" stroke-width="2" marker-end="url(#sl5anth)"/>
<rect x="190" y="30" width="190" height="40" rx="8" class="bxg"/><text x="285" y="46" text-anchor="middle">Transformative pathways</text><text x="285" y="62" text-anchor="middle" class="mut">rethinking principles 1–5</text>
<rect x="190" y="180" width="190" height="40" rx="8" class="bxw"/><text x="285" y="196" text-anchor="middle">Business as usual</text><text x="285" y="212" text-anchor="middle" class="mut">conventional principles</text>
<rect x="436" y="24" width="160" height="44" rx="8" class="bxg"/><text x="516" y="43" text-anchor="middle" font-weight="700">Good Anthropocene</text><text x="516" y="59" text-anchor="middle" class="mut">2050</text>
<rect x="436" y="184" width="160" height="44" rx="8" class="bxa"/><text x="516" y="203" text-anchor="middle" font-weight="700">Dystopian futures</text><text x="516" y="219" text-anchor="middle" class="mut">2050</text>
<text x="610" y="130" text-anchor="end" class="mut">↑ benefits for</text><text x="610" y="144" text-anchor="end" class="mut">people and nature</text>
</g></svg>`,cap:"McPhearson et al. (2021): from today's status quo, rethinking growth, efficiency, the state, the commons and justice leads to a 'good Anthropocene'; business as usual leads to dystopian futures.",slide:"L2 slide 28"},
  {title:"Cheapest emission cuts: buildings first",svg:`<svg viewBox="0 0 620 240" role="img" aria-label="Emission reduction potential by sector, approximate"><g font-size="11">
<path d="M40 190 L600 190" class="ln"/>
<rect x="55" y="40" width="54" height="150" class="fw"/><rect x="55" y="32" width="54" height="8" class="fi"/>
<rect x="135" y="155" width="54" height="35" class="fw"/><rect x="135" y="125" width="54" height="30" class="fi"/><rect x="135" y="83" width="54" height="42" class="fm"/>
<rect x="215" y="162" width="54" height="28" class="fw"/><rect x="215" y="100" width="54" height="62" class="fi"/><rect x="215" y="90" width="54" height="10" class="fm"/>
<rect x="295" y="145" width="54" height="45" class="fw"/><rect x="295" y="110" width="54" height="35" class="fi"/><rect x="295" y="100" width="54" height="10" class="fm"/>
<rect x="375" y="157" width="54" height="33" class="fw"/><rect x="375" y="135" width="54" height="22" class="fi"/><rect x="375" y="122" width="54" height="13" class="fm"/>
<rect x="455" y="148" width="54" height="42" class="fw"/><rect x="455" y="140" width="54" height="8" class="fi"/>
<rect x="535" y="174" width="54" height="16" class="fw"/>
<text x="82" y="206" text-anchor="middle" font-weight="700">Buildings</text><text x="162" y="206" text-anchor="middle">Agriculture</text><text x="242" y="206" text-anchor="middle">Industry</text><text x="322" y="206" text-anchor="middle">Energy</text><text x="402" y="206" text-anchor="middle">Forestry</text><text x="482" y="206" text-anchor="middle">Transport</text><text x="562" y="206" text-anchor="middle">Waste</text>
<rect x="120" y="222" width="12" height="10" class="fw"/><text x="138" y="231">low cost</text><rect x="230" y="222" width="12" height="10" class="fi"/><text x="248" y="231">medium cost</text><rect x="360" y="222" width="12" height="10" class="fm"/><text x="378" y="231">high cost</text>
<text x="20" y="20" class="mut">Mitigation potential by sector, GtCO₂-eq (WRI, approx.)</text>
</g></svg>`,cap:"World Resources Institute (after IPCC AR4): buildings offer the biggest emission cuts, almost all at low cost; transport cuts are also mostly low-cost. Bar heights approximate, read from the slide.",slide:"L2 slide 31"},
  {title:"Circular city: two material cycles",svg:`<svg viewBox="0 0 620 270" role="img" aria-label="Circular economy biological and technical cycles"><defs><marker id="sl5circ" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<text x="150" y="20" text-anchor="middle" font-weight="700" class="fg">Renewables (biological)</text><text x="470" y="20" text-anchor="middle" font-weight="700" class="fi">Finite materials (technical)</text>
<rect x="230" y="34" width="160" height="26" rx="6" class="bx"/><text x="310" y="51" text-anchor="middle">Parts manufacturer</text>
<rect x="230" y="68" width="160" height="26" rx="6" class="bx"/><text x="310" y="85" text-anchor="middle">Product manufacturer</text>
<rect x="230" y="102" width="160" height="26" rx="6" class="bx"/><text x="310" y="119" text-anchor="middle">Service provider</text>
<rect x="190" y="150" width="100" height="30" rx="8" class="bxg"/><text x="240" y="169" text-anchor="middle">Consumer</text>
<rect x="330" y="150" width="100" height="30" rx="8" class="bxi"/><text x="380" y="169" text-anchor="middle">User</text>
<rect x="15" y="40" width="165" height="150" rx="10" class="bxg" opacity="0.6"/>
<text x="97" y="62" text-anchor="middle">farming / collection</text><text x="97" y="80" text-anchor="middle">biochemical feedstock</text><text x="97" y="98" text-anchor="middle">regeneration (biosphere)</text><text x="97" y="116" text-anchor="middle">cascades</text><text x="97" y="134" text-anchor="middle">anaerobic digestion</text><text x="97" y="152" text-anchor="middle">biogas</text><text x="97" y="170" text-anchor="middle">extraction of feedstock</text>
<rect x="440" y="40" width="165" height="150" rx="10" class="bxi" opacity="0.6"/>
<text x="522" y="62" text-anchor="middle" font-weight="700">inner loops first:</text><text x="522" y="82" text-anchor="middle">1 share</text><text x="522" y="100" text-anchor="middle">2 maintain / prolong</text><text x="522" y="118" text-anchor="middle">3 reuse / redistribute</text><text x="522" y="136" text-anchor="middle">4 refurbish/remanufacture</text><text x="522" y="154" text-anchor="middle">5 recycle</text>
<path d="M240 180 C240 230 110 230 98 194" class="ln" marker-end="url(#sl5circ)"/><path d="M380 180 C380 230 510 230 522 194" class="ln" marker-end="url(#sl5circ)"/>
<text x="310" y="250" text-anchor="middle" class="mut">collection → minimise systematic leakage and negative externalities</text>
</g></svg>`,cap:"Ellen MacArthur Foundation 'butterfly' diagram shown for circular cities (with the Metabolic Cities Program): biological materials cascade back to the biosphere; technical materials circulate through ever-wider loops, from sharing to recycling.",slide:"L2 slide 34"},
  {title:"Features of a 20-minute neighbourhood",svg:`<svg viewBox="0 0 620 300" role="img" aria-label="Features of a 20-minute neighbourhood"><g font-size="11">
<circle cx="310" cy="150" r="62" class="bxg"/><text x="310" y="146" text-anchor="middle" font-weight="700">20-minute</text><text x="310" y="162" text-anchor="middle" font-weight="700">neighbourhood</text>
<circle cx="310" cy="150" r="105" fill="none" class="ln" stroke-dasharray="3 4"/>
<text x="310" y="30" text-anchor="middle">Local shopping centres</text>
<text x="420" y="44">Local health services</text>
<text x="458" y="72">Local schools</text>
<text x="472" y="102">Lifelong learning</text>
<text x="480" y="132">Playgrounds and parks</text>
<text x="480" y="162">Green street spaces</text>
<text x="472" y="192">Community gardens</text>
<text x="458" y="222">Sport and recreation</text>
<text x="400" y="256">Safe streets and spaces</text>
<text x="310" y="282" text-anchor="middle">Affordable housing options</text>
<text x="220" y="256" text-anchor="end">Ability to age in place</text>
<text x="162" y="222" text-anchor="end">Housing diversity</text>
<text x="148" y="192" text-anchor="end">Walkability</text>
<text x="140" y="162" text-anchor="end">Safe cycling networks</text>
<text x="140" y="132" text-anchor="end">Local public transport</text>
<text x="148" y="102" text-anchor="end">Well connected to PT,</text><text x="148" y="115" text-anchor="end">jobs and services</text>
<text x="162" y="72" text-anchor="end">Local employment</text>
</g></svg>`,cap:"Features of a 20-minute neighbourhood (UN-Habitat 2022, World Cities Report, after State of Victoria). Shown alongside 'The 15-minute Paris' and Utrecht's '10-minute city'.",slide:"L2 slides 37–38"},
  {title:"What predicts household carbon? (UK)",svg:`<svg viewBox="0 0 620 230" role="img" aria-label="Regression tree of household CO2 by settlement characteristics"><defs><marker id="sl5tree" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="230" y="14" width="160" height="40" rx="8" class="bxi"/><text x="310" y="31" text-anchor="middle" font-weight="700">1. Density</text><text x="310" y="46" text-anchor="middle" class="mut">split at 50 pop/ha</text>
<path d="M270 54 L150 92" class="ln" marker-end="url(#sl5tree)"/><path d="M350 54 L470 92" class="ln" marker-end="url(#sl5tree)"/>
<text x="196" y="72" text-anchor="end" class="mut">lower density</text><text x="424" y="72" class="mut">higher density</text>
<rect x="70" y="94" width="160" height="40" rx="8" class="bxw"/><text x="150" y="111" text-anchor="middle" font-weight="700">2. Income</text><text x="150" y="126" text-anchor="middle" class="mut">split at £900 / week</text>
<rect x="390" y="94" width="160" height="40" rx="8" class="bxw"/><text x="470" y="111" text-anchor="middle" font-weight="700">3. Household size</text><text x="470" y="126" text-anchor="middle" class="mut">split at 2.3 persons</text>
<rect x="20" y="164" width="270" height="50" rx="8" class="bx"/><text x="155" y="184" text-anchor="middle">then: heating degree days,</text><text x="155" y="200" text-anchor="middle">poor housing condition, central heating</text>
<rect x="330" y="164" width="270" height="50" rx="8" class="bx"/><text x="465" y="184" text-anchor="middle">then: density, central heating,</text><text x="465" y="200" text-anchor="middle">income, heating degree days</text>
<path d="M150 134 L150 160" class="ln" marker-end="url(#sl5tree)"/><path d="M470 134 L470 160" class="ln" marker-end="url(#sl5tree)"/>
</g></svg>`,cap:"Baiocchi et al. (2015): a regression tree splits UK settlements first on density, then on income (less dense) or household size (denser), ending in settlement types with different kg CO₂ per capita. Urban form matters, but only together with income and household traits.",slide:"L2 slide 40"}
 ],
 tables:[
  {title:"Sustainable urban form matrix (Jabareen 2006)",head:["Design concept","Neotraditional","Compact city","Urban containment","Eco-city"],rows:[["Density","Moderate","High","Moderate","Moderate"],["Diversity","High","High","Moderate","Moderate"],["Mixed land use","High","High","Moderate","Moderate"],["Compactness","Moderate","High","Moderate","Low"],["Sustainable transportation","Moderate","High","Moderate","High"],["Passive solar design","Low","Low","Low","High"],["Greening / ecological design","Moderate","Low","Low","High"],["Total score","15 points","17 points","12 points","16 points"]],slide:"L2 slide 39"},
  {title:"How cities are called upon to save the planet (Angelo & Wachsmuth 2020, Table 1)",head:["Global problem","Emerged","Non-city solution","City solution","Type of solution"],rows:[["Sprawl: too much resource consumption, as in suburban sprawl","1960s","Limiting capitalist growth (Meadows et al. 1972); limiting urban growth (Callenbach 1975)","Concentrate people and resources in efficient urban spaces: compact cities, densification, smart cities","Spatial planning (for affluent Northern cities)"],["Informal settlements: physical vulnerability, sanitation, health, extreme weather, too-rapid growth, lack of infrastructure","1980s","Sustainable development (Brundtland 1987; Habitat I)","Informal settlements as model for resilience and sustainable design (Brand 2010); sustainable urban development (Habitat II)","Architecture/design (for poor Southern cities; eventually a model for Northern cities)"],["Climate change: need for global coordination to reduce GHG emissions","1990s","Multilateral treaty process (UNFCCC 1992; Kyoto 1997)","Interlocal networks (ICLEI 1990); empowered mayors; Mayors' Climate Protection Agreement 2007; cities as climate protagonists (Habitat III)","Governance (everywhere)"],["Physical vulnerability of cities' infrastructure, populations and assets to extreme weather","2000s","None","New investment in resilience in coastal cities (100 Resilient Cities; Rebuild By Design)","—"]],slide:"L2 slide 46"},
  {title:"The evolving urban agenda in international policy forums (Parnell 2015)",head:["Period","Conceptions of cities","Strategies","Programmes / frameworks","Inputs to advance targets"],rows:[["UNCED 1992 (recognition of 'the local')","Cities and urban growth as problems; sustainable urban and rural development","Local authority and stakeholder engagement; more integrated local planning","Local Agenda 21 (urban sustainability planning); integrated development planning","'Major Groups'; coalition of local government associations / Curitiba Summit; Local Government Awards"],["Habitat II 1996 (cities as strategic sites in a globalising economy)","Cities as growth centres, 'half the world's population'; focus on mega-cities","Inclusive cities; good urban governance; public–private partnerships / privatisation","City Development Strategies; Cities Alliance; Cities Without Slums; best practices and benchmarking","UN-Habitat Best Practices / Dubai Award; Global Urban Observatory; World Water Forum"],["Rio+20 / current and next (the world as an urban system)","Cities as centres of economic, social and ecological productivity; 'city as opportunity', 'innovation spaces', 'development agents', 'leaders of climate action'","Regional (rural–urban) integration; green urban economy; transition theory / regenerative cities; cities for life (equity and social justice)","Urban Nexus; smart cities initiatives; initiative for an Urban SDG","Global Town Hall; Stakeholder Forum"]],slide:"L2 slide 47"},
  {title:"Urban sustainability categories in the literature (Cohen 2017, Table 5, first part)",head:["Category","Instances in literature","Unique elements","Sources referencing"],rows:[["Air quality","19","2","16"],["Arts, culture and recreation","40","18","22"],["Buildings","49","19","18"],["Built environment","30","9","17"],["Climate change","18","3","14"],["Community","22","9","18"],["Economy","104","41","40"],["Education","16","6","12"],["Energy","45","12","33"],["Equity","73","28","30"],["Food systems","14","8","11"],["Governance","124","32","34"],["Growth and development","8","5","8"],["Housing","29","9","20"],["Infrastructure","29","11","16"],["Land use","84","13","36"],["(continued: management, manufacturing, material use, mobility and transportation, natural environment, natural resources, pollution, public health, quality of life, safety, technology, waste, water)","too small to read","",""]],slide:"L2 slide 22"},
  {title:"Environmental challenges faced by cities and their regions (number of cities; two bars per item on the slide)",head:["Challenge","Bar 1","Bar 2"],rows:[["Air pollution","34","34"],["Traffic congestion","33","37"],["Lack/loss of green space","25","22"],["Severe storms and flooding","22","23"],["Stormwater management","21","22"],["Noise pollution","21","22"],["Heat waves","18","17"],["Solid waste disposal","15","14"],["Solid waste processing","12","13"],["Decline of native species/habitats","11","11"],["Water pollution","11","10"],["Sewage treatment and disposal","8","8"],["Forest fires","7","6"],["Water shortages/droughts","6","6"],["Sea level rise","5","5"],["Energy shortages/scarcity","5","3"],["Land/soil erosion; light pollution; ground contamination","4","4"],["Lack/loss of ecologically productive land","3","4"],["Food shortages/access to food","2","2"],["Drinking water shortages; timber, mineral and other resource shortages","1","1 / 0"]],slide:"L2 slide 18"}
 ],
 points:[
  {t:"Where urban growth will happen",d:"The largest population increases will be in small and medium-sized cities; India, China and Nigeria will account for 37% of population growth until 2050. Not all Global South cities are growing (e.g. Maputo), and new types of cities may emerge: eco-cities, 'economic' cities, satellite cities, newly built smart cities, virtual cities, reclaimed cities on water (Weight of Cities 2019).",slide:"L2 slide 4"},
  {t:"Energy since 1950 vs the whole Holocene",d:"“A recent study shows that human energy expenditure since 1950 (~22 zetajoules (ZJ)), particularly related to fossil fuels, exceeds that across the entire prior 11,700 years of the Holocene (~14.6 ZJ)” (Elmqvist et al. 2021, referring to Syvitski et al. 2020, whose figure shows population, energy use and GDP per capita all shooting up together).",slide:"L2 slide 5"},
  {t:"Urban shrinkage as a new challenge",d:"A global map of annual population change at Functional Urban Area level, 2000–2015 (European Commission 2022), shows shrinking FUAs (negative rates) alongside growing ones, notably in Europe and East Asia. The lecturer asks whether shrinkage is a new sustainability challenge.",slide:"L2 slide 7"},
  {t:"Cities are vulnerable",d:"60%+ of cities are on coastlines and urban populations seem increasingly susceptible to air pollution and heat. “The overall proportion of sealed land in Europe has increased by over 6% since 2000. Meanwhile, an estimated 26.9% of urban areas saw a significant (>10%) increase in population living within existing floodplains between 2011 and 2021.” Add entrenched inequality, poverty and violence (e.g. Cape Town) and path-dependent infrastructure systems.",slide:"L2 slide 9"},
  {t:"Bigger cities: richer but more unequal",d:"“Larger cities are generally richer but more unequal than smaller cities. The opportunities that cities bring are unevenly distributed in space, preventing entire neighbourhoods and groups of population from accessing proper health care, good schools, sanitation, piped water, employment opportunities and adequate housing among others” (UN DESA).",slide:"L2 slide 12"},
  {t:"Domestic Material Consumption (definition)",d:"DMC: “A measure of the total amount of materials directly used by an economy and defined as the annual quantity of raw materials extracted from the domestic territory, plus all physical imports, minus all physical exports.” The chart shows aggregate global urban DMC rising steeply to 2050 in every world region, driven by rising incomes (Weight of Cities 2019).",slide:"L2 slide 13"},
  {t:"Urban air pollution",d:"“96% of people living in EU cities were exposed to levels of air pollution by fine particulate matter (PM2.5) above the WHO guideline.” Shown with a UN News item: the WHO warns of rising urban air pollution, with poorer cities most at risk.",slide:"L2 slide 16"},
  {t:"Urbanisation and biodiversity loss",d:"Urbanisation causes biodiversity loss through direct effects (habitat converted to urban land) and indirect effects. A map of projected urban-caused habitat loss 2000–2030 highlights hotspots in the eastern US, south-east China, Brazil and Nigeria.",slide:"L2 slide 17"},
  {t:"Three definitions of urban sustainability",d:"Mega & Pederson (1998): a sustainable city is “one which succeeds in balancing economic, environmental and socio-cultural progress through processes of active citizen participation.” Hamilton et al. (2002): “the process of developing a built environment that meets people’s needs whilst avoiding unacceptable social or environmental impacts.” Wu (2014): “an adaptive process of facilitating and maintaining a virtual cycle between ecosystem services and human well-being through concerted ecological, economic, and social actions in response to changes within and beyond the urban landscape.”",slide:"L2 slide 20"},
  {t:"Hardly any measured city CO₂ data",d:"World Bank (2022): consistently measured emissions estimates exist for only about 80 cities, “only half in developing countries. What’s more, hardly any estimates are based on actual emissions. Most estimates rely on parameters from engineering studies that are applied to survey-based activity measures for transport, energy production, and manufacturing.”",slide:"L2 slide 21"},
  {t:"Local monitoring: Amsterdam and Utrecht",d:"Cities now report on the SDGs themselves through Voluntary Local Reviews (Amsterdam 2022; 'Utrecht and the Global Goals' 2023). Example indicator: Amsterdam's 2019 modal split for trips by residents and visitors: car 29%, bicycle 28%, public transport 25%, walking 16%, moped 2%.",slide:"L2 slide 23"},
  {t:"Tanguay et al. studied 17 cities",d:"The three measurement problems (broad definition, no standard classification of sustainable development indicators, data constraints) come from Tanguay et al. (2010), who studied 17 cities in Europe, Asia and North America.",slide:"L2 slide 24"},
  {t:"Pessimistic view: planning itself is the problem",d:"“As such, spatial planning itself, focused on guiding land use, permitting private developments and building technical infrastructures/public services is not sustainable.” The city also “becomes abstracted from more fundamental processes of socio-economic and socio-ecological change”. Illustration: Asia is home to 99 of the world's 100 most vulnerable cities (Jakarta: pollution, flooding, heatwaves).",slide:"L2 slide 26"},
  {t:"The 'dystopian Anthropocene' (full quote)",d:"“We define a ‘dystopian Anthropocene’ as one that broadly mirrors the present, where the current status quo is maintained into the future with human societies facing rampant inequality, unacceptable social and environmental injustice, economic models and development trajectories focused on growth, law used as a reactive tool to cement the status quo, and environmental ills from human-caused pollution, climate change, and ecosystem degradation unchanged or worse.” (McPhearson et al. 2021)",slide:"L2 slide 27"},
  {t:"Do we live in the Anthropocene?",d:"Term from Paul J. Crutzen (chemist) and Eugene F. Stoermer (biologist); not universally accepted. Proposed start dates: 12–15k years ago (agricultural revolution), 1760 (industrial revolution) or 1945. Human activity has shifted the planet into a fundamentally different (irreversible?) state in biodiversity and bioactivity, land cover, climate and geomorphology, so 'radical' planning shifts must account for complexity (knowledge, institutions, business, behaviour) and couple social, ecological and technological systems.",slide:"L2 slide 28"},
  {t:"Mayors bypassing national governments",d:"Example of the political and organisational optimistic arguments: US mayors (then LA mayor Eric Garcetti, chair of C40) sought to bypass Trump with a direct role at UN climate talks: “If cities are invited to be at the table, I believe that they will help accelerate the work that needs to be done.”",slide:"L2 slide 29"},
  {t:"UN-Habitat: don't vilify cities",d:"World Cities Report 2024 (Cities and Climate Action): “Vilifying cities as producers of greenhouse gas emissions is to fundamentally misunderstand their potential to deliver a more sustainable future for our planet... net zero or low-carbon pathways can be achieved through appropriate climate responsive planning choices.” Compact cities with integrated transport and energy-efficient buildings can be significantly more sustainable than suburban or rural areas.",slide:"L2 slide 30"},
  {t:"Quick wins in transport and buildings",d:"The New Climate Economy: “investments in transport – vehicle efficiency and electrification, modal shift, and urban freight logistics improvements – have a positive NPV under nearly all scenarios, as do the residential buildings measures”. Weight of Cities: if cities were more resource-efficient in transport, commercial buildings and heating/cooling, resource use could fall by about 46–67%.",slide:"L2 slide 31"},
  {t:"Ontological dimensions: kinds of 'sustainable city'",d:"The lecture lists the city models through which urban sustainability is pursued: resilient cities (Rockefeller's 100 Resilient Cities, Cape Town Resilience Strategy, Melbourne's 'Resilient City Foodbowl'), low-carbon cities (City of Cape Town Climate Change Strategy), circular cities (Metabolic Cities Program), green/eco cities and nature-based solutions (blue-green infrastructure in Chinese cities), compact cities (Jenks, Burton & Williams, 'The Compact City: A Sustainable Urban Form?') and the 15-minute city.",slide:"L2 slides 32–36"},
  {t:"15-minute Paris and the Utrecht '10-minute city'",d:"The 15-minute Paris drawing groups daily needs around home: learn, work, share and reuse, stock up, enjoy the outdoors, take care of your health, get around, stay active, eat healthy, be engaged in your community (Nigudkar 2021). Utrecht: “All of this helps us turn Utrecht into the ‘10-minute city’. In our city, everyone and everything you need is close by”, under the banner 'Healthy Urban Living for Everyone'.",slide:"L2 slides 37–38"},
  {t:"Settlement types × lifestyle groups",d:"A heatmap (Baiocchi et al. 2015) cross-tabulates human settlement types (from the regression tree) with ONS lifestyle groups (e.g. rural economies, young city professionals, multicultural inner city, suburbia), showing that low-carbon dense settlement types are dominated by specific social groups: urban form and who lives there go together.",slide:"L2 slide 41"},
  {t:"MDGs: Goal 7 targets",d:"MDG Goal 7 (ensure environmental sustainability): Target 7C, halve by 2015 the proportion without sustainable access to safe drinking water and basic sanitation (indicators split urban and rural); Target 7D, by 2020 a significant improvement in the lives of at least 100 million slum-dwellers (indicator: proportion of urban population living in slums).",slide:"L2 slide 48"},
  {t:"MDGs → SDGs: three shifts",d:"(a) from the Global South to universal goals; (b) much more emphasis on social values and ecological limits; (c) a standalone urban goal/agenda (SDG 11). “The SDGs provide a comprehensive and integrated framework of 17 goals, 169 targets and 231 unique indicators designed to guide progress on sustainable development to 2030” (Wiedmann and Allen 2021).",slide:"L2 slides 48–49"},
  {t:"SDG dashboard for OECD countries",d:"A dashboard colours each OECD country's progress on all 17 SDGs (achieved, challenges remain, significant challenges, major challenges). The Netherlands, highlighted, shows major challenges on several goals too: rich countries are far from 'sustainable'.",slide:"L2 slide 50"},
  {t:"Copenhagen's carbon-neutral 2025 goal fails",d:"Illustrating Krähmer's degrowth critique: the headline “Copenhagen’s dream of being carbon neutral by 2025 goes up in smoke” (Euractiv 2022), because the capital failed to reach its target after its iconic waste incinerator (Amager Bakke / CopenHill, with a ski slope on top) did not meet CO₂ capture requirements for state support.",slide:"L2 slide 51"},
  {t:"Conclusions: what planning can do",d:"Planning is key to achieving more sustainable cities through vision-setting, urban form, encouraging institutional change and tackling political conflicts and trade-offs. Open questions: do growth, externalisation and efficiency make absolute sustainability impossible? Is a new, relative conception of sustainability needed? “Should we abandon growth completely?”",slide:"L2 slide 52"}
 ]},
 p3:{figs:[
  {title:"Ten traits of wicked problems",svg:`<svg viewBox="0 0 620 300" role="img" aria-label="Characteristics of wicked problems after Rittel and Webber"><g font-size="11">
<circle cx="310" cy="150" r="56" class="bxa"/><text x="310" y="146" text-anchor="middle" font-weight="700" font-size="13">Wicked</text><text x="310" y="163" text-anchor="middle" font-weight="700" font-size="13">problems</text>
<rect x="215" y="10" width="190" height="34" rx="8" class="bxw"/><text x="310" y="24" text-anchor="middle">Problems are never</text><text x="310" y="38" text-anchor="middle">completely solved</text>
<rect x="420" y="40" width="190" height="26" rx="8" class="bxw"/><text x="515" y="57" text-anchor="middle">Every problem is unique</text>
<rect x="430" y="80" width="180" height="26" rx="8" class="bxw"/><text x="520" y="97" text-anchor="middle">No clear definition</text>
<rect x="430" y="120" width="180" height="34" rx="8" class="bxw"/><text x="520" y="134" text-anchor="middle">Multi-causal, multi-</text><text x="520" y="148" text-anchor="middle">scalar, interconnected</text>
<rect x="430" y="168" width="180" height="34" rx="8" class="bxw"/><text x="520" y="182" text-anchor="middle">Multiple stakeholders,</text><text x="520" y="196" text-anchor="middle">conflicting agendas</text>
<rect x="400" y="222" width="200" height="34" rx="8" class="bxw"/><text x="500" y="236" text-anchor="middle">Straddle organisational</text><text x="500" y="250" text-anchor="middle">and disciplinary bounds</text>
<rect x="215" y="256" width="190" height="34" rx="8" class="bxw"/><text x="310" y="270" text-anchor="middle">Every wicked problem</text><text x="310" y="284" text-anchor="middle">is connected to others</text>
<rect x="20" y="222" width="200" height="34" rx="8" class="bxw"/><text x="120" y="236" text-anchor="middle">Every solution ramifies</text><text x="120" y="250" text-anchor="middle">throughout the system</text>
<rect x="10" y="150" width="190" height="34" rx="8" class="bxw"/><text x="105" y="164" text-anchor="middle">Solutions not right/wrong,</text><text x="105" y="178" text-anchor="middle">but better/worse</text>
<rect x="10" y="80" width="190" height="34" rx="8" class="bxw"/><text x="105" y="94" text-anchor="middle">Long time to evaluate</text><text x="105" y="108" text-anchor="middle">solutions</text>
</g></svg>`,cap:"Characteristics of wicked problems, based upon Rittel and Webber (1973), shown next to Ackoff's 'mess' quote.",slide:"L3 slide 7"},
  {title:"Tame, complex and wicked problems",svg:`<svg viewBox="0 0 620 290" role="img" aria-label="Complexity versus stakeholder difficulties grid"><defs><marker id="sl5grid" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="250" y="20" width="110" height="60" class="bxi" opacity="0.8"/><rect x="360" y="20" width="110" height="60" class="bxi" opacity="0.4"/><rect x="470" y="20" width="110" height="60" class="bxa"/>
<rect x="250" y="80" width="110" height="60" class="bxi" opacity="0.8"/><rect x="360" y="80" width="110" height="60" class="bxw"/><rect x="470" y="80" width="110" height="60" class="bxi" opacity="0.4"/>
<rect x="250" y="140" width="110" height="60" class="bxg"/><rect x="360" y="140" width="110" height="60" class="bxi" opacity="0.4"/><rect x="470" y="140" width="110" height="60" class="bxi" opacity="0.8"/>
<text x="525" y="55" text-anchor="middle" font-weight="700">Wicked</text><text x="415" y="115" text-anchor="middle" font-weight="700">Complex</text><text x="305" y="175" text-anchor="middle" font-weight="700">Tame</text>
<path d="M250 200 L250 14" class="ln" marker-end="url(#sl5grid)"/><path d="M250 200 L600 200" class="ln" marker-end="url(#sl5grid)"/>
<text x="240" y="40" text-anchor="end">Conflict over definition</text><text x="240" y="54" text-anchor="end">of problem and solutions</text>
<text x="240" y="106" text-anchor="end">Problem defined, but</text><text x="240" y="120" text-anchor="end">solution not clear</text>
<text x="240" y="166" text-anchor="end">Both problem and</text><text x="240" y="180" text-anchor="end">solution defined</text>
<text x="20" y="16" class="mut">Complexity ↑</text>
<text x="305" y="220" text-anchor="middle">Cooperative or</text><text x="305" y="234" text-anchor="middle">indifferent</text>
<text x="415" y="220" text-anchor="middle">Many parties, each</text><text x="415" y="234" text-anchor="middle">with some knowledge</text>
<text x="525" y="220" text-anchor="middle">Many parties,</text><text x="525" y="234" text-anchor="middle">conflicting values</text>
<text x="425" y="270" text-anchor="middle" class="mut">Stakeholder / institutional difficulties →</text>
</g></svg>`,cap:"DeFries & Nagendra (2017): problems become wicked when high complexity (conflict over problem and solution) meets many parties with conflicting values and interests.",slide:"L3 slide 9"},
  {title:"Three routes around Campbell's triangle",svg:`<svg viewBox="0 0 620 300" role="img" aria-label="Three resolution routes on the planner's triangle"><defs><marker id="sl5tri" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="245" y="20" width="130" height="40" rx="8" class="bxi"/><text x="310" y="37" text-anchor="middle" font-weight="700">Equity,</text><text x="310" y="52" text-anchor="middle" font-weight="700">social justice</text>
<rect x="120" y="200" width="130" height="40" rx="8" class="bxw"/><text x="185" y="217" text-anchor="middle" font-weight="700">Economic</text><text x="185" y="232" text-anchor="middle" font-weight="700">development</text>
<rect x="370" y="200" width="130" height="40" rx="8" class="bxg"/><text x="435" y="217" text-anchor="middle" font-weight="700">Environmental</text><text x="435" y="232" text-anchor="middle" font-weight="700">protection</text>
<path d="M280 60 L215 196" class="ln" marker-end="url(#sl5tri)"/><path d="M215 196 L280 60" class="ln" marker-end="url(#sl5tri)"/>
<path d="M340 60 L405 196" class="ln" marker-end="url(#sl5tri)"/><path d="M405 196 L340 60" class="ln" marker-end="url(#sl5tri)"/>
<path d="M250 220 L366 220" class="ln" marker-end="url(#sl5tri)"/><path d="M370 220 L254 220" class="ln" marker-end="url(#sl5tri)"/>
<rect x="250" y="105" width="120" height="62" rx="20" class="bxg" opacity="0.7"/><text x="310" y="124" text-anchor="middle" font-size="10">sustainability as the</text><text x="310" y="138" text-anchor="middle" font-size="10">ongoing (never-ending)</text><text x="310" y="152" text-anchor="middle" font-size="10">process of resolving</text><text x="310" y="164" text-anchor="middle" font-size="10">the three conflicts</text>
<text x="200" y="125" text-anchor="end" class="acc" font-weight="700">1. Social welfare state</text><text x="200" y="140" text-anchor="end">'redistribution through growth;</text><text x="200" y="154" text-anchor="end">growth through equity'</text>
<text x="420" y="125" class="acc" font-weight="700">3. Environmental justice</text><text x="420" y="140">'achieve equity through</text><text x="420" y="154">environmentalism'</text>
<text x="310" y="262" text-anchor="middle" class="acc" font-weight="700">2. Environmental regulation / resource management</text><text x="310" y="278" text-anchor="middle">'economic development through resource management and conservation'</text>
<text x="215" y="172" text-anchor="end" class="mut">property</text><text x="405" y="172" class="mut">development</text><text x="310" y="214" text-anchor="middle" class="mut">resource</text>
</g></svg>`,cap:"Each side of the triangle has a historical resolution strategy: the social welfare state (property conflict), environmental regulation (resource conflict) and environmental justice (development conflict). The planner types sit at the corners: equity planner, economic development planner, environmental planner.",slide:"L3 slides 13, 17"},
  {title:"Health gains of green and blue space",svg:`<svg viewBox="0 0 620 260" role="img" aria-label="Health benefits of living near green and blue spaces"><defs><marker id="sl5eea" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="210" y="14" width="200" height="40" rx="8" class="bxg"/><text x="310" y="31" text-anchor="middle" font-weight="700">Living, working, learning</text><text x="310" y="46" text-anchor="middle" font-weight="700">near green/blue space</text>
<rect x="20" y="80" width="160" height="30" rx="8" class="bxi"/><text x="100" y="99" text-anchor="middle">Improved immune function</text>
<rect x="20" y="170" width="160" height="30" rx="8" class="bxi"/><text x="100" y="189" text-anchor="middle">Improved social cohesion</text>
<rect x="440" y="80" width="160" height="30" rx="8" class="bxi"/><text x="520" y="99" text-anchor="middle">More physical activity</text>
<rect x="440" y="170" width="160" height="30" rx="8" class="bxi"/><text x="520" y="183" text-anchor="middle">Relaxation and</text><text x="520" y="196" text-anchor="middle">restoration</text>
<rect x="215" y="70" width="190" height="180" rx="8" class="bx"/>
<text x="310" y="92" text-anchor="middle">Better mental health</text><text x="310" y="118" text-anchor="middle">Better cognitive function</text><text x="310" y="144" text-anchor="middle">Less cardiovascular illness</text><text x="310" y="170" text-anchor="middle">Less type 2 diabetes</text><text x="310" y="196" text-anchor="middle">Reduced mortality</text><text x="310" y="222" text-anchor="middle">Better maternal and</text><text x="310" y="236" text-anchor="middle">foetal outcomes</text>
<path d="M180 95 L211 120" class="ln" marker-end="url(#sl5eea)"/><path d="M180 185 L211 165" class="ln" marker-end="url(#sl5eea)"/><path d="M440 95 L409 120" class="ln" marker-end="url(#sl5eea)"/><path d="M440 185 L409 165" class="ln" marker-end="url(#sl5eea)"/>
</g></svg>`,cap:"EEA (2022): pathways (immune function, social cohesion, physical activity, restoration) through which green and blue space improves health. This is the 'gain' side of the greening dilemma.",slide:"L3 slide 18"},
  {title:"BeltLine: extra home-value growth by segment",svg:`<svg viewBox="0 0 620 240" role="img" aria-label="Cumulative home value appreciation 2011 to 2015 within half a mile of BeltLine segments"><g font-size="11">
<path d="M60 200 L600 200" class="ln"/>
<text x="54" y="204" text-anchor="end" class="mut">0%</text><text x="54" y="144" text-anchor="end" class="mut">20%</text><text x="54" y="84" text-anchor="end" class="mut">40%</text>
<path d="M60 140 L600 140 M60 80 L600 80" class="ln" stroke-dasharray="3 4" opacity="0.5"/>
<rect x="80" y="39" width="50" height="161" class="acc"/><rect x="132" y="103" width="50" height="97" class="fm"/><text x="105" y="33" text-anchor="middle" font-weight="700">53.7%</text><text x="157" y="97" text-anchor="middle">32.2%</text><text x="131" y="218" text-anchor="middle" font-weight="700">NW</text>
<rect x="215" y="50" width="50" height="150" class="acc"/><rect x="267" y="103" width="50" height="97" class="fm"/><text x="240" y="44" text-anchor="middle" font-weight="700">50.1%</text><text x="292" y="97" text-anchor="middle">32.2%</text><text x="266" y="218" text-anchor="middle" font-weight="700">NE</text>
<rect x="350" y="24" width="50" height="176" class="acc"/><rect x="402" y="103" width="50" height="97" class="fm"/><text x="375" y="18" text-anchor="middle" font-weight="700">58.8%</text><text x="427" y="97" text-anchor="middle">32.2%</text><text x="401" y="218" text-anchor="middle" font-weight="700">SW</text>
<rect x="485" y="45" width="50" height="155" class="acc"/><rect x="537" y="103" width="50" height="97" class="fm"/><text x="510" y="39" text-anchor="middle" font-weight="700">51.5%</text><text x="562" y="97" text-anchor="middle">32.2%</text><text x="536" y="218" text-anchor="middle" font-weight="700">SE</text>
<rect x="160" y="226" width="12" height="10" class="acc"/><text x="178" y="235">within ½ mile of BeltLine</text><rect x="360" y="226" width="12" height="10" class="fm"/><text x="378" y="235">not within ½ mile</text>
</g></svg>`,cap:"Immergluck & Balan (2018), Figure 4: cumulative expected home-price change 2011–2015 near each BeltLine segment vs elsewhere in Atlanta (32.2%).",slide:"L3 slide 28"},
  {title:"How central is greening to gentrification?",svg:`<svg viewBox="0 0 620 180" role="img" aria-label="Role of greening in gentrification across 17 cities"><g font-size="12">
<text x="20" y="20" class="mut" font-size="11">Anguelovski et al. 2022: role of greening in 17 cities</text>
<rect x="150" y="38" width="240" height="30" rx="6" class="bxa"/><text x="140" y="58" text-anchor="end" font-weight="700">Lead</text><text x="400" y="58">8 cities: standout explainer</text>
<rect x="150" y="83" width="180" height="30" rx="6" class="bxw"/><text x="140" y="103" text-anchor="end" font-weight="700">Integrated</text><text x="340" y="103">6: explains equally (with growth</text><text x="340" y="117" font-size="11">corridors, transit-oriented development)</text>
<rect x="150" y="128" width="90" height="30" rx="6" class="bx"/><text x="140" y="148" text-anchor="end" font-weight="700">Subsidiary</text><text x="250" y="148">3: relevant, secondary role</text>
</g></svg>`,cap:"Greening is the lead driver of gentrification in 8 of 17 North American and European cities, an integrated driver in 6 and subsidiary in 3.",slide:"L3 slide 30"}
 ],
 tables:[
  {title:"Three perspectives on planning and urban sustainability",head:["Perspective","Central question","Sustainability is understood as…","Role of the planner","Typical response"],rows:[["Normative","What should a sustainable city look like?","A desirable condition or set of goals","Goal setter / implementer","Set targets, indicators and plans to move cities towards sustainability"],["Dilemma-based","How can we reconcile competing objectives?","A balance among competing environmental, economic and social objectives","Mediator / negotiator","Identify trade-offs, negotiate interests, build compromises"],["Critical","Why are cities organised in ways that continually produce unsustainability?","A contested political and socio-economic condition","Critic / transformative actor","Question growth, power, inequality, consumption and the assumptions underlying conventional planning"]],slide:"L3 slides 2–3"},
  {title:"Normative approach: five principles (McPhearson et al. 2021)",head:["Principle","What it means on the slide"],rows:[["1. Rethinking growth","From GDP to ecologically based business models where society/nature is at the core of 'value'; degrowth"],["2. Rethinking efficiency","Non-exceedance of critical environmental thresholds; socially and ecologically beneficial use"],["3. Rethinking the state","Strong, proactive state: 'transformative governance' (obligations towards earth systems, solving conflicts, building capacity, giving societal direction); polycentricity: recognising power across actors and levels"],["4. Rethinking the commons","Encourage commons (nature-based, cultural, knowledge, ownership, digital); 'generation and qualitative improvement of new and existing public urban spaces'"],["5. Rethinking justice","Transform systems (social, climate, political) that cause disproportionate impacts and injustices; reciprocity and care for humans and non-human entities (new rights); consider alternative knowledges"]],slide:"L3 slide 4"},
  {title:"Examples of wicked problems in ecosystem management (DeFries & Nagendra 2017)",head:["Management problem","Example question","Reasons for wickedness"],rows:[["Control of infectious disease","Where and when will outbreaks occur? Will vaccinations and other control strategies be effective?","Nonlinear population dynamics of vectors and hosts; feedbacks between disease and human behaviour"],["Non-point source pollution","Which sources (agricultural or urban runoff) and pollutants should managers target to improve water quality?","Complex causality from multiple sources; long lag times in system response"],["Fire management at urban–wildland interfaces","Should managers suppress fires?","Unintended consequences of increased fuel loads and fire severity"],["Conservation of biodiversity","How much and where should places be protected from other sectors (agriculture, mining, roads, fishing)? How to protect species beyond protected areas? How to rectify inequities for communities that lose access to resources?","Differences in values; mismatch of ecological and administrative boundaries; divergent stakeholder objectives"]],slide:"L3 slide 10"},
  {title:"Weighing trade-offs of urban greening",head:["Environmental and health gains","Social and economic costs"],rows:[["Reduced urban heat-island effect and improved air quality","Rising land values, rents and property taxes"],["Stormwater management and climate resilience","Direct displacement (eviction, unaffordability)"],["Recreational access and mental/physical health benefits","Indirect displacement of social networks and culture; increased social isolation of those living in green areas"],["Progress toward municipal sustainability and climate targets","Unequal distribution of amenity benefits by race and class"],["Increased biodiversity and ecological connectivity","Erosion of trust between residents and planners"]],slide:"L3 slide 29"},
  {title:"Anti-displacement planning: fostering vs taming green gentrification",head:["Side","Fostering (▲)","Taming (▼)"],rows:[["Resource side","District mayors reinforcing demands for greenery by better-off residents; subsidy schemes prioritising greening in areas dominated by private rental housing","Subsidies prioritise dense/heat-exposed districts; city-wide greening budget allocated by greening responsibilities instead of district wealth; large municipal and limited-profit housing stock buffers displacement; new subsidised social housing on central brownfields reduces green-led rent pressures"],["Demand side","Better-off civil society groups advocate greening in participatory channels; broad demand for greenery near housing across all groups","District mayors override greening proposals when worried about social upgrading; tenants refrain from demanding greening for fear of rent increases or displacement"],["Supply side","Some district mayors pursue greening to attract better-off residents; some landlords use temporary contracts and location surcharges to capitalise on proximity to new green features","Some district mayors intentionally refrain from greening to avoid fuelling social upgrading; reference-value rent regulation plus widespread social housing limit immediate green-led displacement"]],slide:"L3 slide 32"},
  {title:"Effects of community land trusts on gentrification",head:["Negative effect of gentrification","CLTs' counteracting effect","Gentrifying neighbourhood","Average neighbourhood"],rows:[["Displacement","Increase racial diversity","+, mixed","+, consistent"],["Displacement","Maintain middle-class ratio","+, consistent","+, mixed"],["Displacement","Stabilise income level","+, mixed","+, consistent"],["Displacement","Maintain education level","+, consistent","+, mixed"],["Displacement","Increase length of residence","− (negative)","none"],["Displacement","Decrease age fluctuation","none","none"],["Lower affordability","Increase affordability","+, consistent","+, consistent"],["Lower affordability","Decrease owner-occupied housing rate","+, consistent","+, mixed"],["Skyrocketing property prices","Stabilise housing price","+, mixed","− (negative)"]],slide:"L3 slide 33"}
 ],
 points:[
  {t:"Khakee: planning is dilemmatic",d:"“Planning is nearly always dilemmatic. Defined as the application of knowledge to a set of future actions, planning is dilemmatic because the future is wrought with quantitative and qualitative uncertainties as well as surprise events” (Khakee 2020).",slide:"L3 slide 5"},
  {t:"Rittel & Webber: the easy problems are gone",d:"From 'Dilemmas in a General Theory of Planning' (1973): the “professional's job was once seen as solving an assortment of problems that appeared to be definable, understandable and consensual… these relatively easy problems have been dealt with, we have been turning our attention to others that are much more stubborn”.",slide:"L3 slide 6"},
  {t:"Ackoff's 'mess' (full quote)",d:"“Every problem interacts with other problems and is therefore part of a system of interrelated problems, a system of problems . . . I choose to call such a system a mess . . . The solution to a mess can seldom be obtained by independently solving each of the problems of which it is composed . . . Efforts to deal separately with such aspects of urban life as transportation, health, crime, and education seem to aggravate the total situation” (Ackoff 1974, p. 21).",slide:"L3 slide 7"},
  {t:"Dilemmas paradigm: no 'perfect' solutions",d:"Your role as a planner is not to find 'perfect' solutions. Accept that we live largely in capitalist systems, which create 'conditions of unceasing growth, upheaval, and disruption': the internal logic of capitalism is not to 'sustain' anything.",slide:"L3 slide 11"},
  {t:"Campbell's ideal vs planning reality",d:"“In an ideal world, planners serve the broader public interest by holistically balancing and harmonizing three goals: to enable economic growth and prosperity, to distribute resources fairly, and in this process not to degrade ecosystems.” But realities in practice are often restrictive and guided by the narrower interests of their clients (authorities and bureaucracies). Campbell is Associate Professor of Urban Planning at the University of Michigan.",slide:"L3 slides 12–13"},
  {t:"Property conflict: the property contradiction",d:"Economic growth/capitalist accumulation ↔ equity. Competing claims on and uses of property: the private sector simultaneously resists and needs social intervention, given the intrinsically contradictory nature of property; an ambivalent relationship between private interests and the public good.",slide:"L3 slide 14"},
  {t:"Resource conflict: Campbell's examples",d:"Campbell's list of resource conflicts: “water politics in California, timber versus the spotted owl in the Pacific Northwest, tropical deforestation in Brazil, park planning in the Adirondacks, greenbelt planning in Britain”.",slide:"L3 slide 15"},
  {t:"Development conflict: global scale",d:"“The most allusive [elusive] conflict”: global efforts to protect the environment might prevent measures to reduce poverty and address inequalities between rich and poor nations; elite environmentalism breeds political mistrust.",slide:"L3 slide 16"},
  {t:"Before and after: greening in Utrecht",d:"Photo pairs show greening transformations: a car park turned into a park, and Utrecht's Catharijnesingel: a motorway in 1982, a canal again 'now'. These are the kind of projects whose success can raise land values.",slide:"L3 slide 19"},
  {t:"Definition of green gentrification",d:"“Green gentrification” describes how creating or upgrading urban environmental amenities (parks, greenways, eco-districts) “can produce and reinforce environmental privilege, concentrating clean, green, healthy space among those who can afford to live near it” (synthesised from Gould & Lewis 2017). A 'gentrified urban area starterpack' meme (coffee chains, joggers, small dogs, street art) opens the topic.",slide:"L3 slides 20–21"},
  {t:"Gowanus Canal: 'Venice of Brooklyn'?",d:"Brooklyn Daily Eagle (2017): the Gowanus Canal, “notorious for its toxic waters”, is advertised as the future Venice of Brooklyn with a state-of-the-art park planned by the Gowanus Canal Conservancy, an example of clean-up as an amenity that attracts investment.",slide:"L3 slide 22"},
  {t:"Treadmill of production: success = displacement",d:"Gould and Lewis (2017) place greening in a broader “treadmill of production”: growth coalitions of developers, city agencies and boosters use green infrastructure to attract capital and higher-income residents, so rising land values are often the intended signal of 'success'. The crux: “the metrics that make a greening project look successful (rising property values, new investment) are frequently the same metrics that predict displacement.”",slide:"L3 slide 23"},
  {t:"Barcelona: method and link to superblocks",d:"18 new green spaces in socially vulnerable neighbourhoods (1990s–2000s) were part of a citywide regeneration strategy and a precursor to today's superblocks (superilles). Anguelovski, Connolly, Masip & Pearsall (2018) tracked six socio-demographic indicators around all 18 sites. Lesson: green gentrification “depends on a neighborhood's location and pre-existing market pressure, which is precisely why it remains a planning choice rather than an inevitability.”",slide:"L3 slide 24"},
  {t:"Atlanta BeltLine: the project and the warning",d:"A 22-mile loop of trails, parks and planned streetcar lines on a disused freight-rail corridor connecting 45 neighbourhoods, launched as a flagship of sustainable transit-oriented redevelopment. Immergluck & Balan used regression analysis of home sales before and after segments opened (2011–2015) and warn that without affordable-housing safeguards it risks driving exclusion in neighbourhoods that are disproportionately lower-income and Black.",slide:"L3 slides 25–27"},
  {t:"Nuances: lag times, proximity, regions",d:"Green gentrification often follows proximity to new green space, often with longer lag times, suggesting location and 'design' effects. It is more prevalent in North America but still evident in Europe (Anguelovski et al. 2022, map of 17 cities incl. Barcelona, Amsterdam, Copenhagen, Lyon, Vancouver, Atlanta).",slide:"L3 slide 30"},
  {t:"'Just green enough': how",d:"Wolch, Byrne & Newell (2014) scale greening to existing residents' needs: modest, community-directed improvements rather than flagship projects. Mind that the quantity of greenspace has consequences; avoid beautification and design-oriented thinking; deeper participation with local residents; greening that does not cause gentrification (book: Curran & Hamilton, 'Just Green Enough').",slide:"L3 slide 31"},
  {t:"Discussion questions (exam-style)",d:"Which values do you prioritise: more green areas or addressing social inequalities? Should planners limit exploitation of ecosystems for housing (e.g. waterfront developments)? Should planners prioritise compact development to reduce sprawl, even if this means less green space and biodiversity in the city? Should planners accept green gentrification as a trade-off, since some people benefit, possibly over the longer term?",slide:"L3 slide 34"}
 ]},
 p4:{figs:[
  {title:"House of Thorbecke: coordination scheme",svg:`<svg viewBox="0 0 620 280" role="img" aria-label="Vertical and horizontal coordination between national, provincial and local levels"><defs><marker id="sl5thb" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="12">
<rect x="100" y="40" width="420" height="70" rx="8" class="bxi" opacity="0.5"/><rect x="100" y="110" width="420" height="70" rx="8" class="bxi" opacity="0.75"/><rect x="100" y="180" width="420" height="70" rx="8" class="bxi"/>
<text x="508" y="80" text-anchor="end" font-weight="700">national</text><text x="508" y="150" text-anchor="end" font-weight="700">provincial</text><text x="508" y="220" text-anchor="end" font-weight="700">local</text>
<rect x="120" y="48" width="150" height="30" rx="6" class="bx"/><text x="195" y="68" text-anchor="middle">DG Spatial Planning</text>
<rect x="120" y="212" width="250" height="30" rx="6" class="bx"/><text x="245" y="232" text-anchor="middle">342 municipalities (1-1-2024)</text>
<path d="M160 78 L160 208" class="ln" stroke-width="2" marker-end="url(#sl5thb)"/><path d="M240 210 L240 82" class="ln" stroke-width="2" marker-end="url(#sl5thb)"/>
<text x="152" y="150" text-anchor="end" font-size="11">top-down</text><text x="248" y="150" font-size="11">bottom-up</text>
<path d="M60 250 L60 34" class="ln" marker-end="url(#sl5thb)"/><path d="M60 34 L60 250" class="ln" marker-end="url(#sl5thb)"/><text x="50" y="145" text-anchor="middle" transform="rotate(-90 50 145)" font-weight="700">vertical coordination</text>
<path d="M100 22 L520 22" class="ln" marker-end="url(#sl5thb)"/><path d="M520 22 L100 22" class="ln" marker-end="url(#sl5thb)"/><text x="310" y="16" text-anchor="middle" font-weight="700">horizontal coordination</text>
</g></svg>`,cap:"Dutch coordination scheme: top-down and bottom-up vertical coordination between national, provincial and local government, plus horizontal coordination within each level.",slide:"L4 slides 10–11"},
  {title:"Stages in land and real estate development",svg:`<svg viewBox="0 0 620 300" role="img" aria-label="Land value rises from alternative use through re-zoning, land development and construction"><defs><marker id="sl5land" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" class="fm"/></marker></defs><g font-size="11">
<rect x="40" y="240" width="160" height="34" rx="8" class="bxg"/><text x="120" y="261" text-anchor="middle">Initial / alternative use</text>
<rect x="40" y="170" width="160" height="34" rx="8" class="bxg"/><text x="120" y="191" text-anchor="middle">Developable land</text>
<rect x="40" y="100" width="160" height="34" rx="8" class="bxw"/><text x="120" y="121" text-anchor="middle">Developed land</text>
<rect x="40" y="30" width="160" height="34" rx="8" class="bxi"/><text x="120" y="51" text-anchor="middle">New real estate</text>
<path d="M120 240 L120 208" class="ln" marker-end="url(#sl5land)"/><path d="M120 170 L120 138" class="ln" marker-end="url(#sl5land)"/><path d="M120 100 L120 68" class="ln" marker-end="url(#sl5land)"/>
<text x="128" y="228">re-zoning</text><text x="128" y="158">land development</text><text x="128" y="88">construction</text>
<rect x="340" y="30" width="70" height="244" class="fi" opacity="0.35"/>
<rect x="340" y="30" width="70" height="80" class="fi"/><rect x="340" y="110" width="70" height="80" class="fi" opacity="0.65"/><rect x="340" y="190" width="70" height="72" class="fi" opacity="0.35"/><rect x="340" y="262" width="70" height="12" class="fw"/>
<path d="M200 47 L336 32" class="ln" stroke-dasharray="3 3"/><path d="M200 117 L336 110" class="ln" stroke-dasharray="3 3"/><path d="M200 187 L336 190" class="ln" stroke-dasharray="3 3"/><path d="M200 257 L336 268" class="ln" stroke-dasharray="3 3"/>
<path d="M430 34 L430 106" class="accs" stroke-width="2" marker-end="url(#sl5land)"/><text x="440" y="74">− construction costs</text>
<path d="M430 114 L430 186" class="accs" stroke-width="2" marker-end="url(#sl5land)"/><text x="440" y="150">− land development costs</text>
<text x="440" y="226" font-weight="700">surplus / land rent</text><text x="440" y="242" class="mut">value gained by re-zoning</text>
<text x="375" y="22" text-anchor="middle" class="mut">Value</text>
</g></svg>`,cap:"Residual land value: the value of new real estate minus construction and land development costs leaves a surplus (land rent) above the initial use, created mainly by re-zoning. This is what active land policy tries to capture.",slide:"L4 slide 22"}
 ],
 tables:[
  {title:"Roles of government levels in Dutch planning",head:["Level","Spatial role","Time horizon","Type of planning"],rows:[["National","Strategic choices (e.g. mainports) and equal distribution of resources","Long term (>10 years), macro level","Strategic"],["Provinces","Spatial visions; translating national policies ('search areas', 'provincial puzzles'); under the Omgevingswet stronger 'area managers'","Medium term (5–10 years), meso level","Tactical"],["Municipalities","Legally binding land-use zoning plans (now Omgevingsplan), negotiations, solving problems","Short term (<5 years), micro level","Operational"]],slide:"L4 slides 12–13, 26"},
  {title:"Municipal intervention strategies: a balancing act",head:["Strategy","Position","Promise","Risk"],rows:[["Informal, open planning ('polderen')","Alongside the system","Co-creation and conflict reduction","Tokenism and unequal power relations"],["Active land policy","Outside: municipality as private stakeholder","Control over land development + financing","Dubious 'hats' and financial risks"],["Public land instruments (pre-emption, expropriation, leasehold, Omgevingsplan)","Inside: municipality as public stakeholder","Legal certainty and legitimacy","Rigidity and lengthy procedures"]],slide:"L4 slides 14, 30"},
  {title:"Omgevingswet: instruments and who uses them",head:["Instrument","Who","What it does"],rows:[["Omgevingsvisie (environmental vision)","Every municipality (obligatory), also provinces and state","Strategic, long-term vision integrating all spatial interests"],["Omgevingsplan (environmental plan; was bestemmingsplan)","Municipality","Central, comprehensive articulation of how space is allocated and regulated"],["Omgevingsverordening (environmental ordinance)","Province","Direct provincial rules besides the land-use plan"],["Projectbesluit (project decision)","Province or ministry","Direct local intervention by higher government ('they can make use of this')"],["AMvB (national rules)","Ministry","National general rules"]],slide:"L4 slides 25–27"}
 ],
 points:[
  {t:"Planning as a public activity (definition)",d:"Planning is part of the executive branch (trias politica, next to legislative and judicial), implements planning law and is controlled by/in court. Definition: “the systematic preparation of policy-making and executive actions that are aimed at consciously intervening in spatial order and at organizing these interventions”. Because government acts in public and private space for 'the public good', the formal planning system matters for the legitimacy of spatial interventions.",slide:"L4 slides 6–7"},
  {t:"Art. 21 of the Constitution (quote)",d:"“The care of the government focuses on the habitability of the land and the protection and improvement of the living environment”, translated into the Environment and Spatial Planning Act (Omgevingswet).",slide:"L4 slide 7"},
  {t:"History in one slide",d:"Traditionally a strong (?) national government; influence of spatial planning concepts and doctrines; aimed at increasing spatial quality. Pendulum movements: beyond blueprint planning and the 'makeable society', beyond entrepreneurial and participatory planning, but neither is gone. “‘Involving the public’ will not save the world – regardless of the obligation in the new spatial planning act.”",slide:"L4 slide 9"},
  {t:"Decentralised unitary state",d:"Napoleonic tradition (top-down rules) combined with Thorbecke's (1848) decentralised unitary state: only partial autonomy of lower governments (principle of equivalence; egalitarianism). Multi-level dynamics are complex and likely not eased by the Omgevingswet.",slide:"L4 slides 10, 12"},
  {t:"Open planning: from inspraak to interactive governance",d:"Involve key stakeholders as early as possible; actors have influence (from government to governance); joint solutions + implementation = support ('draagvlak'). Participation means interactive governance instead of 'just' voicing concerns at council meetings ('inspraak'). Cf. Healey (1995): the communicative turn in planning.",slide:"L4 slide 17"},
  {t:"Open planning: the informal comes first",d:"The primacy of the informal trajectory; effectiveness and legitimacy matter; ambitious and intervention-oriented, in contrast to 'permit-planning' that only limits negative external effects. Paradox with the heavily formalised/legalised Dutch system: the formal process comes 'towards the end', with planning law as 'codification' of earlier informal agreements.",slide:"L4 slide 18"},
  {t:"Extra-legal ('buitenwettelijk') coordination",d:"In practice coordination runs through informal networks of actors organised around shared interests (governance), multi-level and multi-sectoral. This extra-legal structure has become more common under the Omgevingswet. Extra-legal means not illegal, but also not codified in law (plans, agreements, covenants).",slide:"L4 slide 19"},
  {t:"Ricardo: price determines rent",d:"Active land policy starts from land price and land value: function determines price, “price follows the product”. “The price of corn is not high because the land rent paid is high, but the high rent is paid because the price of corn is high” (Ricardo 1817). Active land policy = government intervention in the land market via public or private land instruments.",slide:"L4 slide 21"},
  {t:"VINEX to NOVEX: details",d:"Strategic greenfield housing locations; municipalities buy up, service and sell land, often in PPPs; land speculators and free riders play a role. The 'double hat problem': the municipality is both regulator and land developer. It only works well in rising markets; in the 2008–2010 collapse municipalities went (near) bankrupt through active land policy, and “now: the same story all over again (example Rijnenburg)”.",slide:"L4 slide 23"},
  {t:"Omgevingswet goal (quote)",d:"“With a view to sustainable development, the habitability of the country, and the protection and improvement of the living environment, aimed at coherently: (a) achieving and maintaining a safe and healthy physical living environment and good environmental quality, also due to the intrinsic value of nature; and (b) efficiently managing, using, and developing the physical living environment to meet societal needs.” Wider than Art. 21: 'everyone is required to' care.",slide:"L4 slide 25"},
  {t:"Complementary task allocation (ETFAL)",d:"Thorbecke's coordination scheme remains (strategic, tactical, operational roles), but depending on the task, levels may act 'complementary' to solve problems at 'the most suitable level': 'a balanced allocation of functions to locations' (ETFAL). Provinces get a stronger role as 'area managers', and province and state can intervene locally through a project decision.",slide:"L4 slide 26"},
  {t:"Pre-emption, expropriation, leasehold: experiences",d:"Voorkeursrecht and onteigening are strong regulatory tools; erfpacht is potentially a softer option. Main goal: strategic control over future allocation of functions. Experiences differ: combating NIMBYism vs detrimental effects on local spatial quality. Example Moerdijk: unclear strategies of different levels of government (developed further in the afternoon PSC session).",slide:"L4 slide 28"},
  {t:"Can governance be 'just'?",d:"Is the planning system able to deal with the current crises (housing, energy, climate)? General impression: wicked planning problems are beyond either state or market to resolve. Can governance approaches provide a viable alternative? They challenge the classic system and the public role in land use; questions include how to avoid spatial fragmentation and how to incorporate governance outcomes in the formal system.",slide:"L4 slides 31–32"}
 ]}
};
